### PR TITLE
Mobile: Partially resolves #10207: display recommended plugin alert

### LINKED ISSUE #10207: Mobile: Describe the plugin settings page
### Operating system

Android

### Joplin version

3.0.0

### Desktop version info

_No response_

### Current behaviour

At present, the mobile plugins settings page has no description of what plugins are, who creates/publishes them, etc.
screenshot: Plugin settings page. Has: List of installed plugins with delete buttons, install from file, and search (and advanced settings)

### Expected behaviour

The plugin settings screen *might* have the following:
- [x] A description of who publishes plugin plugins and how to tell.
   - Resolved -- see: https://github.com/laurent22/joplin/pull/10348
- [x] What "recommended" plugins are.
   - Resolved -- see: https://github.com/laurent22/joplin/pull/10348
- [x] What to do if a plugin doesn't work on mobile. (Maybe mark plugins as a beta feature?)
   - Resolved -- most plugins marked as incompatible.
- If using a GitHub mirror, what this means.
   - Currently, a warning is shown at the top of the screen (similar to desktop). However, it isn't clear from the warning what a "mirror" is or why it's being used.
- A link for more information.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by DarkFalc0n**
Partially resolves #10207 

This is a revised version of the previous PR #10235

### CODE REVIEW

File: packages/app-mobile/components/screens/ConfigScreen/plugins/PluginBox.tsx [hunk 1]
```diff
@@ -37,6 +37,26 @@ interface Props {
 	onShowPluginLog?: PluginCallback;
 }
 
+// defines the recommended chip press event alert
+// moved to top level to avoid redefining the function on each render since this isn't plugin specific
+// doing so eliminates the need to use useCallback
+const onRecommendedPress = () => {
+	Alert.alert(
+		_(''),
```
Comment (DarkFalc0n) [inline packages/app-mobile/components/screens/ConfigScreen/plugins/PluginBox.tsx]: The title is a required field, so bypassed it by using an empty string, as recommended [here](https://reactnative.dev/docs/alert#alert)

Comment (laurent22) [reply packages/app-mobile/components/screens/ConfigScreen/plugins/PluginBox.tsx]: We don't need to localise empty strings so just `''`

File: packages/app-mobile/components/screens/ConfigScreen/plugins/PluginBox.tsx [hunk 2]
```diff
@@ -37,6 +37,26 @@ interface Props {
 	onShowPluginLog?: PluginCallback;
 }
 
+// defines the recommended chip press event alert
+// moved to top level to avoid redefining the function on each render since this isn't plugin specific
+// doing so eliminates the need to use useCallback
```
Comment (laurent22) [inline packages/app-mobile/components/screens/ConfigScreen/plugins/PluginBox.tsx]: Remove this please

File: packages/app-mobile/components/screens/ConfigScreen/plugins/PluginBox.tsx [hunk 3]
```diff
@@ -106,7 +126,13 @@ const PluginBox: React.FC<Props> = props => {
 		if (!props.item.manifest._recommended || !props.isCompatible) {
 			return null;
 		}
-		return <Chip icon='crown' mode='outlined'>{_('Recommended')}</Chip>;
+		return <Chip
+			icon='crown'
+			mode='outlined'
+			onPress={() => onRecommendedPress()}
```
Comment (laurent22) [inline packages/app-mobile/components/screens/ConfigScreen/plugins/PluginBox.tsx]: You went through the trouble of creating a separate function to avoid re-rendering, yet here you create a new function on each render. So just `onPress={onRecommendedPress}`
