### PR TITLE
Mobile: Fixes #15071: Fix share error toast cut off on Android 15+

### LINKED ISSUE #15071: Mobile: No valid notebook is available toast is partially cut off, when sharing to Joplin
### Operating system

Android

### Joplin version

3.6.15

### Desktop version info

_No response_

### Current behaviour

Please note, this requires the change in https://github.com/laurent22/joplin/pull/15064 to be able to access the appropriate code path which shows the toast.

Reproduction steps (using Android 16):
1. Delete all existing notebooks
2. Switch to all notes
3. Using Chrome, go to www.google.com
4. In the menu, use share... and share to the Joplin app
5. A toast saying 'No valid notebook is available. Please create or select a notebook and try again.' will appear, but it is partially cut off

Image

This is likely related to not catering for insets on Android 15+

### Expected behaviour

The toast should not be cut off

### Logs

_No response_

### PR DESCRIPTION
**Pull request by varunkumar-22**
Fixes #15071
### Problem:

On Android 15, apps run edge to edge by default, meaning the window extends behind the status bar. The error toast shown when sharing to Joplin with no notebook available was being rendered behind the status bar and partially cut off

**Bug:**

https://github.com/user-attachments/assets/eeb52898-8c17-4cf4-957a-5e0a386809d8

### Fix
The fix passes the actual safe area top inset as marginTop on the alert view, so the toast always appears fully below the status bar. A fallback to StatusBar.currentHeight is kept for older Android versions where useSafeAreaInsets may not be populated yet
Requires #15064
### Test Plan
**Tested locally:**

https://github.com/user-attachments/assets/ce2ad723-8fe1-4e33-a0f3-8932b2da3a4c

### CODE REVIEW

File: packages/app-mobile/root.tsx [hunk 1]
```diff
@@ -103,14 +103,25 @@ import SamlShared from '@joplin/lib/components/shared/SamlShared';
...
+import { SafeAreaProvider, useSafeAreaInsets } from 'react-native-safe-area-context';
 import appReducer from './utils/appReducer';
 import SyncWizard from './components/SyncWizard/SyncWizard';
 import Synchronizer from '@joplin/lib/Synchronizer';
 
 const logger = Logger.create('root');
 const perfLogger = PerformanceLogger.create();
 
+// eslint-disable-next-line @typescript-eslint/no-explicit-any -- DropdownAlert is untyped
+const SafeDropdownAlert = ({ alert }: { alert: (func: any)=> void }) => {
```
[the remark this answers is not in the document]
Comment (varunkumar-22) [reply packages/app-mobile/root.tsx]: recheck

[the remark this answers is not in the document]
Comment (varunkumar-22) [reply packages/app-mobile/root.tsx]: recheck

File: packages/app-mobile/root.tsx [hunk 2]
```diff
@@ -103,14 +103,25 @@ import SamlShared from '@joplin/lib/components/shared/SamlShared';
...
 const perfLogger = PerformanceLogger.create();
 
+type DropdownAlertSetter = (func: unknown)=> void;
+
+const SafeDropdownAlert = ({ alert }: { alert: DropdownAlertSetter }) => {
+	const insets = useSafeAreaInsets();
+	// On Android 15+ the app runs edge-to-edge, so DropdownAlert's built-in translucent path
+	// (which uses StatusBar.currentHeight) may not account for the full safe area top inset.
+	// We pass the actual inset as marginTop on the inner alert view to ensure it's fully visible.
+	const topInset = insets.top || StatusBar.currentHeight || 0;
```
Comment (mrjo118) [inline packages/app-mobile/root.tsx]: I think "StatusBar.currentHeight" should not be be included here, because on versions of Android older than 15, I think the viewport is already below the status bar. Additionally I think the comment is not needed, as I think the concept of safe area / insets is used throughout the app and does not need further explaination

**Comment by mrjo118** [comment]
Please can you action the comment and retest on both Android 16 and Android 14?

File: packages/app-mobile/root.tsx (hunk 2 above)
Comment (varunkumar-22) [reply packages/app-mobile/root.tsx]: Thanks for the feedback! while testing this, I ran into an issue where after applying the initial fix, the toast was still appearing at the very top of the screen even after it timed out

Screenshot 2026-04-11 at 10 19 25 PM


 After digging into it more, I realised that was not actually related to the insets at all, it was caused by using animatedViewStyle instead of alertViewStyle with marginTop, which I have since corrected

That's right about StatusBar.currentHeight  , on android older than 15 the viewport already starts below the status bar so the fallback is not  needed, and insets.top handles the Android 15+ edge to edge case cleanly on its own
I have removed the fallback and the comment as suggested

**Comment by varunkumar-22** [comment]
Tested on both Android 14 and Android 16 , both work as expected 
Attaching the screen recordings below:

### ANDROID 14:

https://github.com/user-attachments/assets/64740ff1-67c7-4118-af19-23466caac24e

### ANDROID 16:

https://github.com/user-attachments/assets/977ab857-c0d2-4f84-80d3-f0337702ba00

**Review by mrjo118 — APPROVED** [review]

File: packages/app-mobile/root.tsx [hunk 3]
```diff
@@ -103,14 +103,21 @@ import SamlShared from '@joplin/lib/components/shared/SamlShared';
...
 const logger = Logger.create('root');
 const perfLogger = PerformanceLogger.create();
 
+type DropdownAlertSetter = (func: unknown)=> void;
+
+const SafeDropdownAlert = ({ alert }: { alert: DropdownAlertSetter }) => {
+	const insets = useSafeAreaInsets();
+	return <DropdownAlert alert={alert} translucent alertViewStyle={{ padding: 8, marginTop: insets.top }} />;
+};
+
```
Comment (laurent22) [inline packages/app-mobile/root.tsx:131]: Please don't use inline styles. For component we use the pattern `const component = (props: Props) => {}` so please define a Props interface for it

Please name it SafeAreaDropdownAlert or DropdownAlertWrapper, or something like this. The current name is unclear ("safe" is vague)

File: packages/app-mobile/root.tsx [hunk 4]
```diff
@@ -771,10 +778,9 @@ class AppComponent extends React.Component<AppComponentProps, AppComponentState>
 							<View style={{ flex: 1, backgroundColor: theme.backgroundColor }}>
 								{ shouldShowMainContent && <AppNav screens={appNavInit} dispatch={this.props.dispatch} /> }
 							</View>
-							{/* eslint-disable-next-line @typescript-eslint/no-explicit-any -- Old code before rule was applied */}
-							<DropdownAlert alert={(func: any) => (this.dropdownAlert_ = func)} />
 							<SyncWizard/>
 						</SafeAreaView>
+						<SafeDropdownAlert alert={(func) => { this.dropdownAlert_ = func as typeof this.dropdownAlert_; }} />
```
Comment (laurent22) [inline packages/app-mobile/root.tsx]: Do we really need this? `as typeof this.dropdownAlert_` Isn't it the same as `as any`?

File: packages/app-mobile/root.tsx (hunk 3 above)
Comment (varunkumar-22) [reply packages/app-mobile/root.tsx:131]: Thanks for the feedback, I have defined a Props interface and renamed it to DropdownAlertWrapper

File: packages/app-mobile/root.tsx (hunk 4 above)
Comment (varunkumar-22) [reply packages/app-mobile/root.tsx]: Yeah you are right, but if I remove the cast entirely typescript throws an error since func is unknown and `dropdownAlert_` expects a specific function type, using `typeof this.dropdownAlert_` felt like the cleanest way around it without adding a new explicit any
If "any" is preferred Iam okay to make the changes

Comment (laurent22) [reply packages/app-mobile/root.tsx]: The preferred way is to discuss and investigate the issue. Is "any" better than what you had? How about importing the `DropdownAlert` component with `import` so that it is typed properly? `func: unknown` is your own definition. But if I check the type of "alert" in DropdownAlert I see it's set to this:  `alert?: ( func: (data?: DropdownAlertData) => Promise<DropdownAlertData> ) => void;`. Can we use this existing type?

Comment (varunkumar-22) [reply packages/app-mobile/root.tsx]: yes i think that's a much cleaner approach, apologize I had not noticed DropdownAlertData was already exported from the library
I will push the changes

**Comment by laurent22** [comment]
Doesn't build:

2026-04-14T04:07:02.0975871Z ##[error]➤ YN0000: │ root@workspace:. STDOUT [@joplin/app-mobile]: node_modules/react-native-dropdownalert/DropdownAlert.tsx(1,8): error TS1259: Module '"/home/runner/work/joplin/joplin/packages/lib/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag
2026-04-14T04:07:02.0990313Z ##[error]➤ YN0000: │ root@workspace:. STDOUT [@joplin/app-mobile]: node_modules/react-native-dropdownalert/DropdownAlert.tsx(360,9): error TS2554: Expected 0 arguments, but got 1.
2026-04-14T04:07:02.0995109Z ##[error]➤ YN0000: │ root@workspace:. STDOUT [@joplin/app-mobile]: node_modules/react-native-dropdownalert/DropdownAlert.tsx(387,30): error TS2554: Expected 0 arguments, but got 1.
2026-04-14T04:07:02.1000287Z ##[error]➤ YN0000: │ root@workspace:. STDOUT [@joplin/app-mobile]: node_modules/react-native-dropdownalert/DropdownAlert.tsx(390,33): error TS2554: Expected 0 arguments, but got 1.
2026-04-14T04:07:02.1004871Z ##[error]➤ YN0000: │ root@workspace:. STDOUT [@joplin/app-mobile]: node_modules/react-native-dropdownalert/DropdownAlert.tsx(393,27): error TS2554: Expected 0 arguments, but got 1.
2026-04-14T04:07:02.1007761Z ##[error]➤ YN0000: │ root@workspace:. STDOUT [@joplin/app-mobile]: node_modules/react-native-dropdownalert/DropdownAlert.tsx(396,33): error TS2554: Expected 0 arguments, but got 1.
2026-04-14T04:07:02.1010633Z ##[error]➤ YN0000: │ root@workspace:. STDOUT [@joplin/app-mobile]: node_modules/react-native-dropdownalert/DropdownAlert.tsx(399,26): error TS2554: Expected 0 arguments, but got 1.
2026-04-14T04:07:02.1013241Z ##[error]➤ YN0000: │ root@workspace:. STDOUT [@joplin/app-mobile]: node_modules/react-native-dropdownalert/DropdownAlert.tsx(410,11): error TS2554: Expected 0 arguments, but got 1.
2026-04-14T04:07:02.1016104Z ##[error]➤ YN0000: │ root@workspace:. STDOUT [@joplin/app-mobile]: node_modules/react-native-dropdownalert/DropdownAlert.tsx(432,31): error TS2345: Argument of type 'string' is not assignable to parameter of type 'StatusBarStyle'.
2026-04-14T04:07:02.1019472Z ##[error]➤ YN0000: │ root@workspace:. STDOUT [@joplin/app-mobile]: node_modules/react-native-dropdownalert/DropdownAlert.tsx(434,31): error TS2345: Argument of type 'string' is not assignable to parameter of type 'StatusBarStyle'.
2026-04-14T04:07:30.7310784Z ➤ YN0000: │ root@workspace:. STDOUT The command failed in workspace @joplin/app-mobile@workspace:packages/app-mobile with exit code 2
2026-04-14T04:07:30.7316377Z ➤ YN0000: │ root@workspace:. STDOUT Failed with errors in 48s 148ms
2026-04-14T04:07:30.8934680Z ➤ YN0000: │ root@workspace:. STDERR [04:07:30] 'build' errored after 3.23 min
2026-04-14T04:07:30.8941473Z ➤ YN0000: │ root@workspace:. STDERR [04:07:30] Error: Command failed with exit code 1: yarn run buildSequential

File: packages/app-mobile/root.tsx [hunk 5]
```diff
@@ -23,6 +23,15 @@ import { AppState as RNAppState, EmitterSubscription, View, Text, Linking, Nativ
...
 const DropdownAlert = require('react-native-dropdownalert').default;
+
+// Mirrors the DropdownAlertData type from react-native-dropdownalert
+interface DropdownAlertData {
+	type?: string;
+	title?: string;
+	message?: string;
+	interval?: number;
+	resolve?: (_value: DropdownAlertData)=> void;
+}
```
Comment (varunkumar-22) [inline packages/app-mobile/root.tsx:34]: Defined locally because importing directly from the library triggers an esModuleInterop build error due to how its typescript is set up internally
