### PR TITLE
Fix: Long URL in note properties no longer breaks the dialog layout

### LINKED ISSUE #12643: Problem with long URL in note properties
### Operating system

Windows

### Joplin version

3.3.13

### Desktop version info

Joplin 3.3.13 (prod, win32)

Device: win32, Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
Client ID: 6f5f2ab53b484795a50806b4c5e06674
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes
Alternative instance ID: -

Revision: 144ed59

Backup: 1.4.3
Freehand Drawing: 3.0.1

### Current behaviour

If you enter a very long URL in properties of a note, then the properties will be no longer available for viewing.

Image

### Expected behaviour

Truncating or wrapping the url is needed

### Logs

_No response_

### PR DESCRIPTION
**Pull request by SAYAN02-DEV**
### Desktop: Fixes #12643 - Long URL in Note Properties no longer breaks the layout

---

### 🐛 Problem

Opening the **Note Properties** dialog with a very long URL in the `source_url` field caused the layout to overflow or become unreadable.  
This prevented users from properly viewing or interacting with other note properties.

---
### ✅ Solution

Applied inline CSS styles to the URL field in `NotePropertiesDialog.tsx`:

```css
display: 'inline-block';
maxWidth: '180px';
overflow: 'hidden';
whiteSpace: 'nowrap';
textOverflow: 'ellipsis';
```
---
### After Fix:
Screenshot 2025-07-03 165057

### CODE REVIEW

File: packages/app-desktop/gui/NotePropertiesDialog.tsx [hunk 1]
```diff
@@ -411,9 +411,17 @@ class NotePropertiesDialog extends React.Component<Props, State> {
 					const ll = this.latLongFromLocation(value);
 					url = Note.geoLocationUrlFromLatLong(ll.latitude, ll.longitude);
 				}
-				const urlStyle: React.CSSProperties = { ...theme.urlStyle, maxWidth: '180px', overflow: 'hidden', whiteSpace: 'nowrap', textOverflow: 'ellipsis' };
+				// const urlStyle: React.CSSProperties = { ...theme.urlStyle, maxWidth: '100%', wordBreak: 'break-all', display: 'inline-block' };
```
Comment (laurent22) [inline packages/app-desktop/gui/NotePropertiesDialog.tsx]: remove comment

File: packages/app-desktop/gui/NotePropertiesDialog.tsx [hunk 2]
```diff
@@ -411,9 +411,17 @@ class NotePropertiesDialog extends React.Component<Props, State> {
...
+					...theme.urlStyle,
+					maxWidth: '180px',
+					overflow: 'hidden',
+					whiteSpace: 'nowrap',
+					textOverflow: 'ellipsis',
+					display: 'inline-block',
+				};
 				controlComp = (
-					<a href="#" onClick={() => bridge().openExternal(url)} style={urlStyle}>
+					<a href="#" onClick={() => bridge().openExternal(url)} style={urlStyle} title ={url}>
```
Comment (laurent22) [inline packages/app-desktop/gui/NotePropertiesDialog.tsx]: remove unrelated change

**Comment by SAYAN02-DEV** [comment]
I removed the comments and unwanted changes. Apologies, I accidentally clicked "Resolve conversation". Please feel free to reopen if it's not yet addressed.
