### PR TITLE
Desktop: Unindent empty list markup on Enter

### LINKED ISSUE #2405: Last error: Error: On file cc0e6915b30947edb5698361e8baf592.md: Item cannot be null
I added a bunch of new notebooks on my desktop.
It synchronise to my phone via syncthing. Then I started to notice the same error on both devices when synchronising.

I am not able to see these new notebooks on my phone despite the folder (on filesystem) being full synchronised.

### Desktop
Joplin version: 1.0.178 (prod, darwin)
Client ID: d0cffdc90adb49d0a7e9fcd2d1f7fc79
Sync Version: 1
Revision: 953aa5d (HEAD)
Platform: macOS
OS specifics: 10.14.6

### Mobile
Android Joplin 1.0.316
Database v27
Android OnePlus 7
Android version 10
Build number Oxygen OS 10.3.0.GM57AA

## Steps To Reproduce

A bit hard to "reproduce" now that my sync is broken.

## Content of the cc..92.md file (on desktop)
[syncReport-1580337579570-android.txt](https://github.com/laurent22/joplin/files/4131168/syncReport-1580337579570-android.txt)

```
id: cc0e6915b30947edb5698361e8baf592
parent_id: dce4b501c98b437f8ebb53aaa2f92a2f
created_time:
updated_time: 2020-01-24T00:00:29.831Z
is_conflict:
latitude:
longitude:
altitude:
author:
source_url:
is_todo:
todo_due:
todo_completed:
source:
source_application:
application_data:
order:
user_created_time:
user_updated_time:
encryption_cipher_text: JED01000022012daf68976b0340b8a533be3364ada71b0003d2{"iv":"PXIYKIp/GqZvocI+SVMv+Q==","v":1,"iter":1000,"ks":128,"ts":64,"mode":"ocb2","adata":"","cipher":"aes","salt":"noOLojCA5Gg=","ct":"i/bQ2R2Hcy8POBBCGP8KtGsiqHaabMuHSsZoK/NYOQYftCoQR8+RlLeEPm5PpVsv/sh72Z9MxKQJGc2XWkxZ6i4eFP5LnHiWDfEYgR2M1qHpnwRgoBVNLMWaanXC8icB5HWNywOPs5nBKoqJxjMD8RQTd8KFEGRqLU/M7HZeuB7or9ayv7iAWgoT7LY2WGVaFQCD7dqCjojxv1R3zox1H+E91bL6QWDs87Keh+SYbM2IQGSCMSaTf605IpEb0zjoBHCbrv9H4yZrrYN2VIRwMkx61lJSQ5n2WnJVowQgmaByVAKu3g3T9QeoS0h7i+hNwn6TrGtjaTR0BvAhQLMqLm0kYr7ki+kmLATtRh9GK8Br/cbcqSeoXAv9x1tdAjH2ctw1V/TIC4wekGSL8wk44gxly2RIJ7JvZIV2GWzAZ86ubJyZedGp80l2F2rCHQMrT2suxGnC/SvRzb7sk50anEWlX8zHRvAgr+bKy/FKuzlzlK9CfcIVeH57gs9QRthrAROxmyQJivMLD9WUDyDRa6+44MIAvJUr81hQb4HDrq0/u0hTME168l59pqi3T+s+N4wddoCpXVpxANYAPOGa3BGOnaSywJzqdwY7Afi7VpFgwgJZAxEYQRjVA0tIzWKEAmj6SeZh7GnVNByKDNF+X/OQpDA2nWH20M8pHxRc49e4DCUtIQVV8VOemjIhvukGbjH593H+FMEeRxgeob/8YZHhK45PT8ghRIJmckpTCo5sAC5JwijXwVPlxipB8mfMTBiMwsOLj+Eb3CYMeiW3m8lTTntGio24N0/3J9bcMMVN0HBHhiIDrAY+Mm79IA+gfMKiy0A="}
encryption_applied: 1
markup_language:
type_: 1ddw=="}
encryption_applied: 1
markup_language:
type_: 1
```

## Logfile

[log-desktop.txt](https://github.com/laurent22/joplin/files/4131071/log-desktop.txt)

### LINKED ISSUE #2614: Uneven Behavior of List Elements
An issue with ElectronClient.

After adding a few elements in a list item ( NumberList, BulletedList ), if we **press the Enter key**, the **last unused row should get deleted automatically** which doesn't happen in Joplin.<br><br>

Here is how it behaves:<br>
jopnote

Here is how it should behave:<br>
expectnote

### PR DESCRIPTION
**Pull request by sinkuu**
Fixes #2614 

cc @Rishgod

### CODE REVIEW

**Comment by tessus** [comment]
The wrong issue is linked.

**Comment by sinkuu** [comment]
Added.

**Comment by sinkuu** [comment]
Another possibility is to unindent, which is adopted by Dropbox Paper and Evernote.

```markdown
- item
    - item
    - item (hit enter in this line)
- x  <---- cursor is here (hitting enter again removes `- `)
````

**Comment by tessus** [comment]
> Another possibility is to unindent

Yes, this would also be a nice solution, but probably more complicated to implement.
Your latest fix was already great, so the PR looks ready to me.

But maybe Laurent does like your idea better, since people coming from Evernote certainly would feel right at home with that behavior. Let's wait for Laurent's input.

File: ElectronClient/gui/NoteText.jsx [hunk 1]
```diff
@@ -1016,6 +1001,16 @@ class NoteTextComponent extends React.Component {
 				return this.$getIndent(line);
 			};
 
+			// Returns tokens of the line if it starts with a list token.
+			const listTokens = (editor, row) => {
+				const tokens = editor.session.getTokens(row);
+				if (tokens.length > 0 && ['markup.list', 'list'].indexOf(tokens[0].type) !== -1) {
+					return tokens;
+				} else {
+					return undefined;
```
Comment (mic704b) [inline ElectronClient/gui/NoteText.jsx]: Why return undefined instead of null?

File: ElectronClient/gui/NoteText.jsx [hunk 2]
```diff
@@ -1016,6 +1001,16 @@ class NoteTextComponent extends React.Component {
 				return this.$getIndent(line);
 			};
 
+			// Returns tokens of the line if it starts with a list token.
+			const listTokens = (editor, row) => {
+				const tokens = editor.session.getTokens(row);
+				if (tokens.length > 0 && ['markup.list', 'list'].indexOf(tokens[0].type) !== -1) {
+					return tokens;
```
Comment (mic704b) [inline ElectronClient/gui/NoteText.jsx]: Move one of the returns at the end of the function, ideally this one.

File: ElectronClient/gui/NoteText.jsx [hunk 3]
```diff
@@ -1041,6 +1036,42 @@ class NoteTextComponent extends React.Component {
 
 				indentOrig.call(this);
 			};
+
+			// Delete a list markup (e.g. `- `) from an empty list item on hitting Enter.
+			// (https://github.com/laurent22/joplin/pull/2772)
+			this.editor_.editor.commands.addCommand({
+				name: 'enter',
+				bindKey: { win: 'Enter', mac: 'Enter' },
```
Comment (mic704b) [inline ElectronClient/gui/NoteText.jsx]: Is this necessary?

**Comment by mic704b** [comment]
Hi @sinkuu thanks for the changes.  I deleted my comments immediately and was going to try again later, but it seems you saw them anyway! Thanks for making the changes.

File: ElectronClient/gui/NoteText.jsx [hunk 4]
```diff
@@ -1041,6 +1035,42 @@ class NoteTextComponent extends React.Component {
 
 				indentOrig.call(this);
 			};
+
+			// Delete a list markup (e.g. `- `) from an empty list item on hitting Enter.
+			// (https://github.com/laurent22/joplin/pull/2772)
+			this.editor_.editor.commands.addCommand({
+				name: 'enter',
+				bindKey: 'Enter',
```
Comment (mic704b) [inline ElectronClient/gui/NoteText.jsx]: Are you sure about this?  My original comment was more of a question, but this is better if it works.

File: ElectronClient/gui/NoteText.jsx [hunk 5]
```diff
@@ -1016,6 +1001,15 @@ class NoteTextComponent extends React.Component {
...
 			};
 
+			// Returns tokens of the line if it starts with a list token.
+			const listTokens = (editor, row) => {
+				const tokens = editor.session.getTokens(row);
+				if (!tokens.length || ['markup.list', 'list'].indexOf(tokens[0].type) === -1) {
+					return null;
+				}
+				return tokens;
+			};
```
Comment (mic704b) [inline ElectronClient/gui/NoteText.jsx]: That looks better!  Thanks.

File: ElectronClient/gui/NoteText.jsx (hunk 4 above)
Comment (sinkuu) [reply ElectronClient/gui/NoteText.jsx]: Yes, they are equivalent.

https://github.com/ajaxorg/ace/blob/c6aa009c9fd12822222b36a81387d91c60c6e8d2/lib/ace/keyboard/hash_handler.js#L91-L95

**Comment by mic704b** [comment]
> Another possibility is to unindent

and then clear after that.

**Comment by tessus** [comment]
@mic704b 

> and then clear after that.

I think in this case only after a second Enter, because you might want to continue the list....

**Comment by sinkuu** [comment]
https://github.com/laurent22/joplin/pull/2772/commits/d3409a192550acc0f5f70b14bf8973a9da08362d:

Peek 2020-03-17 18-13

https://github.com/laurent22/joplin/pull/2772/commits/707d053748289a59c3e7c97e2a8964eb5567e0b4:

Peek 2020-03-17 18-18

**Comment by mic704b** [comment]
Looks good.

Does this have any effect when entering numbered lists?  Have you tested mid-line multiline selections?

It's a shame we have no way to automated test this, to make sure no one breaks it in the future.

File: ElectronClient/gui/NoteText.jsx [hunk 6]
```diff
@@ -1025,9 +1019,9 @@ class NoteTextComponent extends React.Component {
 				const range = this.getSelectionRange();
 				if (range.isEmpty()) {
 					const row = range.start.row;
-					const tokens = this.session.getTokens(row);
+					const tokens = listTokens(this, row);
 
-					if (tokens.length > 0 && tokens[0].type == 'markup.list') {
+					if (tokens) {
 						if (tokens[0].value.search(/\d+\./) != -1) {
```
Comment (mic704b) [inline ElectronClient/gui/NoteText.jsx]: On seeing this, i think it would be clearer if `listTokens` always returns a list, and we go
```
if (tokens.length > 0)
```
No bug here, it just looks suspicious.

**Comment by sinkuu** [comment]
> Does this have any effect when entering numbered lists?

It works the same for all Markdown list syntaxes (`-`, `*`, `1.` etc.).

>  Have you tested mid-line multiline selections?

I added `multiSelectAction: 'forEach'`:
Peek 2020-03-18 10-03

**Comment by sinkuu** [comment]
@mic704b I made automated tests here: https://github.com/sinkuu/joplin-ace-indent-test/blob/master/spec/indentSpec.js I don't know how I can integrate this to Joplin (if that's a good idea) though. The tests require Ace's `MockRenderer` which is not included in published packages.

**Comment by tessus** [comment]
I think the behavior should be like the way you have alerady described:

```
- item
    - item
    - item
- x  <---- cursor is here (hitting enter again removes `- `)
```

This behavior makes the most sense. Then I think we are good to merge. Just waiting for Laurent's input.

**Comment by sinkuu** [comment]
Changed to unindenting behavior.

**Comment by tessus** [comment]
Great. This helps a lot with usability.

**Comment by mic704b** [comment]
>  I made automated tests here

@sinkuu that looks really good. Nice work.

> I don't know how I can integrate this to Joplin (if that's a good idea) though

I think when it is testing behaviour implemented in Joplin then it makes a lot of sense.  (Though it might even make sense when testing required behaviour of dependencies too).  However let's see what Laurent thinks, when things calm down a bit.

**Comment by laurent22** [comment]
The test units you've created look good @sinkuu. Any chance you could add them to this pull request? You could put the test in CliClient/tests and feel free to add any required dependency to CliClient/package.json as dev dependency.

**Comment by sinkuu** [comment]
Done.

**Comment by PackElend** [comment]
ready to merge?

**Comment by laurent22** [comment]
Sorry for being late to review this @sinkuu, and unfortunately I see there are some conflicts, due to the recent refactoring of NoteText.jsx, please could you take a look at them?

I've moved the previous code from your pull request to a custom hook in `AceEditor/utils/useListIdent.ts`. I believe you might need to move some of your changes to this file, and the rest probably in AceEditor.tsx.

**Comment by tessus** [comment]
@sinkuu have you had the time to look into this? I was quite busy and unavailable the last 2 weeks, so I couldn't look into it myself.

**Comment by tessus** [comment]
I really would hate seeing this not merged. This made working with lists and checklists a lot easier and better.

**Comment by tessus** [comment]
Works perfectly! Thanks!

**Comment by tessus** [comment]
@laurent22 can I merge this?

**Comment by laurent22** [comment]
Yes, if it's working for you then let's merge. Thanks @sinkuu!
