### PR TITLE
All: Use removeDiactritics from string-utils to avoid a bug in diacricits lib

### LINKED ISSUE #4025: Cyrillic L (Л) replaced by 'n' when searching
## Environment

Joplin version: 1.3.11
Platform: Linux
OS specifics: Linux Mint 19.3 (based on Ubuntu 18.04)

## Steps to reproduce

1. Create note titled with cirillic symbol "Л"
image

2. Press `Ctrl+P` and type some text from title

3. In search results you can see that "Л" was replaced with "n"
image

### PR DESCRIPTION
**Pull request by roman-r-m**
Fixes #4025

### CODE REVIEW

**Comment by laurent22** [comment]
Is it possible to add a test unit for this? Maybe in services_SearchEngine?

**Comment by roman-r-m** [comment]
> 
> 
> Is it possible to add a test unit for this? Maybe in services_SearchEngine?

Done

File: packages/app-cli/tests/services_SearchEngine.js [hunk 1]
```diff
@@ -515,4 +515,14 @@ describe('services_SearchEngine', function() {
...
 	}));
+
+	it('should not mistake cyrillic "l" for latin "n"', asyncTest(async () => {
+		const n1 = await Note.save({ title: 'latin n', body: 'n' });
+		const n2 = await Note.save({ title: 'cyrillic l', body: 'л' });
+
+		await engine.syncTables();
+
+		expect((await engine.search('n')).length).toBe(1);
+		expect((await engine.search('л')).length).toBe(1);
```
Comment (laurent22) [inline packages/app-cli/tests/services_SearchEngine.js:526]: Could you check the result content rather than just the number of search results please? For example with this test if the search engine suddenly starts returning "latin n" for both queries, we won't know about it.

Comment (roman-r-m) [reply packages/app-cli/tests/services_SearchEngine.js]: Fixed to check ids, getting the content requires an extra step as search does not return it.

File: packages/app-cli/tests/services_SearchEngine.js [hunk 2]
```diff
@@ -511,4 +511,14 @@ describe('services_SearchEngine', function() {
...
 	}));
+
+	it('should not mistake cyrillic "l" for latin "n"', (async () => {
+		const n1 = await Note.save({ title: 'latin n', body: 'n' });
+		const n2 = await Note.save({ title: 'cyrillic l', body: 'л' });
+
+		await engine.syncTables();
+
+		expect((await engine.search('n'))[0].id).toBe(n1.id);
+		expect((await engine.search('л'))[0].id).toBe(n2.id);
```
Comment (laurent22) [inline packages/app-cli/tests/services_SearchEngine.js:522]: Thanks for adding this, but could you also put back the check on the number of results please?

Comment (roman-r-m) [reply packages/app-cli/tests/services_SearchEngine.js]: done

**Comment by laurent22** [comment]
All good now, thanks @roman-r-m!
