### PR TITLE
Desktop: Fixes #11443: Accessibility: Do not override focus order when pressing tab/shift-tab on the note list

### LINKED ISSUE #11443: Inaccessible Backward Navigation in Note List Using Shift+Tab
### Operating system

Windows

### Joplin version

3.1.24

### Desktop version info

Joplin 3.1.24 (prod, win32)

ID do cliente: ecdb6b3128d549d29e46c9f0743a3b09
Versão Sync: 3
Versão do Perfil: 47
Keychain Suportada: Sim

Revisão: d581264

Backup: 1.4.2
Describe image: 1.7.0

### Current behaviour

When focusing on the list of notes, either using the Ctrl+Shift+L command or manually with a screen reader, it is not possible to return to the interface using Shift+Tab.

Steps to reproduce:

1. Focus on the list of notes using the shortcut or manually.  
2. Press Shift+Tab to exit the note list and navigate to the "Reverse sort order" button.  
3. Observe that it is not possible to return to the interface from the list. Navigation is only possible by moving forward with the Tab key.

### Expected behaviour

Make it possible to exit the notes list normally, without blocking the interface. Both forward and backward (tab and shift+tab).

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

Fixes #11443. Related to #10795.

Before this pull request, Joplin overrode the default focus order when:
- Pressing <kbd>tab</kbd> from the notebook list (skipping sync, new note, new to-do, search, sort by, etc.).
- Pressing <kbd>shift</kbd>-<kbd>tab</kbd> from the note list (skipping sort by, search, new to-do, etc.).

This pull request removes the above two overrides, making it easier for screen reader/keyboard only users to access the note list controls and the sync button.

## Replacement shortcuts

To preserve ability to navigate quickly between the notes list and sidebar, new shortcuts have been added:
- Pressing <kbd>enter</kbd> from the **notebook list**: Navigates to the note list.
- Pressing <kbd>shift</kbd>-<kbd>enter</kbd> from the **note list**: Navigates to the notebook list.

Also, for consistency,
- Pressing <kbd>enter</kbd> from the **note list**: Navigates to the title of the currently open note (if any).

## Additional notes

- <kbd>Enter</kbd> was selected, in part, because it's similar to what's done in VSCode when the file tree is focused. When I 1) focus the file tree and 2) press enter, VSCode jumps focus to the editor (skipping focusable elements in between). 
- Currently (before this PR), checkboxes are toggled in the note list by pressing <kbd>space</kbd> (and not <kbd>enter</kbd>). (Though perhaps they should be toggled by <kbd>enter</kbd>?)

# Testing plan

<details><summary>Manual testing -- Fedora 41</summary>

1. Start Joplin (with a notebook and note open).
2. Focus the note list.
3. Press <kbd>tab</kbd>.
4. Verify that "Synchronize" is selected.
5. Press <kbd>tab</kbd>.
6. Verify that the "new note" button is selected.
7. Press <kbd>tab</kbd>.
8. Verify that the "new to-do" button is selected.
9. Press <kbd>tab</kbd>.
10. Verify that the search field is selected.
11. Press <kbd>tab</kbd>.
12. Verify that the search button is selected.
13. Press <kbd>tab</kbd>.
14. Verify that the "toggle sort order field" button is selected.
15. Verify that the "reverse sort order" button is selected.
16. Press <kbd>tab</kbd>.
17. Verify that an item in the note list is selected.
18. Press <kbd>tab</kbd>.
19. Verify that the title input for the currently open note is focused.
20. Press <kbd>shift</kbd>-<kbd>tab</kbd>.
21. Verify that the note list is focused.
22. Press <kbd>shift</kbd>-<kbd>tab</kbd>.
23. Verify that the "reverse sort order" button is focused.
24. Press <kbd>tab</kbd>.
    - This should focus the note list.
25. Press <kbd>shift</kbd>-<kbd>enter</kbd>.
26. Verify that the notebook list has focus.
27. Press <kbd>enter</kbd>.
28. Verify that the note list has focus.
29. Press <kbd>enter</kbd>.
30. Verify that the note title input has focus.

</details>

### CODE REVIEW

File: packages/app-desktop/gui/Sidebar/hooks/useOnSidebarKeyDownHandler.ts [hunk 1]
```diff
@@ -54,14 +54,13 @@ const useOnSidebarKeyDownHandler = (props: Props) => {
...
-		} else if (event.code === 'Tab') {
+		} else if (event.code === 'Tab' && event.shiftKey) {
 			event.preventDefault();
 
-			if (event.shiftKey) {
-				void CommandService.instance().execute('focusElement', 'noteBody');
-			} else {
-				void CommandService.instance().execute('focusElement', 'noteList');
-			}
+			void CommandService.instance().execute('focusElement', 'noteBody');
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/gui/Sidebar/hooks/useOnSidebarKeyDownHandler.ts:60]: This focus override should also be removed, though perhaps in a follow-up pull request.
