### PR TITLE
Desktop: Fixes #14613: Fix JPEG image paste from clipboard on Linux

### LINKED ISSUE #14613: Only PNG (not JPEG) images can be posted from clipboard on linux
### Operating system

Linux

### Joplin version

v3.6.3 (also reproduced on 3.5.13)

### Desktop version info

_No response_

### Current behaviour

1. Get a JPEG image into the clipboard (for example by `xclip -selection clipboard -t image/jpeg someimage.jpg`). Note that copying an image from browser won't reproduce the issue because browsers provide multiple formats including image/png (you can use `xclip -selection clipboard -t TARGETS -o` to see what formats the current clipboard content provides).
2. Try to Ctrl-V paste it into a note and watch nothing happen.

The same process works fine with an image/png image in the clipboard, and drag-and-dropping a JPEG file into the note also works (so it's not a general failure to handle JPEG images).

### Expected behaviour

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by moaaz-ae**
On Linux, pasting a JPEG image from the system clipboard into a Joplin note does nothing. The image is silently dropped. PNG paste works fine, and drag-and-dropping a JPEG file also works. Only JPEG clipboard paste is broken.

## The problem

Two Electron/Chromium platform behaviours combine to break this:

1. `clipboard.availableFormats()` returns `[]` for JPEG-only clipboard data on Linux, even though the JPEG bytes are present. This is a known Chromium limitation ([electron/electron#32490](https://github.com/electron/electron/issues/32490)). Since the old code iterated over `availableFormats()`, the loop body never executed for JPEG.

2. `clipboard.readImage()` returns an empty `NativeImage` for JPEG-only clipboard data, so even if the format were detected, the old `readImage()` to `nativeImage.toJPEG()` path would produce a corrupt file.

## The fix

Replace the detection and reading strategy in `getResourcesFromPasteEvent`:

| Before                                             | After                                                             |
| -------------------------------------------------- | ----------------------------------------------------------------- |
| `clipboard.availableFormats()` to detect formats   | `clipboard.has(format)` against a fixed list of supported formats |
| `clipboard.readImage()` to read image data         | `clipboard.readBuffer(format)` to read raw bytes                  |
| `shim.writeImageToFile()` (NativeImage conversion) | `shim.fsDriver().writeFile()` (write buffer directly)             |
| `event.preventDefault()` called before attachment  | `event.preventDefault()` called only after successful attachment  |

`clipboard.has()` and `clipboard.readBuffer()` work correctly on all platforms (Linux, macOS, Windows), so the fix is applied unconditionally rather than behind a platform check.

The function signature and return type are unchanged. All three callers (TinyMCE, CodeMirror v5, CodeMirror v6) work without modification.

### Automated

All 11 tests pass in `resourceHandling.test.ts` (7 existing + 4 new).

### Manual

1. Copied JPEG via `xclip -selection clipboard -t image/jpeg test.jpeg`, pressed Ctrl+V in Joplin. Image appears in note.
2. Copied PNG via `xclip -selection clipboard -t image/png test.png`, pressed Ctrl+V. Image appears in note.
3. Copied image from browser (right-click, Copy Image), pressed Ctrl+V. Image appears in note.
4. Pasted plain text. Text appears normally, no interference.
5. Tested in both Rich Text (TinyMCE) and Markdown (CodeMirror) editors.

### Video

https://github.com/user-attachments/assets/35c109d0-aec0-486d-80e1-d6ff66cae87f

## AI Assistance Disclosure

This PR used AI to assist with code refactoring and test design. All code has been manually reviewed and tested.

### CODE REVIEW

**Comment by moaaz-ae** [comment]
I have read the CLA Document and I hereby sign the CLA

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts [hunk 1]
```diff
@@ -93,28 +93,37 @@ export function resourcesStatus(resourceInfos: any) {
...
+			try {
+				await shim.fsDriver().remove(filePath);
+			} catch (cleanupError) {
+				logger.warn('getResourcesFromPasteEvent: Failed to remove temporary file.', cleanupError);
+			}
+		}
 
-			if (md) output.push(md);
+		if (md) {
+			if (event) event.preventDefault();
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts]: Currently, `.preventDefault` is called after an `await`. This might prevent the `.preventDefault` call from preventing the default paste behavior in the Markdown editor (the Rich Text Editor seems to always call `.preventDefault`).

If the clipboard contains both `text/plain` and an `image/png`, are both the text and image pasted?

(Thank you for working on this!)

Comment (moaaz-ae) [reply packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts]: `.preventDefault()` is now before the first await.

When the clipboard holds both text and image data, the result depends on what is actually there (tested manually).

Copying an image from a browser puts an image/png blob on the clipboard, so both editors paste only the image.

Copying a text block with inline images puts text/plain and text/html on the clipboard instead. There is no image/png blob since the images are just URLs in the HTML. Because of this, `getResourcesFromPasteEvent` returns nothing. TinyMCE downloads these images via `processImagesInPastedHtml` so they get pasted, but the Markdown editor does not and simply falls back to the default CodeMirror plain text paste. Since this appears to be pre-existing behavior, I’ve left it as-is for this PR, but we could create a separate issue for it if needed.

Comment (personalizedrefrigerator) [reply packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts]: > .preventDefault() is now before the first await.

Thank you!

> but the Markdown editor does not and simply falls back to the default CodeMirror plain text paste. Since this appears to be pre-existing behavior, I’ve left it as-is for this PR, but we could create a separate issue for it if needed.

Please leave this as-is.

**Review by personalizedrefrigerator — APPROVED** [review]

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.test.ts [hunk 2]
```diff
@@ -129,4 +143,44 @@ describe('resourceHandling', () => {
...
+
+	// Tests for getResourcesFromPasteEvent - clipboard image paste (issue #14613)
+	// The test environment (non-Electron, no sharp) skips image validation and
+	// just copies the file, so any non-empty buffer works as test data.
+	const testImageBuffer = Buffer.from(minimalPng, 'base64');
+
+	afterEach(() => {
+		mockClipboard.has.mockReset();
+		mockClipboard.readBuffer.mockReset();
+	});
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/gui/NoteEditor/utils/resourceHandling.test.ts]: (Optional) This is fine as-is, but for readability, consider moving this near the top of the `describe` block:
- This could make it easier to locate: Most existing `afterEach` declarations are placed near the beginning of `describe`.
- The clipboard mocks are defined near the start of the `describe` block.

Comment (moaaz-ae) [reply packages/app-desktop/gui/NoteEditor/utils/resourceHandling.test.ts]: Done

**Review by personalizedrefrigerator — APPROVED** [review]

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.test.ts (hunk 2 above)
Comment (personalizedrefrigerator) [reply packages/app-desktop/gui/NoteEditor/utils/resourceHandling.test.ts]: Thanks!

**Comment by bsavant** [comment]
This change appears to have caused a regression that no longer allows pasting of png or jpeg images from the clipboard on MacOS.

**Comment by moaaz-ae** [comment]
Sorry about that. Since I don't use macOS, I can't reproduce or test this myself.

To be safe, I can wrap my changes in a Linux-only check so macOS (and Windows) go back to their previous working state. Let me know if that sounds good.

@bsavant In the meantime, could you let me know if this happens with all images and what app you're copying from? Also, are there any errors in the console (Help > Toggle Development Tools) when you paste?

**Comment by laurent22** [comment]
Reverted in 379a53eca57893acf463ead8afc306a72eeff429 due to https://github.com/laurent22/joplin/issues/15022#issuecomment-4189250496
