### PR TITLE
Chore: Desktop: Fix NoteEditor unnecessary rerendering

### LINKED ISSUE #8652: Note content does not refresh after sync
Note content does not refresh after sync.

## Environment

Joplin version: 2.12.10
Platform: macOS
OS specifics: Ventura 13.4.1 (arm64)
Sync: File system

## Steps to reproduce

1. Open a note on device A.
2. Edit the same note on device B.
3. Sync B, then sync A.
4. The note does not refresh on device A.
5. Switch to a different note and back, and the content changes.

## Describe what you expected to happen

In version 2.11 the same process works (note content refreshes immediately after sync).

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This is a follow-up PR to #8654. `NoteEditor.tsx` had a property that (unnecessarily) changed whenever the app state changed. See [comment](https://github.com/laurent22/joplin/pull/8654#issuecomment-1676160246).

This also fixes #8652 (when encryption is disabled), though it does not fix the bugs in `useFormNote`.

# Testing

See the manual testing steps in https://github.com/laurent22/joplin/pull/8654.

### CODE REVIEW

File: packages/lib/services/share/reducer.ts [hunk 1]
```diff
@@ -82,10 +82,6 @@ export const parseShareCache = (serialized: string): State => {
 	};
 };
 
-export const readFromSettings = (state: RootState): State => {
-	return parseShareCache(state.settings['sync.shareCache']);
-};
```
Comment (personalizedrefrigerator) [inline packages/lib/services/share/reducer.ts:87]: `readFromSettings` was added in https://github.com/laurent22/joplin/commit/77482a0c956987434a4e1f7d645aeec8d51292eb#diff-abe2fce8500ff5467a22c4d5983313ee7f3d2085895706702a57aa7f8274e3edR85 and is now unused.

File: packages/app-desktop/gui/NoteEditor/NoteEditor.tsx [hunk 2]
```diff
@@ -656,7 +660,7 @@ const mapStateToProps = (state: AppState) => {
 		isSafeMode: state.settings.isSafeMode,
 		useCustomPdfViewer: false,
 		syncUserId: state.settings['sync.userId'],
-		shareCache: readFromSettings(state),
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/gui/NoteEditor/NoteEditor.tsx:659]: `readFromSettings` returned a new object every time it was called, causing `NoteEditor` to rerender unnecessarily.

**Comment by laurent22** [comment]
Looks good too, thanks. If you could also rebase on release-2.12 that would be great
