### PR TITLE
Desktop: Fixes #12042: Fix toggling lists in the Rich Text Editor

### LINKED ISSUE #12042: Desktop, RTE: One-item lists are disappearing
### Operating system

Linux

### Joplin version

3.3.3

### Desktop version info

Joplin 3.3.3 (prod, linux)

Client ID: a04f8be4f3a34a92ac07a571a7113f8d
Sync Version: 3
Profile Version: 47
Keychain Supported: No
Alternative instance ID: -

Revision: 23254e6

Backup: 1.4.2
collector: 1.0.0
Favorites: 1.3.2
Markdown Table: Colorize: 1.2.0
Note list (Preview): 1.1.0
Note overview: 1.7.1
Note Tabs: 1.4.0
Random Note Reloaded: 1.0.4
Rich Markdown: 0.15.1
Whitespacer: 1.0.2

### Current behaviour

1. Activate the RTE
2. Create a one-item list (numbered, unnumbered or checkbox)
3. Go to a different note
4. Go back to the note. **There is no list anymore.**

Detailed report at the forum: https://discourse.joplinapp.org/t/checkbox-list-disapear/44608

### Expected behaviour

The list should be preserved.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request fixes a regression caused by the [upgrade to TinyMCE 6](https://github.com/laurent22/joplin/pull/11652).

Fixes #12042.

> [!IMPORTANT]
>
> Due to [build issues](https://github.com/laurent22/joplin/blob/dev/Assets/TinyMCE/JoplinLists/README.md) with the Joplin lists plugin, the built `lists.js` and source files were both modified manually. I'm looking into rebasing the Joplin-related changes to the list plugin on the upstream lists plugin.

# Testing plan

Manual testing on Fedora 41 Linux:
1. Create a note with a bulleted list.
2. Select the bulleted list and click the "bullet list" button in the toolbar.
3. Verify that the list has been removed.
4. Click "checkbox list" in the toolbar.
5. Verify that the list has been restored, but as a checklist.
6. Click "numbered list" in the toolbar.
7. Verify that the list has been converted to a numbered list.

### CODE REVIEW

**Comment by mrjo118** [comment]
There's a typo in the PR title for Desktop

File: packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/plugins/lists.js [hunk 1]
```diff
@@ -1576,7 +1576,7 @@
     var removeStyles = function (dom, element, styles) {
       Tools.each(styles, function (style) {
         var _a;
```
Comment (Paramesh-T-S) [inline packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/plugins/lists.js:1578]: Hi, It is good to remove the unused variable "_a".
