### PR TITLE
Desktop: Fixes #3917: Fixed numbered list bug in markdown editor

### LINKED ISSUE #3917: Numbered lines
When using the numbered lines option on a section of a text, it should detect the lines and so have different numbers for each lines.
Right Now it's a succession a 1. In the left section. The good appearance works in the preview part so the right part. 

## Environment

Joplin version: 1.2.6
Platform: windows 10 pro
OS specifics: 

## Steps to reproduce

1. 
2. 
3.

### PR DESCRIPTION
**Pull request by MichBoi**
This PR fixed [#3917](https://github.com/laurent22/joplin/issues/3917). Increasing number will be added to the front of each line in markdown editor, if users select multiple lines and use numbered list. My solution is to detect whether the user is trying to add a numbered list by checking if string1 starts with number. If it is, add increasing number to each selected line accordingly. Please let me know if it is a good solution or I need to do something further. Thank you in advance!

### CODE REVIEW

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts [hunk 1]
```diff
@@ -75,6 +75,12 @@ export default function useCursorUtils(CodeMirror: any) {
 		// Batches the insert operations, if this wasn't done the inserts
 		// could potentially overwrite one another
 		this.operation(() => {
+
+			let num = 0;
+			if (string1.match(/^\d/)) {
```
Comment (CalebJohn) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts:80]: Instead of this logic here, you should use [`olLineNumber`](https://github.com/laurent22/joplin/blob/dev/packages/lib/markdownUtils.ts#L83) from the markdownUtils module.
Also if you move this logic inside the `selectedStrings` (after line 84) for loop then you'll get the correct counting behaviour if the user has multiple selections.

Comment (MichBoi) [reply packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts]: Hello! I've used olLineNumber and move this logic inside of the for loop. Thank you for your feedback.

Comment (CalebJohn) [reply packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts]: Looks good!

**Comment by CalebJohn** [comment]
Looks good to me! Thanks for the update @MichBoi 
I'll leave it to @laurent22 to do the final merge.

**Comment by laurent22** [comment]
Looks good, thanks for the fix!
