### PR TITLE
Desktop: Fixes #14216: Fix undo/redo menu items in the Rich Text and Markdown editors

### LINKED ISSUE #14216: The Undo menu item doesn't do anything
Joplin 3.6.2 (prod, darwin)

Create a note with this content in the Markdown editor:

```markdown
- [ ] one
- [ ] two
- [ ] three
```

- Open the Rich Text editor
- Place the cursor at the end of "two"
- Press enter
- Select Edit -> Undo

=> Does not work

- Switch to Markdown editor
- Place the cursor on the empty line after `- [ ] two`
- Press Backspace
- Select Edit -> Undo

=> Does not work

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request works around what seems to be an Electron/Chromium bug related to the undo/redo menu items (see [comment](https://github.com/laurent22/joplin/issues/14216#issuecomment-3808301196)).

When the CodeMirror or TinyMCE editor has focus, the "Undo" and "Redo" menu items now use the `editor.undo` and `editor.redo` commands. Otherwise, the native Electron undo/redo is used. Previously, the "undo" and "redo" menu items always used the default Electron undo/redo.

Fixes #14216.

# Testing plan

[Screencast from 2026-01-27 17-23-20.webm](https://github.com/user-attachments/assets/62aa6e00-1f1a-4ae7-b663-c5f186e896e5)

On Fedora 43 Linux:

1. Focus the note title.
2. Clear the note title.
3. Use the edit > undo menu item to undo.
4. Use the edit > redo menu item to redo.
5. Use the edit > undo menu item to undo.
6. Repeat steps 1-5 for the note body (Markdown editor).
7. Repeat steps 1-5 for the note body (Rich Text editor).

### CODE REVIEW

File: packages/app-desktop/gui/WindowCommandsAndDialogs/commands/utils/canUseNativeUndo.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import { WindowControl } from '../../utils/useWindowControl';
+
+// CodeMirror and TinyMCE both have trouble with native Electron
+// undo/redo.
+// See https://github.com/laurent22/joplin/issues/14216
+const canUseNativeUndo = (control: WindowControl) => {
+	const dom = control.getFocusedDocument();
+	return !dom.activeElement.closest('.CodeMirror, div.joplin-tinymce');
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/gui/WindowCommandsAndDialogs/commands/utils/canUseNativeUndo.ts:8]: An alternative might be to return `true` only if the selection has an `input`/`textarea` ancestor. However, this approach is likely to conflict with plugins that use custom edit controls (with no `editor.undo`/`editor.redo` handlers).
