### PR TITLE
Desktop: Fixes #14628: prevent renderer crash when closing secondary window

### LINKED ISSUE #14628: Renderer process crash after opening note in new window, and then closing that window
### Operating system

Windows

### Joplin version

3.6.4

### Desktop version info

Joplin 3.6.4 (dev, win32)

Device: win32, AMD Ryzen 7 5800X3D 8-Core Processor           
Client ID: c07c6c0f85d9467189635e30310d9d9f
Sync Version: 3
Profile Version: 49
Keychain Supported: Yes
Alternative instance ID: -
Sync target: (None)
Editor: Markdown

Revision: 85e5bbd

Backup: 1.5.1
Freehand Drawing: 4.3.0

### Current behaviour

Steps to Re-create:

1. Navigate to a Note
2. From the note list, right click another Note | Open in new window (this will work as expected)
3. Close that new window

After closing the window, I see that the main window turns white and shows a message that the renderer process is gone

Example:

Image

### Expected behaviour

Closing the window shouldn't cause a renderer process crash

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Kaushalendra-Marcus**
fixes #14628

## Problem
Closing a note opened in a secondary window caused the main window's renderer process to crash (white screen / "renderer process gone") on Windows and Linux.

The crash is an Electron-level assertion failure (`(Environment::GetCurrent(isolate)) == (env)`) during secondary window teardown, related to upstream issue electron/electron#33868. The exact trigger is still under investigation - as noted by @personalizedrefrigerator, the crash occurs even when React Portal rendering is disabled.

## Solution
- **ElectronAppWrapper.ts**: When Electron detects the secondary window closing, immediately notify the main renderer via IPC (`secondary-window-closing`) instead of waiting for the 2-second poll. Also wrapped `main-window-focused` send in try-catch to handle temporarily disposed render frames.
- **NewWindowOrIFrame.tsx**: Set `doc = null` immediately when `secondary-window-closing` IPC fires so React stops rendering the Portal into the destroyed document before `WINDOW_CLOSE` triggers unmounting. Fixed `const unmounted` bug (could never change) to `let unmounted`, added `unmounted = true` in cleanup, added `if (unmounted) break` after sleep to prevent duplicate close calls, and replaced `shim.setTimeout` with native `setTimeout` to prevent Node.js assertion failures when the secondary window's environment is torn down.
- **app.ts**: Listen for `secondary-window-closing` IPC and dispatch `WINDOW_CLOSE` to unmount the Portal immediately.

## Test Plan
1. Right-click a note in the note list -> Open in new window
2. Close the new window
3. Verify the main window remains stable, no white screen or renderer crash
4. Verify a new secondary window can be opened after closing

Automated test added: `should not crash when closing a secondary window` in `multiWindow.spec.ts`.

## Demo
https://github.com/user-attachments/assets/e770879f-d440-4994-8cad-d2a67af8339e

## AI Usage
AI was used for debugging assistance and implementation guidance in this PR.

## Notes
This builds on the approach from #14640 by @manjhss, which was closed as stale. Additional fixes include replacing `shim.setTimeout` with native `setTimeout` to prevent Node.js assertion failures, adding error handling for disposed render frames, and removing duplicate `WINDOW_CLOSE` dispatch from the polling loop.

### CODE REVIEW

**Comment by personalizedrefrigerator** [comment]
<blockquote>

Right-click a note in the note list → Open in new window
Close the new window
Verify the main window remains stable — no white screen or renderer crash

</blockquote>

To reproduce the original issue, I usually have to open multiple secondary windows (e.g. 5), and close all of them, one after another. See [comment](https://github.com/laurent22/joplin/pull/14640#issuecomment-4019808146) for an example.

**Comment by Kaushalendra-Marcus** [comment]
thank you for the feedback
this PR fixes the single-window case from the issue description 
the multiple window scenario is a related edge case I am still investigating and will address in a follow-up

**Comment by Kaushalendra-Marcus** [comment]
I have been working on this for the past 2 days and can reproduce the multiple-window crash locally. The Node.js assertion fires during secondary window teardown but I'm struggling to find a clean fix. Do you have any suggestions on the best approach to handle this case?

**Comment by personalizedrefrigerator** [comment]
>  this PR fixes the single-window case from the issue description

Are you able to consistently reproduce the single-window case locally? I was only able to reproduce the issue with several secondary windows.

**Comment by Kaushalendra-Marcus** [comment]
> Are you able to consistently reproduce the single-window case locally?

yes I was able to reproduce the crash with a single window locally on windows. The crash occurred consistently when closing a single secondary window, the renderer process gone dialog appeared each time.

**Comment by personalizedrefrigerator** [comment]
> Do you have any suggestions on the best approach to handle this case?

This pull request currently keeps the polling loop, which runs every two seconds. As such, there should still be time for a render to occur between when the user closes a window and when React can no longer render to it. 

It might be helpful to adjust the `const parentNode` line:
```ts
const parentNode = loaded ? doc?.body : null;
```

I've previously tried adjusting it to check the `closed` property on the secondary window (accessing the window using [doc.defaultView](https://developer.mozilla.org/en-US/docs/Web/API/Document/defaultView)):
```ts
const parentNode = loaded && !doc?.defaultView?.closed ? doc?.body : null;
```

This change should remove the risk of rendering into the secondary window just after the window is closed. However, it didn't seem to fix the issue for me.

**Comment by personalizedrefrigerator** [comment]
> Do you have any suggestions on the best approach to handle this case?

I also suggest testing changes manually, rather than relying on `multiWindow.spec.ts` to determine if the many-window case of the issue can still happen. It seems to be possible for  the test in `multiWindow.spec.ts` to fail (with a crash/hang) even when running against Joplin 3.5.x.

**Comment by Kaushalendra-Marcus** [comment]
I tried the `defaultView.closed` check as suggested, it didn't fix the issue for me either, same crash occurs. Will continue investigating other approaches.

**Comment by mrjo118** [comment]
> > this PR fixes the single-window case from the issue description
> 
> Are you able to consistently reproduce the single-window case locally? I was only able to reproduce the issue with several secondary windows.

I am able to with just 1 secondary window on Windows 10.

@Kaushalendra-Marcus FYI it's now mandatory to include an AI disclosure section in the PR description, regardless of whether AI was used or not

**Comment by Kaushalendra-Marcus** [comment]
> AI disclosure section in the PR description

I updated the PR description including AI usage

File: packages/app-desktop/ElectronAppWrapper.ts [hunk 1]
```diff
@@ -483,6 +487,9 @@ export default class ElectronAppWrapper {
 			window.webContents.setZoomFactor(this.mainWindow().webContents.getZoomFactor());
 
 			window.once('close', () => {
+				if (this.win_ && !this.win_.isDestroyed() && !this.win_.webContents.isDestroyed()) {
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/ElectronAppWrapper.ts]: Are both `this.win_.isDestroyed()` and `this.win_.webContents.isDestroyed()` necessary? If so, consider including a brief comment explaining why.

File: packages/app-desktop/ElectronAppWrapper.ts [hunk 2]
```diff
@@ -411,7 +411,11 @@ export default class ElectronAppWrapper {
 		// OS-level focus gain without conflating it with the 'window-focused' channel that
 		// handles Joplin-internal window routing.
 		this.win_.on('focus', () => {
-			this.win_?.webContents.send('main-window-focused');
+			try {
+				this.win_?.webContents.send('main-window-focused');
+			} catch (_error) {
+				// Renderer may be temporarily disposed after closing secondary windows
+			}
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/ElectronAppWrapper.ts]: If this error needs to be caught, consider converting it to a warning (e.g. with `console.warn`) to help future debugging.

**Review by personalizedrefrigerator — COMMENTED** [review]
For the most part, this looks good to me! See comments below for changes that could be good to have prior to merging.

**Comment by mrjo118** [comment]
I tested the change on this PR, and while it does fix the crash if I open 1 note in a new window then close it, if I open 2 notes in new windows and close them in the order which I opened them, then it still crashes with the same error.
I also managed to make the full UI freeze except the menu bar, though I don't know how to reproduce that.

**Review by personalizedrefrigerator — APPROVED** [review]
I'm marking this as approved:
- As per @mrjo118's [comment](https://github.com/laurent22/joplin/pull/14849#issuecomment-4111666451), this is better than the previous behavior.
- The code changes look good to me.

If this auto-closes https://github.com/laurent22/joplin/issues/14628 on merge, I plan to re-open it as "not resolved".

Possible things try in a follow-up pull request include:
- Increasing the ["close on unmount" timeout](https://github.com/laurent22/joplin/blob/741e1b19e5254b5aeb414a104c79d3573c280b51/packages/app-desktop/gui/NewWindowOrIFrame.tsx#L75).
- Rather than closing the window immediately when the close button is clicked (**update**: See [comment](https://github.com/laurent22/joplin/pull/14882#discussion_r2977050792)):
  1. Calling `.preventDefault` from the main [process's on secondary window close](https://github.com/laurent22/joplin/blob/741e1b19e5254b5aeb414a104c79d3573c280b51/packages/app-desktop/ElectronAppWrapper.ts#L483) handler.
  2. Also in the close listener, hiding the window with `.hide`.
  3. Waiting until the component has been fully unmounted to close the window from the main process.

File: packages/app-desktop/ElectronAppWrapper.ts (hunk 1 above)
Comment (Kaushalendra-Marcus) [reply packages/app-desktop/ElectronAppWrapper.ts]: added a comment explaining why both checks are needed

File: packages/app-desktop/ElectronAppWrapper.ts (hunk 2 above)
Comment (Kaushalendra-Marcus) [reply packages/app-desktop/ElectronAppWrapper.ts]: done, converted to console.warn for easier debugging.

**Comment by Kaushalendra-Marcus** [comment]
> I tested the change on this PR, and while it does fix the crash if I open 1 note in a new window then close it, if I open 2 notes in new windows and close them in the order which I opened them, then it still crashes with the same error. I also managed to make the full UI freeze except the menu bar, though I don't know how to reproduce that.

thank you for testing
the 2-window crash will be addressed in a follow up PR

**Comment by Kaushalendra-Marcus** [comment]
> I'm marking this as approved:
> 
> * As per @mrjo118's [comment](https://github.com/laurent22/joplin/pull/14849#issuecomment-4111666451), this is better than the previous behavior.
> * The code changes look good to me.
> 
> If this auto-closes #14628 on merge, I plan to re-open it as "not resolved".
> 
> Possible things try in a follow-up pull request include:
> 
> * Increasing the ["close on unmount" timeout](https://github.com/laurent22/joplin/blob/741e1b19e5254b5aeb414a104c79d3573c280b51/packages/app-desktop/gui/NewWindowOrIFrame.tsx#L75).
> * Rather than closing the window immediately when the close button is clicked:
>   
>   1. Calling `.preventDefault` from the main [process's on secondary window close](https://github.com/laurent22/joplin/blob/741e1b19e5254b5aeb414a104c79d3573c280b51/packages/app-desktop/ElectronAppWrapper.ts#L483) handler.
>   2. Also in the close listener, hiding the window with `.hide`.
>   3. Waiting until the component has been fully unmounted to close the window from the main process.

thank you for the review and suggestions
I will look into the follow up approaches for the multi window case in a separate PR

**Comment by personalizedrefrigerator** [comment]
> Rather than closing the window immediately when the close button is clicked (update: See https://github.com/laurent22/joplin/pull/14882#discussion_r2977050792):

Note: Implemented here: https://github.com/laurent22/joplin/pull/14892

**Update**: Even with #14892, the changes in this pull request seem to be necessary to fix the issue. See [comment](https://github.com/laurent22/joplin/pull/14892#issuecomment-4120962068).

**Comment by personalizedrefrigerator** [comment]
> The secondary window content is rendered via a React Portal from the main window's renderer process. When the secondary window is closed, Joplin polls every 2 seconds to detect it. During that gap, React keeps trying to render into an already-destroyed document, crashing the shared renderer process.

I'm not sure that this is related to React... I can still reproduce the crash if I disable the React portal rendering (closing blank secondary windows can still cause the crash).

**Comment by Kaushalendra-Marcus** [comment]
> I'm not sure that this is related to React... I can still reproduce the crash if I disable the React portal rendering (closing blank secondary windows can still cause the crash).

Thank you for investigating further. I've updated the PR description to reflect this - the React Portal explanation has been replaced with a reference to the Electron-level assertion failure and electron/electron#33868.

**Comment by mrjo118** [comment]
@Kaushalendra-Marcus Please resolve the conflicts

@laurent22 FYI this PR is still required, as Henry's PR fixes related use cases, but not the case as per the repro steps on the linked issue

**Comment by mrjo118** [comment]
@Kaushalendra-Marcus The conflicts were not resolved correctly. It looks like you completely removed the change made in https://github.com/laurent22/joplin/pull/14892/changes and also your change is no longer fixing the linked issue anymore, as I still get that crash with the latest code.

EDIT: I've created PR https://github.com/laurent22/joplin/pull/14953 to resolve the issue

**Comment by laurent22** [comment]
> @Kaushalendra-Marcus The conflicts were not resolved correctly. It looks like you completely removed the change made in https://github.com/laurent22/joplin/pull/14892/changes and also your change is no longer fixing the linked issue anymore, as I still get that crash with the latest code.

What was actually merged in this PR? I see there are indeed changes after it was approved. Should we revert it then if it's doesn't fix the issue?

**Comment by mrjo118** [comment]
> > @Kaushalendra-Marcus The conflicts were not resolved correctly. It looks like you completely removed the change made in https://github.com/laurent22/joplin/pull/14892/changes and also your change is no longer fixing the linked issue anymore, as I still get that crash with the latest code.
> 
> What was actually merged in this PR? I see there are indeed changes after it was approved. Should we revert it then if it's doesn't fix the issue?

I don't think there's a need to revert now that I've made a PR which re-applies the missing changes. I compared what is on that PR upon merge with a git patch I made before from it, in order to work out the differences

**Comment by Kaushalendra-Marcus** [comment]
I apologize for the incorrect conflict resolution - the changes from #14892 were accidentally removed during the merge. Thank you to @mrjo118 for creating #14953 to restore the missing changes. No need to revert, #14953 should address this properly.
