### PR TITLE
All: Resolves #3528: Upload Big Notes to Onedrive

### LINKED ISSUE #3528: OneDrive Error when uploading very large notes
Reported in the [forum](https://discourse.joplinapp.org/t/last-error-error-the-maximum-request-length-supported-is-4mb/10129). OneDrive gives the error: `Last error: Error: The maximum request length supported is 4MB.`  when you have a note with a very big amount of text (basically the text needs to be bigger than > 4 MB). I am not sure why an user would have such a big note but it seems that some users have such note as it have been posted on the forum. 

## Environment

Joplin version: 1.0.229
Platform: All platforms

## Steps to reproduce

1. Select OneDrive as sync target  
2. Import a markdown file > 4 MB as note
3. Synchronize 

## Logfile
Given in the  [forum](https://discourse.joplinapp.org/t/last-error-error-the-maximum-request-length-supported-is-4mb/10129)

### PR DESCRIPTION
**Pull request by jonath92**
I fixed the current limitation not being able to upload Notes > 4 MB to OneDrive. As this has been reported already twice on the forum this seems to happen more often than you would expect. 

Unfortunately I always received an `ECONNRESET` Error when using the `shim.fetch` method. That's why I used the native `fetch` method instead. Of course I googled this problem but couldn't find anything useful. If you or someone else give can me some hints how to fix this, I will do this and I am also happy to improve my code if you find anything else.  I didn't test it on mobile as it is very unlikely that this error occurs on mobile.

### CODE REVIEW

File: packages/lib/onedrive-api.js [hunk 1]
```diff
@@ -136,20 +136,35 @@ class OneDriveApi {
...
+
+		let response = null;
+		if (content && shim.isNode) {
+			// couldn't get it working with shim.fetch on desktop but works without problem with the native fetch.
+			// Always received `ECONNRESET` Error. Tried to disable compress option and increased timeout
+			// but didn't help.
+			response = await fetch(url,options);
+		} else {
+			response = await shim.fetch(url,options);
+		}
```
Comment (laurent22) [inline packages/lib/onedrive-api.js:166]: I understand why you've done this, but we can't have special cases like this across the codebase with some code using one fetch and other using a different one.

Also that code would bypass the retry and timeout mechanism as well as break in the CLI app, which doesn't have a native fetch. If native fetch is better in the desktop app, perhaps the shim can be updated to use it everywhere instead (but that would require extensive testing)? It would also still need to work with the CLI app which is going to use node-fetch.

Or perhaps the solution here is to use shim.fetchBlob?

Comment (jonath92) [reply packages/lib/onedrive-api.js]: Yes, I understand that.  I was afraid of that. It was an act of desperation to be honest :D. But I fixed it now. The reason for the error was that the object of options.body was an ArrayBuffer and not a Buffer.

File: packages/lib/onedrive-api.js [hunk 2]
```diff
@@ -179,32 +192,34 @@ class OneDriveApi {
...
-						endByte = fileSize - 1;
-						contentLength = fileSize - ((numberOfChunks - 1) * chunkSize);
+						endByte = byteSize - 1;
+						contentLength = byteSize - ((numberOfChunks - 1) * chunkSize);
 					} else {
 						endByte = (i + 1) * chunkSize - 1;
 						contentLength = chunkSize;
 					}
-					this.logger().debug(`${options.path}: Uploading File Fragment ${(startByte / 1048576).toFixed(2)} - ${(endByte / 1048576).toFixed(2)} from ${(fileSize / 1048576).toFixed(2)} Mbit ...`);
+					this.logger().debug(`Uploading File Fragment ${(startByte / 1048576).toFixed(2)} - ${(endByte / 1048576).toFixed(2)} from ${(byteSize / 1048576).toFixed(2)} Mbit ...`);
```
Comment (jonath92) [inline packages/lib/onedrive-api.js:201]: I removed the options.path because this is undefined in case of note and it was not really useful anyway.

File: packages/lib/onedrive-api.js (hunk 1 above)
Comment (laurent22) [reply packages/lib/onedrive-api.js]: >  The reason for the error was that the object of options.body was an ArrayBuffer and not a Buffer.

That's good to know, thanks for looking into @jonath92.

**Comment by laurent22** [comment]
To verify that the fix handles all possible cases, please could run the tests using OneDrive as sync target? To do so you would need to modify test-utils.js here to use OneDrive:

https://github.com/laurent22/joplin/blob/544d879c0b1a5c166e8d64aee2b4871daf08cfa5/packages/app-cli/tests/test-utils.js#L124

Then create a token file as described there:

https://github.com/laurent22/joplin/blob/544d879c0b1a5c166e8d64aee2b4871daf08cfa5/packages/app-cli/tests/test-utils.js#L444

Finally to run the tests you would go in `packages/app-cli` then run `npm test -- synchronizer`. If you need some help with that, please let me know.

**Comment by laurent22** [comment]
Actually I haven't tried OneDrive test units with Jest (before we were using Jasmine), so it's possible you will need to adjust the timeout as was done for Jasmine:

https://github.com/laurent22/joplin/blob/544d879c0b1a5c166e8d64aee2b4871daf08cfa5/packages/app-cli/tests/test-utils.js#L136

I don't know if there's even a timeout for Jest, if there isn't then it should just work.

**Comment by jonath92** [comment]
Unfortunately I wasn't able to run the test successful. I merged the current dev branch in my local branch. And as you said I removed the comment for onedrive in `test.utils.js` and commented memory out as SyncTarget. Then I opened the link for creating the Redirect URL and copied the full URL (which look like that `https://joplinapp.org#access_token=....`) in `.joplin/packes/app-cli/tests/support/onedrive-auth.txt`. After that I ran the command  `npm test -- synchronizer` in the `/packages/app-cli` directory.  However I got some errors which I could fix by a fresh install of joplin (i.e running `npm install` in the root directory) but after that I received the following errors which I don't know how to fix. I don't know how to adjust the timeout although I don't think that this is the reason for the error. 

```
> joplin@1.4.3 test /home/jonathan/Projekte/joplin/packages/app-cli
> jest --config=jest.config.js --runInBand --bail --forceExit "synchronizer"


  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Unhandled Rejection at: Promise Promise {
      <rejected> TypeError: Cannot read property 'put' of undefined
          at LockHandler.<anonymous> (/home/jonathan/Projekte/joplin/packages/lib/services/synchronizer/LockHandler.ts:149:19)
          at Generator.next (<anonymous>)
          at /home/jonathan/Projekte/joplin/packages/lib/services/synchronizer/LockHandler.js:31:67
          at new Promise (<anonymous>)
          at Object.<anonymous>.__awaiter (/home/jonathan/Projekte/joplin/packages/lib/services/synchronizer/LockHandler.js:10:10)
          at LockHandler.saveLock (/home/jonathan/Projekte/joplin/packages/lib/services/synchronizer/LockHandler.js:175:12)
          at LockHandler.<anonymous> (/home/jonathan/Projekte/joplin/packages/lib/services/synchronizer/LockHandler.ts:154:15)
          at Generator.next (<anonymous>)
          at /home/jonathan/Projekte/joplin/packages/lib/services/synchronizer/LockHandler.js:31:67
          at new Promise (<anonymous>)
    } reason: TypeError: Cannot read property 'put' of undefined
        at LockHandler.<anonymous> (/home/jonathan/Projekte/joplin/packages/lib/services/synchronizer/LockHandler.ts:149:19)
        at Generator.next (<anonymous>)
        at /home/jonathan/Projekte/joplin/packages/lib/services/synchronizer/LockHandler.js:31:67
        at new Promise (<anonymous>)
        at Object.<anonymous>.__awaiter (/home/jonathan/Projekte/joplin/packages/lib/services/synchronizer/LockHandler.js:10:10)
        at LockHandler.saveLock (/home/jonathan/Projekte/joplin/packages/lib/services/synchronizer/LockHandler.js:175:12)
        at LockHandler.<anonymous> (/home/jonathan/Projekte/joplin/packages/lib/services/synchronizer/LockHandler.ts:154:15)
        at Generator.next (<anonymous>)
        at /home/jonathan/Projekte/joplin/packages/lib/services/synchronizer/LockHandler.js:31:67
        at new Promise (<anonymous>)".

      147 | 
      148 |     private async saveLock(lock: Lock) {
    > 149 |             await this.api_.put(this.lockFilePath(lock), JSON.stringify(lock));
          |                             ^
      150 |     }
      151 | 
      152 |     // This is for testing only

      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:149:19)
      at ../lib/services/synchronizer/LockHandler.js:31:67
      at Object.<anonymous>.__awaiter (../lib/services/synchronizer/LockHandler.js:10:10)
      at LockHandler.saveLock (../lib/services/synchronizer/LockHandler.js:175:12)
      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:154:15)
      at ../lib/services/synchronizer/LockHandler.js:31:67
      } reason: TypeError: Cannot read property 'put' of undefined
      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:149:19)
      at ../lib/services/synchronizer/LockHandler.js:31:67
      at Object.<anonymous>.__awaiter (../lib/services/synchronizer/LockHandler.js:10:10)
      at LockHandler.saveLock (../lib/services/synchronizer/LockHandler.js:175:12)
      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:154:15)
      at ../lib/services/synchronizer/LockHandler.js:31:67
      at console.log (node_modules/@jest/console/build/BufferedConsole.js:197:10)
      at process.<anonymous> (tests/synchronizer_LockHandler.ts:54:5)

 FAIL  tests/synchronizer_LockHandler.js
  ● Console

    console.info
      Testing with sync target: onedrive

      at Object.<anonymous> (tests/test-utils.js:130:9)

  ● synchronizer_LockHandler › should acquire and release a sync lock

    TypeError: Cannot read property 'driveId' of null

      76 | 
      77 |      async appDirectory() {
    > 78 |              const driveId = this.accountProperties_.driveId;
         |                                                      ^
      79 |              const r = await this.execJson('GET', `/me/drives/${driveId}/special/approot`);
      80 |              return `${r.parentReference.path}/${r.name}`;
      81 |      }

      at OneDriveApi.appDirectory (../lib/onedrive-api.js:78:43)
      at initFileApi (tests/test-utils.js:458:28)
      at setupDatabaseAndSynchronizer (tests/test-utils.js:322:9)

  ● synchronizer_LockHandler › should not use files that are not locks

    TypeError: Cannot read property 'delete' of undefined

      348 | 
      349 |     async releaseLock(lockType: LockType, clientType: string, clientId: string) {
    > 350 |             await this.api_.delete(this.lockFilePath({
          |                             ^
      351 |                     type: lockType,
      352 |                     clientType: clientType,
      353 |                     clientId: clientId,

      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:350:19)
      at ../lib/services/synchronizer/LockHandler.js:31:67
      at Object.<anonymous>.__awaiter (../lib/services/synchronizer/LockHandler.js:10:10)
      at LockHandler.releaseLock (../lib/services/synchronizer/LockHandler.js:381:12)
      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:192:15)
          at Generator.throw (<anonymous>)
      at rejected (../lib/services/synchronizer/LockHandler.js:21:32)

  ● synchronizer_LockHandler › should allow multiple sync locks

    TypeError: Cannot read property 'put' of undefined

      53 | 
      54 |      it('should not use files that are not locks', asyncTest(async () => {
    > 55 |              await fileApi().put('locks/desktop.ini', 'a');
         |                           ^
      56 |              await fileApi().put('locks/exclusive.json', 'a');
      57 |              await fileApi().put('locks/garbage.json', 'a');
      58 |              await fileApi().put('locks/sync_mobile_72c4d1b7253a4475bfb2f977117d26ed.json', 'a');

      at Suite.<anonymous> (tests/synchronizer_LockHandler.ts:55:16)
      at tests/synchronizer_LockHandler.js:31:67
      at Object.<anonymous>.__awaiter (tests/synchronizer_LockHandler.js:10:10)
      at callback (tests/synchronizer_LockHandler.ts:54:69)
      at Object.<anonymous> (tests/test-utils.js:557:10)

  ● synchronizer_LockHandler › should auto-refresh a lock

    TypeError: Cannot read property 'delete' of undefined

      348 | 
      349 |     async releaseLock(lockType: LockType, clientType: string, clientId: string) {
    > 350 |             await this.api_.delete(this.lockFilePath({
          |                             ^
      351 |                     type: lockType,
      352 |                     clientType: clientType,
      353 |                     clientId: clientId,

      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:350:19)
      at ../lib/services/synchronizer/LockHandler.js:31:67
      at Object.<anonymous>.__awaiter (../lib/services/synchronizer/LockHandler.js:10:10)
      at LockHandler.releaseLock (../lib/services/synchronizer/LockHandler.js:381:12)
      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:192:15)
          at Generator.throw (<anonymous>)
      at rejected (../lib/services/synchronizer/LockHandler.js:21:32)

  ● synchronizer_LockHandler › should call the error handler when lock has expired while being auto-refreshed

    TypeError: Cannot read property 'delete' of undefined

      348 | 
      349 |     async releaseLock(lockType: LockType, clientType: string, clientId: string) {
    > 350 |             await this.api_.delete(this.lockFilePath({
          |                             ^
      351 |                     type: lockType,
      352 |                     clientType: clientType,
      353 |                     clientId: clientId,

      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:350:19)
      at ../lib/services/synchronizer/LockHandler.js:31:67
      at Object.<anonymous>.__awaiter (../lib/services/synchronizer/LockHandler.js:10:10)
      at LockHandler.releaseLock (../lib/services/synchronizer/LockHandler.js:381:12)
      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:192:15)
          at Generator.throw (<anonymous>)
      at rejected (../lib/services/synchronizer/LockHandler.js:21:32)

  ● synchronizer_LockHandler › should not allow sync locks if there is an exclusive lock

    TypeError: Cannot read property 'delete' of undefined

      348 | 
      349 |     async releaseLock(lockType: LockType, clientType: string, clientId: string) {
    > 350 |             await this.api_.delete(this.lockFilePath({
          |                             ^
      351 |                     type: lockType,
      352 |                     clientType: clientType,
      353 |                     clientId: clientId,

      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:350:19)
      at ../lib/services/synchronizer/LockHandler.js:31:67
      at Object.<anonymous>.__awaiter (../lib/services/synchronizer/LockHandler.js:10:10)
      at LockHandler.releaseLock (../lib/services/synchronizer/LockHandler.js:381:12)
      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:192:15)
          at Generator.throw (<anonymous>)
      at rejected (../lib/services/synchronizer/LockHandler.js:21:32)

  ● synchronizer_LockHandler › should not allow exclusive lock if there are sync locks

    TypeError: Cannot read property 'delete' of undefined

      348 | 
      349 |     async releaseLock(lockType: LockType, clientType: string, clientId: string) {
    > 350 |             await this.api_.delete(this.lockFilePath({
          |                             ^
      351 |                     type: lockType,
      352 |                     clientType: clientType,
      353 |                     clientId: clientId,

      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:350:19)
      at ../lib/services/synchronizer/LockHandler.js:31:67
      at Object.<anonymous>.__awaiter (../lib/services/synchronizer/LockHandler.js:10:10)
      at LockHandler.releaseLock (../lib/services/synchronizer/LockHandler.js:381:12)
      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:261:15)
          at Generator.throw (<anonymous>)
      at rejected (../lib/services/synchronizer/LockHandler.js:21:32)

  ● synchronizer_LockHandler › should allow exclusive lock if the sync locks have expired

    TypeError: Cannot read property 'delete' of undefined

      348 | 
      349 |     async releaseLock(lockType: LockType, clientType: string, clientId: string) {
    > 350 |             await this.api_.delete(this.lockFilePath({
          |                             ^
      351 |                     type: lockType,
      352 |                     clientType: clientType,
      353 |                     clientId: clientId,

      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:350:19)
      at ../lib/services/synchronizer/LockHandler.js:31:67
      at Object.<anonymous>.__awaiter (../lib/services/synchronizer/LockHandler.js:10:10)
      at LockHandler.releaseLock (../lib/services/synchronizer/LockHandler.js:381:12)
      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:192:15)
          at Generator.throw (<anonymous>)
      at rejected (../lib/services/synchronizer/LockHandler.js:21:32)

  ● synchronizer_LockHandler › should decide what is the active exclusive lock

    TypeError: Cannot read property 'delete' of undefined

      348 | 
      349 |     async releaseLock(lockType: LockType, clientType: string, clientId: string) {
    > 350 |             await this.api_.delete(this.lockFilePath({
          |                             ^
      351 |                     type: lockType,
      352 |                     clientType: clientType,
      353 |                     clientId: clientId,

      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:350:19)
      at ../lib/services/synchronizer/LockHandler.js:31:67
      at Object.<anonymous>.__awaiter (../lib/services/synchronizer/LockHandler.js:10:10)
      at LockHandler.releaseLock (../lib/services/synchronizer/LockHandler.js:381:12)
      at LockHandler.<anonymous> (../lib/services/synchronizer/LockHandler.ts:192:15)
          at Generator.throw (<anonymous>)
      at rejected (../lib/services/synchronizer/LockHandler.js:21:32)

Test Suites: 1 failed, 1 of 3 total
Tests:       9 failed, 9 total
Snapshots:   0 total
Time:        3.729 s
Ran all test suites matching /synchronizer/i.
npm ERR! Test failed.  See above for more details.
` ``

**Comment by laurent22** [comment]
Thanks for giving it a try, it seems Jest runs the tests in a more efficient way than Jasmine, but then it means certain hidden bugs with regards to non awaited promises are popping up. I will need to run these test suite for the Joplin Server sync target, so I'll look at it at that time and try to fix the issues. Hopefully that should also make it work for OneDrive too.

**Comment by laurent22** [comment]
@jonath92, could you give the test units another try please? As now they all seem to pass on dev branch. Just one thing to keep in mind is that for OneDrive they need to be run sequentially, so you would start them with `npm test -- --runInBand` from packages/app-cli

**Comment by laurent22** [comment]
@jonath92, the test units can run now but there's a problem with the code:

> ReferenceError: Blob is not defined
>           at FileApiDriverOneDrive.put (packages/lib/file-api-driver-onedrive.js:143)

Perhaps you need to add an additional package for it to work in Node and Electron?

**Comment by jonath92** [comment]
sorry but I don't have much time at the moment. I will have a look at 28th if that is ok?

**Comment by laurent22** [comment]
Sure there's no rush, I just thought I'd give a try to the test units just in case it just works.

**Comment by jonath92** [comment]
I don't understand why the test has failed because when testing it manually it worked on mobile @laurent22 . However I have changed it now so that is also passing the test now.

File: packages/lib/onedrive-api.js [hunk 3]
```diff
@@ -4,6 +4,8 @@ const time = require('./time').default;
 const Logger = require('./Logger').default;
 const { _ } = require('./locale');
 const urlUtils = require('./urlUtils.js');
+const str2ab = require('string-to-arraybuffer');
```
Comment (laurent22) [inline packages/lib/onedrive-api.js:7]: I would prefer if we don't add this package as it's unsupported, and I expect not necessary. Node buffer supports many formats - is it not possible to use one of its helper functions to load the content?

**Review by laurent22 — COMMENTED** [review]
The error was due to unrelated linter issues on dev branch, so I've triggered a rebuilt to see if it passes now. So you are saying it now works on both mobile and when running the test units on Node?

**Comment by jonath92** [comment]
Thanks for your patience @laurent22. Now it is working on mobile and when running the test units on Node without additional packages.

**Comment by laurent22** [comment]
Perfect, thanks for the update @jonath92 and happy new year!
