### PR TITLE
Desktop: Resolves #4813 : skip empty lines while converting selection to list 

### LINKED ISSUE #4813: Converting a selection to a bulleted or numbered list results in adding an extra row to the list
## Environment

Joplin version: 1.7.11
Platform: Linux 
OS specifics: Ubuntu 20.04 LTS

## Steps to reproduce

After selecting a block of text (see screenshot) and clicking the "Bulleted list" button in the toolbar, an additional `-` bullet item is added to the row immediately below the selection:

(selected 3 rows)
image

After converting to a bulleted list (selection was extended automatically by the editor):
image

## Describe what you expected to happen

- Only convert the selected rows to a bulleted list. 

- Note that the same issue occurs when converting  a selection to a Numbered List. 

- Changing the font appearance (i.e. Bold/Italic) works as expected - changes are only applied to selection.

### PR DESCRIPTION
**Pull request by lkiThakur**
Before 
before
After Fix
fixed
Steps:
1. Copy paste following content to joplin
item1  
item2  
item3  
a paragraph

2. Take cursor to beggining of document and press `shift+down arrow` thrice to select 1st 3 lines.
3. Toggle list using editor toolbar.

### CODE REVIEW

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts [hunk 1]
```diff
@@ -89,6 +89,7 @@ export default function useCursorUtils(CodeMirror: any) {
 
 				for (let j = 0; j < lines.length; j++) {
 					const line = lines[j];
+					if (!line) continue;
```
Comment (roman-r-m) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts:92]: Maybe it should be `break` instead?
What'd happen if you select the text below and convert it to a list?
```
list
list


not list

```

Comment (lkiThakur) [reply packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts:92]: > What'd happen if you select the text below and convert it to a list?
## After the fix:
### Case 1: Only 1st and 2nd lines are selected
 Both 1st and 2nd lines will be converted to list; 

### Case 2: All four lines are selected
"All except third (empty)"  line will be converted to list.

> Before fix : in case 2 above; all 4 lines will be converted to list

Comment (lkiThakur) [reply packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts:92]: > Maybe it should be `break` instead?
I'm not sure; It depends on what is the expected behaviour for the case you described?

Comment (CalebJohn) [reply packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts:92]: I just checked the behaviour of google docs and microsoft word. It looks like Word behaves with the continue behaviour. Google docs just adds a bullet to every line. 

I have no personal preference, but someone else might. It could probably be worth putting this to a poll on the forum.

Comment (lkiThakur) [reply packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts:92]: [LInk](https://discourse.joplinapp.org/t/expected-behaviour-when-creating-list-using-toolbar/16683) to the poll on joplin forum.

**Comment by laurent22** [comment]
By the way, from the look of it there's again an opportunity to add tests here. As I understand a good part of the function simply processes some strings so that could be extracted to a function and properly unit tested. Maybe with a bit of extra effort it's even possible to setup tests for the whole hook.

**Comment by lkiThakur** [comment]
I've added the tests and some modifications are done  in the file to be tested to implement tests.

I manually tested inserting and removing lists to ensure that i did not broke anything while trying to test it.

one additional test will be added when result of [this poll](https://discourse.joplinapp.org/t/expected-behaviour-when-creating-list-using-toolbar/16683) is filnalised.

**Comment by laurent22** [comment]
For the list behaviour, it seems the most common across editors is this one:

image

So could you implement it that way please?

**Comment by lkiThakur** [comment]
ollist-2021-04-27_16 26 59

I have made changes to get the behaviour as asked by laurent sir in the above message.
The code used to achive this behaviour is written in a way so as to allow easy switching to other behaviours in consideration.

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts [hunk 2]
```diff
@@ -1,6 +1,24 @@
 import markdownUtils from '@joplin/lib/markdownUtils';
 import Setting from '@joplin/lib/models/Setting';
-
+export function modifyListLines(lines: string[],num: number,string1: string) {
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts:3]: Please could you give a descriptive name to "string1"?

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts [hunk 3]
```diff
@@ -1,6 +1,24 @@
...
+	for (let j = 0; j < lines.length; j++) {
+		const line = lines[j];
+		if (!line && j == lines.length - 1) continue;
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts:6]: strict equality `===`

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts [hunk 4]
```diff
@@ -1,20 +1,21 @@
 import markdownUtils from '@joplin/lib/markdownUtils';
 import Setting from '@joplin/lib/models/Setting';
-export function modifyListLines(lines: string[],num: number,string1: string) {
+export function modifyListLines(lines: string[],num: number,listSymbol: string) {
+	console.log(listSymbol,':string');
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts:4]: Console
