### PR TITLE
Desktop: Fixes #9304: Fix HTML resource links lost when editing notes in the rich text editor

### LINKED ISSUE #9304: Editing an HTML note in the rich text editor removes resource links
## Operating system

macOS

## Joplin version

2.13.5

## Desktop version info

Joplin 2.13.5 (prod, darwin)

Client ID: 64df9fdc01c6479ead3a1f7b132d48a6
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 1d04ec6

## Current behaviour

Editing an HTML note with an attachment link in the rich text editor clears the link's target. For example,

```html
<a href=":/93d25985c31c4aad91d5e710390de5f1" alt="syncReport-1689640089262.txt">syncReport-1689640089262.txt</a>
```

becomes

```html
<p><a data-from-md="" href="#">syncReport-1689640089262.txt</a>. Some edit here.</p>
```

### Reproduction steps
1. Create a new HTML note (for example, by exporting a note as HTML,  then importing it as HTML)
2. Open the note in the markdown/HTML editor (HTML in this case)
3. Delete the note's content
4. Attach a file to the note using the "attach" button
5. Switch to the rich text editor
6. Edit the note
7. Switch back to the markdown/HTML editor

## Expected behaviour

The resource link should be preserved.

## Logs

**Note**: This log is from the Electron development tools and starts just before attaching a resource to the HTML note.
```
Logger.ts:254 07:58:35: Preparing scheduled sync
Logger.ts:254 07:58:35: Starting scheduled sync
Logger.ts:254 07:58:35: Synchronizer: Sync: starting: Starting synchronisation to target 3... supportsAccurateTimestamp = false; supportsMultiPut = false [1699977515154]
Logger.ts:254 07:58:35: Synchronizer: Indexing resources...
Logger.ts:254 07:58:35: ResourceService::indexNoteResources: Start
Logger.ts:254 07:58:35: ResourceService::indexNoteResources: Completed
Logger.ts:254 07:58:35: Synchronizer: Sync target remote info: SyncInfo {version_: 3, masterKeys_: Array(5), e2ee_: {…}, activeMasterKeyId_: {…}, ppk_: {…}}
Logger.ts:254 07:58:35: Synchronizer: Sync target is already setup - checking it...
Logger.ts:254 07:58:35: Synchronizer: Sync target local info: SyncInfo {version_: 3, masterKeys_: Array(5), e2ee_: {…}, activeMasterKeyId_: {…}, ppk_: {…}}
useMessageHandler.ts:18 Got ipc-message: noteRenderComplete undefined
Logger.ts:254 07:58:37: Synchronizer: Sync: updateRemote: local has changes: Note: (Local dd659c3451ff488eb6dd27fce922d4f9): (Remote dd659c3451ff488eb6dd27fce922d4f9.md)
Logger.ts:254 07:58:37: Synchronizer: Processing a path that has already been done: dd659c3451ff488eb6dd27fce922d4f9.md. sync_time was not updated? Remote item has an updated_time in the future?
Logger.ts:254 07:58:37: Synchronizer: Sync: finished: Synchronisation finished [1699977515154]
Logger.ts:254 07:58:37: Synchronizer: Operations completed: 
Logger.ts:254 07:58:37: Synchronizer: updateRemote: 1
Logger.ts:254 07:58:37: Synchronizer: Total folders: 25
Logger.ts:254 07:58:37: Synchronizer: Total notes: 717
Logger.ts:254 07:58:37: Synchronizer: Total resources: 982
Logger.ts:254 07:58:37: Sync has finished and note has never been changed - reloading it
Logger.ts:254 07:58:41: resourceHandling: Attaching /Users/MyUserName/Downloads/Link text.pdf
Logger.ts:254 07:58:41: resourceHandling: File was attached.
useMessageHandler.ts:18 Got ipc-message: noteRenderComplete undefined
TinyMCE.tsx:336 Loading script /Applications/Joplin.app/Contents/Resources/app.asar/vendor/lib/tinymce/tinymce.min.js
loadScript.ts:14 Loading script: {src: '/Applications/Joplin.app/Contents/Resources/app.asar/vendor/lib/tinymce/tinymce.min.js', id: 'tinyMceScript', loaded: false}
TinyMCE.tsx:336 Loading script gui/NoteEditor/NoteBody/TinyMCE/plugins/lists.js
loadScript.ts:14 Loading script: {src: 'gui/NoteEditor/NoteBody/TinyMCE/plugins/lists.js', id: 'tinyMceListsPluginScript', loaded: false}
useMessageHandler.ts:18 Got ipc-message: noteRenderComplete null
useMessageHandler.ts:18 Got ipc-message: noteRenderComplete null
Logger.ts:254 07:58:46: SearchEngine: Updating FTS table...
Logger.ts:254 07:58:47: SearchEngine: Updated FTS table in 21ms. Inserted: 1. Deleted: 0
useMessageHandler.ts:18 Got ipc-message: noteRenderComplete null
useMessageHandler.ts:18 Got ipc-message: noteRenderComplete null
2useMessageHandler.ts:18 Got ipc-message: noteRenderComplete undefined
```

## Additional information

This has also been tested on Linux (Ubuntu 23.10) with Joplin 2.12.19. The issue is present in that version as well.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

Fixes links to resources written in HTML would be discarded when editing a note in the rich text editor.

Fixes #9304.

# Testing

This pull request's Playwright test only covers the case where a resource link is added to a markdown note. As such, the HTML case must be tested manually. To do this,
1. Export a note as HTML
2. Import that note as HTML
3. Delete the content of the note
4. Attach a resource
5. Switch to the WYSIWYG editor
6. Switch back to the markdown editor

This has been successfully tested on Ubuntu 23.10.

# Notes

**HTML note only**: The resource link, after editing in the WYSIWYG editor, looks similar to this:
```
<p><a data-from-md="" href=":/fed66f2f1c214d8dbf0a6180b6788448" onclick="ipcProxySendToHost(&quot;:/fed66f2f1c214d8dbf0a6180b6788448&quot;, { resourceId: &quot;&quot; }); return false;">index.html</a>. This is a test...</p>
```

The `onclick` attribute is added by `HtmlToHtml` [here](https://github.com/laurent22/joplin/blob/aaa1dc853dd28d3f4796e95cc176f126d8646996/packages/renderer/MdToHtml/linkReplacement.ts#L103) (called [here](https://github.com/laurent22/joplin/blob/aaa1dc853dd28d3f4796e95cc176f126d8646996/packages/renderer/HtmlToHtml.ts#L126)).

When rendering in a way that will be saved in the database (and not directly shown in the note viewer), we should not add `onclick` handlers.

### CODE REVIEW

File: packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx [hunk 1]
```diff
@@ -42,6 +43,7 @@ function markupRenderOptions(override: MarkupToHtmlOptions = null): MarkupToHtml
 			},
 		},
 		replaceResourceInternalToExternalLinks: true,
+		allowedFilePrefixes: [Setting.value('resourceDir')],
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx]: **Note:** This currently allows `file://` URLs that point to the resource directory in all rendering done by the rich text editor.

I'm currently checking to see if this can be restricted to one of the several usages of `markupRenderOptions`. **Edit**: `allowedFilePrefixes` was moved.

File: packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx [hunk 2]
```diff
@@ -857,7 +858,18 @@ const TinyMCE = (props: NoteBodyEditorProps, ref: any) => {
...
+				const result = await props.markupToHtml(
+					props.contentMarkupLanguage,
+					props.content,
+					markupRenderOptions({
+						resourceInfos: props.resourceInfos,
+
+						// Allow file:// URLs that point to the resource directory.
+						// This prevents HTML-style resource URLs (e.g. <a href="file://path/to/resource/.../"></a>)
+						// from being discarded.
+						allowedFilePrefixes: [Setting.value('resourceDir')],
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx]: Would it be possible to pass this value as a prop to the component? It means we can remove the dependency to the Setting class

Comment (personalizedrefrigerator) [reply packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx]: Here are ~~two~~ three possible ways to do this:
1. Add as a property to `NoteBodyEditorProps` (which is already large)
    - Increasing the size of `NoteBodyEditorProps` makes it more difficult to mock in tests. 
2. Make `TinyMCE` a connected component (it currently isn't) and access `resourceDir` using Redux.
    - Making `TinyMCE` a connected component adds a direct dependency on Redux.


3. [`newMarkupToHtml`](https://github.com/laurent22/joplin/blob/3c40854a8ceb40415b2e52ae60f9322871623836/packages/app-desktop/gui/NoteEditor/utils/useMarkupToHtml.ts#L35) should already have access to the resource base URL. As such, an alternative approach could be to add an `allowResourceFileUrls` option.

Comment (laurent22) [reply packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx]: > Add as a property to NoteBodyEditorProps (which is already large)
> Increasing the size of NoteBodyEditorProps makes it more difficult to mock in tests.

I think this is fine. It's an annoyance but still better than making the component connected
