### PR TITLE
Mobile: Fixed the switch and slider on config screen

### LINKED ISSUE #2891: Mobile: The slider & buttons on the config page does not look good in OLED theme.
## Environment

Joplin version: 1.0.322
Platform: Mobile 
OS : Android

Light Theme:
img-1

img-2

OLED Theme:
img-3

img-4

## Describe what you expected to happen
They should be visible properly.

### PR DESCRIPTION
**Pull request by Rahulm2310**
**Before:**
77423682-c6538980-6df5-11ea-8281-333175b202f5

77423680-c489c600-6df5-11ea-8a38-28080e7d484a

**After:**
switch

slider

fixes #2891

### CODE REVIEW

File: ReactNativeClient/lib/components/screens/config.js [hunk 1]
```diff
@@ -391,7 +391,7 @@ class ConfigScreenComponent extends BaseScreenComponent {
 						<Text key="label" style={this.styles().switchSettingText}>
 							{md.label()}
 						</Text>
-						<Switch key="control" style={this.styles().switchSettingControl} value={value} onValueChange={value => updateSettingValue(key, value)} />
+						<Switch key="control" style={this.styles().switchSettingControl} trackColor={{ false: '#969696' }} value={value} onValueChange={value => updateSettingValue(key, value)} />
```
Comment (CalebJohn) [inline ReactNativeClient/lib/components/screens/config.js]: Please change these to values from the theme. Maybe this color can be integrated with style? If not it should still draw from the theme color.

Comment (Rahulm2310) [reply ReactNativeClient/lib/components/screens/config.js]: Sir, I tried it but it seems that it could not be integrated with style.But yeah, i will draw it from the theme color.

Comment (Rahulm2310) [reply ReactNativeClient/lib/components/screens/config.js]: @CalebJohn I have made the changes.Could you please review it

**Comment by Rahulm2310** [comment]
@PackElend please label me

**Comment by CalebJohn** [comment]
LGTM

File: ReactNativeClient/lib/components/screens/config.js [hunk 2]
```diff
@@ -409,7 +409,7 @@ class ConfigScreenComponent extends BaseScreenComponent {
 					</Text>
 					<View style={{ display: 'flex', flexDirection: 'row', alignItems: 'center', flex: 1 }}>
 						<Text style={this.styles().sliderUnits}>{unitLabel}</Text>
-						<Slider key="control" style={{ flex: 1 }} step={md.step} minimumValue={md.minimum} maximumValue={md.maximum} value={value} onValueChange={value => updateSettingValue(key, value)} />
+						<Slider key="control" style={{ flex: 1 }} maximumTrackTintColor={theme.settingComponentTintColor} step={md.step} minimumValue={md.minimum} maximumValue={md.maximum} value={value} onValueChange={value => updateSettingValue(key, value)} />
```
Comment (laurent22) [inline ReactNativeClient/lib/components/screens/config.js:412]: did you read the comment just above your change?

Comment (Rahulm2310) [reply ReactNativeClient/lib/components/screens/config.js:412]: Oops, sorry for that. I will remove it from the slider. But is it appropriate for the switch component ?

File: ReactNativeClient/lib/components/global-style.js [hunk 3]
```diff
@@ -39,6 +39,7 @@ const globalStyle = {
 	htmlCodeColor: 'rgb(0,0,0)',
 
 	codeThemeCss: 'atom-one-light.css',
+	settingComponentTintColor: '#969696',
```
Comment (laurent22) [inline ReactNativeClient/lib/components/global-style.js:42]: Please don't create a new property and re-use one of the existing colours.

**Comment by Rahulm2310** [comment]
@laurent22  Sir, I have made the changes

**Comment by laurent22** [comment]
Looks good, thank you @Rahulm2310!
