### PR TITLE
Make plugin links clickable from search

### LINKED ISSUE #4505: Link to Plugin doesn't work while searching
## Environment

Joplin version: Joplin 1.7.11 (prod, darwin)
Platform: Mac
OS specifics: OS version

## Steps to reproduce

1. Go to **Settings > Plugins**
2. Search for a plugin, i.e. `a`
3. Hover over the title and click
4. Does NOT take you to URL for plugin

## Describe what you expected to happen

Once the plugin is Installed, this link works. Would be nice to read about plugin before installing.

### PR DESCRIPTION
**Pull request by roman-r-m**
Fixes #4505

### CODE REVIEW

**Review by tessus — COMMENTED** [review]
LGTM

File: packages/app-desktop/gui/ConfigScreen/controls/plugins/PluginBox.tsx [hunk 1]
```diff
@@ -137,9 +137,10 @@ export default function(props: Props) {
 	const item = props.item ? props.item : manifestToItem(props.manifest);
 
 	const onNameClick = useCallback(() => {
-		if (!props.item.manifest.homepage_url) return;
-		bridge().openExternal(props.item.manifest.homepage_url);
-	}, [props.item]);
+		const manifest = props.item ? props.item.manifest : props.manifest;
+		if (!manifest.homepage_url) return;
+		bridge().openExternal(manifest.homepage_url);
+	}, [props.item, props.manifest]);
```
Comment (laurent22) [inline packages/app-desktop/gui/ConfigScreen/controls/plugins/PluginBox.tsx:143]: Instead of "props.item", could you directly use the "item" variable defined above?

Comment (roman-r-m) [reply packages/app-desktop/gui/ConfigScreen/controls/plugins/PluginBox.tsx]: Done

File: packages/app-desktop/gui/ConfigScreen/controls/plugins/PluginBox.tsx [hunk 2]
```diff
@@ -137,9 +137,10 @@ export default function(props: Props) {
 	const item = props.item ? props.item : manifestToItem(props.manifest);
 
 	const onNameClick = useCallback(() => {
-		if (!props.item.manifest.homepage_url) return;
-		bridge().openExternal(props.item.manifest.homepage_url);
-	}, [props.item]);
+		const manifest = item.manifest;
+		if (!manifest.homepage_url) return;
+		bridge().openExternal(manifest.homepage_url);
+	}, [props.item, props.manifest]);
```
Comment (laurent22) [inline packages/app-desktop/gui/ConfigScreen/controls/plugins/PluginBox.tsx:143]: Also please update the dependencies. I believe only `item` is now needed as a dependency.

Comment (roman-r-m) [reply packages/app-desktop/gui/ConfigScreen/controls/plugins/PluginBox.tsx]: Also done

File: packages/app-desktop/gui/ConfigScreen/controls/plugins/PluginBox.tsx [hunk 3]
```diff
@@ -137,8 +137,9 @@ export default function(props: Props) {
 	const item = props.item ? props.item : manifestToItem(props.manifest);
 
 	const onNameClick = useCallback(() => {
-		if (!props.item.manifest.homepage_url) return;
-		bridge().openExternal(props.item.manifest.homepage_url);
+		const manifest = item.manifest;
+		if (!manifest.homepage_url) return;
+		bridge().openExternal(manifest.homepage_url);
 	}, [props.item]);
```
Comment (laurent22) [inline packages/app-desktop/gui/ConfigScreen/controls/plugins/PluginBox.tsx:143]: The dependency should be `item`, not `props.item`. In fact, would you mind memoizing the `item` variable while you're at it? `const item = useMemo(() => { return props.item ? props.item : manifestToItem(props.manifest) }, [props.items, props.manifest])`

Comment (roman-r-m) [reply packages/app-desktop/gui/ConfigScreen/controls/plugins/PluginBox.tsx]: Also done

**Comment by laurent22** [comment]
Looks good now, thanks for the fix!
