### PR TITLE
fix(turndown-plugin-gfm): handle tables with captions

### LINKED ISSUE #5861: TABLE with CAPTION or COLGROUP render empty headers
This issue was originally [reported here](https://github.com/laurent22/joplin-turndown-plugin-gfm/issues/5) but it seems that repo has been archived, and the code now lives here.

Tables such as

```html
<table>
  <caption>My table</caption>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th> 
  </tr>
  <tr>
    <td>Jill</td>
    <td>Smith</td>
  </tr>
</table>
```

or

```html
<table>
  <colgroup>
    <col style="" />
    <col style="" />
  </colgroup>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th> 
  </tr>
  <tr>
    <td>Jill</td>
    <td>Smith</td>
  </tr>
</table>
```

Render an empty header, such as

```markdown
|     |     |
| --- | --- |My table
| Firstname | Lastname |
| Jill | Smith |
```

COLGROUP should be ignored, CAPTION should be displayed before the table. Expected output should be:

```markdown
My table
| Firstname | Lastname |
| --- | --- |
| Jill | Smith |
```

### PR DESCRIPTION
**Pull request by maxpatiiuk**
- [x] Fixes #5861 by adding support for `caption` elements so that they are correctly parsed, without breaking markdown syntax
- [x] Adds a test case for this
   - Unfortunately, I wasn't able to run the test as the build fails - maybe there is something wrong with my environment:

      <details>
      <summary>Build Failure</summary>

      ```yaml
      npm run build
      
      > @joplin/turndown-plugin-gfm@1.0.54 build
      > rollup -c config/rollup.config.cjs.js
      
      (node:1331) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
      (Use `node --trace-warnings ...` to show where the warning was created)
      [!] RollupError: Node tried to load your configuration file as CommonJS even though it is likely an ES module. To resolve this, change the extension of your configuration to ".mjs", set "type": "module" in your package.json file or pass the "--bundleConfigAsCjs" flag.
      
      Original error: Cannot use import statement outside a module
      https://rollupjs.org/command-line-interface/#bundleconfigascjs
      /Users/maxpatiiuk/site/git/joplin/packages/turndown-plugin-gfm/config/rollup.config.cjs.js:1
      import config from './rollup.config';
      ^^^^^^
      
      SyntaxError: Cannot use import statement outside a module
          at internalCompileFunction (node:internal/vm:77:18)
          at wrapSafe (node:internal/modules/cjs/loader:1288:20)
          at Module._compile (node:internal/modules/cjs/loader:1340:27)
          at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
          at Module.load (node:internal/modules/cjs/loader:1207:32)
          at Module._load (node:internal/modules/cjs/loader:1023:12)
          at cjsLoader (node:internal/modules/esm/translators:356:17)
          at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
          at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
          at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
      
      
      npm ERR! Lifecycle script `build` failed with error:
      npm ERR! Error: command failed
      npm ERR!   in workspace: @joplin/turndown-plugin-gfm@1.0.54
      npm ERR!   at location: /Users/maxpatiiuk/site/git/joplin/packages/turndown-plugin-gfm
      ```

      And after adding `"type": "module"` in package.json:

      ```yaml
      npm run build                                                                                                                                                                      5s
      
      > @joplin/turndown-plugin-gfm@1.0.54 build
      > rollup -c config/rollup.config.cjs.js
      
      [!] Error: Cannot find module '/Users/maxpatiiuk/site/git/joplin/packages/turndown-plugin-gfm/config/rollup.config' imported from /Users/maxpatiiuk/site/git/joplin/packages/turndown-plugin-gfm/config/rollup.config.cjs.js
      file:///Users/maxpatiiuk/site/git/joplin/packages/turndown-plugin-gfm/config/rollup.config
      Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/maxpatiiuk/site/git/joplin/packages/turndown-plugin-gfm/config/rollup.config' imported from /Users/maxpatiiuk/site/git/joplin/packages/turndown-plugin-gfm/config/rollup.config.cjs.js
          at finalizeResolution (node:internal/modules/esm/resolve:264:11)
          at moduleResolve (node:internal/modules/esm/resolve:917:10)
          at defaultResolve (node:internal/modules/esm/resolve:1130:11)
          at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
          at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
          at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
          at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
          at link (node:internal/modules/esm/module_job:84:36)
      
      
      npm ERR! Lifecycle script `build` failed with error:
      npm ERR! Error: command failed
      npm ERR!   in workspace: @joplin/turndown-plugin-gfm@1.0.54
      npm ERR!   at location: /Users/maxpatiiuk/site/git/joplin/packages/turndown-plugin-gfm
      ```

      </details>

### CODE REVIEW

**Comment by personalizedrefrigerator** [comment]
> Unfortunately, I wasn't able to run the test as the build fails - maybe there is something wrong with my environment:

Joplin uses `yarn`, so things might not work with `npm` ([see the build documentation](https://joplinapp.org/help/dev/BUILD#building)).

Additionally, we store new automated tests for `turndown` in [packages/app-cli/tests/html_to_md](https://github.com/laurent22/joplin/tree/dev/packages/app-cli/tests/html_to_md). These tests can be run with
```bash
bash$ cd packages/app-cli
bash$ yarn tsc
bash$ yarn test
```

**Comment by maxpatiiuk** [comment]
Fixed
Also added colgroup/col ignore and associated tests

File: packages/turndown-plugin-gfm/src/tables.js [hunk 1]
```diff
@@ -98,10 +98,23 @@ rules.table = {
       }
     }
 
-    return '\n\n' + emptyHeader + content + '\n\n'
+    var captionContent = node.caption == null ? '' : node.caption.textContent || '';
+    var caption = captionContent === '' ? '' : captionContent + '\n\n';
```
Comment (laurent22) [inline packages/turndown-plugin-gfm/src/tables.js]: Can we do something like this instead? `const captionContent = node.caption?.textContent || ''`

Also for new code please use `const` (or `let` but not `var`)

Comment (maxpatiiuk) [reply packages/turndown-plugin-gfm/src/tables.js]: > Can we do something like this instead?

absolutely - I wasn't sure if I was allowed to use new syntax in this file given how old the syntax around is

---

edit:

I'm having a build error when I try to use optional chaining:

```yaml
❯ yarn build-all

> @joplin/turndown-plugin-gfm@1.0.54 build-cjs
> rollup -c config/rollup.config.cjs.js && rollup -c config/rollup.config.browser.cjs.js


src/gfm.js → lib/turndown-plugin-gfm.cjs.js...
[!] Error: Unexpected token
src/tables.js (101:40)
 99:     }
100:
101:     const captionContent = node.caption?.textContent || '';
                                             ^
102:     const caption = captionContent === '' ? '' : `${captionContent}\n\n`;
103:     const tableContent = `${emptyHeader}${content}`.trimStart();

npm ERR! Lifecycle script `build-cjs` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @joplin/turndown-plugin-gfm@1.0.54
npm ERR!   at location: /Users/maxpatiiuk/site/git/joplin/packages/turndown-plugin-gfm
```

Looks like rollup version is 6 years old:

```yaml
❯ yarn rollup --version
rollup version 0.50.1
```

6 years worth of updates probably would have some breaking changes, so updating rollup is likely outside the scope of this PR.

Though, I was able to update the code to use `const` and template literals

File: packages/turndown-plugin-gfm/src/tables.js [hunk 2]
```diff
@@ -98,10 +98,23 @@ rules.table = {
       }
     }
 
-    return '\n\n' + emptyHeader + content + '\n\n'
+    const captionContent = node.caption == null ? '' : node.caption.textContent || '';
```
Comment (laurent22) [inline packages/turndown-plugin-gfm/src/tables.js]: just `!note.caption`

File: packages/turndown-plugin-gfm/src/tables.js [hunk 3]
```diff
@@ -98,10 +98,23 @@ rules.table = {
...
+    const caption = captionContent === '' ? '' : `${captionContent}\n\n`;
```
Comment (laurent22) [inline packages/turndown-plugin-gfm/src/tables.js]: `!captionContent`

File: packages/turndown-plugin-gfm/src/tables.js (hunk 2 above)
Comment (maxpatiiuk) [reply packages/turndown-plugin-gfm/src/tables.js]: okay, will change
I usually try to avoid implicit boolean casting (and have ESLint rules for that) to write more explicit, less flaky code

Comment (laurent22) [reply packages/turndown-plugin-gfm/src/tables.js]: You previously had a non-strict equality check which is flaky anyway. But in general it's not useful to strictly check for null, undefined, empty string, etc. and that might even introduce bugs. There are cases where it matters but not here. Here we just want to check if something exists and it doesn't matter if it's null, undefined, false or something else.
