### PR TITLE
All: Fixes #8561: Fix OneDrive sync crash on throttle

### LINKED ISSUE #8561: OneDrive sync issues
I use Microsoft OneDrive to sync 2 windows laptops and 1 android device. Encryption is enabled.

For all devices the synchronisation fails randomly with always the same error message: TypeError: On file ad59f2174a8c411b8d41d97cd6ee959b.md: Cannot read properties of undefined (reading 'retry-after')

This error is not always on the same .md file. For each one, I have checked it directly on OneDrive without issue.

## Environment
Joplin version: Joplin 2.11.11 (prod, win32) Révision : 6886f6f
Platform: Windows 10 64bit and Android 11

## Logfile
...
2023-07-26 18:56:17: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2023-07-26 18:56:17: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2023-07-26 18:56:18: Synchronizer: "BasicDelta: Report: {"timestamp":1690383254000,"older":1699,"newer":39,"equal":1}"
2023-07-26 18:56:18: Synchronizer: "Sync: fetchingTotal: Fetching delta items from sync target"
2023-07-26 18:56:18: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2023-07-26 18:56:18: Synchronizer: "Sync: fetchingProcessed: Processing fetched item"
2023-07-26 18:56:18: Synchronizer: "TypeError: On file ad59f2174a8c411b8d41d97cd6ee959b.md: Cannot read properties of undefined (reading 'retry-after')
TypeError: On file ad59f2174a8c411b8d41d97cd6ee959b.md: Cannot read properties of undefined (reading 'retry-after')
    at OneDriveApi.<anonymous> (C:\Users\me\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:339:244)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\me\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"
2023-07-26 18:56:18: Synchronizer: "Sync: finished: Synchronisation finished [1690390365688]"
2023-07-26 18:56:18: Synchronizer: "Operations completed: "
2023-07-26 18:56:18: Synchronizer: "fetchingTotal: 1762"
2023-07-26 18:56:18: Synchronizer: "fetchingProcessed: 1714"
2023-07-26 18:56:18: Synchronizer: "deleteLocal: 1"
2023-07-26 18:56:18: Synchronizer: "Total folders: 203"
2023-07-26 18:56:18: Synchronizer: "Total notes: 1147"
2023-07-26 18:56:18: Synchronizer: "Total resources: 478"
2023-07-26 18:56:18: Synchronizer: "There was some errors:"
2023-07-26 18:56:18: Synchronizer: "TypeError: On file ad59f2174a8c411b8d41d97cd6ee959b.md: Cannot read properties of undefined (reading 'retry-after')
TypeError: On file ad59f2174a8c411b8d41d97cd6ee959b.md: Cannot read properties of undefined (reading 'retry-after')
    at OneDriveApi.<anonymous> (C:\Users\me\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:339:244)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\me\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\onedrive-api.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)"
2023-07-26 18:56:18: "Sync has finished and note has never been changed - reloading it"
2023-07-26 18:56:19: "DecryptionWorker: starting decryption..."
2023-07-26 18:56:19: "DecryptionWorker: completed decryption."

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This should fix #8561. The code previously attempted to access headers through `response?.headers?._headers`, which seems to not exist.

`shim` uses `nodeFetch` internally on desktop and CLI, which [documents a `.get` method on `response.headers`](https://github.com/node-fetch/node-fetch#accessing-headers-and-other-metadata). This seems to be equivalent to the browser [`Headers.get`](https://developer.mozilla.org/en-US/docs/Web/API/Headers/get) method.

# Testing

**I have not managed to get throttled by OneDrive**. ~~As such, this pull request has only been tested with the included automated test.~~

I have verified that `headers.get` works for a sample request on mobile and desktop.

# Notes

I'm currently working on extending the existing mobile on-device tests to include a test for `shim.fetch`. Ideally all tests would run in CI (and pass) with `fsDriverNode` as well.

### CODE REVIEW

File: packages/lib/onedrive-api.ts [hunk 1]
```diff
@@ -343,14 +343,21 @@ export default class OneDriveApi {
...
 					continue;
-				} else if (error?.code === 'activityLimitReached' && response?.headers?._headers['retry-after'][0] && !isNaN(Number(response?.headers?._headers['retry-after'][0]))) {
+				} else if (error?.code === 'activityLimitReached') {
 					// Wait for OneDrive throttling
 					// Relavent Microsoft Docs: https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#best-practices-to-handle-throttling
 					// Decrement retry count as multiple sync threads will cause repeated throttling errors - this will wait until throttling is resolved to continue, preventing a hard stop on the sync
 					i--;
-					const sleepSeconds = response.headers._headers['retry-after'][0];
+
+					const retryAfter = response.headers?.get?.('retry-after') ?? 1;
```
Comment (personalizedrefrigerator) [inline packages/lib/onedrive-api.ts]:
```suggestion
					const retryAfter = response.headers?.get?.('retry-after') ?? '1';
```

`retryAfter` should be of type `string`.

Note that the conditionals were added here to handle the case that the `headers` API actually *doesn't* work this way for some types of `fetch` (e.g. do `fetchBlob`/`uploadBlob` always return a `Response` with `headers`?).

This should be checked.
