### PR TITLE
Desktop: Replace Ace with Code mirror

### LINKED ISSUE #3054: Desktop: Disable syntax highlighting inside Katex code
When using `<` inside Katex, the editor falsely recognize it as a HTML tag and messes up syntax highlighting. See below:

image

Use following snippet for reproducing:
```
Equation1

$$
\sum_{i<j}
$$


This text should not be highlighted. But it is.
```

## Environment

Joplin version: 1.0.200
Platform: Linux
OS specifics: Ubuntu 19.10 (5.3.0-46-generic)

## Steps to reproduce

1. Copy the above snippet into editor
2. See editor highlighting text incorrectly

## Describe what you expected to happen

The editor should ignore `<` or other mathematical symbols inside Katex.

### LINKED ISSUE #3229: Highlight is buggy when combined with LaTeX equations
When two distant LaTeX equations contain the symbol `_` (used for subscripts in LaTeX and for italic in Mrkdown), the text in between is highlighted as italic text. 

The same problem also occurs within the same equation if two `_` are present.

## Environment

Joplin version: 1.0.201 (e65af8c)
Platform: macOS
OS specifics: 10.14.4

## Steps to reproduce

Type the following in a note:

```
$x_i$ Lorem Ipsum $y_i$.
```

The text between `_` will be highlighted incorrectly as italic: `i$ Lorem Ipsum $y`

## Describe what you expected to happen

I expect `_` within equations to be ignored by the highlighter.

### LINKED ISSUE #3236: Nord theme markdown syntax needs improvement
After the last update the markdown syntax highlighting for the Nord theme had some colors changed. 

This is relevant only for the code editor, the preview is working fine.

This is how it looks at the moment:
image

## Environment

Joplin version: Joplin 1.0.211 (prod, darwin)
Platform: Mac OS

## Steps to reproduce

1. On settings, change the theme to "Nord"
2. Create new note
3. Type markdown syntax on the code editor and check the syntax highlight

## Describe what you expected to happen

This is how it should look, based on the Nord theme applied on other text editors

VSCode:
image

SublimeText:
image

Thank you so much for your hard work!

### LINKED ISSUE #3269: Inconsistent syntax highlighting colors in themes
This is a continuation of #2883 since that issue has been closed and the fix caused other issues.

## Example with "Dark" theme 

image
Syntax highlighting works as expected 

## "Solarized Dark" theme

image 
Since the changes in the latest version of Joplin, it looks like the colors from the "dark" theme was used for solarized. This changed the color of inline code from blue to yellow for instance. Technically syntax highlighting is added to everything now but don't think these are the solarized theme colors. It's a strange hybrid now.

Same text in gedit with solarized dark theme for comparison:
image
Note that inline code is blue (like it was in the previous Joplin version).

## "Solarized Light" theme
image
This is closer to the solarized colors but the list could use a bit more color as it doesn't stand out from the regular text. Furthermore, solarized light is the companion to solarized dark and the syntax highlighting colors should actually be similar between the two. Right now there is no consistency.

Same text in gedit with solarized light theme for comparison:
image

## "Dracula" theme
image
I'm not as familiar with this theme but I think the colors are missing/wrong for this as well.

Same text in VS Code with the official Dracula theme:
image

## "Nord" theme
image
I'm also not familiar with this theme but it looks like it is using the same colors as solarized light currently.

Same text in VS Code with the Nord theme:
image

#3236 Covers the issues with the Joplin Nord theme in more detail.

## Environment

Joplin version: 1.0.216
Platform: Linux
OS specifics: Solus 4.1

### PR DESCRIPTION
**Pull request by CalebJohn**
for reference #3269  #3236  #3054  #3229  #3147  #1762

As mentioned on the [forum](https://discourse.joplinapp.org/t/desktop-invisible-spacing/8400/) I've been experimenting with a transition to codemirror rather than ace editor. I still haven't finished the transition yet but so far things are looking really good. There was a lot of code in the old module that was necessary to get around Ace's quirks that has been removed. I still have quite a bit of refactoring to do but I have a functional base here if anyone is keen to test.

Perhaps more importantly codemirror works with non-monospace fonts :) It can also handle varying line heights (adjustable with css), and it supports inline images (will need to be added in a different pull request).
image

### CODE REVIEW

File: ElectronClient/gui/NoteEditor/NoteBody/AceEditor/AceEditor.tsx [hunk 1]
```diff
@@ -5,14 +5,15 @@ import { useState, useEffect, useRef, forwardRef, useCallback, useImperativeHand
 import { EditorCommand, NoteBodyEditorProps } from '../../utils/types';
```
Comment (laurent22) [inline ElectronClient/gui/NoteEditor/NoteBody/AceEditor/AceEditor.tsx:5]: Any reason for the changes on Ace Editor related files? The app can handle multiple text editors, which makes it much easier to migrate to other editors. In NoteEditor.tsx, you could simply import your CodeMirror component, then if props.bodyEditor === "CodeMirror", load it.

So I guess instead of changing the AceEditor files, you'd just copy what you've done so far to NoteBody/CodeMirror and revert the changes on the AceEditor files. If you need some more info on how to get it working let me know.

File: ElectronClient/gui/NoteEditor/NoteBody/AceEditor/CodeMirror.tsx [hunk 2]
```diff
@@ -0,0 +1,206 @@
...
+	theme: any,
+	readOnly: boolean,
+	autoMatchBraces: boolean,
+	keyMap: string,
+	cancelledKeys: CancelledKeys,
+	onChange: any,
+	onScroll: any,
+	onEditorContextMenu: any,
+	onEditorPaste: any,
+}
```
Comment (laurent22) [inline ElectronClient/gui/NoteEditor/NoteBody/AceEditor/CodeMirror.tsx:41]: The editor should support the NoteBodyEditorProps (doesn't have to support all of them, but that should be the input).

File: ElectronClient/gui/NoteEditor/NoteBody/AceEditor/CodeMirror.tsx [hunk 3]
```diff
@@ -0,0 +1,206 @@
...
+			props.onEditorContextMenu();
+		}
+	}, [props.onEditorContextMenu]);
+
+	// eslint-disable-next-line no-unused-vars, @typescript-eslint/no-unused-vars
+	const editor_paste = useCallback((_cm: any, _event: any) => {
+		props.onEditorPaste();
+	}, [props.onEditorPaste]);
+
+	const divRef = useCallback(node => {
```
Comment (laurent22) [inline ElectronClient/gui/NoteEditor/NoteBody/AceEditor/CodeMirror.tsx:142]: For references, you should probably use `useRef`. Then to initialise the editor, you can use `useEffect(() => {}, [])`

File: ElectronClient/gui/NoteEditor/NoteBody/AceEditor/AceEditor.tsx (hunk 1 above)
Comment (CalebJohn) [reply ElectronClient/gui/NoteEditor/NoteBody/AceEditor/AceEditor.tsx:5]: Basically just laziness, I didn't know the new aspects of the code very well and I didn't want to waste time figuring out how to support a third editor before I even had one working. 
I was initially planning on doing exactly what you suggested before making this public but decided it was better to get some visibility first. I'll definitely make those changes before taking this out of draft.

File: ElectronClient/gui/NoteEditor/NoteBody/AceEditor/CodeMirror.tsx (hunk 3 above)
Comment (CalebJohn) [reply ElectronClient/gui/NoteEditor/NoteBody/AceEditor/CodeMirror.tsx:142]: What's the benefit of this change? This function get's called with a reference to the div everytime it's loaded and unloaded, I otherwise don't need the reference. I'm happy to make the change, I'm just new to hooks and looking to learn it better.

Comment (laurent22) [reply ElectronClient/gui/NoteEditor/NoteBody/AceEditor/CodeMirror.tsx]: It's mostly to keep things more standard. I think the way you've done it, you've more or less reimplemented useRef.

Comment (CalebJohn) [reply ElectronClient/gui/NoteEditor/NoteBody/AceEditor/CodeMirror.tsx]: I see what you mean, I changed it in the way you suggested and it ended up being much cleaner. :+1:

File: ElectronClient/gui/NoteEditor/NoteBody/AceEditor/CodeMirror.tsx (hunk 2 above)
Comment (CalebJohn) [reply ElectronClient/gui/NoteEditor/NoteBody/AceEditor/CodeMirror.tsx]: I've restructured the code a bit, so what you're looking at here is basically a react wrapper around codemirror. There is another component that handles the integration with Joplin. Confusingly I've renamed that other one to CodeMirror.tsx and called the wrapper Editor.tsx.

**Comment by CalebJohn** [comment]
In reference to your 3 items.
1. Codemirror technically [does support](https://www.npmjs.com/package/@inkdropapp/codemirror-spell-checker) spellcheck, but when I did a quick test I wasn't able to get it working. Fortunately it's not that hard to get working with codemirror since it's fairly extendable.
2. For now I have variable sized headers set in style.css, but we can discuss how we want this done, the editor definitely supports it though!
3. Codemirror includes a builtin search function which I previously had turned on. It also has good support for marking arbitrary text (and reflecting the mark in the sidebar). I think the best option is to keep the joplin search and then write a custom plugin to integrate with it. I probably won't do that in this pull request, but it will be relatively straightforward.

Overall we also benefit by having an editor that's easier to interact with and won't require as much hacking to get basic functionality.

**Comment by laurent22** [comment]
> Codemirror technically does support spellcheck, but when I did a quick test I wasn't able to get it working. Fortunately it's not that hard to get working with codemirror since it's fairly extendable.

Eventually, I hope we can use the Atom spell checking package throughout the app to load dictionaries and get spelling suggestions, then each component (CodeMirror, TinyMCE, and title text input) would handle displaying the results. As long as CodeMirror has a well supported way to highlight terms then it's most likely good enough. Last time I've checked this with Ace Editor it was quite complicated.

> For now I have variable sized headers set in style.css, but we can discuss how we want this done, the editor definitely supports it though!

Ok that's good to know. It might be that we leave it as monospace by default, but it's good if users can change it, and that will also allow us to improve the default editor styling, with larger heading, bold fonts, etc.

> Codemirror includes a builtin search function which I previously had turned on. It also has good support for marking arbitrary text (and reflecting the mark in the sidebar). I think the best option is to keep the joplin search and then write a custom plugin to integrate with it. I probably won't do that in this pull request, but it will be relatively straightforward.

Ok that should work then, likewise if there's a well supported way to highlight terms it should work.

**Comment by CalebJohn** [comment]
This is ready to be reviewed I think. I have all the functionality (that I know of) that was in the original AceEditor and seems to be bug free (from my testing). But I plan to use this branch myself for the next few days to be sure.
I also added in some smart functionality to do with lists (basically adding and extending the functionality provided by @sinkuu in #2790 and #2772) to show off how we can easily make extensions to codemirror in order to add more complex behavior. Similarly I added a line sorting function because it was in the aceeditor [and it does get used](https://discourse.joplinapp.org/t/sort-lines/8874/2). 

What I haven't done yet, but would like to do, is add a new file to the documentation that outlines how to extend the codemirror editor component, so standby for that before merging.

**Comment by laurent22** [comment]
Thanks for the update @CalebJohn. Obviously it's a huge PR and not so easy to review. There's a lot of duplicate code between the AceEditor and CodeMirror files so long term we should only have one "Code View" editor to keep things maintainable. If CodeMirror is superior we'll use it and drop Ace Editor.

One thing I didn't find is the vim/emacs support? You've imported some files related to it, but I'm not sure they are used yet?

Also is there any reason why the editor code is split between CodeMirror.tsx and Editor.ts? I can sort of see why you've done that, but the way I see it CodeMirror.tsx should have direct access to the editor instance, without a wrapper in between. The wrapper means we'll need to have some kind of bridge so that CodeMirror.tsx can access the properties and methods of the editor. I feel that's not necessary and might make the code more difficult to maintain.

Also the role of each file is not entirely clear, I guess Editor.tsx is lower level, but I think there's some overlap.

For AceEditor.tsx and TinyMCE.tsx, I've put the editor instance directly accessible from the component. Then I've used a bunch of React hooks to lower down the line count and keep things more manageable. What do you think? Would it make sense to put the editor instance in CodeMirror.tsx?

By the way we haven't really discussed the various code editors. Obviously there are other ones, like Monaco for instance, and CodeMirror 6 might be released some day. Any reason why you went for CodeMirror in particular?

**Comment by CalebJohn** [comment]
> Obviously it's a huge PR and not so easy to review. There's a lot of duplicate code between the AceEditor and CodeMirror files so long term we should only have one "Code View" editor to keep things maintainable. If CodeMirror is superior we'll use it and drop Ace Editor.

:+1: 

> One thing I didn't find is the vim/emacs support? You've imported some files related to it, but I'm not sure they are used yet?

This is because of the way codemirror plugins work, during import the plugin registers itself with the codemirror instance, so we just need to pass it a keymap name (default, vim, emacs) and codemiror will handle the rest.

> Also is there any reason why the editor code is split between CodeMirror.tsx and Editor.ts? I can sort of see why you've done that, but the way I see it CodeMirror.tsx should have direct access to the editor instance, without a wrapper in between. The wrapper means we'll need to have some kind of bridge so that CodeMirror.tsx can access the properties and methods of the editor. I feel that's not necessary and might make the code more difficult to maintain.
Also the role of each file is not entirely clear, I guess Editor.tsx is lower level, but I think there's some overlap.
For AceEditor.tsx and TinyMCE.tsx, I've put the editor instance directly accessible from the component. Then I've used a bunch of React hooks to lower down the line count and keep things more manageable. What do you think? Would it make sense to put the editor instance in CodeMirror.tsx?

What I was going for was as you've guessed. Separating the Joplin behavior from the codemirror behavior. Which I did for a few reasons. 
1. Make updating editor behavior more manageable. In the future I want to improve the codemirror editor by adding more plugins so I think it's good to make a distinction between editor behavior that interacts with Joplin, and just plain editor behavior. 
2. Anticipating the upgrade to Codemirror 6, I feel that splitting things up like this makes the Codemirror.tsx file (the one that handle Joplin) more robust against changes in the underlying editor because it only makes use of basic editor functions, or ones that I have defined in the utils folder.
3. There is a lot of boilerplate code necessary for the interactions with the codemirror instance itself, so it's nice to keep this separate from the rest of the codebase. You'll notice that the entirety of Editor.tsx is devoted to these boilerplate interactions. The more complex codemirror code is formatted like plugins in the utils folder (this puts different behaviors in different files).

I actually did end up giving CodeMirror.tsx direct access to the codemirror editor, but most if not all the interactions with it are handled by higher level functions defined in one of the utils modules. Since this is such a large pull request (and I think you'll find it's not quite as large as it seems), I would be open to discussing it in a bit more detail over the discord, that way I can give you a much quicker introduction to why I structured it like this and how everything interacts.

> By the way we haven't really discussed the various code editors. Obviously there are other ones, like Monaco for instance, and CodeMirror 6 might be released some day. Any reason why you went for CodeMirror in particular?

Not a terribly strong reason, but the Jupyter environment uses codemirror to power it's markdown editor (with variable font size) so I have some trust in it. I compared markdown support in Monaco as well and it seemed to be lacking the advanced features that were either already in codemirror (variable font size) or could be added fairly easily (inline images, etc.). I like how easy it is to write plugins for codemirror so even if we have to add support for certain features ourselves it won't be as much of a pain as it was with aceeditor.

On the topic of codemirror 6, I just don't trust that it will be ready for use in Joplin for at least a few years, so as long as we keep the codebase manageable we should be able to upgrade then (or stick with the more stable codemirror 5).

**Comment by laurent22** [comment]
Thanks for the info @CalebJohn, I'll go through it again and get back to you. I just thought about over things that ideally should work in a new editor:

- Emojis. Currently Ace Editor doesn't support them properly as it treats one emoji as multiple characters so you can have your cursor in the middle of an emoji.
- Handling of Asian languages, in particular whether these three issues are fixed:
    - Weird characters when inputting Korean language: https://github.com/laurent22/joplin/issues/113 https://github.com/laurent22/joplin/issues/1351
    - Alignment issue: https://github.com/laurent22/joplin/issues/3134

All these I expect should be fixed if the editor properly handle unicode and non-monospace fonts, but worth checking anyway.

**Comment by CalebJohn** [comment]
Thanks @laurent22 I had meant to check these cases but I forgot.
I checked emoji support following issue #2244 and I was able to reproduce the error with Ace but not with Codemirror
I checked #113 and #1351 using the Japanese mozc input on my computer and I could at least reproduce the weird characters while editing, but the didn't persist after a selection was made (Ace). I did not have any issues while using codemirror.

I couldn't reproduce #3134 but I reached out to the poster and I hope to check it soon. That one may be difficult to reproduce because I think it might be a font issue, but I'm fairly confident it will be fixed.

**Comment by laurent22** [comment]
Thanks for checking this @CalebJohn. I've just gave a try to the branch and didn't find any issue, and since your changes are quite well isolated I'm keen to merge this so that we can start using it everyday, and find any remaining edge case if any. If you find any issue, feel free to open a new pull request for it, and thanks again for this great improvement!

**Comment by CalebJohn** [comment]
Thanks Laurent! Fingers crossed there aren't too many issues!
