### PR TITLE
Mobile: Fixes #10065 filtered deleted and trash folder when counting active notebooks

### LINKED ISSUE #10065: Mobile: New note button throws exception on first start in dev mode when there are no notebooks
### Operating system

Android 13

### Joplin version

3.0.0

### Desktop version info

_No response_

### Current behaviour

To reproduce:
1. Start a new copy of the mobile app in development mode such that there are no notebooks
2. Click the "new note" button

**Note**: This may also happen when creating a new, empty profile.

### Expected behaviour

The new note button should not create an unhandled promise rejection or should not be visible.

### Logs

Error message:
```
 WARN  Possible Unhandled Promise Rejection (id: 2):
TypeError: Cannot read property 'id' of null
TypeError: Cannot read property 'id' of null
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:607208:116)
    at next (native)
    at fulfilled (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:606956:30)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/5815x2p5/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/5815x2p5/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:27987:26)
    at _callTimer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:27906:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:27936:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:28099:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4267:46)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4079:45)
    at __guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4251:15)
    at flushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4078:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4072:33)

```

### PR DESCRIPTION
**Pull request by Sidd-R**
## Summary

Filtered the array of folders for trash and deleted folders before taking its length. Earlier both were being considered which led to trash and deleted folders to be considered as active notebooks and the ui of an active notebook was being displayed. When there was an attempt to create a new note/todo list, the Folder.defaultFolder() returned null in screens/Notes.tsx and when its id was accessed, it gave cannot read property error.

- Fixes #10065

## Rationale

Filtered the folders using the following logic:
 - Used the folder id of trash folder to filter it out.
 - Filtered folders whose deleted time was not equal to 0 to remove deleted folders.

Now when there are no active notebooks, create new notebook option is shown and the floating button for creating new note/todo is hidden.

Before:
before_

After:
after_

Tested on Android 13

Link to my introduction in forum: - [https://discourse.joplinapp.org/t/introducing-sidd-r/36498](https://discourse.joplinapp.org/t/introducing-sidd-r/36498)

### CODE REVIEW

**Comment by Sidd-R** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Sidd-R** [comment]
Hello, this is my first time contributing to Joplin and I have tried my best to follow the given guidelines as much as possible but incase if I missed anything do let me know! Also, any tips to improve my pr would be appreciated!

**Comment by Sidd-R** [comment]
@PackElend label me please

File: packages/app-mobile/components/NoteList.tsx [hunk 1]
```diff
@@ -90,7 +90,11 @@ class NoteListComponent extends Component<NoteListProps> {
 				keyExtractor={item => item.id}
 			/>;
 		} else {
-			if (!this.props.folders.length) {
+			// calculate number of folders except deleted and trash folder
+			// trash folder id: de1e7ede1e7ede1e7ede1e7ede1e7ede
+			const atleastOneNotebookExists = this.props.folders.filter((folder: FolderEntity) => folder.id !== 'de1e7ede1e7ede1e7ede1e7ede1e7ede' && folder.deleted_time === 0).length > 0;
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/NoteList.tsx]: Consider using `getTrashFolderId` here instead of `de1e7ede1e7ede1e7ede1e7ede1e7ede`. ([`getTrashFolderId` is defined here](https://github.com/laurent22/joplin/blob/52810c51f53106f42eef891ca2500abb941c7893/packages/lib/services/trash/index.ts#L36)).

Thank you for working on this!

Comment (roman-r-m) [inline packages/app-mobile/components/NoteList.tsx]: Will this not cause the same error as https://github.com/laurent22/joplin/issues/10073 ?

Comment (Sidd-R) [reply packages/app-mobile/components/NoteList.tsx]: Hey, it is not causing that error as of now, I don't get how the changes I have made can possibly cause that error. Can you please elaborate on it?

Comment (roman-r-m) [reply packages/app-mobile/components/NoteList.tsx]: I'm not saying your changes caused that issue, of course. I mean if you have a conflicts folder, won't your code have the same errors as the issue I linked.

Comment (Sidd-R) [reply packages/app-mobile/components/NoteList.tsx]: Hey, I have made the suggested changes and updated the pr. Do let me know if any other changes are needed!

Comment (Sidd-R) [reply packages/app-mobile/components/NoteList.tsx]: Oh, got it. Then I'll add another condition to check whether the folder id matches with the conflict folder id before checking for the deleted_time attribute. This should resolve it I guess, correct me if I'm wrong. 

I can use the `conflictFolderId()` function to get its id.


OR

maybe we can add deleted_time attribute to the conflicts folder object, that would fix #10073  as well.

before:
```	
public static conflictFolder(): FolderEntity {
		const now = Date.now();

		return {
			type_: this.TYPE_FOLDER,
			id: this.conflictFolderId(),
			parent_id: '',
			title: this.conflictFolderTitle(),
			updated_time: now,
			user_updated_time: now,
			share_id: '',
			is_shared: 0,
		};
	}
```

after:
```	
public static conflictFolder(): FolderEntity {
		const now = Date.now();

		return {
			type_: this.TYPE_FOLDER,
			id: this.conflictFolderId(),
			parent_id: '',
			title: this.conflictFolderTitle(),
			updated_time: now,
			user_updated_time: now,
			share_id: '',
			is_shared: 0,
                     +  deleted_time: 0,
		};
	}
```

File: packages/app-mobile/components/NoteList.tsx [hunk 2]
```diff
@@ -90,7 +91,12 @@ class NoteListComponent extends Component<NoteListProps> {
 				keyExtractor={item => item.id}
 			/>;
 		} else {
-			if (!this.props.folders.length) {
+			const trashFolderId = getTrashFolderId();
+
+			// calculate number of folders except deleted and trash folder
+			const atleastOneNotebookExists = this.props.folders.filter((folder: FolderEntity) => folder.id !== trashFolderId && folder.deleted_time === 0).length > 0;
```
Comment (laurent22) [inline packages/app-mobile/components/NoteList.tsx]: Please use the term "folder" (not "notebook") in code

File: packages/app-mobile/components/screens/Notes.tsx [hunk 3]
```diff
@@ -238,7 +238,12 @@ class NotesScreenComponent extends BaseScreenComponent<any> {
 		const thisComp = this;
 
 		const makeActionButtonComp = () => {
-			if (this.props.notesParentType === 'Folder' && itemIsInTrash(parent)) return null;
+			const trashFolderId = getTrashFolderId();
+
+			// calculate number of folders except deleted and trash folder
+			const atleastOneNotebookExists = this.props.folders.filter((folder: FolderEntity) => folder.id !== trashFolderId && folder.deleted_time === 0).length > 0;
```
Comment (laurent22) [inline packages/app-mobile/components/screens/Notes.tsx]: Since you use the same code in two places please make it a function that takes folders as input and returns a boolean. You can put it in models/Folder.ts

Also name it something like `atLeastOneRealFolderExists` since the trash folder is a virtual one

Comment (Sidd-R) [reply packages/app-mobile/components/screens/Notes.tsx]: I made the changes you suggested and have added unit test for the same.

File: packages/lib/models/Folder.test.ts [hunk 4]
```diff
@@ -353,4 +353,17 @@ describe('models/Folder', () => {
 		await expectThrow(async () => Folder.delete(folder2.id, { toTrash: true, toTrashParentId: folder2.id }));
 	});
 
+	it('should tell if atleast one folder other than trash and deleted exists', async () => {
```
Comment (laurent22) [inline packages/lib/models/Folder.test.ts]: Should be "at least" (not sure why "atleast" was in our dictionary but I removed it now)

File: packages/lib/models/Folder.test.ts [hunk 5]
```diff
@@ -353,4 +353,17 @@ describe('models/Folder', () => {
...
+		expect(Folder.atLeastOneRealFolderExists(folders)).toBe(false);
+
+		const f1 = await Folder.save({ title: 'folder1' });
+		folders = await Folder.all({ includeTrash: true });
+		expect(Folder.atLeastOneRealFolderExists(folders)).toBe(true);
+
+		await Folder.delete(f1.id, { toTrash: true });
+		folders = await Folder.all({ includeTrash: true });
+		expect(Folder.atLeastOneRealFolderExists(folders)).toBe(false);
+	});
```
Comment (laurent22) [inline packages/lib/models/Folder.test.ts:370]: Thank you for adding the tests. Also please add a case for testing an empty array

Comment (Sidd-R) [reply packages/lib/models/Folder.test.ts:370]: I have added the test case for testing an empty array, please check.

**Comment by laurent22** [comment]
Looks good now, thanks @Sidd-R!
