### PR TITLE
Desktop,Mobile,Cli: Fixes #8891: Fix AWS S3 sync error

### LINKED ISSUE #8891: S3 async,report"TypeError: Cannot read properties of undefined"
aliyun oss,s3 async

## Environment

Joplin version: 2.13.1
Platform: 
OS specifics: win10

## Describe what you expected to happen
aliyun oss,s3 async

## Logfile
21:22:43: Preparing scheduled sync
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:22:43: Starting scheduled sync
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:22:43: Synchronizer: Sync: starting: Starting synchronisation to target 8... supportsAccurateTimestamp = false; supportsMultiPut = false [1694870563793]
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:22:43: Synchronizer: Indexing resources...
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:22:43: ResourceService::indexNoteResources: Start
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:22:43: ResourceService::indexNoteResources: Completed
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:22:44: Synchronizer: Sync target remote info: SyncInfo {version_: 3, masterKeys_: Array(0), e2ee_: {…}, activeMasterKeyId_: {…}, ppk_: {…}}
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:22:44: Synchronizer: Sync target is already setup - checking it...
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:22:44: Synchronizer: Sync target local info: SyncInfo {version_: 3, masterKeys_: Array(0), e2ee_: {…}, activeMasterKeyId_: {…}, ppk_: {…}}
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:22:44: Synchronizer: TaskQueue.stop: syncDownload: waiting for tasks to complete: 0
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:22:44: Synchronizer: TaskQueue.stop: syncDownload: Done, waited for 0
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:23:07: Synchronizer: TypeError: Cannot read properties of undefined (reading 'length')
    at FileApiDriverAmazonS3.metadataToStats_ (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-amazon-s3.js:179:27)
    at FileApiDriverAmazonS3.list (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-amazon-s3.js:224:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getDirStats (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-amazon-s3.js:191:19)
log @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206
error @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\utils\dist\Logger.js:80
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:988
rejected @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:6
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:4
start @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:356
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:122
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:4
timeoutCallback @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:78
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:147
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:4
Registry.scheduleSync @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:57
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:66
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:4
execute @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:26
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:161
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:4
execute @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:152
onClick @ C:\Program Files\Joplin\resources\app.asar\gui\Sidebar\Sidebar.js:496
onClick @ C:\Program Files\Joplin\resources\app.asar\gui\Button\Button.js:206
callCallback @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4164
invokeGuardedCallbackDev @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4213
invokeGuardedCallback @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4291
executeDispatch @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9041
processDispatchQueueItemsInOrder @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9073
processDispatchQueue @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9086
dispatchEventsForPlugins @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9097
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9288
batchedUpdates$1 @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26140
batchedUpdates @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:3991
dispatchEventForPluginEventSystem @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:6465
dispatchEvent @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:6457
dispatchDiscreteEvent @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:6430
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:23:07: Synchronizer: Sync: finished: Synchronisation finished [1694870563793]
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:23:07: Synchronizer: Operations completed: 
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:23:07: Synchronizer: Total folders: 11
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:23:07: Synchronizer: Total notes: 44
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:23:07: Synchronizer: Total resources: 68
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:23:07: Synchronizer: There was some errors:
log @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206
warn @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\utils\dist\Logger.js:79
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:253
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:4
logSyncSummary @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:227
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:1019
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
rejected @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:6
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:4
start @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:356
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:122
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:4
timeoutCallback @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:78
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:147
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:4
Registry.scheduleSync @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:57
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:66
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:4
execute @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:26
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:161
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:4
execute @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:152
onClick @ C:\Program Files\Joplin\resources\app.asar\gui\Sidebar\Sidebar.js:496
onClick @ C:\Program Files\Joplin\resources\app.asar\gui\Button\Button.js:206
callCallback @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4164
invokeGuardedCallbackDev @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4213
invokeGuardedCallback @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4291
executeDispatch @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9041
processDispatchQueueItemsInOrder @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9073
processDispatchQueue @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9086
dispatchEventsForPlugins @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9097
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9288
batchedUpdates$1 @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26140
batchedUpdates @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:3991
dispatchEventForPluginEventSystem @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:6465
dispatchEvent @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:6457
dispatchDiscreteEvent @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:6430
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:23:07: Synchronizer: TypeError: Cannot read properties of undefined (reading 'length')
    at FileApiDriverAmazonS3.metadataToStats_ (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-amazon-s3.js:179:27)
    at FileApiDriverAmazonS3.list (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-amazon-s3.js:224:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getDirStats (C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\file-api-driver-amazon-s3.js:191:19)
log @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206
warn @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\node_modules\@joplin\utils\dist\Logger.js:79
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:256
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:4
logSyncSummary @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:227
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:1019
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
rejected @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:6
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:5
processTicksAndRejections @ node:internal/process/task_queues:95
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:4
start @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\Synchronizer.js:356
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:122
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:4
timeoutCallback @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:78
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:147
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:4
Registry.scheduleSync @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\registry.js:57
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:66
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:7
fulfilled @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:5
Promise.then (async)
step @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:7
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:4
execute @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\commands\synchronize.js:26
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:161
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:8
__awaiter @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:4
execute @ C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\lib\services\CommandService.js:152
onClick @ C:\Program Files\Joplin\resources\app.asar\gui\Sidebar\Sidebar.js:496
onClick @ C:\Program Files\Joplin\resources\app.asar\gui\Button\Button.js:206
callCallback @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4164
invokeGuardedCallbackDev @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4213
invokeGuardedCallback @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:4291
executeDispatch @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9041
processDispatchQueueItemsInOrder @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9073
processDispatchQueue @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9086
dispatchEventsForPlugins @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9097
(anonymous) @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9288
batchedUpdates$1 @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:26140
batchedUpdates @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:3991
dispatchEventForPluginEventSystem @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:6465
dispatchEvent @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:6457
dispatchDiscreteEvent @ C:\Program Files\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:6430
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:23:07: Sync has finished and note has never been changed - reloading it
C:\Program Files\Joplin\resources\app.asar\node_modules\@joplin\utils\dist\Logger.js:206 21:23:08: DecryptionWorker: cannot start because no master key is currently loaded.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

Fixes a "cannot read property `length` of `undefined`" error when syncing with Amazon S3.

The check for `undefined`/`null` is moved to `metadataToStats_` from the method that calls it.

# Notes

- **I have not tested this**, as I have not set up Amazon S3 sync.

### CODE REVIEW

File: packages/lib/file-api-driver-amazon-s3.js [hunk 1]
```diff
@@ -175,6 +175,12 @@ class FileApiDriverAmazonS3 {
 	}
 
 	metadataToStats_(mds) {
+		// aws-sdk-js-v3 can rerturn undefined instead of an empty array when there is
+		// no metadata in some cases.
+		//
+		// Thus, we handle the !mds case.
+		if (!mds) return [];
```
Comment (laurent22) [inline packages/lib/file-api-driver-amazon-s3.js:182]: Probably this fix is more proper than modify the response object, but I don't really see how it can fix the issue?

Or was it because of the strict equality check with undefined, when response.Contents was actually "null" or something similar?

Comment (personalizedrefrigerator) [reply packages/lib/file-api-driver-amazon-s3.js:182]: Not included in the diff (it's near line 224), because it was unchanged, we have
```ts

		while (response.IsTruncated) {
			response = await this.s3ListObjects(prefixPath, response.NextContinuationToken);
			output = output.concat(this.metadataToStats_(response.Contents, prefixPath));
		}
```
which doesn't include the check for `response.Contents === undefined`.

An alternate fix could be to add a second check for `response.Contents === undefined` inside the `while` loop.

Comment (laurent22) [reply packages/lib/file-api-driver-amazon-s3.js:182]: Oh right, I missed that so that's good then. The check on metadataToStats_ makes sense

**Comment by laurent22** [comment]
Thanks for the fix! Let's merge and see if that fixes the issue
