### PR TITLE
Desktop: Fixes #8520: Fix WYSIWYG theme not matching the system theme after several global theme changes

### LINKED ISSUE #8520: Desktop: Rich text/WYSIWYG editor: Doesn't always change theme to match system theme
## Environment

Joplin version: 2.12.4, 2.11.11
Platform: Desktop
OS specifics: MacOS, Ubuntu 23.10

## Steps to reproduce

1. Change the system theme to dark mode
2. Open the WYSIWYG editor
3. Change the system theme to light mode
4. Change the system theme to dark mode

## Describe what you expected to happen

In step 4, the rich text editor theme should change to dark mode, rather than remaining in light mode.

## Notes

This issue is already referenced here:
https://github.com/laurent22/joplin/blob/9aafdd2d10b2d3132dd15ec598831b74bcf23f4b/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx#L694-L704

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary
After changing the system theme from light to dark and dark back to light, the TinyMCE theme could previously not match the system theme.

Fixes #8520.

# Testing plan
1. Enable "Automatically switch theme to match system theme"
2. Open the rich text editor
3. Create a note with math and code blocks
4. Toggle system dark mode
5. Toggle system dark mode
6. Toggle system dark mode
7. Add more math and code blocks

After all steps, the rich text editor theme should match the system theme. In step 7, new math blocks should render.

### CODE REVIEW

File: packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx [hunk 1]
```diff
@@ -690,6 +690,9 @@ const TinyMCE = (props: NoteBodyEditorProps, ref: any) => {
 	// Set the initial content and load the plugin CSS and JS files
 	// -----------------------------------------------------------------------------------------
 
+	const documentCssElements: Record<string, HTMLLinkElement> = {};
+	const documentScriptElements: Record<string, HTMLScriptElement> = {};
+
 	const loadDocumentAssets = (editor: any, pluginAssets: any[]) => {
 		// Note: The way files are cached is not correct because it assumes there's only one version
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx]: Since you fixed this bug, please also update (or remove if no longer needed) this comment

**Comment by laurent22** [comment]
That's very good, thanks for fixing this. I've been using the Rich Text editor more lately, and indeed I've noticed that the theme wasn't automatically changing
