### PR TITLE
Mobile: Fixes #11864: Fix voice recorder crash

### LINKED ISSUE #11864: Crash when using the "record audio" feature in the iOS pre-release
### Operating system

iOS

### Joplin version

13.3.1

### Desktop version info

Joplin Mobile 13.3.1 (prod, ios)

Client ID: d3e66a0d32b54e6bb895613e67349ff3
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 200d3c84e (dev)

Extra Markdown editor settings: 1.10.1

iOS version: 18.3.1
FTS enabled: 1
Hermes enabled: 1

### Current behaviour

I'm getting an error when trying to use the voice recording feature in the latest iOS pre-release:
```
02-19T21:27:08: AudioRecording: Error starting recording: TypeError: undefined is not a function
TypeError: undefined is not a function
    at formatMsToDurationLocal (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-ewsyxzklwwggmtdeyavpfmrkhqhv/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:394609:26)
    at AudioRecordingBanner (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-ewsyxzklwwggmtdeyavpfmrkhqhv/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:586516:87)
```

For context, `formatMsToDurationLocal` is a new function that was added to `@joplin/utils` when adding the audio recorder. It's used for displaying the recording duration.

Here are a few possible causes of the issue:
- `@joplin/utils` wasn't rebuilt with the latest changes before the iOS release was created.
- There's an issue with the duration formatting logic.

### Expected behaviour

Joplin should not crash when attempting to record audio.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request fixes a crash when attaching a new audio recording on Android and iOS. It avoids use of `dayjs`, which may not work correctly in React Native for Android/iOS. 

Fixes #11864.

# Testing plan

On Android 13:
1. Click "Attach..." from the note actions menu
2. Click "Record audio"
3. Click "Start recording"
4. Verify that a time stamp in the format "0:12" is shown and the right number increases once per second.
5. Wait roughly one minute.
6. Verify that the first number increases to "1".
7. Click "Done".
8. Verify that this attaches a new recording to the note.
9. Verify that the recording can be played.

### CODE REVIEW

File: packages/utils/time.ts [hunk 1]
```diff
@@ -161,14 +158,11 @@ export const formatDateTimeLocalToMs = (anything: string) => {
...
-	}
-	return dayjs.duration(ms).format(format);
+export const formatMsToDurationCompat = (ms: number) => {
+	// Avoid using dayjs (and @joplin/utils/time) for formatting here.
+	// See https://github.com/laurent22/joplin/issues/11864
+	const seconds = Math.floor(ms / Second) % 60;
+	const minutes = Math.floor(ms / Minute);
+	const paddedSeconds = `${seconds}`.padStart(2, '0');
+	return `${minutes}:${paddedSeconds}`;
 };
```
Comment (personalizedrefrigerator) [inline packages/utils/time.ts:168]: **Notes**:
- formatMsToDurationLocal was added in the [voice recording PR](https://github.com/laurent22/joplin/pull/11836).
- This output format doesn't change to match the current locale.
- Without the `duration` plugin, implementing this with `formatMsToLocal`, I still observe a crash (error message: `dayjs is not a function (it is Object)`).
- React Native Hermes doesn't seem to support the [Intl.DurationFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DurationFormat/format#browser_compatibility) API.
