### PR TITLE
Desktop,Mobile,Cli: Fixes #13522: Fix "cannot add an item as a child of a read-only item" error when updating share IDs

### LINKED ISSUE #13522: Sharing a new folder: Error: "Cannot add an item as a child of a read-only item"
### Operating system

Linux

### Joplin version

f4a0a246

### Desktop version info

_No response_

### Current behaviour

With a local test account, I'm getting a "Synchronizer: Could not update share because an item is readonly: Hlt: Cannot add an item as a child of a read-only item" error when trying to share a folder:

screenshot: Cannot add item as a child of a read-only item

This error, interestingly, comes from a folder from a different share while running `updateNoteShareIds`. Updating a particular note's `share_id` is blocked with a "child of a read-only item" error.

> [!NOTE]
>
> The error message's low contrast is tracked by https://github.com/laurent22/joplin/issues/13520.

### Expected behaviour

Either:
1. The client should not attempt to update the `share_id` of notes in a read-only share, or
2. Updating the `share_id` for these notes should not fail.

### Logs

<details>

```
08:38:52: SearchEngine: Updating FTS table...
Logger.ts:317 08:38:52: Updating items_normalized from Object
Logger.ts:317 08:38:52: SearchEngine: Updated FTS table in 3ms. Inserted: 0. Deleted: 0
Logger.ts:317 08:38:52: Performance: SearchEngine/syncTables: End at 44.84s (took 103.4ms)
Logger.ts:317 08:38:59: Preparing scheduled sync
Logger.ts:317 08:38:59: Starting scheduled sync
Logger.ts:317 08:38:59: Synchronizer: Sync: starting: Starting synchronisation to target 10... supportsAccurateTimestamp = true; supportsMultiPut = true} [1761233939243]
Logger.ts:317 08:38:59: Synchronizer: Indexing resources...
Logger.ts:317 08:38:59: ResourceService::indexNoteResources: Start
Logger.ts:317 08:38:59: Performance: ResourceService/indexNoteResources: Start at 51.62s
Logger.ts:317 08:38:59: Performance: ResourceService/indexNoteResources: End at 51.72s (took 103.2ms)
Logger.ts:317 08:38:59: ResourceService::indexNoteResources: Completed
Logger.ts:317 08:38:59: Performance: ShareService/maintenance: Start at 51.72s
Logger.ts:317 08:38:59: ShareService: Refresh share invitations: Object Object
Logger.ts:317 08:38:59: ShareService: Refreshed shares: Object
Logger.ts:317 08:38:59: models/Folder: updateNoLongerSharedItems: Object
Logger.ts:317 08:38:59: Performance: ShareService/maintenance: End at 51.75s (took 33.7ms)
Logger.ts:317 08:38:59: models/Folder: updateFolderShareIds: Object
Logger.ts:317 08:38:59: models/Folder: updateNoteShareIds: notes to update: 630
Logger.ts:317 08:38:59: ShareService: Refreshed share users: Object
````

Then:
```
08:38:38: ShareFolderDialog: Hlt: Cannot add an item as a child of a read-only item
    at checkIfItemCanBeAddedToFolder (file:///home/self/Documents/joplin/packages/lib/models/utils/readOnly.ts:66:10)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Note.save (file:///home/self/Documents/joplin/packages/lib/models/BaseItem.ts:1019:5)
    at Note.save (file:///home/self/Documents/joplin/packages/lib/models/Note.ts:847:19)
    at Folder.updateNoteShareIds (file:///home/self/Documents/joplin/packages/lib/models/Folder.ts:554:4)
    at Folder.updateAllShareIds (file:///home/self/Documents/joplin/packages/lib/models/Folder.ts:713:3)
    at e.shareFolder (file:///home/self/Documents/joplin/packages/lib/services/share/ShareService.ts:148:3)
    at file:///home/self/Documents/joplin/packages/app-desktop/gui/ShareFolderDialog/ShareFolderDialog.tsx:213:12
```

</details>

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request fixes an error related to read-only shares by disabling a "not read-only" assertion when updating `share_id`s (e.g. if the `share_id`s were invalid due to an incomplete sync or issue elsewhere). Previously, if one `share_id` failed to update, calls to `updateAllShareIds` could fail. This prevented sharing new notebooks.

Fixes #13522.

# Testing

This pull request includes an automated test that failed previously.

I have verified that:
- It's possible to share a notebook without the "read-only share" error in my test environment.

### CODE REVIEW

File: packages/lib/models/Folder.ts [hunk 1]
```diff
@@ -556,7 +556,10 @@ export default class Folder extends BaseItem {
 				share_id: row.share_id || '',
 				parent_id: row.parent_id,
 				updated_time: Date.now(),
-			}, { autoTimestamp: false });
+			}, {
+				autoTimestamp: false,
+				disableReadOnlyCheck: true,
```
Comment (personalizedrefrigerator) [inline packages/lib/models/Folder.ts:561]: Note: This may lead to conflicts:

https://github.com/laurent22/joplin/blob/94725c533cc76cdd042fa114976b5459528ad208/readme/dev/spec/read_only.md?plain=1#L24
