### PR TITLE
Desktop, Mobile: Fixes #12987: Fix images rendered in the Markdown editor don't reload when downloaded

### LINKED ISSUE #12987: Markdown editor: Images rendered in the Markdown editor don't refresh after editing or being downloaded from the sync target
### Operating system

Linux

### Joplin version

3.4.5

### Desktop version info

_No response_

### Current behaviour

With a recent 3.4.x release of Joplin, images are rendered inline in the Markdown editor. On desktop, editing these images in the image editor (or presumably in an external application), does not update the image rendered in the Markdown editor.

To reproduce:
1. Attach a drawing to a note.
2. Edit the drawing.
3. Dismiss the editor dialog.
4. Observe that the old image is still shown in the editor.
5. Observe that the updated image is shown in the viewer.

### Expected behaviour

The image should be refreshed in the Markdown editor when changed by the image editor.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

Adds logic to reload images in the Markdown editor when changed externally. On mobile, this logic only applies to the case where images are downloaded from the sync target.

Fixes #12987.

# Notes

- This pull request adds a `?r=...` to images rendered in the Markdown editor when these images are changed externally. This is similar to the `?t=...` appended to image resources in the note viewer to force them to reload.

# Testing

## Manual testing — editing an image

**Desktop**: 
1. Open the desktop app and create a new note.
2. Attach a drawing.
3. Save the drawing and close the image editor.
4. Verify that the drawing is rendered in the editor.
5. Re-open the image editor.
6. Make a change to the drawing and dismiss the editor.
7. Verify that the copy of the drawing rendered in the editor has been updated to include the changes from the editor.

## Manual testing — iOS: downloading and decrypting an image

**iOS simulator**:

https://github.com/user-attachments/assets/31abafdc-3342-4b74-9242-b7559db50271

The above screen recording shows 1) opening a note in an editor 2) the images loading.

<details><summary>Show testing last done with an older version of this pull request</summary>

## Manual testing — downloading an image

**Android**:
1. Connect to a local Joplin Server (if not already done).
2. Set "Attachment download behavior" to "Auto".
3. On desktop, create a note with several attached images.
4. Open the note on Android in the Rich Text Editor (regression testing).
5. Verify that the images are not initially visible.
6. Verify that the images re-render and become visible.
7. Repeat steps 3-6 for the Markdown editor.

> [!NOTE]
>
> The Android-specific manual testing plan above was completed with an older version of this pull request.

</details>

### CODE REVIEW

File: packages/app-mobile/contentScripts/markdownEditorBundle/contentScript.ts [hunk 1]
```diff
@@ -47,6 +48,10 @@ export const createEditorWithParent = ({
 		throw new Error(`Unable to find parent element for editor (class name: ${JSON.stringify(parentElementOrClassName)})`);
 	}
 
+	// resolveImageSrc can be called frequently for the same image. To avoid unnecessary IPC,
+	// use an InMemoryCache.
+	const resolvedImageSrcCache = new InMemoryCache();
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/contentScripts/markdownEditorBundle/contentScript.ts:53]: On mobile, this change prevents flickering when images are downloaded from the sync target. In particular, updating one image would (often) cause CodeMirror to reload the `ImageWidget`s for all visible images. The reloaded image would remain blank until the image SRC could be fetched over IPC through `resolveImageSrc`.

**Comment by personalizedrefrigerator** [comment]
Marking as a draft until additional manual testing has been done on mobile.

File: packages/app-mobile/components/NoteEditor/NoteEditor.tsx [hunk 2]
```diff
@@ -342,10 +342,18 @@ function NoteEditor(props: Props) {
...
 			const wasDownloaded = isDownloaded(lastNoteResources.current, key);
-			if (!wasDownloaded && isDownloaded(props.noteResources, key)) {
-				editorControl.onResourceDownloaded(key);
+			const hasDownloaded = !wasDownloaded && isDownloaded(props.noteResources, key);
+
+			const wasEncrypted = isEncrypted(lastNoteResources.current, key);
+			const hasDecrypted = wasEncrypted && !isEncrypted(props.noteResources, key);
+
+			if (hasDownloaded || hasDecrypted) {
+				editorControl.onResourceChanged(key);
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/NoteEditor/NoteEditor.tsx:356]: **hasDecrypted change**: Checking whether a resource has just downloaded isn't sufficient — it's also necessary to reload the resource when it's decrypted.

**Comment by personalizedrefrigerator** [comment]
The failing test seems unrelated to this pull request:
```
 [@joplin/transcribe]: FAIL dist/src/api/handler/createJob.test.js
[@joplin/transcribe]:   ● createJob › should delete the original file after storing
[@joplin/transcribe]: 
[@joplin/transcribe]:     expect(received).toBe(expected) // Object.is equality
[@joplin/transcribe]: 
[@joplin/transcribe]:     Expected: false
[@joplin/transcribe]:     Received: true
[@joplin/transcribe]: 
[@joplin/transcribe]:       77 |
[@joplin/transcribe]:       78 | 		const originalFile = await exists('./test_file.png');
[@joplin/transcribe]:     > 79 | 		expect(originalFile).toBe(false);
[@joplin/transcribe]:          | 		                     ^
[@joplin/transcribe]:       80 | 	});
[@joplin/transcribe]:       81 | });
[@joplin/transcribe]:       82 |
[@joplin/transcribe]: 
[@joplin/transcribe]:       at Object.toBe (src/api/handler/createJob.test.ts:79:24)
```
