### PR TITLE
Desktop: fix window dimensions and position when the application start

### LINKED ISSUE #2476: Check and fix window dimensions and position when the application start
It happens that the Joplin window, when starting, is off-screen or has invalid dimensions, like 1x1 pixel.

After the app is started (1 or 2 seconds after to make sure it's properly initialised), there should be two checks:

- Check that the window has correct dimensions (for example a minimum of 100x100 pixels)
- Check that the window rectangle is within one of the active screens.

If it's not, the window should be moved to the right location and set to the right dimensions.

You will need to make sure that it works also when the "Start minimised" option is enabled in the settings. In other words, the code shouldn't make the window visible when it should in fact be minimised.

### PR DESCRIPTION
**Pull request by daukadolt**
Addresses #2476

1. BrowserWindow set up to have a minimum width and height of 100 px. This is addressed by setting minWidth, minHeight properties of BrowserWindow.
2. Centered position on a primary display is enforced if BrowserWindow rectangle doesn't match any display.

Electron app doesn't allow scaling any lower than minHeight and minWidth, which I've checked. However, I could not enforce the application to have a position outside my only display both through setting x, y manually [here](https://github.com/laurent22/joplin/blob/4f8e7b0e2b3436025cf704c8bbc278499764a228/ElectronClient/app/ElectronAppWrapper.js#L57) or through [BrowserWindow.setPosition()](https://www.electronjs.org/docs/api/browser-window#winsetpositionx-y-animate). Hence, I could not check my solution on this one.

I initially wanted to discuss my approach (like setting arbitrary 100px for minHeight/minWidth) in the issue, but (sorry if I'm wrong) I thought that since pull request would either way be reviewed discussion could be set here.

Looking forward for comments.

### CODE REVIEW

**Review by tessus — COMMENTED** [review]
I think we could try to corrupt the `window-state-prod.json` on purpose. On macOS, this file is in `~/Library/Application Support/Joplin`. Not sure about Linux and Windows.

**Comment by tessus** [comment]
This is a great start, but to bring it to the next level, I'd suggest the following: make the default size and position dependent of the screen size. e.g. that it takes 80%-85% of the width and height and that it is centered. This is just an idea and not necessary. 
This is just a workaround for people who run into the weird problem of a 1x1 sized window or a window off screen (due to multiple monitors).

**Comment by gasolin** [comment]
set minWidth/minHeight also solves the user occasionally scale the window to a minimum `line` issue.
 
https://discourse.joplinapp.org/t/installing-joplin-1-0-174-on-macos-catalina-results-in-no-visible-window/4425/10

@daukadolt I suggest to set the `minWidth: 480, minHeight: 320` to keep the Joplin window barely workable

**Comment by daukadolt** [comment]
@tessus I've made default width and height dependent on the primary screen, since that is the screen that the app is spawned on for the first time. However, Travis build has failed and I wonder why. After a quick run through the logs and repo it seems that the [first line](https://github.com/laurent22/joplin/blob/5bbedc7e3cb293247e4faa8b0947102169769337/ElectronClient/app/gui/ResourceScreen.tsx#L1) intended for eslint is the culprit, but how come did the master repo build successfully? Or my commit somehow messes with it. And why is the build performed on laurent22/master instead of my master branch?

Additionally, I tried playing around with `window-state.json` file, but it's BrowserWindow constructor that is safeguarding against spawning outside any display, I believe.
[electron-window-state](https://github.com/daukadolt/joplin/blob/894e9f464333191df40f80a0dd2c5f12f11afcd8/ElectronClient/app/ElectronAppWrapper.js#L44) package too has some safeguards against spawning outside any window, but I've even modified it's code in node_modules by hardcoding return of 4000 [here for x and y](https://github.com/mawie81/electron-window-state/blob/2701d9a0f90a44dc8dbf81430538ceb16c9ff27a/index.js#L174).

**Comment by tessus** [comment]
Right now all builds fail in Travis. We have to fix that. So don't worry about it right now.

I'll have a look at your new commit either tonight or tomorrow.

**Comment by daukadolt** [comment]
@gasolin I like your suggestion, I will commit updated minimum dimensions after all other issues will be resolved

**Comment by tessus** [comment]
Please rebase, so that the conflicts are resolved.

**Comment by daukadolt** [comment]
> Please rebase, so that the conflicts are resolved. This will also solve the Travis builds. The build process has changed, so everything should be fine now. Please have a look at the updated BUILD.md file.

Got it. I've checked the updated test steps. What do you think about @gasolin 's suggestion on minWidth/minHeight? I can change them if everything else is fine.

**Comment by daukadolt** [comment]
Found a typo in my code, sorry for the sloppiness. However, here again, BrowserWindow safeguards against too big of a height. Doing `2*currentWorkArea.height`still renders app within my mac's desktop, not going any lower than the dock and not higher than the menu bar. Tried resizing dock as well.

**Comment by daukadolt** [comment]
@PackElend could you please tag this PR as gsoc-2020 as well?

**Review by tessus — COMMENTED** [review]
LGTM, but I'd change the `defaultWidth` and `defaultHeight` to something more sane.
Or depending on the actual screen size.

**Comment by daukadolt** [comment]
> LGTM, but I'd change the `defaultWidth` and `defaultHeight` to something more sane.
> Or depending on the actual screen size.

@tessus you mean using screen size instead of workArea?

**Comment by tessus** [comment]
I meant that if your screen is e.g. 1024x768, use ca 80-85% of that for the window size. Maybe 800x600 and position it (1024-800)/2 , (800-600)/2 so that it is in the middle of the screen.

This should of course only be done, if there's a problem with the size or the position in the first place. If the data in `window-state-prod.json` is correct, you don't have to do anything.

File: ElectronClient/ElectronAppWrapper.js [hunk 1]
```diff
@@ -43,9 +43,12 @@ class ElectronAppWrapper {
 
 		const windowStateKeeper = require('electron-window-state');
 
+		const currentWorkArea = screen.getPrimaryDisplay().workArea;
+		const [defaultWidth, defaultHeight] = [0.8*currentWorkArea.width, 0.8*currentWorkArea.height];
```
Comment (laurent22) [inline ElectronClient/ElectronAppWrapper.js]: Please round the values. Also I don't see a need to create these separate values, so if you could set the properties on stateOptions directly that would be best.

**Review by laurent22 — CHANGES_REQUESTED** [review]

**Comment by laurent22** [comment]
Just left one comments. @tessus, is there something more that needs to be changed? I see he already uses 80% of the space or did I miss something?

**Comment by tessus** [comment]
No, @laurent22, all is good. The OP has already changed the code according to my suggestion.

**Comment by laurent22** [comment]
Perfect, then there's just this one minor change to make and we can merge.

File: ElectronClient/ElectronAppWrapper.js (hunk 1 above)
Comment (daukadolt) [reply ElectronClient/ElectronAppWrapper.js]: @laurent22 can you take a look at the changes?

**Comment by scotrod** [comment]
Bump. This is still happening with Joplin 2.6.10 (prod, win32)

Client ID: cf27eb0272a5451ca45a96eaa6351910
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 98fba37

This issue appeared only on my multi-monitor setup - after I deleted the folder in `C:\Users\USER\AppData\Roaming\Joplin\` it worked like a charm.

**Comment by tormung83** [comment]
@scotrod and all, this is still happening on Multi monitor and laptop's main display, docked and undocked. 
Deleting the `C:\Users\USER\AppData\Roaming\Joplin\` did not make any difference. 

OS: Windows 11 22H2 (OS Build 22621.1555)
Joplin version: 2.9.17
