### PR TITLE
Mobile: Fixes #11276: Fix new note button is pushed offscreen on certain Android devices

### LINKED ISSUE #11276: Plus Icon disappeared
### Operating system

Android

### Joplin version

3.0.8

### Desktop version info

_No response_

### Current behaviour

GrapheneOS, based on Android 15
Joplin 3.0.8

Note: I installed Joplin from Aurora-store, which caused no problem for the app to work fine for more than a year. 

Recently the Plus Icon (to create new notes) has disappeared. I do not know exactly how long ago the icon was still there, but it must have been not more than two weeks ago. 

I tried switching to another notebook, then closing the app and restarting it, but it didn't help. 

### Expected behaviour

To display the icon

### Logs

_No response_

### LINKED ISSUE #11315: New item button hidden when using 3-button navigation mode
### Operating system

Android

### Joplin version

3.1.7 (prod, android)

### Desktop version info

_No response_

### Current behaviour

1. When using 3-Button navigation mode in Android (v14 and v15)
2. The red "new item" button at the bottom of the screen is hidden by the 3-button navigation bar and can not be clicked without precise clicking

### Expected behaviour

1. When using 3-Button navigation mode in Android
2. The New item button should be moved up so it's above the navigation bar.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request fixes a regression &mdash; on certain Android devices, the "+" button for creating new notes was pushed partially or completely offscreen. This seems to have been introduced in Joplin v3.0.1 by https://github.com/laurent22/joplin/pull/10123.

Fixes #11276.
Fixes #11315.

> [!NOTE]
>
> Currently, this pull request targets `release-3.1`.

## Details

React Native Paper's `<FAB.Group>` renders an invisible `<View>` that covers most/all of Joplin's UI. This view is present even when the `FAB.Group` is collapsed.

To allow users to continue to interact with the application while the view is visible, `react-native-paper` uses [`pointerEvents={'box-none'}`](https://github.com/callstack/react-native-paper/blob/9162a1fdf4e97c0669de8a8fa2057d8cfbe2e728/src/components/FAB/FABGroup.tsx#L345) when the FAB.Group is collapsed. Unfortunately, [this breaks TalkBack on Android's "tap to navigate" feature](https://github.com/callstack/react-native-paper/issues/4064), which significantly impacts users that rely on TalkBack to use the app.

Starting from Joplin v3.0.1, the `<View>` added by React Native is made smaller by adding margins above and to the left. These margins are determined by the screen size and an offset. Even with this solution, a small portion of the screen still blocks TalkBack's tap-to-navigate. As reported in #11276, this workaround also pushed the new note/new to-do buttons offscren.

This commit changes how the FAB.Group's invisible `<View>` is resized. Previously it was done with margins. Now, it's done with the top/left absolute positioning properties.

**Note**: If [this upstream pull request](https://github.com/callstack/react-native-paper/pull/4514) is merged, it should be possible to remove the workaround entirely.

# Screen recording

# Testing plan

## TalkBack regression testing

**Android 13**:
1. Verify that the new note menu can be opened and closed by clicking on the "+" button.
2. Enable TalkBack.
3. Tap the "new note" button.
4. Verify that it receives focus.
5. Tap on a note in the note list (far away from the "+" button).
6. Verify that it receives focus.
7. Open the note.
8. Verify that the edit button can be focused by Talkback.
9. Verify that tapping on the titlebar focuses it.
10. Focus the edit button, then double-tap.
11. Verify that edit mode is open.

[screen recording, roughly demonstrates testing plan below](https://github.com/user-attachments/assets/d4c98eaf-8f30-4a3b-9a44-4c23f5728269)

**Note**: Observe that the "New note" and "New to-do" buttons can be focused by TalkBack even when the menu is collapsed. See [this upstream pull request](https://github.com/callstack/react-native-paper/pull/4498) for a possible fix.

## Verifying that the new note button isn't pushed offscreen

**Android 14 emulator in 3-button navigation mode**:
1. Open the notes list in portrait mode (such that the three navigation buttons are at the bottom of the screen).
2. Verify that the new note button is completely on-screen.

> [!NOTE]
>
> On the Android 14 emulator, before this PR, the "+" button was not completely pushed offscreen (about 3/4ths of the button visible).

### CODE REVIEW

File: packages/app-mobile/components/buttons/FloatingActionButton.tsx [hunk 1]
```diff
@@ -71,10 +71,22 @@ const FloatingActionButton = (props: ActionButtonProps) => {
...
+		if (!adjustMargins) {
+			return {};
+		}
+
+		// Internally, React Native Paper uses absolute positioning to make its
+		// (usually invisible) view fill the screen. Setting top and left to
+		// undefined causes the view to take up only part of the screen.
+		return {
+			top: undefined,
+			left: undefined,
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/buttons/FloatingActionButton.tsx:87]: This overrides the `top: 0` and `left: 0` in the default view styles.
