### PR TITLE
Desktop: Accessibility: Improve scrollbar contrast

### LINKED ISSUE #8817: Scrollbar thumb is barely visible in Light theme
## Environment

Joplin version: 2.12.15
Platform: Windows
OS specifics:  Windows 11 22H2

## Steps to reproduce

1. Select Tools > Options > Appearance > Theme: Light
2. Open a profile which has many tags.

## Describe what you expected to happen

Expect to see thumb of scrollbar, but it is extremely difficult to find.

Thumb is slightly easier to see in dark themes, but still almost invisible in most.
Screenshot 2023-09-10 111027_2

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request increases the scrollbar contrast, particularly in the sidebar, which has a dark background in light  mode.

Fixes https://github.com/laurent22/joplin/issues/8817 (which was originally fixed by https://github.com/laurent22/joplin/pull/8831, though that fix was [reverted](https://github.com/laurent22/joplin/commit/1f19072f8f996d67a68648430dade743a23e1969)).
Related to #10795 (WCAG 2.2 [SC 1.4.3](https://www.w3.org/WAI/WCAG22/quickref/#contrast-minimum)).

# Screenshots

| Theme | Before | After |
|------|------|------|
| Light | before: the scrollbar in the dark-background sidebar is difficult to see | after: the scrollbar in the dark-background sidebar is easier to see |
| Dark | before/dark | after/dark: Scrollbars are now slightly easier to see |

# To-do

- [x] Check that the new scrollbar contrast is sufficient (at least 3:1).
    - [Sidebar/light mode: 3.8:1](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF75&bcolor=313640)
    - [Notes list/light mode: 3.01:1](https://webaim.org/resources/contrastchecker/?fcolor=32373F8A&bcolor=F4F5F6)

### CODE REVIEW

File: packages/lib/theme.ts [hunk 1]
```diff
@@ -97,7 +97,49 @@ const globalStyle = (() => {
 	};
 })();
 
-export function extraStyles(theme: Theme) {
+export const derivedColors = (theme: Theme) => {
```
Comment (personalizedrefrigerator) [inline packages/lib/theme.ts]: Since `scrollbarThumbColor` is used in `renderer/`, it needs to be available on mobile. As such, derived colors were refactored into a new `derivedColors` function that can be used in `app-mobile`'s `global-style.ts`.

File: packages/renderer/noteStyle.ts [hunk 2]
```diff
@@ -137,14 +137,13 @@ export default function(theme: any, options: Options = null) {
 			border: none;
 		}
 		::-webkit-scrollbar-thumb {
-			background: rgba(100, 100, 100, 0.3); 
-			border-radius: 5px;
```
Comment (personalizedrefrigerator) [inline packages/renderer/noteStyle.ts:141]: **Note**: Setting `border-radius` here is unnecessary (it's already set a few lines above).

File: packages/app-desktop/main.scss [hunk 3]
```diff
@@ -53,7 +53,19 @@ a {
...
+}
+
+:root {
+	--scrollbar-thumb-color: var(--joplin-scrollbar-thumb-color);
+	--scrollbar-thumb-color-hover: var(--joplin-scrollbar-thumb-color-hover);
+}
+
+// Uses a scrollbar with secondary colors. Should be used for content with
+// background matching joplin-background-color2.
+._scrollbar2 {
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/main.scss:66]: `_scrollbar2` follows the naming pattern for [RSCSS helper classes](https://ricostacruz.com/rscss/helpers.html). RSCSS also suggests including all helpers in a single file called `helpers`. For now, `_scrollbar2` is included in `main.scss` (near the other scrollbar logic). If desired, I can move it to a new `helpers.scss` file.
