### PR TITLE
- All: Resolves #4313: Quick onedrive delta fix

### LINKED ISSUE #4313: OneDrive always full sync issue
## Environment

Joplin version: Win 1.5.14, iOS 10.5.1
Platform: Windows, macOS, iOS, Android
OS specifics: Windows 10, iOS 14.3

## Steps to reproduce

1. setup Synchronization target to OneDrive
2. sync until first full sync done
3. sync again, it is still full sync

## Describe what you expected to happen
I have 17000 notes, about 38000 items in Joplin, I use OneDrive as storage, and sync every day. In 2020, every thing is fine. But I got full sync issue in 2021.

Joplin always full sync every time. I try to delete Joplin App, all of JoplinProfile and data in local. After first full sync finished, it still full sync again and again, or stop in middle, no delta sync.

I use latest Joplin version in Windows 10, macOS, iOS and Android, which have same issue.

## Logfile
Windows Log when sync break in middle:
2021-01-06 10:19:34: "RevisionService::maintenance: Starting..."
2021-01-06 10:19:34: "RevisionService::maintenance: Service is enabled"
2021-01-06 10:19:34: "RevisionService::collectRevisions: Created revisions for 0 notes"
2021-01-06 10:19:52: "Got unhandled error:", "ECONNRESET", "request to https://public.bn.files.1drv.com/y4mgSQZv_y7Zv3FeAejXs7CDf3N6qXtlo13TSp4bo72xoyYgK73DcU3SmhYiCTInoClDmxBIPWngQiilR7jJVcTY8iVcDzhmmxRG8MyzWMtPFbqr5z83VihAk4LPtsvo-0_JC9DRV4lipzUw4GpY56OmLSkm6SRlwFfjJEpBPTRfnyIyuQYo0IDTVxlW72-tDoII4TbiYWbCl8lOkn6KJvvkDzK0WvtV9nWQLj_evuSFFc/36b02c3421c94ece8c88cd03872ad0ad.md failed, reason: read ECONNRESET", "FetchError: request to https://public.bn.files.1drv.com/y4mgSQZv_y7Zv3FeAejXs7CDf3N6qXtlo13TSp4bo72xoyYgK73DcU3SmhYiCTInoClDmxBIPWngQiilR7jJVcTY8iVcDzhmmxRG8MyzWMtPFbqr5z83VihAk4LPtsvo-0_JC9DRV4lipzUw4GpY56OmLSkm6SRlwFfjJEpBPTRfnyIyuQYo0IDTVxlW72-tDoII4TbiYWbCl8lOkn6KJvvkDzK0WvtV9nWQLj_evuSFFc/36b02c3421c94ece8c88cd03872ad0ad.md failed, reason: read ECONNRESET
Code: ECONNRESET
FetchError: request to https://public.bn.files.1drv.com/y4mgSQZv_y7Zv3FeAejXs7CDf3N6qXtlo13TSp4bo72xoyYgK73DcU3SmhYiCTInoClDmxBIPWngQiilR7jJVcTY8iVcDzhmmxRG8MyzWMtPFbqr5z83VihAk4LPtsvo-0_JC9DRV4lipzUw4GpY56OmLSkm6SRlwFfjJEpBPTRfnyIyuQYo0IDTVxlW72-tDoII4TbiYWbCl8lOkn6KJvvkDzK0WvtV9nWQLj_evuSFFc/36b02c3421c94ece8c88cd03872ad0ad.md failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\D\AppData\Local\Temp\1mM0wIAapQQoIcMOyYoSSmZVYw2\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
2021-01-06 10:19:52: "Got unhandled error:", "ECONNRESET", "request to https://public.bn.files.1drv.com/y4mTLy1GF7uqrdJZrlPY0CCBBvFSKjKgG0lILduof2jzcPGEn5dJptujTN0rKhUfZOVI1EIxEXmhn7aZMGwk_mB2sX4TyfHwR9PLZiu8oBobQNgciAZZEbHrsbTop8NAfb9FIR8ckIOYdmiIEqlqfwOqrDMqLZRCDBrN-C79PVfNsO5uX-qHtrovA2yQo_XWK348cCokUeMPi-y6y6Q6uWb7JtLQYNh9tbmkABRbe26iU4/bd6433dc802944f08e818523a95c637a.md failed, reason: read ECONNRESET", "FetchError: request to https://public.bn.files.1drv.com/y4mTLy1GF7uqrdJZrlPY0CCBBvFSKjKgG0lILduof2jzcPGEn5dJptujTN0rKhUfZOVI1EIxEXmhn7aZMGwk_mB2sX4TyfHwR9PLZiu8oBobQNgciAZZEbHrsbTop8NAfb9FIR8ckIOYdmiIEqlqfwOqrDMqLZRCDBrN-C79PVfNsO5uX-qHtrovA2yQo_XWK348cCokUeMPi-y6y6Q6uWb7JtLQYNh9tbmkABRbe26iU4/bd6433dc802944f08e818523a95c637a.md failed, reason: read ECONNRESET
Code: ECONNRESET
FetchError: request to https://public.bn.files.1drv.com/y4mTLy1GF7uqrdJZrlPY0CCBBvFSKjKgG0lILduof2jzcPGEn5dJptujTN0rKhUfZOVI1EIxEXmhn7aZMGwk_mB2sX4TyfHwR9PLZiu8oBobQNgciAZZEbHrsbTop8NAfb9FIR8ckIOYdmiIEqlqfwOqrDMqLZRCDBrN-C79PVfNsO5uX-qHtrovA2yQo_XWK348cCokUeMPi-y6y6Q6uWb7JtLQYNh9tbmkABRbe26iU4/bd6433dc802944f08e818523a95c637a.md failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\D\AppData\Local\Temp\1mM0wIAapQQoIcMOyYoSSmZVYw2\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
2021-01-06 10:19:53: "FetchError: On file 36b02c3421c94ece8c88cd03872ad0ad.md: request to https://public.bn.files.1drv.com/y4mgSQZv_y7Zv3FeAejXs7CDf3N6qXtlo13TSp4bo72xoyYgK73DcU3SmhYiCTInoClDmxBIPWngQiilR7jJVcTY8iVcDzhmmxRG8MyzWMtPFbqr5z83VihAk4LPtsvo-0_JC9DRV4lipzUw4GpY56OmLSkm6SRlwFfjJEpBPTRfnyIyuQYo0IDTVxlW72-tDoII4TbiYWbCl8lOkn6KJvvkDzK0WvtV9nWQLj_evuSFFc/36b02c3421c94ece8c88cd03872ad0ad.md failed, reason: read ECONNRESET
Code: ECONNRESET
FetchError: request to https://public.bn.files.1drv.com/y4mgSQZv_y7Zv3FeAejXs7CDf3N6qXtlo13TSp4bo72xoyYgK73DcU3SmhYiCTInoClDmxBIPWngQiilR7jJVcTY8iVcDzhmmxRG8MyzWMtPFbqr5z83VihAk4LPtsvo-0_JC9DRV4lipzUw4GpY56OmLSkm6SRlwFfjJEpBPTRfnyIyuQYo0IDTVxlW72-tDoII4TbiYWbCl8lOkn6KJvvkDzK0WvtV9nWQLj_evuSFFc/36b02c3421c94ece8c88cd03872ad0ad.md failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (C:\Users\D\AppData\Local\Temp\1mM0wIAapQQoIcMOyYoSSmZVYw2\resources\app.asar\node_modules\@joplin\lib\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"

### PR DESCRIPTION
**Pull request by jonath92**
Quick fix for #4313

Onedrive currently gives always an "Resync required" error when making a delta request to a specific directory but not when making a request to the root. I will open an issue later at the Onedrive api docs and when it is working again we can revert the changes of this pr again as it is more efficient to make the request to the folder than filtering the delta response to only get the changes for the joplin folder. But it is definitely much better to filter the request than making a full resync each time.

### CODE REVIEW

**Comment by laurent22** [comment]
Would that break support for OneDrive Business?

File: packages/lib/file-api-driver-onedrive.js [hunk 1]
```diff
@@ -220,9 +220,8 @@ class FileApiDriverOneDrive {
 		};
 
 		const freshStartDelta = () => {
-			// Business Accounts are only allowed to make delta requests to the root. For some reason /delta gives an error for personal accounts and :/delta an error for business accounts
 			const accountProperties = this.api_.accountProperties_;
-			const url = (accountProperties.accountType === 'business') ? `/drives/${accountProperties.driveId}/root/delta` : `${this.makePath_(path)}:/delta`;
+			const url = `/drives/${accountProperties.driveId}/root/delta`;
```
Comment (jonath92) [inline packages/lib/file-api-driver-onedrive.js:224]: Here you can see that the url stays the same for OneDrive for Business

**Comment by jonath92** [comment]
No. It has no changes for OneDrive for Business as the used URL stays the same. As far as I can the current problem shouldn't occur for OneDrive for Business users (however I can't test as I currently don't have access to a Business account and when you make a test account you need to wait about 24 hours before you can use the account).

**Comment by laurent22** [comment]
Thanks for the fix, then let's merge.
