### PR TITLE
Desktop: Resolves #5288: Added back fitContent without breaking panels.

### LINKED ISSUE #5288: After Joplin update Layout distroyed by using TOC
Hi,

using outline-plugin or TOC from the Joplin-Plugin-Tutorial:
Click on an TOC list element will move the layout upwards (all panels right of note-list-sidebar), so the head and editor-menü are dissapeared.
Repair only through Joplin restart.
 
## Environment

Joplin version: 2.2.4
Platform: Windows 7
OS specifics: Home

## Steps to reproduce

1. using outline-plugin or TOC from the Joplin-Plugin-Tutorial
2. Click list element will move the layout upwards, so head and menü rows are dissapeared
3. Repair through Joplin restart

## Describe what you expected to happen
Clicking list element should scroll note panel to that heading without scrolling other panels

## Logfile
image
[-1628657327897.log](https://github.com/laurent22/joplin/files/6965945/-1628657327897.log)

### PR DESCRIPTION
**Pull request by Ahmad45123**
I've realized my issue. I assumed that UserWebview was only used by dialogs which was fatal haha. Even when testing I only tested plugins that had dialogs in them and completely forgot that there's other UI elements that shared the same Webview file.

The issue was that `vw` and `vh` are relative to the browser dimensions and not it's parents. This is perfectly fine for dialogs as they're indeed relative to the window but when it comes to panels, those MUST be sized relative to their parent or else they'd have really large dimensions as we saw in Note Tabs plugins.

So a possible fix would be to simply apply the `vw` and `vh` stuff ONLY for dialogs but the rest of UI must still use `100%`. This was achieved by simply moving over the code to `UserWebviewDialog` instead of `UserWebview`

### Testing
I've tested Note Tabs plugin panels, Tagging plugin dialog (uses fitToContent), Conflict Resolution dialog (doesn't use fit to content), and finally the outline plugin.  All of them seemed to work perfectly now :)

### CODE REVIEW

File: packages/app-desktop/services/plugins/UserWebviewDialog.tsx [hunk 1]
```diff
@@ -113,7 +116,7 @@ export default function UserWebviewDialog(props: Props) {
 						viewId={props.viewId}
 						themeId={props.themeId}
 						borderBottom={false}
-						fitToContent={true}
+						fitToContent={props.fitToContent}
```
Comment (laurent22) [inline packages/app-desktop/services/plugins/UserWebviewDialog.tsx:119]: Since you now moved the prop to the Dialog component, do we still need it here?

Comment (Ahmad45123) [reply packages/app-desktop/services/plugins/UserWebviewDialog.tsx:119]: Yes because I still want the Userwebview to have 100% width and 100% height.

Comment (laurent22) [reply packages/app-desktop/services/plugins/UserWebviewDialog.tsx:119]: Something's not right with having this property on two nested components. Could you explain how it work when fitToContent is true, and when it's false? What's the dimensions of Dialog, and what's the dimensions of UserWebview?

Comment (Ahmad45123) [reply packages/app-desktop/services/plugins/UserWebviewDialog.tsx:119]: ## UserWebview

When `fitToContent` is true, it'll be sized according to the content thus having exact pixel values. When it's false, it'll have 100% width and 100% height, filling it's parent completely.

We want this to be false so that the Webview grows to fill to the parent Dialog div.

## Dialog
When `fitToContent` is true, we'll leave the dimensions for this as `auto` in order to make it grow with the Webview. If it's false, we want to make this Dialog `90vw` wide `80vh` high. Ofcourse the Webview will always fill this 100%.

I did think about having the Dialog always at 90vh and 80vh but this caused issues like this: 
image

The `iframe` has exact pixel dimensions but the Dialog div is way larger. _(it must be auto when fitToContent is on.)_

Comment (laurent22) [reply packages/app-desktop/services/plugins/UserWebviewDialog.tsx:119]: So do you see the problem, and do you have any suggestion on how to fix it?

Comment (Ahmad45123) [reply packages/app-desktop/services/plugins/UserWebviewDialog.tsx:119]: I'm not sure where is the problem no?

Comment (Ahmad45123) [reply packages/app-desktop/services/plugins/UserWebviewDialog.tsx:119]: In short, To achieve full screen idea, we want the Dialog to have `90vw and 80vh` and the Webview must have 100% dimensions in order to fill this Dialog parent. Maybe there's a better way then what I did ?

Comment (laurent22) [reply packages/app-desktop/services/plugins/UserWebviewDialog.tsx:119]: I couldn't quite see from the diff but your change makes sense actually. Thanks for clarifying, and let's merge then.
