### PR TITLE
Desktop: Fixed KaTeX font issue in exported PDF

### LINKED ISSUE #3078: Math font in exported PDF is different from that in the preview
Starting from as late as Joplin 1.0.199, the math font in exported PDF is no longer KaTeX-Main. Version 1.0.193 is fine.

On my system the font becomes Tinos, and if I remove Tinos I get Liberation Serif.

tinos

## Environment

Joplin version: 1.0.201 
Platform: Linux
OS specifics: Arch Linux

## Steps to reproduce

1. Export a note with some equations as PDF.
2. Open the PDF in a viewer. The font shapes are obviously different, and the PDF properties say that the font embedded is not KaTeX-Main.

## Describe what you expected to happen

Math in the exported PDF should be rendered using the same font as in preview:

km

### PR DESCRIPTION
**Pull request by kowalskidev**
Fixes #3078

When we export a note `InteropService()` render a note in HTML file in temp directory then using that HTML file PDF get exported, Now I figured out that HTML file requires a `katex.css` which is already exported by plugin and `katex.css` requires the fonts included in fonts directory which is not exported by plugin so we need to export the fonts directory also along with `katex.css` now I added the fonts in `katex.js` so they also will be exported. Now everything working fine!

@PackElend Can you label me please? Thank you!

### CODE REVIEW

File: ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js [hunk 1]
```diff
@@ -17,8 +17,28 @@ katex = mhchemModule(katex);
...
+		{ name: 'fonts/KaTeX_SansSerif-Italic.woff2' },
+		{ name: 'fonts/KaTeX_SansSerif-Regular.woff2' },
+		{ name: 'fonts/KaTeX_Script-Regular.woff2' },
+		{ name: 'fonts/KaTeX_Size1-Regular.woff2' },
+		{ name: 'fonts/KaTeX_Size2-Regular.woff2' },
+		{ name: 'fonts/KaTeX_Size3-Regular.woff2' },
+		{ name: 'fonts/KaTeX_Size4-Regular.woff2' },
+		{ name: 'fonts/KaTeX_Typewriter-Regular.woff2' },
+		// Note: Katex also requires a number of fonts and they need to be specified here
+		// since they will be required while exporting to HTML or PDF.
```
Comment (kowalskidev) [inline ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js:41]: https://github.com/laurent22/joplin/issues/3078#issuecomment-616158572

@laurent22  As you asked me to add comments I've modified your comment 😄

Comment (tessus) [reply ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js:41]: Can you please move the comment after `		{ name: 'katex.css' },` (although in its own line) and change it to:

```
// Note: Katex requires the following fonts to be explicitly specified for exporting
// a note to HTML and PDF.
```

Comment (laurent22) [reply ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js:41]: Let's mention as well that it's not needed for in-app rendering.

> Declaring the fonts is not needed for in-app rendering because they will be loaded automatically from katex.css. However they must be specified for exporting notes to HTML and PDF, so that they can be bundled with the other assets.

Comment (kowalskidev) [reply ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js:41]: > 
> 
> Let's mention as well that it's not needed for in-app rendering.
> 
> > Declaring the fonts is not needed for in-app rendering because they will be loaded automatically from katex.css. However they must be specified for exporting notes to HTML and PDF, so that they can be bundled with the other assets.

Okay sir I'll update the comment with your statement.

File: ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js [hunk 2]
```diff
@@ -17,8 +17,30 @@ katex = mhchemModule(katex);
 function katexStyle() {
 	return [
 		{ name: 'katex.css' },
-		// Note: Katex also requires a number of fonts but they don't need to be specified here
-		// since they will be loaded as needed from the CSS.
+		/* Note: Declaring the fonts is not needed for in-app rendering because
+		they will be loaded automatically from katex.css.
+		However they must be specified for exporting notes to HTML and PDF,
+		so that they can be bundled with the other assets. */
```
Comment (tessus) [inline ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js:23]: Did you install the commit hook? I don't think so, otherwise the commet woulf have been changed to:

```
// Note: Declaring the fonts is not needed for in-app rendering because
// they will be loaded automatically from katex.css.
// However they must be specified for exporting notes to HTML and PDF,
// so that they can be bundled with the other assets.
```

Comment (kowalskidev) [reply ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js:23]: No I didn't know about commit hooks. Should I manually change it to your format?

> // Note: Declaring the fonts is not needed for in-app rendering because
> // they will be loaded automatically from katex.css.
> // However they must be specified for exporting notes to HTML and PDF,
> // so that they can be bundled with the other assets.

Comment (tessus) [reply ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js:23]: No, you should install the commit hook as described in CONTRIBUTING.md and add an empty commit.

Comment (laurent22) [reply ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js:23]: Yes please, and it's strange it didn't get picked up by CI.

Comment (PackElend) [reply ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js:23]: > Should I manually change it to your format?

@kowalskidev, recall what I told you once how to read and interpret comments. Your answer puts you quite a bad position. Your talent to read between the lines need still to be improved

Comment (kowalskidev) [reply ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js]: > @kowalskidev, recall what I told you once how to read and interpret comments. Your answer puts you quite a bad position. Your talent to read between the lines need still to be improved

Oppss!! Sorry sir my bad! I was confused so I simply asked what to do next.
I hope it's all clear now regarding commit hooks.

File: ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js [hunk 3]
```diff
@@ -16,9 +16,31 @@ katex = mhchemModule(katex);
 
 function katexStyle() {
 	return [
+		// Note: Declaring the fonts is not needed for in-app rendering because
+		// they will be loaded automatically from katex.css.
+		// However they must be specified for exporting notes to HTML and PDF,
+		// so that they can be bundled with the other assets.
```
Comment (tessus) [inline ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js:22]: Below the katex.css but above the fonts.

File: ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js (hunk 2 above)
Comment (tessus) [reply ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js]: Well, I'm not sure, if you have installed the hook, since you force pushed. Anyway, the comment form is ok, but at the wrong position. see my other comment

Comment (kowalskidev) [reply ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js]: I think that's an issue with windows. I use dual boot OS (windows and ubuntu) sometime I commit from ubuntu then commit hooks and linter-ci works but in windows I'm not sure it's working properly as it doesn't changed the comments while pushing to GitHub as expected. Next I'll only use ubuntu to make sure everything works fine.

Comment (tessus) [reply ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js]: The pre-commit hook fires when you commit, not when you push. You can test it locally without having to push. Just create a branch and commit a "wrong" multi line comment.
If the comment has been changed, the hook works.

Comment (kowalskidev) [reply ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js]: Thank you sir. I'll test it right now.

Comment (tessus) [reply ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js]: You're welcome. Btw, no need to call me sir.

**Comment by laurent22** [comment]
Great, thanks for the fix!
