### PR TITLE
Server: Fix unique constraint error when multiple `createSharedFolderUserItems` are run concurrently

### LINKED ISSUE #12075: Notebook disappeared after failed sharing attempt
### Operating system

Windows

### Joplin version

3.2.13

### Desktop version info

Joplin 3.2.13 (prod, win32)

Client ID: 798dcc9cebae4ab08da69993d2a2107a
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: a898e17

Backup: 1.4.2
Freehand Drawing: 2.14.0
Victor: 1.0.3

### Current behaviour

_This was reported on the forum here: https://discourse.joplinapp.org/t/notebook-disappeared-after-failed-sharing-attempt/44277_

I attempted to share one of my notebooks. After adding the recipient email address and clicking the "Share" button, nothing happened and the email did not show up in the recipients list. However, the notebook and sub-folders all turned yellow. After confirming that the recipient never received a sharing approval request, I attempted to share the notebook again. I entered the recipient's email address, clicked the "Share" button, and this time it added the recipient email address to the recipients list, and the recipient received an approval request for the shared folder. The recipient clicked "Accept", but the notebook never showed up for the recipient. Then the prompt for the recipient to accept the share appeared again, and the receipient clicked "Accept" again. It eventually gave the recipient an error, stating the following:
'Could not respond to the invitation. Please try again, or check with the notebook owner if they are still sharing it. The error was "insert into "user items" ("created_time", "Item_id", "updated_time", "user_id") values ($1, $2, $3, $4) - duplicate key value violates unique constraint "user_items_user_id_item_id_unique""'.
The notebook never showed up to the recipient after the recipient synced.

So I went back to the source computer and attempted to unshare the notebook so I could attempt to start the sharing process again. However, when I attempted to unshare the notebook, it gave me an error stating "The recipient could not be removed from the list. Please try again", followed by a similar error immediately afterward (screenshots attached).

Then, after it synced, the whole notebook that I had attempted to share then unshare completely vanished. I could not find any trace of it anywhere.

What happened to the notebook, and how can a notebook suddenly vanish?

**Screenshots:**
Image
Image
Image

### Expected behaviour

Notebook should be able to be shared or un-shared correctly, and should not be deleted when unshared

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request ignores "unique constraint" thrown while adding `(user_id, item_id)` pairs to `user_items` while accepting a share. (See [comment](https://github.com/laurent22/joplin/issues/12075#issuecomment-3246245206)).

May partially resolve https://github.com/laurent22/joplin/issues/12075.

# Testing

This pull request includes an automated test that runs `createSharedFolderUserItems` multiple times concurrently (as could happen if the same share is accepted multiple times concurrently).

With this change, the sync fuzzer fails after 22 steps, with conflicts (currently expected, see https://github.com/laurent22/joplin/pull/12993).

### CODE REVIEW

File: packages/server/src/models/UserItemModel.ts [hunk 1]
```diff
@@ -138,20 +145,26 @@ export default class UserItemModel extends BaseModel<UserItem> {
...
+							item_type: ItemType.UserItem,
+							item_id: item.id,
+							item_name: item.name,
+							type: ChangeType.Create,
+							previous_item: '',
+							user_id: userId,
+						});
+					}
+				} catch (error) {
+					if (!options.ignoreAlreadyExists || !isUniqueConstraintError(error)) {
```
Comment (personalizedrefrigerator) [inline packages/server/src/models/UserItemModel.ts:165]:
```suggestion
					if (!isUniqueConstraintError(error)) {
```

Some (almost all?) calls to `UserItemModel.add`/`UserItemModel.addMulti` are already wrapped in a `try`/`catch` that ignores unique constraint errors ([example](https://github.com/laurent22/joplin/blob/58a9c229bbf6cbb915887f29a025246aa1c652b8/packages/server/src/models/ShareModel.ts#L194)). It could make sense to remove the option and always ignore unique constraint errors here.

**Comment by personalizedrefrigerator** [comment]
Closing temporarily until the following in-CI test failure is resolved:
```
[@joplin/server]: FAIL dist/models/ShareModel.test.js
[@joplin/server]:   ● ShareModel › should be possible to run createSharedFolderUserItems multiple times concurrently
[@joplin/server]: 
[@joplin/server]:     error: insert into "user_items" ("created_time", "item_id", "updated_time", "user_id") values ($1, $2, $3, $4) - current transaction is aborted, commands ignored until end of transaction block
[@joplin/server]: 
[@joplin/server]:       at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:369:69)
[@joplin/server]:       at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:187:21)
[@joplin/server]:       at Parser.parse (node_modules/pg-protocol/src/parser.ts:102:30)
[@joplin/server]:       at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)
```

**Comment by personalizedrefrigerator** [comment]
I'm re-running CI — the most recent failing test seems unrelated to this pull request:
```
 [@joplin/transcribe]:   ● FileStorage › should remove files that are older than the given date
[@joplin/transcribe]: 
[@joplin/transcribe]:     expect(received).toBe(expected) // Object.is equality
[@joplin/transcribe]: 
[@joplin/transcribe]:     Expected: 2
[@joplin/transcribe]:     Received: 3
[@joplin/transcribe]: 
[@joplin/transcribe]:       52 | 		await fs.removeOldFiles(new Date('2025-03-03 12:00'));
[@joplin/transcribe]:       53 | 		const files = await readdir('images');
[@joplin/transcribe]:     > 54 | 		expect(files.length).toBe(2);
[@joplin/transcribe]:          | 		                     ^
[@joplin/transcribe]:       55 | 		expect(files.includes(mockedFilenames[2])).toBe(true);
[@joplin/transcribe]:       56 |
[@joplin/transcribe]:       57 | 		for (const file of mockedFiles) {
[@joplin/transcribe]: 
[@joplin/transcribe]:       at Object.toBe (src/services/FileStorage.test.ts:54:24)
```

File: packages/server/src/models/UserItemModel.ts [hunk 2]
```diff
@@ -116,47 +123,53 @@ export default class UserItemModel extends BaseModel<UserItem> {
...
+			if (!('name' in item) || !('id' in item)) throw new Error('item.id and item.name must be set');
 
-				if (this.models().item().shouldRecordChange(item.name)) {
-					await this.models().change().save({
-						item_type: ItemType.UserItem,
-						item_id: item.id,
-						item_name: item.name,
-						type: ChangeType.Create,
-						previous_item: '',
+			await this.withTransaction(async () => {
```
Comment (personalizedrefrigerator) [inline packages/server/src/models/UserItemModel.ts:147]: This `withTransaction` has been moved within the `for` loop to avoid the following error observed while running tests in CI: `current transaction is aborted, commands ignored until end of transaction block`.
