### PR TITLE
Mobile,Desktop: Fix #9200: Fix list renumbering and enable multiple selections

### LINKED ISSUE #9196: CodeMirror 6 beta editor: Multiple cursors are enabled, but missing the ability to alt+drag (as in the CodeMirror 5 editor)
## Environment

Joplin version: 2.13.4
Platform: Desktop
OS specifics: Ubuntu 23.10

## Steps to reproduce

1. Enable the beta editor
2. Open the default `1. Welcome to Joplin!` note
3. Try to use multiple cursors using alt+shift+drag (this works on https://codemirror.net/try/)
4. Select `Joplin`
5. Press <kbd>Ctrl</kbd>+<kbd>d</kbd>

## Describe what you expected to happen

<kbd>alt</kbd>+<kbd>shift</kbd>+drag should create multiple cursors, like <kbd>ctrl</kbd>+<kbd>d</kbd> does.

## Notes

I believe that [allowMultipleSelections](https://codemirror.net/docs/ref/#state.EditorState^allowMultipleSelections) is an extension that needs to be enabled. <kbd>ctrl</kbd>+<kbd>d</kbd> creating multiple selections even when this is disabled is possibly a CodeMirror bug (**edit**: [upstream bug report](https://github.com/codemirror/dev/issues/1288)).

### LINKED ISSUE #9200: Desktop: CM6 beta editor duplicates list items when indenting with multiple selections
## Environment

Joplin version: 2.13.4
Platform: Desktop
OS specifics: Ubuntu 23.10

## Steps to reproduce

1. Enable the beta editor
2. Create a new note with the following text:
```
1. A list:
2. test 1
3. test 2
4. test 3
```
3. Select `test`
5. Press <kbd>ctrl</kbd>+<kbd>d</kbd> twice (shortcut may be different on Mac)
6. Press <kbd>tab</kbd>

## Describe what you expected to happen

Each of the lines with a selection should be indented, as if each had been selected individually and indented one at a time.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request does two things:
- Fixes a list renumbering issue when there are multiple selections (fixes #9200)
- Enables multiple selections (fixes #9196) to allow testing the above manually,
    - On request, enabling multiple selections can be moved to a separate pull request.

# Testing plan

This pull request has an automated test. However, it can be tested manually by:
1. Creating a numbered list:
```
1. this
2. is
3. a
4. test
5. of
6. lists
```
2. Adding cursors to lines 2, 3, and 4:
3. Pressing <kbd>tab</kbd>
4. Removing all cursors, then adding cursors to lines 3 and 4
5. Pressing <kbd>tab</kbd>
6. Adding a cursor to just line 4 (remove the cursor from line 3)
7. Pressing <kbd>tab</kbd>
8. Adding a cursor to line 5
9. Pressing <kbd>shift</kbd>-<kbd>tab</kbd> twice

After each step, each list should have the same numbering as it does in the viewer.

This has been successfully tested on Ubuntu 23.10.

### CODE REVIEW

File: packages/editor/CodeMirror/markdown/markdownReformatter.ts [hunk 1]
```diff
@@ -644,15 +646,38 @@ export const renumberList = (state: EditorState, sel: SelectionRange): Selection
...
+				while (targetIndentLen > indentationLen) {
+					const listNumberRecord = listNumberStack.pop();
+
+					if (!listNumberRecord) {
+						break;
+					} else {
+						targetIndentLen = listNumberRecord.indentationLength;
+						nextListNumber = listNumberRecord.nextListNumber;
+					}
+				}
```
Comment (personalizedrefrigerator) [inline packages/editor/CodeMirror/markdown/markdownReformatter.ts:679]: I'm unsure why this wasn't necessary to handle double de-indentation before.

I suspect previously sublists weren't renumbered with parent lists. However, selecting a parent list and pressing <kbd>tab</kbd> *should* have also caused sublists to be renumbered.
