### PR TITLE
Chore: Resolves #12283: Server: Add fuzzer for detecting sync bugs

### LINKED ISSUE #12283: Create a fuzzer for notebook sharing on Joplin Server
It seems there's a bug related to sharing in Joplin Server/Cloud but it's unclear under which condition it happens. So we could create a fuzzer that randomly do various sharing-related action to find out which ones can cause issues.

It would need to randomly do various tasks:

- Sharing a notebook
- Unsharing a notebook
- Sharing a notebook, having the other person reject the share
- After a share is rejected, share the notebook again and this time accept it
- Change notes in one notebook, sync
- Share a notebook; other user accepts it; notebook is unshared; notebook is shared again before sync

etc.

Maybe everything should be split into "actions" (sharing, unsharing, accepting, rejecting, sync, etc.) then all those would be executed randomly.

After each step, the system should check if the current state is as expected - what notes are on the servers, what notes are on each client.

There's an existing `fuzzing.js` file, and a similar setup could be used: dynamically create CLI clients and use them to do various actions.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request adds a [fuzzer](https://en.wikipedia.org/wiki/Fuzzing) for detecting sync bugs in Joplin Server. 

**Goal**: Detect sync bugs.
- Fuzzing is often associated with finding security bugs. However, detecting security issues is currently not a goal of this task.

Resolves #12283.

# Notes

- The fuzzer can be run using `yarn syncFuzzer start` from the toplevel Joplin directory.
- The fuzzer, in its current state fails after 32 actions, when attempting to move a subfolder of a shared folder. The fuzzer expects the subfolder to become a toplevel notebook only on one client. Instead, the subfolder becomes toplevel on both the sharer and recipient. 

  <details><summary>Sample output on failure</summary>
  
  ```
  [...]
  00:02:32: fuzzer: Step 32 / 50
  00:02:32: fuzzer: Action: moveFolderToToplevel in 0f637d7938d049818efe71fc82df36b3@localhost
  00:02:32: Client: Move af335cd1a67a416f81213e61a444b28d to 
  00:02:35: Client: Sync 0f637d7938d049818efe71fc82df36b3@localhost
  00:02:40: Client: Check state 0f637d7938d049818efe71fc82df36b3@localhost
  00:02:40: Client: Check state 2217944866fa46bb947a2772314b799a@localhost
  00:02:40: fuzzer: .checkState failed. Syncing all clients...
  00:02:40: Client: Sync 0f637d7938d049818efe71fc82df36b3@localhost
  00:02:45: Client: Sync 2217944866fa46bb947a2772314b799a@localhost
  00:02:50: Client: Sync 0de4a0a5fc81405b9757eb71589cba97@localhost
  00:02:55: Client: Check state 0f637d7938d049818efe71fc82df36b3@localhost
  00:02:55: Client: Check state 2217944866fa46bb947a2772314b799a@localhost
  00:02:55: fuzzer: .checkState failed. Syncing all clients...
  00:02:55: Client: Sync 0f637d7938d049818efe71fc82df36b3@localhost
  00:03:00: Client: Sync 2217944866fa46bb947a2772314b799a@localhost
  00:03:05: Client: Sync 0de4a0a5fc81405b9757eb71589cba97@localhost
  00:03:10: Client: Check state 0f637d7938d049818efe71fc82df36b3@localhost
  00:03:10: Client: Check state 2217944866fa46bb947a2772314b799a@localhost
  00:03:10: fuzzer: .checkState failed. Syncing all clients...
  00:03:10: Client: Sync 0f637d7938d049818efe71fc82df36b3@localhost
  00:03:15: Client: Sync 2217944866fa46bb947a2772314b799a@localhost
  00:03:20: Client: Sync 0de4a0a5fc81405b9757eb71589cba97@localhost
  00:03:26: fuzzer: ERROR AssertionError [ERR_ASSERTION]: should have the same folders as the expected state
  + actual - expected
  ... Skipped lines
  
    [
      {
        id: '0a791cb5d74749e9879dce486c02ab27',
        parentId: '',
        title: 'Folder 15'
  ...
      },
  +   {
  +     id: 'af335cd1a67a416f81213e61a444b28d',
  +     parentId: '',
  +     title: 'Subfolder'
  +   }
    ]
  
      at checkFolderState (/home/self/Documents/joplin/packages/tools/fuzzer/Client.js:275:29)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async Client.checkState (/home/self/Documents/joplin/packages/tools/fuzzer/Client.js:278:9)
      at async ClientPool.checkState (/home/self/Documents/joplin/packages/tools/fuzzer/ClientPool.js:26:13)
      at async count (/home/self/Documents/joplin/packages/tools/fuzzer/sync-fuzzer.js:167:17)
      at async retryWithCount (/home/self/Documents/joplin/packages/tools/fuzzer/utils/retryWithCount.js:7:20)
      at async main (/home/self/Documents/joplin/packages/tools/fuzzer/sync-fuzzer.js:166:13) {
    generatedMessage: false,
    code: 'ERR_ASSERTION',
    actual: [Array],
    expected: [Array],
    operator: 'deepStrictEqual'
  }
  00:03:26: fuzzer: Client information:
   Client 0f637d7938d049818efe71fc82df36b3@localhost:
          Command: cd /home/self/Documents/joplin/packages/app-cli && yarn start-no-build --profile /home/self/Documents/joplin/packages/tools/fuzzer/profiles-tmp/0f637d7938d049818efe71fc82df36b3 --env dev
  
  Client 2217944866fa46bb947a2772314b799a@localhost:
          Command: cd /home/self/Documents/joplin/packages/app-cli && yarn start-no-build --profile /home/self/Documents/joplin/packages/tools/fuzzer/profiles-tmp/2217944866fa46bb947a2772314b799a --env dev
  
  Client 0de4a0a5fc81405b9757eb71589cba97@localhost:
          Command: cd /home/self/Documents/joplin/packages/app-cli && yarn start-no-build --profile /home/self/Documents/joplin/packages/tools/fuzzer/profiles-tmp/0de4a0a5fc81405b9757eb71589cba97 --env dev
  00:03:26: fuzzer: An error occurred. Pausing before continuing cleanup.
  [Press enter to continue]
  ```
  
  Observe that:
  - The fuzzer logs commands that can be used to start the individual clients and pauses, waiting for further input. This makes it easier to locally debug issues detected by the fuzzer.
  - The fuzzer logs information about how the expected state is different from the actual state.
  </details>

- The fuzzer works by:
   - Starting an instance of Joplin Server.
   - Creating and initializing a few instances of the CLI app.
   - Creating an expected state.
   - Applying actions to the CLI app instances and updating the expected state.
   - Comparing the state of the CLI apps with the expected state.
- When an error is detected, the fuzzer pauses. At this point, it's possible to start instances of the CLI app (using the test profile directories) and inspect the state of each.

# To-do

- [x] Move the following into separate pull requests:
   - [x] Fix sync issue after deleting shared notebooks (#12583).
   - [x] Add `share` command to the CLI app. (https://github.com/laurent22/joplin/pull/12637)
   - [x] Fix data API when both `include_conflicts=1` and `include_deleted=1` are specified (https://github.com/laurent22/joplin/pull/12650)
   - [x] CLI: Refresh shares when running `sync` (https://github.com/laurent22/joplin/pull/12667)
- [x] Don't always sync immediately after each action. Certain sync bugs may only occur after multiple actions are completed without sync.
- [ ] **Important (but planned for a separate PR)**: Support checking expected conflict state. Currently, the sync fuzzer actions are designed to avoid generating conflicts. This simplifies maintaining an expected state, but doesn't necessarily reflect accurately how users actually use sync.
- [ ] Add more actions to the fuzzer — these don't need to be done in this pull request:
   - [x] Create toplevel folder
   - [x] Create subfolder
   - [x] Share toplevel folder
   - [x] Delete folder
   - [x] Create note
   - [x] Move folder to toplevel
   - [x] Rename note
   - [x] Update note body
   - [x] Move note
   - [x] Move folder to another folder (partial: supports moving a folder to some other **empty** folder)
      - **Note**: Pay attention to the case where a folder is moved into a shared notebook.      
   - [ ] Remove user from share
   - [ ] Add additional user to share (currently the "share toplevel folder" action can only share with one other user)
   - [ ] Publish note
   - [ ] Modify a note on two different clients concurrently, creating a conflict.

### CODE REVIEW

**Comment by laurent22** [comment]
This is great, thank you. For the randomness, is it possible to set a seed so that we can replicate the failing run consistently when it happens?

File: packages/tools/fuzzer/sync-fuzzer.ts [hunk 1]
```diff
@@ -0,0 +1,214 @@
...
+		cleanupTasks.push(() => server.close());
+
+		if (!await server.checkConnection()) {
+			throw new Error('Could not connect to the server.');
+		}
+
+		const profilesDirectory = await createProfilesDirectory();
+		cleanupTasks.push(profilesDirectory.remove);
+
+		const random = new SeededRandom(12345);
```
Comment (personalizedrefrigerator) [inline packages/tools/fuzzer/sync-fuzzer.ts]: This is where the seed is set.

Comment (laurent22) [reply packages/tools/fuzzer/sync-fuzzer.ts]: Ok that looks good then. Later if for example we want to run this on CI it could make sense to start from a different seed every time, then display it so that we know how to replicate locally. But for now a static seed is good enough

File: packages/tools/fuzzer/utils/SeededRandom.ts
Comment (personalizedrefrigerator) [inline packages/tools/fuzzer/utils/SeededRandom.ts:1]: If some other part of Joplin uses a seeded random number generator, it may make sense to use it instead.

File: packages/tools/fuzzer/sync-fuzzer.ts (hunk 1 above)
Comment (personalizedrefrigerator) [reply packages/tools/fuzzer/sync-fuzzer.ts]: I've updated this to allow specifying the seed through a CLI parameter (using `yargs` for CLI flag parsing and help text).

Example:
```console
$ yarn syncFuzzer start --help
node-22 start

Starts the synchronization fuzzer. The fuzzer starts Joplin Server, creates
multiple CLI clients, and attempts to find sync bugs.
Use FUZZER_SERVER_ADMIN_PASSWORD to specify the admin@localhost password for
Joplin Server.

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]
  --seed                                               [number] [default: 12345]
$ yarn syncFuzzer --seed=123456
```

**Note**: `yargs` seems to be using `node-22` as the script name in the help output.

**Comment by personalizedrefrigerator** [comment]
Occasionally, manually running E2EE decryption from the CLI app is failing with the following:
```
2025-07-03 10:29:20: App: Client ID: 02fb474aaf3949148f0a36aa369c62ad
2025-07-03 10:29:20: models/Setting: Applying default migrations...
2025-07-03 10:29:20: e2ee/utils: activeMasterKeySanityCheck: Active key is an enabled key - nothing to do
2025-07-03 10:29:20: e2ee/utils: Trying to load 3 master keys...
2025-07-03 10:29:20: EncryptionService: Loading master key: b9ed85c2796b44358c664e7a6d59b9dd. Make active: <true>
2025-07-03 10:29:20: e2ee/utils: findMasterKeyPassword: Using master password
2025-07-03 10:29:20: e2ee/utils: Loaded master keys: 3
2025-07-03 10:29:20: ResourceFetcher: Auto-add resources: Mode: always
2025-07-03 10:29:20: permanentlyDeleteOldData: Processing items older than 7776000000ms...
2025-07-03 10:29:20: ResourceFetcher: Auto-added resources: 0
2025-07-03 10:29:20: permanentlyDeleteOldData: Items to permanently delete: {"folderIds":[],"noteIds":[]}
2025-07-03 10:29:20: checkDisabledSyncItemsNotification: No errors: Hiding notification
2025-07-03 10:29:20: DecryptionWorker: starting decryption...
2025-07-03 10:29:20: [error] DecryptionWorker: Error: Master key is not loaded: d93256c586864fb29ae1a760fab7efa1
Code: masterKeyNotLoaded
Error: Master key is not loaded: d93256c586864fb29ae1a760fab7efa1
    at EncryptionService.loadedMasterKey (/home/self/Documents/joplin/packages/lib/services/e2ee/EncryptionService.js:181:27)
    at EncryptionService.decryptAbstract_ (/home/self/Documents/joplin/packages/lib/services/e2ee/EncryptionService.js:547:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EncryptionService.decryptString (/home/self/Documents/joplin/packages/lib/services/e2ee/EncryptionService.js:629:9)
    at async Note.decrypt (/home/self/Documents/joplin/packages/lib/models/BaseItem.js:455:27)
    at async DecryptionWorker.start_ (/home/self/Documents/joplin/packages/lib/services/DecryptionWorker.js:190:47)
    at async DecryptionWorker.start (/home/self/Documents/joplin/packages/lib/services/DecryptionWorker.js:272:22)
    at async startDecryption (/home/self/Documents/joplin/packages/app-cli/build/command-e2ee.js:54:36)
    at async Command.action (/home/self/Documents/joplin/packages/app-cli/build/command-e2ee.js:112:17)
    at async Application.execCommand (/home/self/Documents/joplin/packages/app-cli/build/app.js:274:13)
```

If I manually run `sync` and `e2ee decrypt` just after the above error occurs, both succeed.

**Comment by personalizedrefrigerator** [comment]
The fuzzer is currently failing after 24 steps with unexpected conflicts. This seems to happen when a shared folder is deleted by the owner (a duplicate of the bug listed as a "remaining issue" in [this pull request](https://github.com/laurent22/joplin/pull/12583)).

<details><summary>Logs for the CLI app with the unexpected conflict</summary>

Logs related to the conflict:
```
2025-07-03 11:13:34: Synchronizer: Sync: noteConflict: remote has been deleted, but local has changes: Note: (Local 84a473f10af54fd6b1e09dff9016fae2)
2025-07-03 11:13:34: handleConflictAction: Handling conflict: noteConflict
2025-07-03 11:13:34: handleConflictAction: local: {"id":"84a473f10af54fd6b1e09dff9016fae2","parent_id":"c4d5a11241b14c369e160626b1f8ee72","title":"Test (x365)","body":"Testing...","created_time":1751566149437,"updated_time":1751566414463,"is_conflict":0,"latitude":"0.00000000","longitude":"0.00000000","altitude":"0.0000","author":"","source_url":"","is_todo":0,"todo_due":0,"todo_completed":0,"source":"joplindev","source_application":"net.cozic.joplindev-cli","application_data":"","order":1751566149437,"user_created_time":1751566149437,"user_updated_time":1751566149437,"encryption_cipher_text":"","encryption_applied":0,"markup_language":1,"is_shared":0,"share_id":"","conflict_original_id":"","master_key_id":"","user_data":"","deleted_time":0,"sync_time":1751566174125,"type_":1} remoteContent <null>
2025-07-03 11:13:34: handleConflictAction: remoteExists: <false>
2025-07-03 11:13:34: DeleteAction: sync: handleConflictAction: note/resource conflict: titles: ["Test (x365)"]; Item IDs: ["84a473f10af54fd6b1e09dff9016fae2"]
2025-07-03 11:13:34: FileApi: stat 61e5f8b839414e3c9f09ff52bf1407dd.md
2025-07-03 11:13:34: Synchronizer: Sync: noteConflict: remote has been deleted, but local has changes: Note: (Local 61e5f8b839414e3c9f09ff52bf1407dd)
2025-07-03 11:13:34: handleConflictAction: Handling conflict: noteConflict
2025-07-03 11:13:34: handleConflictAction: local: {"id":"61e5f8b839414e3c9f09ff52bf1407dd","parent_id":"c4d5a11241b14c369e160626b1f8ee72","title":"Renamed (129)","body":"Body","created_time":1751565808280,"updated_time":1751566414446,"is_conflict":0,"latitude":"0.00000000","longitude":"0.00000000","altitude":"0.0000","author":"","source_url":"","is_todo":0,"todo_due":0,"todo_completed":0,"source":"joplindev","source_application":"net.cozic.joplindev-cli","application_data":"","order":1751565808280,"user_created_time":1751565808280,"user_updated_time":1751566147324,"encryption_cipher_text":"","encryption_applied":0,"markup_language":1,"is_shared":0,"share_id":"","conflict_original_id":"","master_key_id":"","user_data":"","deleted_time":0,"sync_time":1751566159040,"type_":1} remoteContent <null>
2025-07-03 11:13:34: handleConflictAction: remoteExists: <false>
2025-07-03 11:13:34: DeleteAction: sync: handleConflictAction: note/resource conflict: titles: ["Renamed (129)"]; Item IDs: ["61e5f8b839414e3c9f09ff52bf1407dd"]
2025-07-03 11:13:34: FileApi: stat c4d5a11241b14c369e160626b1f8ee72.md
2025-07-03 11:13:34: Synchronizer: Sync: itemConflict: remote has been deleted, but local has changes: Folder: (Local c4d5a11241b14c369e160626b1f8ee72)
2025-07-03 11:13:34: handleConflictAction: Handling conflict: itemConflict
2025-07-03 11:13:34: handleConflictAction: local: {"id":"c4d5a11241b14c369e160626b1f8ee72","title":"Parent folder","created_time":1751565808263,"updated_time":1751566414433,"user_created_time":1751565808263,"user_updated_time":1751566132367,"encryption_cipher_text":"","encryption_applied":0,"parent_id":"","is_shared":0,"share_id":"","master_key_id":"dc64d5aa0cf243479cef080db3c7b957","icon":"","user_data":"","deleted_time":0,"sync_time":1751566159062,"type_":2} remoteContent <null>
2025-07-03 11:13:34: handleConflictAction: remoteExists: <false>
2025-07-03 11:13:34: DeleteAction: sync: handleConflictAction: non-note conflict: folder title: "Parent folder"; Item IDs: ["c4d5a11241b14c369e160626b1f8ee72"]
2025-07-03 11:13:34: App: Refreshing notes: 2 <undefined>
```

The only previous result for `84a473f10af54fd6b1e09dff9016fae2` in the log is:
```
2025-07-03 11:09:34: Synchronizer: Sync: createLocal: remote exists but local does not: (Remote 84a473f10af54fd6b1e09dff9016fae2.md)
```

Similarly, for `61e5f8b839414e3c9f09ff52bf1407dd`, the only other mention is in a `Sync: createLocal`:
```
2025-07-03 11:09:19: Synchronizer: Sync: fetchingProcessed: Processing fetched item
2025-07-03 11:09:19: Synchronizer: Sync: createLocal: remote exists but local does not: (Remote 61e5f8b839414e3c9f09ff52bf1407dd.md)
2025-07-03 11:09:19: Synchronizer: Sync: fetchingProcessed: Processing fetched item
2025-07-03 11:09:19: Synchronizer: Sync: createLocal: remote exists but local does not: (Remote c4d5a11241b14c369e160626b1f8ee72.md)
```

Full log for this client: [full-log--b2e3258823e1412b9001bb87821f8e16.txt](https://github.com/user-attachments/files/21044386/full-log--b2e3258823e1412b9001bb87821f8e16.txt)

</details>

Share owner logs: [logs-f51933368e7f472c85290e6a735213aa.txt](https://github.com/user-attachments/files/21044841/logs-f51933368e7f472c85290e6a735213aa.txt)


Sync fuzzer log: [sync-fuzzer-log.txt](https://github.com/user-attachments/files/21044394/sync-fuzzer-log.txt)

**Comment by personalizedrefrigerator** [comment]
The `sync` command has also failed (once) due to an `undefined` note sort order: 

<details>

Error message:

```
  command: 'yarn start-no-build --profile /home/self/Documents/joplin/packages/tools/fuzzer/profiles-tmp/a4a76805ffe5496cba6973bcace7cecd --env dev sync',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'Synchronization target:  (9)\nStarting synchronization...',
  stderr: '/home/self/Documents/joplin/packages/lib/database-driver-node.js:23\n' +
    "\t\tconst output = new Error(msg.join(': '));\n" +
    '\t\t               ^\n' +
    '\n' +
    'Error: On query {"sql":"SELECT `id`,`title`,`is_todo`,`todo_completed`,`todo_due`,`parent_id`,`encryption_applied`,`order`,`markup_language`,`is_conflict`,`is_shared`,`share_id`,`deleted_time`,`updated_time`,`user_updated_time`,`user_created_time` FROM `notes` WHERE is_conflict = 0 AND deleted_time = 0 AND parent_id = ? AND is_todo = 1 AND (todo_completed <= 0 OR todo_completed IS NULL) ORDER BY `undefined` COLLATE NOCASE ASC","params":["d42a01a926474a199e6ed96d559a2d7a"]}: Error: SQLITE_ERROR: no such column: undefined: SELECT `id`,`title`,`is_todo`,`todo_completed`,`todo_due`,`parent_id`,`encryption_applied`,`order`,`markup_language`,`is_conflict`,`is_shared`,`share_id`,`deleted_time`,`updated_time`,`user_updated_time`,`user_created_time` FROM `notes` WHERE is_conflict = 0 AND deleted_time = 0 AND parent_id = ? AND is_todo = 1 AND (todo_completed <= 0 OR todo_completed IS NULL) ORDER BY `undefined` COLLATE NOCASE ASC: d42a01a926474a199e6ed96d559a2d7a\n' +
    '    at DatabaseDriverNode.sqliteErrorToJsError (/home/self/Documents/joplin/packages/lib/database-driver-node.js:23:18)\n' +
    '    at JoplinDatabase.sqliteErrorToJsError (/home/self/Documents/joplin/packages/lib/database.js:27:30)\n' +
    '    at JoplinDatabase.tryCall (/home/self/Documents/joplin/packages/lib/database.js:136:32)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async Note.modelSelectAll (/home/self/Documents/joplin/packages/lib/BaseModel.js:328:28)\n' +
    '    at async Note.previews (/home/self/Documents/joplin/packages/lib/models/Note.js:402:38)\n' +
    '    at async Application.refreshNotes (/home/self/Documents/joplin/packages/lib/BaseApplication.js:211:25)\n' +
    '    at async Application.generalMiddleware (/home/self/Documents/joplin/packages/lib/BaseApplication.js:484:13) {\n' +
    "  code: 'SQLITE_ERROR'\n" +
    '}\n' +
    '\n' +
    'Node.js v22.16.0',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

</details>

This might be fixed by 1b51b3ce7985177a4525f109ce7eaeb063df1e0e.

**Comment by mrjo118** [comment]
@personalizedrefrigerator did any of the findings from the fuzzer fix an issue that might have caused https://github.com/laurent22/joplin/issues/12075 ?

**Comment by personalizedrefrigerator** [comment]
> @personalizedrefrigerator did any of the findings from the fuzzer fix an issue that might have caused https://github.com/laurent22/joplin/issues/12075 ?


Thank you for linking to that issue! #12075 looks different from the recent bugs identified and fixed in Joplin Server sync. The fuzzer may need adjustments to be able to find issues similar to #12075. At present,
- the fuzzer avoids sharing an individual notebook two or more times
- https://github.com/laurent22/joplin/issues/12075 seems to be related to sharing a notebook multiple times.

**Comment by mrjo118** [comment]
@personalizedrefrigerator I'll also link https://github.com/laurent22/joplin/issues/12375 in case this is something the fuzzer would be able to help with
