### PR TITLE
Mobile: Resolves #10092: Added empty trash option on long pressing the trash folder.

### LINKED ISSUE #10092: Mobile: Can't empty trash
### Operating system

Android

### Joplin version

3.0.0

### Desktop version info

_No response_

### Current behaviour

To reproduce,
1. Move a folder to the trash
2. Long-press on the trash folder
3. Long-press on the new subfolder of the trash folder

Currently,
1. The trash folder has no long-press menu
2. The subfolder of trash does not have a "permanently delete" option.

### Expected behaviour

As on desktop, it should be possible to
1. Delete folders from the trash notebook, or
2. Clear all items in the trash notebook (including folders).

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Sidd-R**
## Summary

Resolves #10092 partially (implemented one of the mentioned features)

On long pressing the trash folder on the side menu, a modal opens with the option of "empty trash". On pressing, another modal would open asking for final confirmation, on confirming it deletes all the folders and notes in the trash permanently.

## Rationale

Called the `emptyTrash` function from `lib/services/trash/emptyTrash` on pressing the empty trash option.

## Demo

https://github.com/laurent22/joplin/assets/97161173/889ff207-b32d-489e-911d-f61d219c2214

## Testing
Tested on Android 13 physical device.
1. Create a notebook and add some notes/todo to it.
2. Open the side menu, long press on the folders and press the delete option to delete them.
3. Now, again open the side menu, long press on the trash folder, a modal will open, select the empty trash option in it.
4. Then another modal will open asking for final confirmation, on confirming all the folders/notes in trash should be deleted

### CODE REVIEW

File: packages/app-mobile/components/side-menu-content.tsx [hunk 1]
```diff
@@ -146,11 +147,30 @@ const SideMenuContentComponent = (props: Props) => {
...
-		if (folder && folder.id === getTrashFolderId()) return;
-
 		const menuItems: any[] = [];
 
-		if (folder && !!folder.deleted_time) {
+		if (folder && folder.id === getTrashFolderId()) {
+			menuItems.push({
+				text: _('Empty trash'),
+				onPress: async () => {
+					Alert.alert('', _('Are you sure you want to empty the trash?\n\nAll notes and sub-notebooks within trash will be lost forever'), [
```
Comment (laurent22) [inline packages/app-mobile/components/side-menu-content.tsx]: Please use the exact same message as in the desktop app: `This will permanently delete all items in the trash. Continue?`

File: packages/app-mobile/components/side-menu-content.tsx [hunk 2]
```diff
@@ -146,11 +147,30 @@ const SideMenuContentComponent = (props: Props) => {
...
+						{
+							text: _('OK'),
```
Comment (laurent22) [inline packages/app-mobile/components/side-menu-content.tsx]: OK => "Empty trash"

Comment (Sidd-R) [reply packages/app-mobile/components/side-menu-content.tsx]: done!

**Comment by Sidd-R** [comment]
@PackElend label me please!

**Comment by laurent22** [comment]
Looks good now, thanks @Sidd-R!
