### PR TITLE
Desktop: Fixes #15107: Defer sync after master password save to prevent encryption enable race

### LINKED ISSUE #15107: Desktop: Enabling encryption after setting up sync, results in encryption not being enabled unless you enable it again
### Operating system

Windows

### Joplin version

3.6.8

### Desktop version info

_No response_

### Current behaviour

Reproduction steps:
1. Create a new profile
2. Set up sync to an **empty** sync target (eg. file system sync to an empty folder) and click sync
3. Enable encryption, setting any password
4. Upon submitting matching passwords, encryption does not get enabled (you will see a flicker of it being enabled and then immediately disabled). You have to click enable encryption again and re-enter the password to enable it. If you enable encryption before setting up sync, this is not an issue

In the log, this is output upon the initial enable of encryption:
syncInfoUtils: Sync info is using a non-existent key as the active key - clearing it: 247fc79ec97140cd93fb9da1f0014209
fixSyncInfo	@	syncInfoUtils.ts:171
localSyncInfo	@	syncInfoUtils.ts:181

**See video:**

https://github.com/user-attachments/assets/9a0a4dd7-f720-40ef-9f96-64f59338dc16

### Expected behaviour

Encryption should be enabled initially, instead of having to click enable and re-enter the password one more time

### Logs

_No response_

### PR DESCRIPTION
**Pull request by keshav0479**
Fixes #15107

## Problem

Enabling encryption after setting up sync results in it reverting to disabled within seconds. A second enable is needed for it to stick.

## Root cause

Regression from #14664. The new enable flow opens the master password dialog before enabling encryption. On save, the dialog calls `waitForSyncFinishedThenSync()` which triggers an immediate sync (delay 0). The enable flow only resumes in `EncryptionConfigScreen`'s `useEffect` after the dialog closes, so the sync can race with it and overwrite the encryption state with stale sync info. In 3.5 this wasn't an issue because enable completed before sync was triggered.

## Solution

Added an optional `delay` parameter to `reg.waitForSyncFinishedThenSync()` (defaulting to `0` to preserve existing behavior), and pass it through to `scheduleSync`. In the master password dialog save handler, call `waitForSyncFinishedThenSync(null)` so it still waits for any running sync to finish but defers the follow-up sync using `scheduleSync`'s default ~10s delay. This matches pre-#14664 timing and gives the enable flow time to complete.

## Test plan

1. Set up a filesystem sync target and synchronise once
2. Go to Tools > Options > Encryption, set a master password, click Enable
3. Observe encryption stays enabled and does not revert after sync

**Recordings**

Before fix (encryption reverts after enable):

https://github.com/user-attachments/assets/b3f9b200-a344-4f78-8f23-6d18fec17978

After fix (encryption stays enabled):

https://github.com/user-attachments/assets/c998a6f5-c271-4ef5-a342-ba722ca26d09

AI disclosure: Used AI tools for debugging and understanding the race condition. All changes tested manually.

### CODE REVIEW

**Comment by mrjo118** [comment]
> The master key generation uses Argon2 which takes ~2 seconds. During that window a scheduled sync fires, reads the half-written SyncInfo (e2ee flag set but master key not yet persisted), merges it with the remote state, and overwrites it.

I'm not sure the root cause is correct. If that was the case then this issue would occur on mobile too, but it doesn't. I assume if the key is generated on mobile, it would use Argon2 like on desktop?

**Comment by mrjo118** [comment]
The fix does indeed fix the issue though, but I'm not particularly keen on the solution. Can't you target delaying the sync in the place which schedules the sync upon enabling encryption, rather than doing this in the synchronizer itself?

Update:
I tested using Joplin desktop 3.5, and the issue does not occur. I found the issue is a regression caused by https://github.com/laurent22/joplin/pull/14664. The issue is due to a change in behaviour when submitting the new password entry screen which opens when you click enable encryption now. In Joplin 3.5, upon submission of the passwords when enabling encryption, sync triggers 15 seconds later. But in Joplin 3.6 desktop, the sync now triggers immediately in this scenario, which therefore causes the issue.

**Comment by keshav0479** [comment]
> The fix does indeed fix the issue though, but I'm not particularly keen on the solution. Can't you target delaying the sync in the place which schedules the sync upon enabling encryption, rather than doing this in the synchronizer itself?
> 
> Update: I tested using Joplin desktop 3.5, and the issue does not occur. I found the issue is a regression caused by #14664. The issue is due to a change in behaviour when submitting the new password entry screen which opens when you click enable encryption now. In Joplin 3.5, upon submission of the passwords when enabling encryption, sync triggers 15 seconds later. But in Joplin 3.6 desktop, the sync now triggers immediately in this scenario, which therefore causes the issue.

Thanks, your 3.5 vs 3.6 testing really helped pin this down, you’r right, it’s a #14664 regression. The master password dialog calls `waitForSyncFinishedThenSync()` on save, which kicks off sync immediately that was fine before because enable had already finished by then, but with the new dialog flow sync can fire before enable resumes after the dialog closes. I’ll rework the fix to address that specific path and push an update.

**Comment by keshav0479** [comment]
Your findings about the regression and the 3.5 vs 3.6 timing difference made it pretty clear where the actual issue was. Pushed the rework, just swapped `waitForSyncFinishedThenSync()` with `scheduleSync()` in Dialog.tsx and dropped the `Synchronizer` guard. The `encryption.masterPassword` side-effect in `BaseApplication` schedules sync anyway so the immediate one wasn't needed. Updated the description with the correct root cause too also verified in ui it works , have a look :)

File: packages/app-desktop/gui/MasterPasswordDialog/Dialog.tsx [hunk 1]
```diff
@@ -78,7 +78,7 @@ export default function(props: Props) {
 				} else {
 					throw new Error(`Unknown mode: ${mode}`);
 				}
-				void reg.waitForSyncFinishedThenSync();
+				void reg.scheduleSync();
```
Comment (mrjo118) [inline packages/app-desktop/gui/MasterPasswordDialog/Dialog.tsx]: I think it would be safer to still include the waitForSyncToFinish before scheduling the sync, otherwise there is a race condition that if you enable encryption while sync happens to be running, it might not sync the change and it might not auto sync again for some time. A clean way to do this would be to add an optional delay parameter to reg.waitForSyncFinishedThenSync, which is defaulted to 0, and pass that through to scheduleSync. Then revert back to calling reg.waitForSyncFinishedThenSync here, but pass the value as null explicitly so it will use the default delay

Comment (keshav0479) [reply packages/app-desktop/gui/MasterPasswordDialog/Dialog.tsx]: Makes sense, updated ,added a delay parameter to `waitForSyncFinishedThenSync` (defaults to 0 so nothing else changes), and the dialog now passes null so it uses the default `scheduleSync` delay. verified in ui, sync fires ~10s after enable instead of immediately.

**Comment by mrjo118** [comment]
Yep, looks good and I tested it works correctly locally. Just action the CodeRabbit comment and then I'll approve

**Comment by keshav0479** [comment]
Just pushed that fix! thanks for testing it locally .

**Review by mrjo118 — APPROVED** [review]
