### PR TITLE
Desktop: Fixes #8448: Merge changes from upstream turndown project

### LINKED ISSUE #8435: Rich text editor block formatting doesn't format by block
Block-selecting multiline text with leading or trailing spaces and formatting using the rich text editor appears to format correctly, but when the note is redisplayed (by selecting another note and then returning the first note) these lines display with embedded MD.

[https://files.catbox.moe/w52rg4.png](https://files.catbox.moe/w52rg4.png)

This is a sentence with no trailing space.
 This is a sentence with a leading space.
This a sentence with a trailing space. 
This is another sentence with no trailing space.

*This is a sentence with no trailing space.*
* This is a sentence with a leading space.*
*This a sentence with a trailing space. *
*This is another sentence with no trailing space.*

**This is a sentence with no trailing space.**
** This is a sentence with a leading space.**
**This a sentence with a trailing space. **
**This is another sentence with no trailing space.**

## Environment

Joplin version: 2.11.11
Platform: macOS 12.6.7
OS specifics: 

## Steps to reproduce

1. Paste the text block above into Joplin in the RTE. 
2. Block select the 4 lines.
3. Select formatting (Bold for example)
4. Switch to the MD editor, formatting includes leading or trailing whitespace.

## Describe what you expected to happen
All lines formatted as selected in the rich text editor. I was expecting the Rich Text Editor to behave like  

**Test with 
multiple lines in
Github editor.**

and place the MD around the entire text block, not each individual line, which is what causes the lines with leading or trailing spaces to not format correctly.

### LINKED ISSUE #8448: Bold or italic text with spaces gets converted to **text ** or *text * in WYSIWYG editor if the last keystroke was space
Im reopening an issue for I bug i found 2 years ago and just got closed for some reason. Still present in the app.
EDIT - reopening again! bots killed my last issue (https://github.com/laurent22/joplin/issues/8243)

Environment
Joplin version: 2.10.19
Platform: Windows 10 home single language
OS specifics: 1909

Steps to reproduce
ALL STEPS TO BE DONE IN WYSIWYG EDITOR

Create a new note.
Type in some text.
Press space.
Press ctrl-B.
Type in some text.
Press space.
Press ctrl-B.
Type some text.
Now either 1. change to any other note and back; or 2. paste an image from clipboard.
Now your previously bolded text will be **text **.
See gif for further clarification. Note that it is NECESSARY to press space BEFORE turning off the bold modifier.

Describe what you expected to happen
I thing text should stay bolded.

IVE MADE A GIF, CHECK CLOSED ISSUE TO SEE IT - >>> https://github.com/laurent22/joplin/issues/4454
Logfile
[log.txt](https://github.com/laurent22/joplin/files/5914191/log.txt)

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary
The upstream [turndown](https://github.com/mixmark-io/turndown) project has bug fixes related to code blocks and whitespace. This should fix #8448 and should partially fix #8435.

# Notes
Because this pull request may require further testing, it's still a draft.

### CODE REVIEW

File: packages/turndown/src/turndown.js [hunk 1]
```diff
@@ -239,39 +215,35 @@ function replacementForNode (node) {
   var content = process.call(this, node, rule.escapeContent ? rule.escapeContent() : 'auto')
   var whitespace = node.flankingWhitespace
   if (whitespace.leading || whitespace.trailing) content = content.trim()
+
+  const replaceNonbreakingSpaces = space => {
+    // \u{00A0} is a nonbreaking space
+    return space.replace(/\u{00A0}/ug, this.options.nonbreakingSpace);
+  };
```
Comment (personalizedrefrigerator) [inline packages/turndown/src/turndown.js:222]: I added this function after merging changes to optionally replace `\u00A0` characters with `&nbsp;`, making non-breaking spaces noticeable within the markdown editor.

File: packages/app-cli/tests/html_to_md/table_with_empty_header.md [hunk 2]
```diff
@@ -5,5 +5,6 @@
 | [Source](https://github.com/nim-lang/nim) | The github project |
 | [nimble](https://github.com/nim-lang/nimble) | The nim package manager |
 | [choosenim](https://github.com/dom96/choosenim) | Toolchain installer |
+|     |     |
```
Comment (personalizedrefrigerator) [inline packages/app-cli/tests/html_to_md/table_with_empty_header.md:8]: The HTML input file corresponding to this test contains
```html
		<tr>
			<td>&nbsp;</td>
			<td></td>
		</tr>
```
which was previously ignored.

It is no longer ignored and thus the test output has been updated.

**Comment by laurent22** [comment]
Thanks, I think that's a good change, as long as our existing test units are still passing.

- Could you also update the README to mention on which version our fork will now be based?
- Are you able to check that we aren't overwriting our custom code? (that was added to support the web clipper)

There's also turndown-plugin-gfm that contains a lot of improvements for the web clipper, but if it needs to be updated we can do so in a separate PR.

**Comment by personalizedrefrigerator** [comment]
I've done a small amount of testing and WebClipper still works (and produces similar output).

I'm testing with WebClipper from the Chrome store and the development version of Joplin (changing the web clipper port accordingly).

<details><summary>Example</summary>

# Clipping the main GitHub repository page for Joplin

Old version of turndown:
[turndown-test-old--markdown.md](https://github.com/laurent22/joplin/files/12053834/turndown-test-old--markdown.md)
[turndown-test-old--rendered.pdf](https://github.com/laurent22/joplin/files/12053836/turndown-test-old--rendered.pdf)


New version:
[turndown-test-old--markdown.md](https://github.com/laurent22/joplin/files/12053914/turndown-test-old--markdown.md)
[turndown-test-new--rendered.pdf.pdf](https://github.com/laurent22/joplin/files/12053903/turndown-test-new--rendered.pdf.pdf)
(**Edit**: Fixed new version PDF possibly rendered from old markdown)



</details>

I've updated the turndown README with information about the commit that changes are based on.

**Comment by laurent22** [comment]
Looks good, thanks @personalizedrefrigerator!
