### PR TITLE
iOS: Fixes #12314: Fix error shown the first time a user attempts to record

### LINKED ISSUE #12314: New recording feature throws an exception on first try
### Operating system

iOS

### Joplin version

Joplin Mobile 13.3.7 (prod, ios)

### Desktop version info

_No response_

### Current behaviour

1. Don't already give mic permission to app
2. Click on new note Button ( '+' on bottom right corner)
3. Click on the new Recording button
4. Mic permission request pops up
5. grant permissions
6. This:

Image

### Expected behaviour

The recording feature should work on first try.

### Logs

```
05-18T06:38:52: AudioRecording: Error starting recording: Error: Prepare encountered an error: Error Domain=EXModulesErrorDomain Code=0 "This experience is currently in the background, so the audio session could not be activated." UserInfo={NSLocalizedDescription=This experience is currently in the background, so the audio session could not be activated.}
Code: E_AUDIO_RECORDERNOTCREATED
Error: Prepare encountered an error: Error Domain=EXModulesErrorDomain Code=0 "This experience is currently in the background, so the audio session could not be activated." UserInfo={NSLocalizedDescription=This experience is currently in the background, so the audio session could not be activated.}
    at promiseMethodWrapper (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:4960:45)
    at anonymous (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:580877:46)
    at ?anon_0_ (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:589629:87)
    at next (native)
    at asyncGeneratorStep (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:65327:19)
    at _next (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:65341:29)
    at anonymous (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:65346:14)
    at tryCallTwo (address at InternalBytecode.js:1:1222)
    at doResolve (address at InternalBytecode.js:1:2541)
    at Promise (address at InternalBytecode.js:1:1318)
    at anonymous (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:65338:25)
    at apply (native)
    at prepareToRecordAsync (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:589647:45)
    at ?anon_0_ (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:587761:45)
    at next (native)
    at asyncGeneratorStep (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:65327:19)
    at _next (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:65341:29)
    at tryCallOne (address at InternalBytecode.js:1:1180)
    at anonymous (address at InternalBytecode.js:1:1874)
    at apply (native)
    at anonymous (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:14625:26)
    at _callTimer (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:14514:17)
    at _callReactNativeMicrotasksPass (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:14552:17)
    at callReactNativeMicrotasks (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:14755:44)
    at __callReactNativeMicrotasks (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:3583:48)
    at anonymous (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:3447:45)
    at __guard (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:3555:15)
    at flushedQueue (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:3446:21)
    at invokeCallbackAndReturnFlushedQueue (/Users/laurent/Library/Developer/Xcode/DerivedData/Joplin-aabednnutrlvgkdcsfhvjkegcpwu/Build/Intermediates.noindex/ArchiveIntermediates/Joplin/BuildProductsPath/Release-iphoneos/main.jsbundle:3440:33)
```

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

Fixes #12314.

> [!NOTE]
>
> This pull request targets `release-3.3`. An alternate fix (but a larger change) [might be to set staysActiveInBackground to `true`](https://github.com/laurent22/joplin/issues/12314#issuecomment-2893059479) and add the necessary permissions to `Info.plist`. After this pull request is merged, it may make sense to [enable `staysActiveInBackground`](https://docs.expo.dev/versions/latest/sdk/audio-av/#playing-or-recording-audio-in-background) on the dev branch for the 3.4 release.
>
> **Update**: It isn't sufficient to set [`staysActiveInBackground: true`](https://github.com/laurent22/joplin/pull/12330). With just this change (and no timeout) I get the following error: "Recording error: Error: Prepare encountered an error: recorder not prepared". 

# Testing

**Web**  (regression testing):
1. Start Joplin and open a note.
    - Joplin should initially not have microphone permissions.
2. Click "Attach", then "Record audio".
4. Verify that a permissions prompt is shown. Click "Allow this time".
3. Click "Start recording".
5. Say something.
6. Click "Done".
7. Verify that the recording is added to the note.

**iOS 18.5**:
1. Start Joplin, create the initial notebook, and create a note using the "recording" button.
    - Joplin should initially not have microphone permissions.
3. Click "Start recording", grant recording permissions, and speak.
7. Click "Done".
8. Verify that the recording is added to the note.

### CODE REVIEW

File: packages/app-mobile/components/voiceTyping/AudioRecordingBanner.tsx [hunk 1]
```diff
@@ -119,6 +119,11 @@ const useAudioRecorder = (onFileSaved: OnFileSavedCallback, onDismiss: ()=> void
 				if (!response.granted) {
 					throw new Error(_('Missing permission to record audio.'));
 				}
+
+				// Work around "This experience is currently in the background, so the audio session could not be activated"
+				// See https://github.com/expo/expo/issues/21782
+				// May be resolved by migrating to expo-audio.
+				await msleep(500);
```
Comment (NBA2K1) [inline packages/app-mobile/components/voiceTyping/AudioRecordingBanner.tsx:126]: One [comment](https://github.com/expo/expo/issues/21782#issuecomment-2307947071) in the upstream issue says that instead of using a timeout you can add `staysActiveInBackground: true` to fix the bug.

Comment (personalizedrefrigerator) [reply packages/app-mobile/components/voiceTyping/AudioRecordingBanner.tsx:126]: Thank you for the suggestion! I was still getting an error (though a different one). See the note in the PR description for details.

Comment (NBA2K1) [reply packages/app-mobile/components/voiceTyping/AudioRecordingBanner.tsx:126]: Ah didn't see the note, thank you!
