### PR TITLE
Mobile: Fixes #10593: Fix plugin list not cached in config screen

### LINKED ISSUE #10593: Cache plugin list in Plugin Config screen
### Operating system

Windows

### Joplin version

3.0.4

### Desktop version info

When opening the plugin config screen, it seems to load the list of plugins and while doing to so searching is not possible. Somehow it's sometimes very slow to load this list on my device and it seems to do that frequently. It fetched that list several times within 5 minutes or so.

If the list is already cached, we should increase the ttl. If it's not cached, we should cache it, even to a file since it will be faster to read from a file than from the internet.

Doesn't have to be for 3.0, depending on complexity.

### Current behaviour

_No response_

### Expected behaviour

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request fixes a logic error that caused the plugin list to not be cached. The plugin list is now refreshed at most once per minute.

Fixes #10593.

# Testing plan

1. Open the settings screen.
2. Open the plugins section.
4. Switch to a different tab.
5. Switch back to the plugins section.
6. Verify that the loading banner didn't appear.
7. Search for and install a plugin.

This has been tested successfully on iOS 17.4.

### CODE REVIEW

**Comment by laurent22** [comment]
Some failing tests on CI:

```
2024-06-14T23:21:28.9666394Z ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: Process started
2024-06-14T23:21:36.2006061Z ##[error]➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [joplin]: tests/services/plugins/RepositoryApi.ts(12,13): error TS2341: Property 'initialize' is private and only accessible within class 'RepositoryApi'.
2024-06-14T23:21:36.2176336Z ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [joplin]: Process exited (exit code 2), completed in 7s 259ms
2024-06-14T23:21:36.2179665Z ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-mobile]: Process started
2024-06-14T23:21:45.3090675Z ##[error]➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: gui/ConfigScreen/controls/plugins/PluginsStates.tsx(128,21): error TS2341: Property 'initialize' is private and only accessible within class 'RepositoryApi'.
2024-06-14T23:21:45.3521615Z ➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-desktop]: Process exited (exit code 2), completed in 16s 385ms
```

File: packages/lib/services/plugins/RepositoryApi.ts [hunk 1]
```diff
@@ -102,6 +103,15 @@ export default class RepositoryApi {
 
 		await this.loadManifests();
 		await this.loadRelease();
+
+		this.lastInitializedTime_ = Date.now();
+	}
+
+	public async reinitialize() {
+		// Refresh at most once per minute
+		if (Date.now() - this.lastInitializedTime_ > 60000) {
```
Comment (personalizedrefrigerator) [inline packages/lib/services/plugins/RepositoryApi.ts]:
```suggestion
		if (Date.now() - this.lastInitializedTime_ > 5 * 60000) {
```
