### PR TITLE
Desktop: Plug CodeMirror into the KeymapService

### LINKED ISSUE #4130: Desktop: Bold and italics keybindings broken when spellchecking is enabled for markdown editor
## Environment

Joplin version: v1.4.12
Platform: Linux
OS specifics: Ubuntu 20.04

## Steps to reproduce

1. Enable spellchecker for markdown editor
2. Try pressing ctrl+b or ctrl+i when the editor has focus, nothing happens

I've spent some time looking into this but have so far come up short, I'll spend more time debugging, but please let me know if you have an insight into what the cause might be. From testing it seems to be specific to the key bindings, for example I can change the bold command to ctrl+r and it works fine, but ctrl+b doesn't.

### PR DESCRIPTION
**Pull request by CalebJohn**
As the title states, this has CodeMirror register all it's commands with the KeymapService, and in turn binds all it's keys to the values provided by the KeymapService.

This also fixes #4130 , the issue there was that when CodeMirror is contenteditable it would sometimes swallow keypresses and they wouldn't become available to the rest of the application (note: I think it's an electron bug but I can't prove it).
This fixes it by registering all commands back to codemirror, so even if the command get's swallowed by codemirror it will still be executed. This doesn't work perfectly because not all commands are registered with the CommandService. It does cover enough to fix the bug however because only commands like Ctrl-B and Ctrl-I are affected (I guess some users might run into this if they bind one of those keys to "quit" for example). 

You'll notice that all the codemirror only commands are under the `editor.codemirror` namespace. I'd like to formalize namespaces a bit and add sections to the Keyboard Shortcuts section of options but I wanted to wait for approval before going ahead and doing that, what do you think @laurent22? What I'm picturing is that KeymapService will get an extra function 'registerNamespace' that takes in a namespace (i.e. `editor.codemirror`) and a nicer name like "Markdown Editor" and will display those in their own table below the main one.

### CODE REVIEW

**Comment by tessus** [comment]
Btw, do you have examples how to add new CodeMirror shortcuts via plugins?

One shortcut I miss is `Cmd+Shift+D` to duplicate lines. But I understand that we don't want to add new ones to the core.

**Comment by CalebJohn** [comment]
@tessus [this example project](https://github.com/laurent22/joplin/tree/dev/packages/app-cli/tests/support/plugins/codemirror_content_script) has an example of how new keybindings can be added. However, after this pr that won't work anymore and the method will change, I haven't documented that yet.

Btw, option+up and option+down should work to swap lines around .

**Comment by tessus** [comment]
>  this example project has an example of how new keybindings can be added. However, after this pr that won't work anymore and the method will change, I haven't documented that yet.

In this case I'll wait for the PR to be merged and the new doc.

> Btw, option+up and option+down should work to swap lines around .

Yep, I thought so too, but it doesn't with:

```
Joplin 1.4.12 (dev, darwin)

Client ID: e354a932e6e143c782264aad4112b674
Sync Version: 2
Profile Version: 34
Keychain Supported: Yes

Revision: be4d53db6 (dev)
```

**Comment by CalebJohn** [comment]
@tessus I've changed the MacOS keybindings on this branch, looks like codemirror uses Alt instead of Opt for keybindings, do you mind pulling this locally to test?

**Comment by tessus** [comment]
I didn't pull this PR, but I changed the current code:

```
diff --git a/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useKeymap.ts b/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useKeymap.ts
index 37d2e2d31..5e2b1f48d 100644
--- a/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useKeymap.ts
+++ b/packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useKeymap.ts
@@ -68,8 +68,8 @@ export default function useKeymap(CodeMirror: any) {
                                'Cmd-]': 'indentMore',
                                'Cmd-/': 'toggleComment',
                                'Cmd-Opt-S': 'sortSelectedLines',
-                               'Opt-Up': 'swapLineUp',
-                               'Opt-Down': 'swapLineDown',
+                               'Alt-Up': 'swapLineUp',
+                               'Alt-Down': 'swapLineDown',

                                'fallthrough': 'basic',
                        };
```

and this fixed it. So you are right. CodeMirror uses `Alt` instead of `Opt`.

**Comment by tessus** [comment]
I'm just wondering what happens now in the shortcut editor for CodeMirror shortcuts when we set a new shortcut with `option+something`. Maybe I should pull the PR and do some testing. I'm currently a bit busy at work, thus it can take a while.

**Comment by CalebJohn** [comment]
@tessus no need just yet, I would appreciate a more thorough review once this is a bit further along. But for now I can confirm it only swaps the `+` for a `-`. so `option+something` -> `option-something`. I'll dig a bit deeper into the keybinding differences tonight and hopefully come up with something that actually works on MacOS.

**Comment by tessus** [comment]
> come up with something that actually works on MacOS.

We might need a translation layer for macOS. However, this should be easily done with regex.

**Comment by laurent22** [comment]
I think the commands should be prefixed simply with "editor." rather than "editor.codemirror", that way they could be used by the rich text editor too, if we ever add support for them. 

Commands are global and should always be declared on application startup. This is done in app.ts, and I think the way you've done it means the commands won't be found by the keymap editor if the app started with the rich text editor. So a better approach would be to define all the commands in a separate file (like in editorCommandDeclaration.ts), and use that in app.ts to register the commands.

Also I haven't found where you register the runtime, so I'm not sure how it works exactly? Commands ideally should have a runtime so that they can be called using execCommand from a plugin or anywhere in the main app. 

It should be like this:

1. Declare all the commands when the app starts (in app.ts)
2. When the CodeMirror component is mounted, register the runtimes, because the commands can now be used
3. When the CodeMirror component is unmounted, unregister the runtimes, since the commands would now be inactive

You might check for example `useWindowCommandHandler.ts` to see how it's done.

**Comment by CalebJohn** [comment]
> I think the commands should be prefixed simply with "editor." rather than "editor.codemirror", that way they could be used by the rich text editor too, if we ever add support for them.

Might thought was that until we implement them they should go under "editor.codemirror" so that a distinction is made between the two editors. This will allow us to have a separate keybinding section for codemirror specific (and maybe one for all editors). Otherwise I think users will complain on he forums. I suppose we could also mark the label with "WYSIWYG: no" like in the renderer plugin section, however, I do prefer the codemirror namespace. What do you think?

> Commands are global and should always be declared on application startup. This is done in app.ts, and I think the way you've done it means the commands won't be found by the keymap editor if the app started with the rich text editor. So a better approach would be to define all the commands in a separate file (like in editorCommandDeclaration.ts), and use that in app.ts to register the commands.

Currently these commands are only being used by codemirror so this wouldn't be a big deal, but I can see a potential issue with plugins (or future maintenance). I'll change the system to use global commands.

> Also I haven't found where you register the runtime, so I'm not sure how it works exactly? Commands ideally should have a runtime so that they can be called using execCommand from a plugin or anywhere in the main app.

The commands I define are specific to CodeMirror so they can't be called anywhere from in the app, they are only useful for keybinding within the CodeMirror editor. The only reason I registered them with the command system was so that the keybindings menu would show a description. I'll update this pull to properly register them as global commands and add an appropriate runtime.

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useKeymap.ts [hunk 1]
```diff
@@ -46,62 +84,49 @@ export default function useKeymap(CodeMirror: any) {
...
-				'Alt-Down': 'swapLineDown',
-
-				'fallthrough': 'basic',
-			};
+		const defaultKeymap: CodeMirrorKey[] = [
+			// Windows/linux
+			{ label: _('Delete line'), command: 'editor.codemirror.deleteLine', default: 'Ctrl+D', macos: 'Cmd+D' },
+			{ label: _('Undo'), command: 'editor.codemirror.undo', default: 'Ctrl+Z', macos: 'Cmd+Z' },
+			{ label: _('Redo'), command: 'editor.codemirror.redo', default: 'Shift+Ctrl+Z', macos: 'Shift+Cmd+Z' },
+			{ label: _('Redo'), command: 'editor.codemirror.redo', default: 'Ctrl+Y', macos: 'Cmd+Y' },
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useKeymap.ts:92]: The "Redo" command appears twice, is that expected?

**Comment by laurent22** [comment]
> Might thought was that until we implement them they should go under "editor.codemirror" so that a distinction is made between the two editors. This will allow us to have a separate keybinding section for codemirror specific (and maybe one for all editors). Otherwise I think users will complain on he forums. I suppose we could also mark the label with "WYSIWYG: no" like in the renderer plugin section, however, I do prefer the codemirror namespace. What do you think?

On one hand I agree with you that if we add a generic command and it doesn't work in both editors, users will ask why, and that will look like a bug when it's not.

On the other hand, once a command is defined we should never change it, and it means there will be two sets of commands for the Rich Text and Markdown editor, and users will have to set the shortcuts for both.

Also it means every time we'll add a command, we'll have to think if it's for CodeMirror or TinyMCE or both. And if it is for both, we'll have to wait for both to be implemented before we release, which makes the development process less flexible.

Because of all this, I think I'd slightly favour your second option with a label saying if the command works for one editor or both. It could a a property in the command declaration, which would be "supportedEditor: CodeMirror/TinyMCE/All", and we can display this info in the keymap editor screen. What do you think?

**Comment by laurent22** [comment]
By the way, in general in the UI we should use the words "Markdown Editor" / "Rich Text Editor' when referring to the two text editors. This is because most users won't know what CodeMirror or TinyMCE is. In code, we should however indeed use codemirror/tinymce.

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useKeymap.ts (hunk 1 above)
Comment (CalebJohn) [reply packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useKeymap.ts:92]: Yes, Redo is commonly mapped to both Shift+Ctrl+Z and Ctrl+Y, this is how it worked previously and is also how it currently works in the WYSIWYG editor.
I still haven't made the updates I talked about earlier, but when I do I'll try to make sure this doesn't conflict. I'll just remove it if it does.

**Comment by CalebJohn** [comment]
What you say makes sense, I agree with you, changing a label is going to be a lot easier than removing commands and forcing everyone to change keybindings and update plugins. I'll update this in a few days to reflect everything that you've said.

> By the way, in general in the UI we should use the words "Markdown Editor" / "Rich Text Editor' when referring to the two text editors. This is because most users won't know what CodeMirror or TinyMCE is. In code, we should however indeed use codemirror/tinymce.

Noted thanks

**Comment by CalebJohn** [comment]
@laurent22 This should be good to go!

In the end I didn't make any changes to the way that plugins register keymaps because keymaps are now consolidated through the command service and the keymap service, so if a plugin developer want's to register a new command they will do it through there (not through the codemirror back-channel that I added on the previous commits).

I know there are a lot of lines changed, but the bulk of them are just keybindings, and the core changes are very small.
As always feel free to question everything and let me know if I can explain anything for you

File: packages/app-desktop/gui/editorCommandNames.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+		'editor.delGroupBefore',
+		'editor.delGroupAfter',
+		'editor.indentLess',
+		'editor.indentMore',
+		'editor.toggleComment',
+		'editor.sortSelectedLines',
+		'editor.swapLineUp',
+		'editor.swapLineDown',
+	];
+}
```
Comment (laurent22) [inline packages/app-desktop/gui/editorCommandNames.ts:21]: Could this array be dynamically built based on the command prefix? That way we won't need to remember to update this list when we add a new command.

Comment (laurent22) [reply packages/app-desktop/gui/editorCommandNames.ts:21]: Also should the other editor commands, without a prefix, be included here? If not, please could you add a comment explaining why (or maybe by renaming the file so that it's clear why some commands are here and not others).

**Review by laurent22 — COMMENTED** [review]
Thanks for the update @CalebJohn, that looks good. I've just left a comment asking to clarify the editorCommandNames file, but other than that it's nearly ready to merge.

**Comment by tessus** [comment]
How do we add additional editor commands or shortcuts? Via a plugin?

e.g. I think the following are important as well (even, if we don't assign shortcuts to them):

```
delCharAfter
duplicateLine
```

**Comment by CalebJohn** [comment]
@tessus
Yes other commands can be added via a plugin, I can add that to the example.

**Comment by tessus** [comment]
Great sounds good. E.g. on macOS `Ctrl+D` is used to delete the character right of the cursor. But it's not working in CodeMirror. So that's probably the first thing I'll add. :-)

File: packages/lib/services/KeymapService.ts [hunk 3]
```diff
@@ -303,6 +303,23 @@ const defaultKeymapItems = {
...
 		{ accelerator: 'F1', command: 'help' },
+		{ accelerator: 'Cmd+D', command: 'editor.deleteLine' },
+		{ accelerator: 'Cmd+Z', command: 'editor.undo' },
+		{ accelerator: 'Cmd+Y', command: 'editor.redo' },
+		{ accelerator: 'Cmd+Home', command: 'editor.goDocStart' },
+		{ accelerator: 'Cmd+End', command: 'editor.goDocEnd' },
+		{ accelerator: 'Cmd+Left', command: 'editor.goGroupLeft' },
+		{ accelerator: 'Cmd+Right', command: 'editor.goGroupRight' },
+		{ accelerator: 'Alt+Left', command: 'editor.goLineStart' },
+		{ accelerator: 'Alt+Right', command: 'editor.goLineEnd' },
```
Comment (tessus) [inline packages/lib/services/KeymapService.ts:314]: On macOS, the default for those 2 should be Ctrl A and E

```
	{ accelerator: 'Ctrl+A', command: 'editor.goLineStart' },
	{ accelerator: 'Ctrl+E', command: 'editor.goLineEnd' },
```

File: packages/lib/services/KeymapService.ts [hunk 4]
```diff
@@ -303,6 +303,23 @@ const defaultKeymapItems = {
...
+		{ accelerator: 'Alt+Backspace', command: 'editor.delGroupBefore' },
+		{ accelerator: 'Alt+Delete', command: 'editor.delGroupAfter' },
+		{ accelerator: 'Cmd+[', command: 'editor.indentLess' },
+		{ accelerator: 'Cmd+]', command: 'editor.indentMore' },
+		{ accelerator: 'Cmd+/', command: 'editor.toggleComment' },
+		{ accelerator: 'Option+Cmd+A', command: 'editor.sortSelectedLines' },
+		{ accelerator: 'Option+Up', command: 'editor.swapLineUp' },
+		{ accelerator: 'Option+Down', command: 'editor.swapLineDown' },
```
Comment (tessus) [inline packages/lib/services/KeymapService.ts:322]: I though we established that `Option` does not work and has to be replaced with `Alt`.

Comment (tessus) [reply packages/lib/services/KeymapService.ts:322]: Oh, these are the ones in the Keyboard Editor. Sorry, I missed that.

Comment (CalebJohn) [reply packages/lib/services/KeymapService.ts:322]: It doesn't work when binding to the codemirror editor, but it works for the regular menu items (I think). When commands get registered with the CodeMirror instance there is a regex translation layer that changes Option -> Alt

Comment (CalebJohn) [reply packages/lib/services/KeymapService.ts:322]: No worries, you comment made me realize that I was translate Opt -> Alt, not Option. It's fixed now!

Comment (tessus) [reply packages/lib/services/KeymapService.ts:322]: Right, it also has to change the + to - I think.

File: packages/lib/services/KeymapService.ts (hunk 3 above)
Comment (CalebJohn) [reply packages/lib/services/KeymapService.ts:314]: Thanks, I've changed this now!

**Comment by CalebJohn** [comment]
> Great sounds good. E.g. on macOS Ctrl+D is used to delete the character right of the cursor. But it's not working in CodeMirror. So that's probably the first thing I'll add. :-)

If that's a standard maxOS keybinding I guess we should conform to it. I've added it to the codemirror bindings for now, it won't show up in the keymap editor (and it can be overwritten), but the default behaviour on mac will be to delete char after.

If you have any more universal MacOS key bindings please let me know and I'll add them in a similar way (unless @laurent22  objects of course). We've just been using the codemirror default keybindings, but it's probably better to conform to the MacOS standard wherever possible.

Also in reference to my last comment, looks like it isn't possible yet to add plugin commands that interact with the editor, so I was wrong on that one. @laurent22  I'm not sure what the correct approach would be to add these kind of commands. As I had attempted earlier we could probably pass them in via a content script option, but I'm not sure that's the best approach. What are your thoughts?

**Comment by tessus** [comment]
No, I can't think of anything other than `Ctrl+D`, and `Ctrl+A` and `Ctrl+E`.

Although `Option+Cmd+A` for `sortSelectedLines` seems strange to me (On Windows S is used). 
I've never really heard or used a shortcut for sorting lines, but I doubt this is standard for macOS input fields or text areas.

**Comment by CalebJohn** [comment]
> Although Option+Cmd+A for sortSelectedLines seems strange to me (On Windows S is used).

`Option+Cmd+S` was already taken for `toggleSidebar` I couldn't come up with an intuitive keybinding so I used a random one. Do you think it would be better to remove it and leave it up to the user to map?

While reviewing this stuff I realize that a lot of the commands probably don't need to be re-mappable. For example `goGroupLeft` (`Ctrl+Left`) on windows is a standard input command and not something that would usually be remapped. I'm going to move those types of commands out of the keyMap interface and into the codemirror definitions.

The difference between those is that the codemirror bindings will only apply when the editor is selected and won't be remappable. If a user wants, they will be able to overwrite those commands however.

**Comment by tessus** [comment]
> Do you think it would be better to remove it and leave it up to the user to map?

Yep, I would think so.

> a lot of the commands probably don't need to be re-mappable.

There is a 50:50 chance that the ones you think should not be re-mapped, actually would make sense to re-map.

As an example, `Cmd+Left` might be used to move to the left beginning of a text group in an editor. However, in a browser, it is used to move to the tab on the left.
It's a matter of opinion. If you don't allow them to be remapped, it will also mean you won't be able to disable them. Or the tab plugin can't use `Cmd+Left` to select the tab on the left of the current one, because I'm pretty sure the editor shortcuts have priority.

File: packages/app-desktop/gui/editorCommandNames.ts (hunk 2 above)
Comment (CalebJohn) [reply packages/app-desktop/gui/editorCommandNames.ts:21]: Good point, these are editor commands that make sense to have key bindings for, but aren't present in the menu. Thinking about this, it might actually make the most sense to add these commands to the menu.

I'm going to add them now and perhaps we can discuss more then.

**Comment by CalebJohn** [comment]
That's a good point but I think for commands (like `Cmd+Left`) it will make sense. This pull request inverts that priority, any command set by a user now has the highest priority, the "editor only" commands will only act as a fallback if the no other command is set to the same key binding. The key bindings that I treat this way are the ones that are universal editing commands which are typically transparently supported (and I would argue that users aren't used to remapping these bindings anyways).

I think we'll need to support more powerful remapping via the plugin system for power users. But as it stands I think this will make sense as a sane default.

**Comment by tessus** [comment]
I think you found a good balance.

This has nothing to do with this PR, but at one point I would like to re-visit the design of the shortcut editor. I would like to be able to
- group certain shortcuts like `Back` and `Forward`
- have sections for Editor, Application, Note, ....
- add description (alternate text) (e.g. while `Back` might be ok as a tooltip or in a menu, in the Shortcut Editor it can be ambiguous)
- use global shortcuts (e.g. allow `New Note` to be a global shortcut; or show/hide joplin)
- use separate sections for plugins (it will be very confusing when all shortcuts are mixed together)

**Comment by CalebJohn** [comment]
A summary of the latest changes.
- I moved a lot of the "basic" editor commands out of the commands system and left them up to the editor to handle
- The remaining commands actually made sense to include in the menu (undo/redo, etc.) so that's where I put them
- I also noticed that not all the edit menu commands are supported by the WYSIWYG editor yet (in fact the edit menu is disabled), so I didn't do anything special to note that some commands are not supported on WYSIWYG (this might be necessary at some point, but I think is out of scope for now)

As I noted in an above comment, all the "basic" editor commands (which are all navigation focused) will have a lower priority than any user set commands.

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx [hunk 5]
```diff
@@ -255,6 +269,17 @@ function CodeMirror(props: NoteBodyEditorProps, ref: any) {
...
+	const editorPaste = useCallback(() => {
+		const clipboardText = clipboard.readText();
+
+		if (clipboardText) {
+			editorPasteText();
+		} else {
+			// To handle pasting images
+			void onEditorPaste();
+		}
+	}, []);
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx:281]: Although for now it won't make a difference, it would be best to add the dependencies to the array - so in this case `editorPasteText` and `onEditorPaste`. For now we don't use the eslint rule to check for missing hook dependencies because it has some issues, but if we enable it later on, there will probably be dependencies to fix so it's best to do it as we go. I guess we don't need to add refs to dependencies though.

**Review by laurent22 — COMMENTED** [review]
Thanks for the update @CalebJohn, it looks good except for one minor issue with an effect dependencies.

**Comment by laurent22** [comment]
> Also in reference to my last comment, looks like it isn't possible yet to add plugin commands that interact with the editor, so I was wrong on that one. @laurent22 I'm not sure what the correct approach would be to add these kind of commands. As I had attempted earlier we could probably pass them in via a content script option, but I'm not sure that's the best approach. What are your thoughts?

Using the `codeMirrorResources` property you've added to content script, it's possible to pass addons and modes, does it not solve the issue? Or is there something more that's needed?

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx (hunk 5 above)
Comment (CalebJohn) [reply packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx]: Good point, thanks for the heads up, it's done.

**Comment by CalebJohn** [comment]
> Using the codeMirrorResources property you've added to content script, it's possible to pass addons and modes, does it not solve the issue? Or is there something more that's needed?

This is in regards to the Joplin commands system. When registering a command you need to pass it a runtime, but from regular plugins you don't have access to the editor instances so it won't be possible to add commands that interact with the editors. That is unless it's possible to register commands from content scripts? Actually is it possible to import the plugin api and use it from content scripts?

**Comment by laurent22** [comment]
> This is in regards to the Joplin commands system. When registering a command you need to pass it a runtime, but from regular plugins you don't have access to the editor instances so it won't be possible to add commands that interact with the editors. That is unless it's possible to register commands from content scripts? Actually is it possible to import the plugin api and use it from content scripts?

If possible I'd rather avoid giving access to the plugin API from the content scripts, as that would be a path to run arbitrary code within the app process, which we want to avoid for reliability and performance reasons. Content scripts should have a narrow task, like rendering some Markdown, or customizing the CodeMirror module, but shouldn't access anything outside of this.

With that in mind, is it not possible to define the CodeMirror command in the content script, and the Joplin command in the plugin? Then this Joplin command will call the CodeMirror one? If not possible maybe we need a generic "execEditorCommand", which will be a bit lower level and would directly run the `execCommand()` handler of the editors?

**Comment by laurent22** [comment]
By the way, I guess what we are discussing now could be part of a separate pull request, is that correct?

**Comment by CalebJohn** [comment]
> If not possible maybe we need a generic "execEditorCommand", which will be a bit lower level and would directly run the execCommand() handler of the editors?

I think this is what will need to be done. Currently all editor commands are added via the `useWindowCommandHandler` script. and it only loads the commands defined in `editorCommands`. It should be possible to have it load a selection of commands from the pluginService and register them to the same runtime. I think that might provide the nicest interface for the plugins? There would either be an option to have the `commands.register` function use the editor runtime, or maybe `commands.editorRegister`? What do you think?

> By the way, I guess what we are discussing now could be part of a separate pull request, is that correct?

Yes it will be separate feature. This PR should be ready.

**Comment by laurent22** [comment]
> I think this is what will need to be done. Currently all editor commands are added via the `useWindowCommandHandler` script. and it only loads the commands defined in `editorCommands`. It should be possible to have it load a selection of commands from the pluginService and register them to the same runtime. I think that might provide the nicest interface for the plugins? There would either be an option to have the `commands.register` function use the editor runtime, or maybe `commands.editorRegister`? What do you think?

Hmm, I'm not sure I'm following. Perhaps it would help if you could provide an example of what you want to do, and what piece is missing to achieve this?

**Comment by CalebJohn** [comment]
Sure. The issue now is that the command system isn't connected to the editor components. As of this pull request a number of selected codemirror commands will be available to to the command service and the keymap service. In fact any codemirror command is actually exposed because the `editor.execCommand` function will pass certain functions to the codemirror instance itself. However, plugin developers have no access to this when defining commands because commands require an attached runtime, and the editor isn't available to plugins. 

One possible fix is to do as you suggest and add a new function that allows for explicitly calling the `editor.execCommand` function. I was just proposing an alternative that might have a smoother interface. i.e. labelling some commands as editor commands. The commands wouldn't need an explicit runtime, because they'd use the one provided by the `useWindowCommandHandler`.

**Comment by laurent22** [comment]
(For now I have merged this pull request and will get back to you regarding the editor commands)

**Comment by CalebJohn** [comment]
Thanks Laurent.

I was just thinking about the commands again, and all editor commands are prefaced with `editor.`so couldn't those commands just execute on the editor instance automatically?

**Comment by laurent22** [comment]
> I was just thinking about the commands again, and all editor commands are prefaced with editor.so couldn't those commands just execute on the editor instance automatically?

Yes I guess that would work. In fact we already have the isEditorCommand function which we could use for this?

**Comment by CalebJohn** [comment]
Yes I think that would work. I took a quick look and I think the only changes will be in `windowCommandHandler.ts`, which will need to change in order to get commands using the CommandService/`isEditorCommand`. And the plugin access to the command service might have to change, I'm not exactly sure.

I'll start drafting up a PR at some point this week.
