### PR TITLE
Desktop: Fixes #4411: Count tags based on showCompletedTodos setting

### LINKED ISSUE #4411: Wrong count in tags
A to-do task completed in a notebook, it’s not counted when it is not show (as expected).
A to-do task completed in a tag, it’s counted  when it is not show (that make confusion)

## Environment

Joplin version:  Joplin 1.6.8
Platform:  Win10
OS specifics: no

## Steps to reproduce

1. Ctrl + T, to create the task and add a tag
2. Count the number of notes/tasks in your selected tag and check the task box
3. Be sure the option “show completed to-dos” is unchecked (View menu)
4. Count the number of notes/tasks in your selected tag

Tag count

## Describe what you expected to happen
Not count not showed tasks

### PR DESCRIPTION
**Pull request by JackGruber**
Count the completed todos at the tag sidebar based on the showCompletedTodos setting.

### CODE REVIEW

File: packages/app-desktop/gui/Sidebar/Sidebar.tsx [hunk 1]
```diff
@@ -448,7 +448,7 @@ class SidebarComponent extends React.Component<Props, State> {
 
 	renderTag(tag: any, selected: boolean) {
 		const anchorRef = this.anchorItemRef('tag', tag.id);
-		const noteCount = Setting.value('showNoteCounts') ? this.renderNoteCount(tag.note_count) : '';
+		const noteCount = Setting.value('showNoteCounts') ? Setting.value('showCompletedTodos') ? this.renderNoteCount(tag.note_count) : this.renderNoteCount(tag.note_count - tag.todo_completed_count) : '';
```
Comment (laurent22) [inline packages/app-desktop/gui/Sidebar/Sidebar.tsx:451]: Could you refactor this logic to avoid the nested ternary operators? This is to clarify a bit the logic.

File: packages/lib/JoplinDatabase.ts [hunk 2]
```diff
@@ -874,6 +874,16 @@ export default class JoplinDatabase extends Database {
...
+
+				queries.push('DROP VIEW tags_with_note_count');
+				queries.push(`CREATE VIEW tags_with_note_count AS 
+						SELECT tags.id as id, tags.title as title, tags.created_time as created_time, tags.updated_time as updated_time, COUNT(notes.id) as note_count, 
+							SUM(CASE WHEN notes.todo_completed > 0 THEN 1 ELSE 0 END) AS todo_completed_count
+						FROM tags 
+							LEFT JOIN note_tags nt on nt.tag_id = tags.id 
+							LEFT JOIN notes on notes.id = nt.note_id 
+						WHERE notes.id IS NOT NULL 
+						GROUP BY tags.id`);
```
Comment (laurent22) [inline packages/lib/JoplinDatabase.ts:886]: We can't add to a migration because it means it won't run for those who are, for example, already at revision 36. So every time you need to add something to the db, you need to create a new migration.

By the way, what will be the performance of dropping and recreating this table? Will it result in a white screen on mobile while it's upgrading?

File: packages/app-cli/tests/models_Tag.ts [hunk 3]
```diff
@@ -1,14 +1,7 @@
...
-const Folder = require('@joplin/lib/models/Folder').default;
-const Note = require('@joplin/lib/models/Note').default;
-const NoteTag = require('@joplin/lib/models/NoteTag').default;
-const Tag = require('@joplin/lib/models/Tag').default;
-const BaseModel = require('@joplin/lib/BaseModel').default;
-const shim = require('@joplin/lib/shim').default;
+import { setupDatabaseAndSynchronizer, switchClient, checkThrowAsync } from './test-utils.js';
+import Folder from '@joplin/lib/models/Folder';
+import Note from '@joplin/lib/models/Note';
+import Tag from '@joplin/lib/models/Tag';
```
Comment (laurent22) [inline packages/app-cli/tests/models_Tag.ts:4]: Great, thanks for converting the file to TypeScript!

File: packages/app-cli/tests/models_Tag.ts [hunk 4]
```diff
@@ -123,21 +133,25 @@ describe('models_Tag', function() {
 		expect(commonTags.length).toBe(0);
 
 		commonTags = await Tag.commonTagsByNoteIds([note0.id, note1.id, note2.id, note3.id]);
+		// @ts-ignore
```
Comment (laurent22) [inline packages/app-cli/tests/models_Tag.ts:136]: Why do we need ts-ignore here?

File: packages/lib/JoplinDatabase.ts (hunk 2 above)
Comment (JackGruber) [reply packages/lib/JoplinDatabase.ts:886]: This happened because we both pushed a 36 and then I didn't raise when resolving the conflict.
So it is best to create a separate DB revision for each PR?
Even if there are in the worst case then x revisions for a new released version?

I just see there is already a 37, even if nothing was done in this one I have to create a 38?
https://github.com/laurent22/joplin/blob/dc2cdb7d3ae751e720c1bb40b53dc048b254862d/packages/lib/JoplinDatabase.ts#L346

>By the way, what will be the performance of dropping and recreating this table? 

Since it is only a view, this should actually have no performance impact. 
But I'm willing to try on my phone with a few thousand notes and tags, but this takes some time for the sync :)

File: packages/app-cli/tests/models_Tag.ts (hunk 4 above)
Comment (JackGruber) [reply packages/app-cli/tests/models_Tag.ts]: I can't figure out why I added the ts-ignore, I have removed them.

File: packages/lib/JoplinDatabase.ts (hunk 2 above)
Comment (laurent22) [reply packages/lib/JoplinDatabase.ts:888]: Indeed it looks like I've accidentally added 37 even though nothing was done. So the next one will have to be 38, otherwise existing clients won't pick up the migration.

And yes, it should be a separate revision for each pull request and, if there are conflicts, we increase the number.

**Comment by JackGruber** [comment]
Ok I have made the performance test on Android, with the following items count:
```
Note: 5345
Folder: 57
Resource: 8939
Tag: 1701
NoteTag: 18470
MasterKey: 0/0
Revision: 642/642
Total: 34512
```
No difference was noticeable on my Motorola X4, 5 second with screen with the DB version 37 and 5-6 seconds during the upgrade from 37 to 38.

File: packages/app-cli/tests/models_Tag.ts [hunk 5]
```diff
@@ -123,21 +133,25 @@ describe('models_Tag', function() {
...
 		commonTags = await Tag.commonTagsByNoteIds([note2.id, note3.id]);
+
 		commonTagIds = commonTags.map(t => t.id);
 		expect(commonTagIds.length).toBe(2);
 		expect(commonTagIds.includes(taga.id)).toBe(true);
 		expect(commonTagIds.includes(tagb.id)).toBe(true);
 
 		commonTags = await Tag.commonTagsByNoteIds([note3.id]);
+
 		commonTagIds = commonTags.map(t => t.id);
```
Comment (laurent22) [inline packages/app-cli/tests/models_Tag.ts:155]: It's a small thing, but you could you remove the white space changes please? Just to keep the diff and blame history simpler.

**Review by laurent22 — COMMENTED** [review]
Brilliant, thanks for checking the performance on mobile! It seems it's when migrating the "notes" table that we can get this white screen on startup. Other than that, there's just a minor tweak to make and we can merge.

File: packages/app-cli/tests/models_Tag.ts (hunk 5 above)
Comment (JackGruber) [reply packages/app-cli/tests/models_Tag.ts]: It's done

**Comment by laurent22** [comment]
Looks good now, thanks @JackGruber!
