### PR TITLE
Desktop: Fixes #6721: Fix exporting resources to md and md + frontmatter

### LINKED ISSUE #6721: Resources with space are not imported on Markdown Frontmatter import
If a note contains resources with space and these are exported as Markdown Frontmatter and imported again, the resources are missing. 
grafik

## Environment

Joplin 2.9.1 (dev, win32)

Client ID: a1021b9020f14fc8bb841cd357208e9d
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: c3179a3

## Steps to reproduce

1.  Create a Note with a resource which contains a space in its name
2. Export this note as Markdown Frontmatter
3. Reimport this note

### Original note
grafik

### Imported note
grafik

### Example ZIP
[example.zip](https://github.com/laurent22/joplin/files/9274459/example.zip)

## Describe what you expected to happen

Also resources with space should be imported

### PR DESCRIPTION
**Pull request by SFulpius**
Fixes #6721.
When exporting to Markdown or Markdown + Front Matter, resource filenames can contain spaces. However [markdown does not support spaces in links](https://github.github.com/gfm/#link-destination). When importing an exported file resources are not imported correctly.

We replace spaces by underscores to solve the issue.

### CODE REVIEW

**Comment by CalebJohn** [comment]
The fix looks great! Can you add some tests for it [here](https://github.com/laurent22/joplin/blob/dev/packages/lib/services/interop/InteropService_Exporter_Md.test.ts)?

File: packages/lib/services/interop/InteropService_Exporter_Md.ts [hunk 1]
```diff
@@ -146,6 +146,9 @@ export default class InteropService_Exporter_Md extends InteropService_Exporter_
 			fileName = friendlySafeFilename(resource.title, null, true);
 		}
 
+		// Markdown link destination should not contain space characters
+		fileName = fileName.replace(' ', '_');
```
Comment (personalizedrefrigerator) [inline packages/lib/services/interop/InteropService_Exporter_Md.ts]:
```suggestion
		fileName = fileName.replace(/\s/g, '_');
```
Let's make sure all spaces are being replaced! Notice that
```
> 'foo bar baz.txt'.replace(' ', '_')
`foo_bar baz.txt`
> 'foo bar baz.txt'.replace(/\s/, '_')
`foo_bar baz.txt`
> 'foo bar baz.txt'.replace(/\s/g, '_')
`foo_bar_baz.txt`
```

See the [MDN documentation for `replace`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#description) for more information.

Comment (SFulpius) [reply packages/lib/services/interop/InteropService_Exporter_Md.ts]: Nice catch! I updated it.

**Comment by SFulpius** [comment]
> The fix looks great! Can you add some tests for it [here](https://github.com/laurent22/joplin/blob/dev/packages/lib/services/interop/InteropService_Exporter_Md.test.ts)?

I added a test. I'm not familiar with testing the exporter service, so please tell me if something is wrong.

File: packages/lib/services/interop/InteropService_Exporter_Md.test.ts [hunk 2]
```diff
@@ -446,5 +446,23 @@ describe('interop/InteropService_Exporter_Md', function() {
 		const resourceFilename = (await fs.readdir(`${exportDir()}/_resources`))[0];
 		expect(fileExtension(resourceFilename)).toBe('jpg');
 	}));
+	it.only('should replace spaces in resource name by underscores', (async () => {
```
Comment (CalebJohn) [inline packages/lib/services/interop/InteropService_Exporter_Md.test.ts]:
```suggestion
	it('should replace spaces in resource name by underscores', (async () => {
```

**Review by CalebJohn — CHANGES_REQUESTED** [review]

File: packages/lib/services/interop/InteropService_Exporter_Md.test.ts (hunk 2 above)
Comment (SFulpius) [reply packages/lib/services/interop/InteropService_Exporter_Md.test.ts]: I already made this change in the last commit.

File: packages/lib/services/interop/InteropService_Exporter_Md.ts [hunk 3]
```diff
@@ -146,6 +146,9 @@ export default class InteropService_Exporter_Md extends InteropService_Exporter_
 			fileName = friendlySafeFilename(resource.title, null, true);
 		}
 
+		// Markdown link destination should not contain space characters
+		fileName = fileName.replace(/\s/g, '_');
```
Comment (laurent22) [inline packages/lib/services/interop/InteropService_Exporter_Md.ts]: I think this fix is not right. Urls with spaces should be supported, so I think it's the code that add the url to the Markdown content that should be escaped. We have utility functions in markdownUtils for this

Comment (SFulpius) [reply packages/lib/services/interop/InteropService_Exporter_Md.ts]: I made some changes, please tell me if it is what you had in mind.

Comment (laurent22) [reply packages/lib/services/interop/InteropService_Exporter_Md.ts]: It's not right either, it should be escaped when it's inserted in the doc.

Or maybe not, I'm not sure, I don't understand why it's not already done

Comment (SFulpius) [reply packages/lib/services/interop/InteropService_Exporter_Md.ts]: So you're suggesting the filename should be escaped when adding an image (or another resource) to a note?
Actually I don't think we need it because from what I've seen we are only using resource id in the note. The issue only happens when we export the note and we use the original filename.

Comment (laurent22) [reply packages/lib/services/interop/InteropService_Exporter_Md.ts]: As I said I'm not sure. I don't know why it's not currently escaped, there could be a good reason, but I'd need to look at the code

Comment (laurent22) [reply packages/lib/services/interop/InteropService_Exporter_Md.ts]: So the fix is correct, however as mentioned the data should only be escaped when the text is added to the document, which would be here: https://github.com/laurent22/joplin/blob/9aa59360c1ef41d35b75b0eb7d53b6a3a6c0ab0f/packages/lib/services/interop/InteropService_Exporter_Md.ts#L75

We only escape when needed, not before. This is to avoid issues with data being double-escaped or code using escaped data, when it expects to deal with unescaped one, which can lead to bugs and security issues.

Are you ok with making this change?

**Comment by laurent22** [comment]
I could make the change directly actually. Thanks for looking into this @SFulpius!
