### PR TITLE
Server: Fixes: #13147: Add LOG_LEVEL env var to control logging verbosity

### LINKED ISSUE #13147: Logging to far too verbose, needs to be far less
### Operating system

Linux

### Joplin version

Joplin Server v3.4.2

### Desktop version info

_No response_

### Current behaviour

There is far too junk in the log files and despite several discourse requests to tune it or allow customisation, it's still logging too much data.

For example:
From 2019: [Joplin logging verbose by default?](https://discourse.joplinapp.org/t/joplin-logging-verbose-by-default/1835)
From 2021: [Logging Levels](https://discourse.joplinapp.org/t/logging-levels/22450)
From2022 [How do I reduce the size of log.txt file?](https://discourse.joplinapp.org/t/how-do-i-reduce-the-size-of-log-txt-file/24184)

Can this be address properly please.

### Expected behaviour

Allow us to turn off or reduce the amount of logs produced.

A simple method of n environment variable in docker called "LOGGING" to set the lowest level (DEBUG, INFO, WARN, ERROR) etc.

Or separate log options to turn on/off specific parts.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by bhorbowicz**
Fixes #13147

## Summary
This PR introduces a new environment variable LOG_LEVEL in the Joplin Server configuration, allowing to specify the desired logging verbosity. The default value remains 'info'. Supported values are: none, error, warn, info, debug.

## Why this is needed
Issue [#13147](https://github.com/laurent22/joplin/issues/13147) described the need for more granular control over server-side logging. By introducing LOG_LEVEL, users can reduce noise (e.g., set to error or none) or increase detail (e.g., debug) for troubleshooting or monitoring purposes.

## Backward compatibility
No breaking changes: existing deployments without LOG_LEVEL set will behave as before (info). Logging calls remain unchanged.

## Testing
1. Start the server without LOG_LEVEL set → expect default behavior at info level.
2. Set LOG_LEVEL=none → run some operations that normally produce logs; verify no log output (or minimal).
3. Set LOG_LEVEL=error → trigger an error condition and verify only error messages appear; no warn/info/debug logs.
4. Set LOG_LEVEL=warn → produce a warning and an info message; verify the warning appears, the info does not.
5. Set LOG_LEVEL=debug → perform normal operations, verifying debug, info, warn, and error logs all appear.
6. Set LOG_LEVEL to an invalid value (e.g., LOG_LEVEL=verbose) → server should log an error about invalid value `Error: Unknown log level: verbose`

### CODE REVIEW

**Comment by bhorbowicz** [comment]
I have read the CLA Document and I hereby sign the CLA

File: packages/server/src/utils/types.ts [hunk 1]
```diff
@@ -190,6 +190,7 @@ export interface Config extends EnvVariables {
 	maxTimeDrift: number;
 	ldap: LdapConfig[];
 	saml: SamlConfig;
+	logLevel: LogLevel;
```
Comment (laurent22) [inline packages/server/src/utils/types.ts]: It doesn't need to be added there, you can access config().LOG_LEVEL directly

Comment (bhorbowicz) [reply packages/server/src/utils/types.ts]: I agree it looks a bit redundant, but I thought it would be cleaner to keep the mapping logic in Config and just return LogLevel. I can update it tomorrow.

Comment (bhorbowicz) [reply packages/server/src/utils/types.ts]: Done

**Comment by laurent22** [comment]
Thank you for adding this!

**Comment by user-mb** [comment]
hi guys, i tried to change the log level via the .env or env variable, but the container logs stay at info.
i am using podman.

~~~
LOG_LEVEL=warn
~~~

**Comment by bhorbowicz** [comment]
I tested this in the latest [revision ](https://github.com/laurent22/joplin/commit/a0bdc1fa9b8513509649869bfda37a07aeed31ce) and it works without any issues. @user-mb which version are you using? This feature will be available in [Joplin Server 3.5.x](https://github.com/laurent22/joplin/blob/dev/readme/about/release_cycle.md).

**Comment by user-mb** [comment]
> I tested this in the latest [revision ](https://github.com/laurent22/joplin/commit/a0bdc1fa9b8513509649869bfda37a07aeed31ce) and it works without any issues. @user-mb which version are you using? This feature will be available in [Joplin Server 3.5.x](https://github.com/laurent22/joplin/blob/dev/readme/about/release_cycle.md).

Thank you for checking this quickly. It's my mistake.

I am using docker.io/joplin/server:latest which seems to be version 3.4.3
