### PR TITLE
All: Resolves #173: Upload attachments > 4 MB when using OneDrive

### LINKED ISSUE #173: Fail to sync attachments larger than 4MB to OneDrive
### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Application

- [x] Desktop
- [ ] Mobile
- [ ] Terminal

I have imported a large set of notes from Evernote to Joplin and I am now trying to sync those notes to an otherwise empty OneDrive.  This has mostly worked but I get a message saying "Some items cannot be synchronised.", looking at the details it says "Resource exceeds OneDrive max file size (4MB)" for each of the unsynchronised files.  However I can upload those same files individually to OneDrive without issue.  

OS X version: High Sierra 10.13.2
Joplin version: 0.10.47 (prod, darwin)

image

---

### PR DESCRIPTION
**Pull request by TheOnlyTrueJonathanHeard**
Solves #173. This Issue has been closed by the Bot but only because of inactivity. Also reported in #3060.

### CODE REVIEW

**Comment by anjulalk** [comment]
Hi,
I don't think requiring `fs` module would work in the React Native environment.

**Comment by TheOnlyTrueJonathanHeard** [comment]
Thank @anjulalk for reviewing my code. You are probably right. I am new to React and have no experience with React Native. I thought when the code is working on linux it will also work on mobile devices as I didn't made any GUI changes. This was obviously very naive. Sorry for that. I will fix my code but due to the lack of experience it might take some time.

**Comment by TheOnlyTrueJonathanHeard** [comment]
Now it is also working with React-Native. But some Todos for me: 
- What is about CLI client?
- What is about testing?
- Solve Todos in code
- Check if it is working on ios with emulator (I checked with android and Linux. But I currently don't have access to Windows and macOS)

**Comment by TheOnlyTrueJonathanHeard** [comment]
I have now tested the Code on Android (on my personal phone which is a Huawei P9 lit with Android 7.0) and Linux (Linux Mint 19.3) and it is working on both without Problems. Also tested with the CliClient without problems. The test of the CliClient doesn't show any failures. 

I haven't written any tests as I don't see any tests for Cloud interaction. I haven't tested on Windows and MacOS as I don't have access to a running Windows at the moment (I could test in a VM but as I would need to install Windows first, I would prefer to do it without). I also didn't test on IOS as I have no access to MacOS or IOS (my previous comment was wrong as I didn't know that you need a MacOS to run IOS in an Emulator). 

So currently I don't see how I can further improve the code but if you see anything @laurent22  and @anjulalk let me know and I will try my best to fix it.

File: ReactNativeClient/lib/fs-driver-node.js [hunk 1]
```diff
@@ -188,6 +188,10 @@ class FsDriverNode extends FsDriverBase {
 		if (encoding === 'ascii') return buffer.toString('ascii');
 		throw new Error(`Unsupported encoding: ${encoding}`);
 	}
+
+	fileSize(filepath) {
+		return fs.statSync(filepath)['size'];
+	}
```
Comment (laurent22) [inline ReactNativeClient/lib/fs-driver-node.js:194]: Please use the `stat()` method for this, and you can then get the size in the `size` property. As the code in this file needs to be duplicated for each platform, we try to keep it as lean as possible.

File: ReactNativeClient/lib/fs-driver-rn.js [hunk 2]
```diff
@@ -156,6 +156,12 @@ class FsDriverRN extends FsDriverBase {
 		handle.offset += length;
 		return output ? output : null;
 	}
+
+	async fileSize(filePath) {
+		const stats = await RNFetchBlob.fs.stat(filePath);
+		return stats.size;
+	}
+
```
Comment (laurent22) [inline ReactNativeClient/lib/fs-driver-rn.js:164]: Same, you don't need to create a new method, you can simply use the existing `stat()` method.

File: ReactNativeClient/lib/onedrive-api.js [hunk 3]
```diff
@@ -170,7 +222,7 @@ class OneDriveApi {
 			let response = null;
 			try {
 				if (options.source == 'file' && (method == 'POST' || method == 'PUT')) {
-					response = await shim.uploadBlob(url, options);
+					response = options.fileType == 'small' ? await shim.uploadBlob(url, options) : await this.uploadBigFile(url, options);
```
Comment (laurent22) [inline ReactNativeClient/lib/onedrive-api.js:225]: Please use strict equality `===`

File: ReactNativeClient/lib/onedrive-api.js [hunk 4]
```diff
@@ -130,6 +130,58 @@ class OneDriveApi {
...
+			},
+		});
+		if (!response.ok) {
+			return response;
+		} else {
+			const data = await response.json();
+			const uploadUrl = data.uploadUrl;
+			// uploading file in 7.5 MiB-Fragments (except the last one) because this is the mean of 5 and 10 Mib which are the recommended lower and upper limits.
+			// https://docs.microsoft.com/de-de/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#best-practices
+			const chunkSize = 7864320;
```
Comment (laurent22) [inline ReactNativeClient/lib/onedrive-api.js:149]: Please set it as `7.5 * 1024 * 1024` for clarity

File: ReactNativeClient/lib/file-api-driver-onedrive.js [hunk 5]
```diff
@@ -129,19 +130,21 @@ class FileApiDriverOneDrive {
 
 		let response = null;
 
-		try {
-			if (options.source == 'file') {
-				response = await this.api_.exec('PUT', `${this.makePath_(path)}:/content`, null, null, options);
+		if (options.source == 'file') {
+			// We need to check the file size as files > 4 MBs are uploaded in a different way than files < 4 MB (see https://docs.microsoft.com/de-de/onedrive/developer/rest-api/concepts/upload?view=odsp-graph-online)
+			const fileSize = await shim.fsDriver().fileSize(options.path);
+			if (fileSize < 4194304) {
```
Comment (laurent22) [inline ReactNativeClient/lib/file-api-driver-onedrive.js:136]: Please set it as `4*1024*1024`

File: ReactNativeClient/lib/onedrive-api.js [hunk 6]
```diff
@@ -130,6 +130,58 @@ class OneDriveApi {
...
+				const headers = {
+					'Content-Length': contentLength,
+					'Content-Range': `bytes ${startByte}-${endByte}/${options.fileSize}`,
+					'Content-Type': 'application/octet-stream; charset=utf-8',
+				};
+
+				const response = await shim.uploadChunk(uploadUrl, handle, { contentLength: contentLength, method: 'PUT', headers: headers });
+
+				if (response.ok) {
+					this.logger().info(`${options.path}: ${(endByte / 1048576).toFixed(2)} from ${(options.fileSize / 1048576).toFixed(2)} Mbit have been uploaded`);
```
Comment (laurent22) [inline ReactNativeClient/lib/onedrive-api.js:174]: I don't think we should log this as that would be one statement for each chunk. Or maybe make it `logger().debug` so that it doesn't appear in production.

File: ReactNativeClient/lib/onedrive-api.js [hunk 7]
```diff
@@ -130,6 +130,58 @@ class OneDriveApi {
...
+				let contentLength = null;
+				if (i == numberOfChunks - 1) {
+					// Last fragment. It is not ensured that the last fragment is a multiple of 327,680 bytes as recommanded in the api doc. The reasons is that the docs are out of day for this purpose: https://github.com/OneDrive/onedrive-api-docs/issues/1200#issuecomment-597281253
+					endByte = options.fileSize - 1;
+					contentLength = options.fileSize - ((numberOfChunks - 1) * chunkSize);
+				} else {
+					endByte = (i + 1) * chunkSize - 1;
+					contentLength = chunkSize;
+				}
+				this.logger().info(`${options.path}: Uploading File Fragment ${(startByte / 1048576).toFixed(2)} - ${(endByte / 1048576).toFixed(2)} from ${(options.fileSize / 1048576).toFixed(2)} Mbit ...`);
```
Comment (laurent22) [inline ReactNativeClient/lib/onedrive-api.js:164]: Also make it `logger().debug` please

File: ReactNativeClient/lib/onedrive-api.js [hunk 8]
```diff
@@ -130,6 +130,58 @@ class OneDriveApi {
...
+			// uploading file in 7.5 MiB-Fragments (except the last one) because this is the mean of 5 and 10 Mib which are the recommended lower and upper limits.
+			// https://docs.microsoft.com/de-de/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#best-practices
+			const chunkSize = 7864320;
+			const numberOfChunks = Math.ceil(options.fileSize / chunkSize);
+			const handle = await shim.fsDriver().open(options.path, 'r');
+			for (let i = 0; i < numberOfChunks; i++) {
+				const startByte = i * chunkSize;
+				let endByte = null;
+				let contentLength = null;
+				if (i == numberOfChunks - 1) {
```
Comment (laurent22) [inline ReactNativeClient/lib/onedrive-api.js:156]: `===`

File: ReactNativeClient/lib/file-api-driver-onedrive.js [hunk 9]
```diff
@@ -129,19 +130,21 @@ class FileApiDriverOneDrive {
...
-				options.headers = { 'Content-Type': 'text/plain' };
-				response = await this.api_.exec('PUT', `${this.makePath_(path)}:/content`, null, content, options);
-			}
-		} catch (error) {
-			if (error && error.code === 'BadRequest' && error.message === 'Maximum request length exceeded.') {
-				error.code = 'rejectedByTarget';
-				error.message = 'Resource exceeds OneDrive max file size (4MB)';
+				path = `${this.makePath_(path)}:/createUploadSession`;
+				options.fileType = 'big';
+				options.fileSize = fileSize;
```
Comment (laurent22) [inline ReactNativeClient/lib/file-api-driver-onedrive.js:142]: I think these two properties are not necessary as you can derive this info from the path (if it contains "createUploadSession", it needs `uploadBigFile()`. And ideally the file size should be retrieved where it's needed, directly in `uploadBigFile()`.

File: ReactNativeClient/lib/shim.js [hunk 10]
```diff
@@ -161,6 +161,24 @@ shim.uploadBlob = () => {
 	throw new Error('Not implemented');
 };
 
+shim.uploadChunk = async function(url, handle, options) {
```
Comment (laurent22) [inline ReactNativeClient/lib/shim.js:164]: Please move this method directly in OneDriveApi as it is useful only there.

File: ReactNativeClient/lib/shim.js [hunk 11]
```diff
@@ -161,6 +161,24 @@ shim.uploadBlob = () => {
...
+
```
Comment (laurent22) [inline ReactNativeClient/lib/shim.js:165]: Please make a copy of the options if you are going to modify them: `options = Object.assign({}, options)`

File: ReactNativeClient/lib/onedrive-api.js [hunk 12]
```diff
@@ -130,6 +130,58 @@ class OneDriveApi {
...
+				const response = await shim.uploadChunk(uploadUrl, handle, { contentLength: contentLength, method: 'PUT', headers: headers });
+
+				if (response.ok) {
+					this.logger().info(`${options.path}: ${(endByte / 1048576).toFixed(2)} from ${(options.fileSize / 1048576).toFixed(2)} Mbit have been uploaded`);
+				} else {
+					await shim.fsDriver().close(handle);
+					return response;
+				}
+			}
+			await shim.fsDriver().close(handle);
```
Comment (laurent22) [inline ReactNativeClient/lib/onedrive-api.js:180]: I expect some of the code above can throw exceptions, in particular `uploadChunk()`, and in this case the handle will remain open. So probably should use something like a try/catch/finally block and close the handle in `finally` (and re-throw errors in the catch block)

**Comment by TheOnlyTrueJonathanHeard** [comment]
Thanks for reviewing @laurent22 much appreciated. Your comments were very helpful.  I think now all your comments are solved.

**Comment by laurent22** [comment]
That looks good, many thanks for this pull request @TheOnlyTrueJonathanHeard!
