### PR TITLE
All: Fixes #14543: Fix ++insert++ syntax rendering fix in markdown

### LINKED ISSUE #14543: ++insert++ syntax isn't rendered in markdown editor when render markup is enabled
### Operating system

Windows

### Joplin version

3.6.3

### Desktop version info

Joplin 3.6.3 (prod, win32)

Device: win32, Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Client ID: acf44d67875e4c478d29d7d4c738fc72
Sync Version: 3
Profile Version: 49
Keychain Supported: Yes
Alternative instance ID: -
Sync target: S3
Editor: Markdown

Revision: 891ab3e

Backup: 1.5.1
Codeblock Autocomplete: 1.0.5
Context Utils: 1.4.4
Copy as HTML: 1.5.5
Heading Navigator: 0.6.3
Journal: 2.0.0
Markdown Alerts and Quotes: 1.3.0
Note Tabs: 1.4.0
Paste as Markdown: 1.1.8
Rich Tables: 1.6.4
Simple Image Resize: 1.5.17
Space Indenter: 0.2.6
Templates: 3.0.0

### Current behaviour

1. Tools | Options | Markdown | check the box for `Enable ++insert++ syntax (wysiwyg: yes)`
2. Tools | Options | Note (or Tools | Options | Editor in v3.6) check the box for `Markdown editor: Render markup in editor`
3. In the markdown editor, type `++insert++` into a note

You'll see that this doesn't get rendered with an underline in the markdown editor with render markup enabled, but does get rendered with an underline in the Markdown Viewer and Rich Text Editor

### Expected behaviour

When both render markup and insert syntax are enabled, `++insert++` syntax should be rendered with an underline in the markdown editor like in the markdown viewer and rich text editor

### Logs

_No response_

### PR DESCRIPTION
**Pull request by justin212407**
Fixes: #14543 

## Summary:

Clicking or rendering `++insert++` syntax in the CodeMirror markdown editor with inline rendering enabled did not display the underline formatting, even though the same syntax rendered correctly in the Markdown Viewer and Rich Text Editor.

This happened because the `++insert++` syntax was only handled by the markdown-it plugin (used in viewers/WYSIWYG renderers), but was never wired into CodeMirror's inline rendering pipeline that handles delimiter hiding and visual formatting in the editor itself.

## Fix:

**Before:**
Screenshot From 2026-03-04 00-07-10

**After:**

https://github.com/user-attachments/assets/c00e7889-942f-47f7-9e87-ef2600ead88f

## Testing:

- All existing test continue to pass.

Screenshot From 2026-03-04 00-10-41

## AI Disclosure:
 - I used AI to locate the files relevant to the issue.

### CODE REVIEW

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/CodeMirror.tsx [hunk 1]
```diff
@@ -352,6 +352,7 @@ const CodeMirror = (props: NoteBodyEditorProps, ref: ForwardedRef<NoteBodyEditor
 			language: isHTMLNote ? EditorLanguageType.Html : EditorLanguageType.Markdown,
 			readOnly: props.disabled,
 			markdownMarkEnabled: Setting.value('markdown.plugin.mark'),
+			markdownInsertEnabled: Setting.value('markdown.plugin.insert'),
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/CodeMirror.tsx:355]: Note: A similar change will most likely need to be made for the mobile app in [`NoteEditor.tsx`](https://github.com/laurent22/joplin/blob/81ed35b117b469aeaf68d80138a723d61596cd5f/packages/app-mobile/components/NoteEditor/NoteEditor.tsx#L279).

Thank you for working on this!

Comment (justin212407) [reply packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/CodeMirror.tsx:355]: sure on it, thank you for reviewing this

**Comment by personalizedrefrigerator** [comment]
For the most part, this looks good to me!

Would it be possible to add a related test to [markdownHighlightExtension.test.ts?](https://github.com/laurent22/joplin/blob/b290046e66f8bc2d84ff06aa739ac018a63cc069/packages/editor/CodeMirror/extensions/markdownHighlightExtension.test.ts#L49)

**Comment by justin212407** [comment]
> For the most part, this looks good to me!
> 
> Would it be possible to add a related test to [markdownHighlightExtension.test.ts?](https://github.com/laurent22/joplin/blob/b290046e66f8bc2d84ff06aa739ac018a63cc069/packages/editor/CodeMirror/extensions/markdownHighlightExtension.test.ts#L49)

Made the requested changes

File: packages/editor/CodeMirror/extensions/markdownHighlightExtension.test.ts [hunk 2]
```diff
@@ -70,4 +70,63 @@ describe('MarkdownHighlightExtension', () => {
...
+
+	it.each([
+		{ // Should support single-word insert
+			text: '++insert++',
+			expectedInsertRanges: [{ from: 0, to: '++insert++'.length }],
+			expectedMarkerRanges: [
+				{ from: 0, to: 2 },
+				{ from: '++insert'.length, to: '++insert++'.length },
+			],
+		},
```
Comment (personalizedrefrigerator) [inline packages/editor/CodeMirror/extensions/markdownHighlightExtension.test.ts:82]: Thank you for adding tests!

I don't think all of these tests are necessary for code coverage: Since `==highlight==` has tests and also uses `createDoubleCharInlineConfig`, consider trimming the `++insert++` tests down to just one or two.

Comment (justin212407) [reply packages/editor/CodeMirror/extensions/markdownHighlightExtension.test.ts:82]: Yeah I should have taken a proper look before adding the tests. I have trimmed the test cases to only two cases which are needed for `++insert++` syntax.

Comment (personalizedrefrigerator) [reply packages/editor/CodeMirror/extensions/markdownHighlightExtension.test.ts:82]: Thank you!

File: packages/editor/CodeMirror/extensions/markdownHighlightExtension.ts [hunk 3]
```diff
@@ -2,38 +2,49 @@ import { tags, Tag } from '@lezer/highlight';
...
+
 const HighlightDelimiter = { resolve: highlightTagName, mark: highlightMarkerTagName };
+const InsertDelimiter = { resolve: insertTagName, mark: insertMarkerTagName };
 
 const isSpaceOrEmpty = (text: string) => text.match(/^\s*$/);
 
-// Markdown extension for recognizing highlighting. This is similar to the upstream
-// extension for strikethrough:
+// Creates a MarkdownConfig for a double-character inline delimiter syntax.
 // https://github.com/lezer-parser/markdown/blob/d6f0aa095722329a0188b9c7afe207dab4835e55/src/extension.ts#L10
```
Comment (personalizedrefrigerator) [inline packages/editor/CodeMirror/extensions/markdownHighlightExtension.ts]: This link to the upstream code now seems slightly out of place. Please either:
- Restore the comment that explains why the code link is relevant, or,
- Remove the link to the upstream code.

Other than that, I've tested this locally and this change looks good to me!

Comment (justin212407) [reply packages/editor/CodeMirror/extensions/markdownHighlightExtension.ts]: I have added the comment back since the code link is still actually relevant. Thank you for reviewing this.

**Review by personalizedrefrigerator — APPROVED** [review]
