### PR TITLE
MacOS: Fixes #12240: Fix printing

### LINKED ISSUE #12240: MacOS: Printing and Export to PDF both fail with console error
### Operating system

macOS

### Joplin version

Joplin 3.3.12 (prod, darwin)

### Desktop version info

Joplin 3.3.12 (prod, darwin)

Device: darwin, Apple M4 Pro
Client ID: 41299f9240454325936b7c207820cf8c
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes
Alternative instance ID: -

Revision: 4d790b6

Backup: 1.4.3
Copy Markdown Links: 1.0.0
Freehand Drawing: 3.0.1
HarvestNote: 1.0.0
KanMug: 1.2.7
Note Tabs: 1.4.0
Rich Markdown: 0.16.0
Templates: 2.4.0
YesYouKan: 1.0.15

### Current behaviour

When trying to use File -> Print or File -> Export All -> PDF on MacOS , they both silently fail, but leave logs in the console.

Image

### Expected behaviour

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request applies the [Windows printing issue workaround](https://github.com/laurent22/joplin/pull/12219) to MacOS.

Fixes #12240.

# Testing

**Note**: For me, prior to this pull request (both Joplin 3.3.x and Joplin 3.2.x), File > Print showed a "No printers available on this network" error dialog (rather than the issue described in #12240). With this pull request, a print dialog is shown that allows selecting a printer or saving as a PDF.

Mac OS Sequoia:
1. Open a note in Joplin.
2. Click "File", then "Print".
3. Near the bottom left of the dialog, expand the "PDF" menu.
4. Click "Open in Preview".
5. Verify that a PDF version of the note is shown in the MacOS preview app.

### CODE REVIEW

File: packages/app-desktop/InteropServiceHelper.ts [hunk 1]
```diff
@@ -112,9 +112,11 @@ export default class InteropServiceHelper {
 							// fails on Linux (even if run in the main process).
 							// As such, we use window.print(), which seems to work.
 							//
-							// 2025-05-03: Windows also needs the window.print() workaround.
+							// 2025-05-03: Windows and MacOS also need the window.print() workaround.
+							// See https://github.com/electron/electron/pull/46937.
 
-							if (shim.isLinux() || shim.isWindows()) {
+							const applyWorkaround = true;
+							if (applyWorkaround) {
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/InteropServiceHelper.ts:119]: It may be possible to restore the original logic after the changes from https://github.com/electron/electron/pull/46937 are included in Joplin.
