### PR TITLE
Desktop: Fix button label wrapping

### LINKED ISSUE #2700: Prevent toolbar buttons from wrapping
Toolbar buttons wrap but they shouldn't:

image

We'd need to make sure they don't wrap, and that the media queries still work so it shows only the buttons below a certain width.

### PR DESCRIPTION
**Pull request by anjulalk**
Fixes #2700 

Refer following screen recording for demonstration:
Peek 2020-03-10 01-32

It looks like search box is too wide but it also needs space for `Usage` link so that's why it is.

### CODE REVIEW

File: ElectronClient/gui/Header.jsx [hunk 1]
```diff
@@ -100,7 +100,7 @@ class HeaderComponent extends React.Component {
 	}
 
 	determineButtonLabelState() {
-		const mediaQuery = window.matchMedia(`(max-width: ${550 * this.props.zoomFactor}px)`);
+		const mediaQuery = window.matchMedia(`(max-width: ${780 * this.props.zoomFactor}px)`);
 		const showButtonLabels = !mediaQuery.matches;
```
Comment (tessus) [inline ElectronClient/gui/Header.jsx]: Why did you change the value from 550 to 780?

Comment (anjulalk) [reply ElectronClient/gui/Header.jsx]: I've increased it to prevent the header content from overflowing. Like in the screenshot below:
image

Comment (tessus) [reply ElectronClient/gui/Header.jsx]: Hmm, in that case they should not overflow but the labels should be hidden that only the icons are shown.

Comment (anjulalk) [reply ElectronClient/gui/Header.jsx]: Yeah, if the media query doesn't match button labels are hidden.

Comment (tessus) [reply ElectronClient/gui/Header.jsx]: thx.

**Comment by tessus** [comment]
LGTM

**Comment by laurent22** [comment]
Looks good, thanks.
