### PR TITLE
Desktop: Adjust the codemirror code block colors for the dark theme

### LINKED ISSUE #3793: Codeview code block font color too close to Nord theme background
image

## Environment
image

Joplin version: 1.1.4
Platform: Mac
OS specifics: desktop app

## Steps to reproduce
1. Write a code block with yaml, bash syntax highlighting (see screenshot)

## Describe what you expected to happen
Syntax highlighting should still work, or at least be readable

### PR DESCRIPTION
**Pull request by CalebJohn**
Fixes #3793 

image

I chose these colors by taking the defaults and adjusting the lightness until the contrast was high enough
image

### CODE REVIEW

File: ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx [hunk 1]
```diff
@@ -416,6 +416,27 @@ function CodeMirror(props: NoteBodyEditorProps, ref: any) {
...
+			.cm-s-monokai span.cm-comment {
+				color: #908b74 !important;
+			}
+
+			.cm-s-material-darker span.cm-comment {
+				color: #878787 !important;
+			}
+
+			.cm-s-solarized.cm-s-light span.cm-comment {
+				color: #8ba1a7 !important;
```
Comment (laurent22) [inline ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx:438]: Isn't it something that should be fixed in the theme files directly (eg. themes/nord.ts, etc.)?

Comment (CalebJohn) [reply ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx:438]: The theme files control the way Joplin components will look and be coloured but these changes are specific to the codemirror themes. AFAIK these aren't integrated yet.

Comment (laurent22) [reply ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx:438]: Ah yes, that's right. Ideally we'd submit a patch upstream but I don't know how responsive they are so let's add this for now.
