### PR TITLE
Mobile: iOS: Resolves #6805: Add button to reduce space below markdown toolbar

### LINKED ISSUE #6805: iOS: Too much space below markdown toolbar when autosuggestions are turned off
## Environment

Joplin version: e40d7331767e4de4e90021d433c75f3dbb2b7672
Platform: Mobile
OS specifics: iOS 15.6.1

## Steps to reproduce

0. Disable auto-suggestions
1. Enable the beta editor
2. Edit a note
3. Show the keyboard

screenshot of the markdown toolbar

## Describe what you expected to happen
The markdown toolbar should be just above the keyboard, like it is on Android.

## Possible solution
 * Add a setting to enable/disable additional space below the toolbar
    * In the markdown toolbar PR, it was observed that some iOS devices have keyboards that overlap the toolbar. My phone appears to be the opposite -- the toolbar, even without the additional padding, is well above the keyboard.
 * ~~Wrap the toolbar in a KeyboardAvoidingView~~ -- this seems to have the same issue as manually adding padding. Regardless, the screen is already wrapped in a KeyboardAvoidingView.
 * ~~Wrap the toolbar in an InputAccessoryView~~. We're using a WebView to edit text. As such, it seems that we can't use an [InputAccessoryView](https://reactnative.dev/docs/inputaccessoryview) because it requires an `inputAccessoryViewID` property.
 * Make the markdown toolbar draggable -- moving it up/down when the keyboard is visible adjusts the space below it.
 * Move the markdown toolbar to the top of the screen.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary
 * Adds a button below the markdown toolbar that moves the toolbar towards the bottom of the screen.
 * This button is only visible on iOS.

# Screenshots

### CODE REVIEW

**Comment by personalizedrefrigerator** [comment]
The effects of pushing the `v` button don't persist when the editor is closed/re-opened. This is because I worry that someone will accidentally press the toggle button (e.g. by pressing `tab` on a physical keyboard) on a device where it shouldn't be pressed.

**Comment by laurent22** [comment]
> The effects of pushing the v button don't persist when the editor is closed/re-opened. This is because I worry that someone will accidentally press the toggle button (e.g. by pressing tab on a physical keyboard) on a device where it shouldn't be pressed.

That makes sense but can't we disable tabbing to that particular button? Maybe we some hack like tabIndex = -1 or by overriding onFocus?

**Comment by personalizedrefrigerator** [comment]
> That makes sense but can't we disable tabbing to that particular button? Maybe we some hack like tabIndex = -1 or by overriding onFocus?

We can do that. I'm still worried that someone will find a way to accidentally click the button. If it's really hard to do, making the setting persistent should be okay.

**Comment by personalizedrefrigerator** [comment]
> > The effects of pushing the v button don't persist when the editor is closed/re-opened. This is because I worry that someone will accidentally press the toggle button (e.g. by pressing tab on a physical keyboard) on a device where it shouldn't be pressed.
> 
> That makes sense but can't we disable tabbing to that particular button? Maybe we some hack like tabIndex = -1 or by overriding onFocus?

I've made pressing the button persistent. Pressing the "hide additional space" button enables an otherwise hidden setting. Only if the setting is enabled, can it be seen and disabled in settings.

I haven't done anything with `onFocus` (I wasn't able to find documentation on `tabIndex` for ReactNative).

File: packages/lib/models/Setting.ts [hunk 1]
```diff
@@ -1039,6 +1039,21 @@ class Setting extends BaseModel {
...
+			// See https://github.com/laurent22/joplin/pull/6823
+			'editor.mobile.removeSpaceBelowToolbar': {
+				value: false,
+				type: SettingItemType.Bool,
+				section: 'note',
+				public: true,
+				appTypes: [AppType.Mobile],
+				show: (settings: any) => settings['editor.mobile.removeSpaceBelowToolbar'],
+				label: () => _('Remove extra space below the markdown toolbar'),
+				description: () => _('Works around bug on some devices where the markdown toolbar does not touch the bottom of the screen.'),
```
Comment (laurent22) [inline packages/lib/models/Setting.ts]: Let's not translate this for now, since hopefully there will be a better workaround later on (and in the meantime we don't want to add more strings to be translated)

File: packages/app-mobile/components/NoteEditor/MarkdownToolbar/ToggleSpaceButton.tsx [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+
+	const decreaseSpaceButton = (
+		<>
+			<View style={{
+				height: additionalPositiveSpace,
+				zIndex: -2,
+			}} />
+			<CustomButton
+				themeId={props.themeId}
+				description={_('Move toolbar to bottom of screen')}
```
Comment (laurent22) [inline packages/app-mobile/components/NoteEditor/MarkdownToolbar/ToggleSpaceButton.tsx]: Let's not translate

Comment (personalizedrefrigerator) [reply packages/app-mobile/components/NoteEditor/MarkdownToolbar/ToggleSpaceButton.tsx]: Changed!

**Comment by laurent22** [comment]
Ok let's merge then, thanks for implementing this fix
