### PR TITLE
Mobile: Fixes #9321: Restore scroll position when returning to the note viewer from the editor or camera

### LINKED ISSUE #9321: Mobile: Note viewer scroll resets to top after closing the image editor
### Operating system

Android, iOS

### Joplin version

2.13.6

### Desktop version info

_No response_

### Current behaviour

Steps to reproduce

1. Add a drawing to the end of a long note
3. Close the image editor.
4. Scroll down to the image
5. Press the edit button
6. Close the image editor

Currently, the viewer is scrolled to the top after closing the editor.

### Expected behaviour

The edited image should be visible after closing the edtior.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

Saves the note viewer's scroll and restores it when closing the image editor/note editor/camera.

Fixes #9321.

# Testing

1. Open a note with a large amount of content
2. Scroll to the end
3. Attach a drawing
4. Draw something and close the editor
    - The editor should still be scrolled to the end.
5. Click to edit the drawing
6. Close the image editor
    - The editor should still be scrolled to the end.
7. Open the note editor
8. Add a heading near the end (e.g. `Some memorable heading`)
9. Add a link to that heading at the top of the note (e.g. `[link](#some-memorable-heading)`)
10. Open the note viewer
    - Should be scrolled to the position from before the editor was opened
11. Click the heading link
    - Should jump to the heading

This has been tested on an Android 12 emulator and an iOS 17 simulator.

### CODE REVIEW

File: packages/app-mobile/components/NoteBodyViewer/hooks/useOnMessage.ts [hunk 1]
```diff
@@ -49,6 +52,14 @@ export default function useOnMessage(
 			onResourceLongPress(msg);
 		} else if (msg.startsWith('edit:')) {
 			onRequestEditResource?.(msg);
+		} else if (msg.startsWith('onscroll:')) {
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/NoteBodyViewer/hooks/useOnMessage.ts]: A `console.info` statement just above this logs a large amount of data because of the `onscroll:` event.

Because of this, it might make sense to add a check to skip logging on scroll events.

Comment (personalizedrefrigerator) [reply packages/app-mobile/components/NoteBodyViewer/hooks/useOnMessage.ts]: Done in 30867472f28fb278e6330419df21623d1d67c6aa

**Comment by laurent22** [comment]
That would be useful feature, thanks for adding this. Let's merge it for 2.13 but sometimes when dealing with scroll there are strange bugs that show up so let's see how it goes. If there are issues we can't solve we'll revert and move it to 2.14
