### PR TITLE
Desktop: Fixes #11783: Plugins: Fix toast notifications don't reappear unless parameters are changed

### LINKED ISSUE #11783: Toast notifications don't reappear unless parameters are changed
> If any of the 'message', 'duration', and 'type' parameters do not change, the toast notification will only display once. The second identical toast will not appear until at least one of these parameters is altered.
> I found an unconventional solution:

```
await (joplin.views.dialogs as any).showToast({message:'Finished', duration:3000+(Date.now()%500), type:'success'});
```

Ref: https://discourse.joplinapp.org/t/add-toast-notifications-api-for-plugin-developers/42897/5?u=laurent

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request fixes #11783 by adding a hook dependency.

This pull request includes an automated test.

### CODE REVIEW

File: packages/app-desktop/gui/PluginNotification/PluginNotification.tsx [hunk 1]
```diff
@@ -35,7 +35,7 @@ export default (props: Props) => {
 		};
 
 		notyfContext.open(options);
-	}, [toast.message, toast.duration, toast.type, notyfContext]);
+	}, [toast.message, toast.duration, toast.type, toast.timestamp, notyfContext]);
```
Comment (laurent22) [inline packages/app-desktop/gui/PluginNotification/PluginNotification.tsx:41]: Could you add a comment to explain why we need this extra property please?
