### PR TITLE
Mobile: Fixes #4450: Background flashes white when opening notes in the iOS app

### LINKED ISSUE #4450: Background flashes white when opening notes in the iOS app
This is the same issue described in [4228](https://github.com/laurent22/joplin/issues/4228), which was closed due to inactivity.
See the screen recoding from the old issue: [https://streamable.com/a3uh43](https://streamable.com/a3uh43)

## Environment

Joplin version: 10.6.3
Platform: iOS
OS specifics: iOS 14.3

## Steps to reproduce

1. Select any theme with a dark background, for example the appropriately named "Dark" theme (Configuration -> Appearance -> Theme)
2. Save the configuration
3. Open any note or todo

## Describe what you expected to happen

The note or todo to open smoothly with a background color matching the one from the selected theme.
Instead, the background of the note flashes white (once) and then correctly resets to the background color of the theme.

### PR DESCRIPTION
**Pull request by tams**
Suggesting a fix for the the flashes of white occurring when opening notes on mobile, most visible with dark themes.

Tested on iOS.

This PR does not target desktop which also received two valuable reports as comments to the ticket:
- [OS X](https://github.com/laurent22/joplin/issues/4450#issuecomment-780287026) by @Jegber
- [Windows](https://github.com/laurent22/joplin/issues/4450#issuecomment-787198109) by @jleighton

### CODE REVIEW

File: packages/app-mobile/components/NoteBodyViewer/NoteBodyViewer.tsx [hunk 1]
```diff
@@ -30,9 +30,9 @@ interface Props {
 export default function NoteBodyViewer(props: Props) {
 	const theme = themeStyle(props.themeId);
 
-	const webViewStyle: any = useMemo(() => {
-		return { backgroundColor: theme.backgroundColor };
-	}, [theme.backgroundColor]);
+	const webViewStyle = {
+		backgroundColor: 'transparent',
+	};
```
Comment (laurent22) [inline packages/app-mobile/components/NoteBodyViewer/NoteBodyViewer.tsx:35]: If it never changes, it should be defined outside the NoteBodyViewer function

Comment (tams) [reply packages/app-mobile/components/NoteBodyViewer/NoteBodyViewer.tsx]: Sure thing!

Does d2a9d0b look like a step in the right direction?

Comment (laurent22) [reply packages/app-mobile/components/NoteBodyViewer/NoteBodyViewer.tsx]: Sorry, what I meant is that you need to move the constant outside the function body, to prevent unnecessary re-renders. So move `const webViewStyle = { backgroundColor: 'transparent', };` before `export default function NoteBodyViewer(props: Props)`. Please don't pass it as a prop as it's just a constant.

Comment (tams) [reply packages/app-mobile/components/NoteBodyViewer/NoteBodyViewer.tsx]: Okay, can do.

So like 799cb27, just moved outside the body.

**Comment by laurent22** [comment]
Ok looks good now, thank you.
