### PR TITLE
Mobile: Support description banners on plugin-registered settings screens

### LINKED ISSUE #10207: Mobile: Describe the plugin settings page
### Operating system

Android

### Joplin version

3.0.0

### Desktop version info

_No response_

### Current behaviour

At present, the mobile plugins settings page has no description of what plugins are, who creates/publishes them, etc.
screenshot: Plugin settings page. Has: List of installed plugins with delete buttons, install from file, and search (and advanced settings)

### Expected behaviour

The plugin settings screen *might* have the following:
- [x] A description of who publishes plugin plugins and how to tell.
   - Resolved -- see: https://github.com/laurent22/joplin/pull/10348
- [x] What "recommended" plugins are.
   - Resolved -- see: https://github.com/laurent22/joplin/pull/10348
- [x] What to do if a plugin doesn't work on mobile. (Maybe mark plugins as a beta feature?)
   - Resolved -- most plugins marked as incompatible.
- If using a GitHub mirror, what this means.
   - Currently, a warning is shown at the top of the screen (similar to desktop). However, it isn't clear from the warning what a "mirror" is or why it's being used.
- A link for more information.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request does the following:
1. ~~Enables showing settings page descriptions on mobile.~~ (Will be moved to a separate PR).
2. Uses the same description component to mark the mobile settings screen as beta, describe it, and link to the plugins help page on Joplin's website.

# Screenshot

screenshot: Settings banner for revealjs slides shown at the top of its settings screen on mobile

<details><summary>Original notes/testing plan</summary>

# Notes

## Previous approach

A previous approach  added  two new static methods to `Setting.ts`: `sectionDescriptionTitle` and `sectionHelpLink`. While this would allow existing plugins to add help links (and configure the headings for their info messages on mobile), it adds more section-specific static methods to `Settings.ts`.

We currently have several such static methods that return different values, given different section names. For example, `sectionNameToLabel`:

https://github.com/laurent22/joplin/blob/2ae08ff46ed3db89ef1756863be7eae7cf4c9379/packages/lib/models/Setting.ts#L2763-L2780

It could make sense to refactor this (perhaps a separate pull request):
- The built-in section names could be stored in an `enum`. For example,
  ```ts
  enum SectionName {
      General = 'general',
      ...
  }
  ```
- Sections could be stored as objects, similar to settings, with properties/methods for getting names/icons/etc instead of static getter methods on the `Setting` object. This would be similar to how we currently define settings in the same file.

# Screenshots

## Plugin page description

screenshot: iOS simulator showing an info banner at the top of the plugin screen with a learn more button. Plugins (beta) on first line in bold, further description on the next line.
screenshot: Similar to the previous (also iOS simulator), but now in portrait mode and dark.

## Effect on an existing plugin that has a settings page description

screenshot: Dialog similar to above displays information about the RevealJS slides plugin. No help link.

# Testing plan

This has been tested manually on iOS by:
1. Installing a plugin with a description (e.g. RevealJS slides)
2. Verifying that the plugin management screen displays a banner with information about plugins on mobile.
3. Verifying that the link leads to the plugins help page on Joplin's website.
4. Verifying that the settings page for RevealJS slides also displays an information banner.

</details>

# Testing plan

This has been tested manually on Android 7 by:
1. Installing a plugin with a description (tested with RevealJS slides)
2. Navigating to that plugin's settings screen and verifying that a banner describing that page is visible.

### CODE REVIEW

File: packages/app-mobile/components/screens/ConfigScreen/plugins/PluginStates.tsx [hunk 1]
```diff
@@ -126,6 +127,11 @@ const PluginStates: React.FC<Props> = props => {
 
 	return (
 		<View>
+			<SectionDescription
+				title={`${_('Plugins')} (Beta)`}
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/screens/ConfigScreen/plugins/PluginStates.tsx]: As is done elsewhere in the code, `(Beta)` is marked as untranslatable.

An alternative could be to do something similar to the following:
```suggestion
				title={_('%s (Beta)', _('Plugins'))}
```

File: packages/app-mobile/components/screens/ConfigScreen/plugins/PluginStates.tsx [hunk 2]
```diff
@@ -126,6 +127,11 @@ const PluginStates: React.FC<Props> = props => {
...
+				description={_('Plugins extend Joplin\'s functionality with additional features. These plugins are developed and maintained by Joplin community members. Not all plugins will work correctly on this device.')}
```
Comment (laurent22) [inline packages/app-mobile/components/screens/ConfigScreen/plugins/PluginStates.tsx]: I think just "Plugins extend Joplin\'s functionality with additional feature."?

At some level the whole application is developed and maintained by Joplin community members so I don't think it's useful to mention this for plugins. And we should assume that they work, or do something about those that don't, so normally all listed plugins should work correctly on the device.

File: packages/app-mobile/components/screens/ConfigScreen/plugins/PluginStates.tsx (hunk 1 above)
Comment (laurent22) [reply packages/app-mobile/components/screens/ConfigScreen/plugins/PluginStates.tsx]: This is fine as it is, because normally beta feature don't remain in this state so we don't want to do anything special in terms of translation.

File: packages/app-mobile/components/screens/ConfigScreen/plugins/PluginStates.tsx (hunk 2 above)
Comment (personalizedrefrigerator) [reply packages/app-mobile/components/screens/ConfigScreen/plugins/PluginStates.tsx]: I plan to look at how Obsidian and other stores do this, then post the results here.

Comment (personalizedrefrigerator) [reply packages/app-mobile/components/screens/ConfigScreen/plugins/PluginStates.tsx]: ## How Obsidian does this

Obsidian divides their plugins into two separate sections in their main settings screen:
- Core plugins
- Community plugins

Community plugins need to be enabled:

screenshot: Plugin UI in Obsidian, community plugins must be enabled by pressing a button

## How Notion does this

Notion provides an ["integrations gallery"](
https://www.notion.so/integrations/all) with about 90 integrations (plugins).  At the bottom of the integrations page, Notion states:
> **Are all Notion integrations included in the directory?**
>
> Integrations listed in the directory are a subset of all integrations available for Notion users. The directory includes all integrations that are built by Notion as well as other integrations that have been made by our partners and third parties. We are continuously adding more integrations to the directory.
>
> **Are integrations listed in the directory reviewed by Notion?**
>
> Integrations that have been made by Notion are subject to the same review process and standards as Notion’s own product and services. Notion conducts a brief review of the third party integrations listed in our directory, but does not sponsor, support, or certify these integrations.

Notion also states that developers can make their own public integrations, but it isn't clear how to find or install integrations not reviewed by Notion.

## Summary

Both Obsidian and Notion (the only two apps I compared to) include information about their plugin review process. Obsidian and Notion both make it difficult to install community plugins that haven't undergone code review.

Comment (laurent22) [reply packages/app-mobile/components/screens/ConfigScreen/plugins/PluginStates.tsx]: Thanks for looking into this. As you suggested it seems we should indeed do something about the fact that the plugins could potentially cause issues. Since we only have community plugins, maybe we could have a screen like Obisdian the first time the user opens the Plugin configuration screen? Then we can provide detailed information there, and at the bottom we'll have the same "Enable plugins" checkbox.

Their screen is pretty good actually - they mention the risks but also what they do to mitigate them, so we could do something similar, what do you think?

Comment (personalizedrefrigerator) [reply packages/app-mobile/components/screens/ConfigScreen/plugins/PluginStates.tsx]: > Their screen is pretty good actually - they mention the risks but also what they do to mitigate them, so we could do something similar, what do you think?

I like that idea. I plan to implement it in a separate PR.

I've removed the logic specific to the plugin management screen from this PR. It now only adds support for displaying section descriptions registered by plugins. For example,
screenshot: Settings banner for revealjs slides shown at the top of its settings screen on mobile

Comment (personalizedrefrigerator) [reply packages/app-mobile/components/screens/ConfigScreen/plugins/PluginStates.tsx]: Follow-up pull request:
- [Part 1: Adds a "report issue" button to installed plugins](https://github.com/laurent22/joplin/pull/10319#discussion_r1567989998) — mentioned as a part of the UI in part 2.
- [Part 2 (not yet opened): Adds the "would you like to enable plugins?" screen](https://github.com/personalizedrefrigerator/joplin/pull/new/pr/mobile-plugin-support/plugin-before-enable-info)

**Review by ghost — COMMENTED** [review]
Тори
