### PR TITLE
Fixes offset in selection caused due to white spaces.

### LINKED ISSUE #2736: DESKTOP: If the text is preceeded by white spaces after converting it into bold text, the text is not selected properly.
# Actual Behavior
selection-bug

# Desired Behavior
selection-fix

### PR DESCRIPTION
**Pull request by Rishgod**
fixes #2736 

## Description
If the white spaces are surrounding the selected text, it causes an offset due to which the selected text is displaced, _Look at GIF 1 only bug should be selected_

## Bug

selection-bug

## Fix

selection-fix

## Explaining the code

-  We know the text offset position of the start and stop _**(the position from where we want our selection to start)**_ so the first step is to convert it from text offset(_indexOf_)  -> CursonPosition(_rows& columns_)

-  Adding string1.length **(the MarkDown Rule, ** for bold etc.)** because we want the text to be selected after the markdown rule like in GIF 2

- Removing `if (this.state.note.body.substr(selection.end) === '') newBody = newBody.trim();`  to take care of a corner case  bug (It does not break the code, look at PR #2582 it details on why this code was added)

@PackElend can you label me please

### CODE REVIEW

**Comment by tessus** [comment]
The function `wrapSelectionWithStrings` is used by more than just bold, italics, code.

Did you test, if the other cases still work as expected?

**Comment by Rishgod** [comment]
> The function `wrapSelectionWithStrings` is used by more than just bold, italics, code.
> 
> Did you test, if the other cases still work as expected?

the other cases are not affected

this is an extension to the previous PR i did which fixes white spaces in case of bold/italics & code , this fixes selection offset in only those cases,

other cases do not have this problem because this problem is only created when you have white spaces surrounding the text

**Comment by tessus** [comment]
> the other cases are not affected

That's my point. But they still use the function which you have modified. Thus you have to check which action triggers that function (e.g. adding a link, ...) and verify that your changes really don't affect these other cases.

**Comment by Rishgod** [comment]
> > the other cases are not affected
> 
> That's my point. But they still use the function which you have modified. Thus you have to check which action triggers that function (e.g. adding a link, ...) and verify that your changes really don't affect these other cases.

I'll do the same and let you know!

File: ElectronClient/gui/NoteText.jsx [hunk 1]
```diff
@@ -1461,7 +1461,12 @@ class NoteTextComponent extends React.Component {
 					let start = selectedStrings[i].search(/[^\s]/);
 					let end = selectedStrings[i].search(/[^\s](?=[\s]*$)/);
 					newBody += selectedStrings[i].substr(0, start) + string1 + selectedStrings[i].substr(start, end - start + 1) + string2 + selectedStrings[i].substr(end + 1);
-					if (this.state.note.body.substr(selection.end) === '') newBody = newBody.trim();
+
+					// correcting selction offset
+					var startCursorPos = this.textOffsetToCursorPosition(selection.start+start, newBody);
+					var endCursorPos = this.textOffsetToCursorPosition(selection.start+end+1,newBody);
```
Comment (laurent22) [inline ElectronClient/gui/NoteText.jsx]: var => const

File: ElectronClient/gui/NoteText.jsx [hunk 2]
```diff
@@ -1461,7 +1461,12 @@ class NoteTextComponent extends React.Component {
 					let start = selectedStrings[i].search(/[^\s]/);
 					let end = selectedStrings[i].search(/[^\s](?=[\s]*$)/);
 					newBody += selectedStrings[i].substr(0, start) + string1 + selectedStrings[i].substr(start, end - start + 1) + string2 + selectedStrings[i].substr(end + 1);
-					if (this.state.note.body.substr(selection.end) === '') newBody = newBody.trim();
+
+					// correcting selction offset
```
Comment (laurent22) [inline ElectronClient/gui/NoteText.jsx]: selction => selection

Also please add more information about what the code does exactly.

File: ElectronClient/gui/NoteText.jsx [hunk 3]
```diff
@@ -1475,12 +1480,25 @@ class NoteTextComponent extends React.Component {
...
 			// Add the number of newlines to the row
 			// and add the length of the final line to the column (for strings with no newlines this is the string length)
-			const newRange = {
-				start: { row: r.start.row + str1Split.length - 1,
-					column: r.start.column + str1Split[str1Split.length - 1].length },
-				end: { row: r.end.row + str1Split.length - 1,
-					column: r.end.column + str1Split[str1Split.length - 1].length },
-			};
+
+			var newRange = {};
```
Comment (laurent22) [inline ElectronClient/gui/NoteText.jsx]: var => let

File: ElectronClient/gui/NoteText.jsx [hunk 4]
```diff
@@ -1475,12 +1480,25 @@ class NoteTextComponent extends React.Component {
...
+
+			if (byLine==false) {
```
Comment (laurent22) [inline ElectronClient/gui/NoteText.jsx]: !byLine

File: ElectronClient/gui/NoteText.jsx [hunk 5]
```diff
@@ -1475,12 +1480,25 @@ class NoteTextComponent extends React.Component {
...
+				// Correcting slection offset when text is surrounded by white spaces
```
Comment (laurent22) [inline ElectronClient/gui/NoteText.jsx]: slection => selection

Also add more information about what the code does here please.

Comment (Rishgod) [reply ElectronClient/gui/NoteText.jsx]: in this PR #2582 we added the functionality to convert text into bold/italics/code even though they were surrounded by spaces,  so in wrapSelection we added this condition that is if byline==false (which means treat the selected text as a block not inline) implement this rule

byline



Now  the issue for wrapping selected text inside markdown rule was created when you implemented this rule, (_because it counts the white spaces which creates an offset_) 

So only cases with byLine== false need the code for correction in selection offset, Hope this clears it up!

File: ElectronClient/gui/NoteText.jsx (hunk 2 above)
Comment (Rishgod) [reply ElectronClient/gui/NoteText.jsx]: `if (this.state.note.body.substr(selection.end) === '') newBody = newBody.trim();`

This was also added in #2582 

**_This has no underling logic only for improving aesthetics, this was removed to take care of a corner case while implementing this current PR._**

so while adding the markdown rule, we basically break the notes into 3 components
(before selected text) - selected text - (after selected text)

so we are checking that if (after selected text) is null remove all the white spaces after applying the closing the markdown rule.


#### With trim functionality
trim-II


#### Without trim functionality
trim-I

File: ElectronClient/gui/NoteText.jsx (hunk 1 above)
Comment (Rishgod) [reply ElectronClient/gui/NoteText.jsx]: we use these variables in other blocks too, what do you prefer
 

-  define them with `let` outside the block

- let these variables be defined with `var`

File: ElectronClient/gui/NoteText.jsx (hunk 3 above)
Comment (Rishgod) [reply ElectronClient/gui/NoteText.jsx]: done!

File: ElectronClient/gui/NoteText.jsx (hunk 4 above)
Comment (Rishgod) [reply ElectronClient/gui/NoteText.jsx]: done.

File: ElectronClient/gui/NoteText.jsx [hunk 6]
```diff
@@ -1475,12 +1480,27 @@ class NoteTextComponent extends React.Component {
...
-				start: { row: r.start.row + str1Split.length - 1,
-					column: r.start.column + str1Split[str1Split.length - 1].length },
-				end: { row: r.end.row + str1Split.length - 1,
-					column: r.end.column + str1Split[str1Split.length - 1].length },
-			};
+
+			let newRange = {};
+
+
+
```
Comment (mic704b) [inline ElectronClient/gui/NoteText.jsx]: Too much whitespace

File: ElectronClient/gui/NoteText.jsx [hunk 7]
```diff
@@ -1475,12 +1480,27 @@ class NoteTextComponent extends React.Component {
...
+			if (!byLine) {
+				// Correcting selection offset when text is surrounded by white spaces
```
Comment (mic704b) [inline ElectronClient/gui/NoteText.jsx]: I'm not sure the `!byLine` means surrounded by whitespace.  I thought it means that the wrapping will happen around all the text selected (as opposed to wrap each line in the selection).  If I am right, is it the comment or the code that is incorrect?

**Comment by mic704b** [comment]
Further to tessus' comment above, a list manual test cases would be helpful if possible. Open to ideas on how you would present it, but just one liners might be good enough: brief description of the scenario and the expected result.

File: ElectronClient/gui/NoteText.jsx (hunk 7 above)
Comment (Rishgod) [reply ElectronClient/gui/NoteText.jsx]: > in this PR #2582 we added the functionality to convert text into bold/italics/code even though they were surrounded by spaces, so in wrapSelection we added this condition that is if byline==false (which means treat the selected text as a block not inline) implement this rule
> 
> byline
> 
> Now the issue of **text not getting properly selected text inside markdown rule** (REASON: _because it counts the white spaces which creates an offset in the selected text, it should ignore all the white spaces before and after the markdown rule and select only the text inside the rule_) was created when you implemented this rule(_**the one in the above image**_),
> 
> So only cases with byLine== false need the code for correction in selection offset, Hope this clears it up!

**Comment by Rishgod** [comment]
> Further to tessus' comment above, a list manual test cases would be helpful if possible. Open to ideas on how you would present it, but just one liners might be good enough: brief description of the scenario and the expected result.

Okay, I'll create a gif and document the cases

File: ElectronClient/gui/NoteText.jsx (hunk 7 above)
Comment (mic704b) [reply ElectronClient/gui/NoteText.jsx]: The comment is a bit misleading because It is not "correcting..." at that point because it hasn't been started yet. It is correct in the context of your changes, but not in the big picture.

Also, I'm pretty sure that `byLine` differentiates between wrapping each line of selected text, versus wrapping the whole of the selected text.  If it is about `inline` and `block` mode, then the argument should have a different name.  Just take care around that, because maybe it isn't doing what you think it is.

PS code screenshots are not appreciated in conversations unless special circumstances. Please use code blocks.

**Comment by laurent22** [comment]
Please rebase the PR to remove the const/let changes.

**Comment by Rishgod** [comment]
> Please rebase the PR to remove the const/let changes.

Noted, I'm a bit busy with college right now, I'll do it soon.

**Comment by Rishgod** [comment]
###BEFORE
BEFORE


###AFTER (manually checking all the cases)
AFTER

File: ElectronClient/gui/NoteText.jsx [hunk 8]
```diff
@@ -1616,7 +1633,7 @@ class NoteTextComponent extends React.Component {
 	}
 
 	commandTextHeading() {
-		this.addListItem('## ');
+		this.addListItem('## ','','', true);
```
Comment (Rishgod) [inline ElectronClient/gui/NoteText.jsx]: HEADING CHANGES

**Comment by Rishgod** [comment]
@laurent22 can you please review this, thank you!

**Comment by laurent22** [comment]
I can't say I understand everything to this part of the code, but it seems like a safe change and to work as expected so let's merge. Thanks @Rishgod

**Comment by Rishgod** [comment]
> I can't say I understand everything to this part of the code, but it seems like a safe change and to work as expected so let's merge. Thanks @Rishgod

sir I can write unit test for the same, based on how [these](https://github.com/laurent22/joplin/pull/2772/files) are written if that is required
