### PR TITLE
Desktop: Resolves #8742: Prompt to restart in safe mode on renderer process hang/crash

### LINKED ISSUE #8742: Application should start in safe mode after a crash
For example if this note is loaded:

https://github.com/laurent22/joplin/files/12407306/bloated.note.-.inline.jex.zip

It is going to freeze the application as CodeMirror parses the large Base64 image. If the user force quit the application, and reopen it, it will freeze again because the same note will still be open.

We should do two things:

- After a crash or force-quit, the app should start in safe mode

- In safe mode, the app should load the note in a simple textarea component. The other editors should not load. We have a `packages/app-desktop/gui/NoteEditor/NoteBody/PlainEditor/PlainEditor_tsx.txt` which renders a plain text editor, which perhaps can be used for this. It used to work but it was a long time ago.

It was also suggest to start the app with no notes being selected but the problem is that as soon as the user switches to a notebook a note will be automatically selected, which may crash the app again.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request adds a prompt to restart and enable safe mode that is shown if any of these cases:
1. The renderer process hangs
2. The renderer process crashes
3. An error occurs during `app().start(...)`

This is a different approach from #8886, which attempted to detect abnormal exits, then display a prompt on the next launch.

Resolves #8742.

# Testing

This pull request can be tested manually by
1. Launching Joplin
2. Opening the development tools
3. Typing `process.crash()` and pressing <kbd>Return</kbd>
4. Clicking "restart in safe mode"
5. Relaunching if necessary
6. Disabling safe mode and restarting
7. Opening the development tools
8. Typing `process.hang()` and closing the development tools
9. Waiting 10-15 seconds
10. Clicking "restart in safe mode"

This pull request has been tested manually on Windows 11 and automated tests.

Note that the automated tests do not cover showing the dialog or an actual crash. A fragile Playwright test that tested some of these things was removed in [commit](https://github.com/laurent22/joplin/pull/9153/commits/afe530b60e0abb6dbf2aabb744fed6d477521686).

# Notes

## How safe mode is enabled

The crash handler enables safe mode by creating a file in the profile directory, rather than writing to `Setting`s.

The crash handler assumes that nothing in the renderer process can be accessed.  It also attempts to avoid completely initializing the application (as the crash could be caused by a bug in the initialization code). Because `Settings` relies on the database, which is initialized/present in the `renderer`, this pull request writes a file to the profile directory, rather than writing to the settings database.

If this file is present on startup (and has content `true`), the app enables safe mode and deletes the file.

### CODE REVIEW

File: packages/app-desktop/integration-tests/util/mockNextShowMessageDialog.ts [hunk 1]
```diff
@@ -0,0 +1,84 @@
+
+import type { ElectronApplication } from '@playwright/test';
+import { BrowserWindow, MessageBoxOptions } from 'electron';
+
+const mockNextShowMessageCall = (
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/integration-tests/util/mockNextShowMessageDialog.ts]: For reference, compare to [`playwright-fake-dialog`](https://github.com/wsw0108/playwright-fake-dialog/blob/master/index.js). (Using this library would likely still require re-implementing much of the below code).

File: packages/app-desktop/integration-tests/util/mockNextShowMessageDialog.ts [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+
+					if (returnIndex === -1) {
+						throw new Error(`Unable to find button matching ${answerPattern}`);
+					}
+
+					result = {
+						response: returnIndex,
+						checkboxChecked: false,
+					};
+				} else {
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/integration-tests/util/mockNextShowMessageDialog.ts]: For the new tests, it should be sufficient to mock *all* `showMessage` calls that match a pattern, rather than just the next. This change should allow much of this function to be simplified, as much of it is related to restoring the original `dialog.showMessageBox` function.

File: packages/app-desktop/main-html.js [hunk 3]
```diff
@@ -157,6 +157,8 @@ app().start(bridge().processArgv()).then((result) => {
 		}
 	}
 
-	// In dev, we leave the app open as debug statements in the console can be useful
-	if (env !== 'dev') bridge().electronApp().exit(1);
+	// In dev, we give the option to leave the app open as debug statements in the
+	// console can be useful
+	const canIgnore = env === 'dev';
+	bridge().electronApp().handleAppFailure(error, canIgnore);
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/main-html.js]: The code several lines above this also handles showing an error message to the user.

As `handleAppFailure` also does this, the original code should be instead used to create a better error message in the `handleAppFailure` dialog.

File: packages/app-desktop/integration-tests/util/mockNextShowMessageDialog.ts (hunk 2 above)
Comment (personalizedrefrigerator) [reply packages/app-desktop/integration-tests/util/mockNextShowMessageDialog.ts]: Done in e4f63faeb06eaf2e9806dcbc570ad2f5840acf5e. Note that the original might be more useful in some cases, so it may alternatively make sense to revert this.

File: packages/app-desktop/main-html.js (hunk 3 above)
Comment (personalizedrefrigerator) [reply packages/app-desktop/main-html.js]: Changed.
