### PR TITLE
Mobile: Fixes #13825: Fix incompatible plugins cannot be uninstalled

### LINKED ISSUE #13825: Mobile: When installing a plugin from file which is incompatible on mobile, it cannot be uninstalled
### Operating system

Android

### Joplin version

3.5.7

### Desktop version info

_No response_

### Current behaviour

Using the install from file option on the plugins screen of both the native app and web app, install a plugin which is not compatible with mobile, eg. https://joplinapp.org/plugins/plugin/joplin-plugin-conflict-resolution/

It is then not possible to uninstall the plugin, because clicking the plugin tile or the 'incompatible' label on the tile does not do anything, due to being in a disabled state

See video:
https://github.com/user-attachments/assets/23eb8bb5-6775-4a13-9610-65e57009c202

### Expected behaviour

You should be able to click the title and uninstall the plugin, as is the case when a compatible plugin is set to disabled

### Logs

_No response_

### PR DESCRIPTION
**Pull request by mrjo118**
Using the install from file option on the plugins screen of both the native app and web app, install a plugin which is not compatible with mobile, eg. https://joplinapp.org/plugins/plugin/joplin-plugin-conflict-resolution/

It is then not possible to uninstall the plugin, because clicking the plugin tile or the 'incompatible' label on the tile does not do anything, due to being in a disabled state.

This is due to a regression introduced by https://github.com/laurent22/joplin/pull/13234, which incorrectly disables the state of the CardButton when the plugin is incompatible. This PR fixes the issue by ensuring the CardButton is always enabled.

This fixes https://github.com/laurent22/joplin/issues/13825

### Testing

See video:

https://github.com/user-attachments/assets/d1407335-5c28-4d3b-8c35-e49dadefbd35

Clicking the 'incompatible' label now also works correctly

### CODE REVIEW

**Comment by personalizedrefrigerator** [comment]
Thank you for fixing this!

File: packages/app-mobile/components/screens/ConfigScreen/plugins/PluginBox/index.tsx [hunk 1]
```diff
@@ -70,7 +70,7 @@ const PluginBox: React.FC<Props> = props => {
 			style={styles.cardContainer}
 			onPress={props.onShowPluginInfo ? onPress : null}
 			testID='plugin-card'
-			disabled={!props.isCompatible}
+			disabled={false}
```
Comment (laurent22) [inline packages/app-mobile/components/screens/ConfigScreen/plugins/PluginBox/index.tsx]: Disabled is an optional property so I think we can just remove it

Comment (mrjo118) [reply packages/app-mobile/components/screens/ConfigScreen/plugins/PluginBox/index.tsx]: Done
