### PR TITLE
Android: Fixes #11292: Fix unable to sync with multiple Nextcloud accounts in different profiles

### LINKED ISSUE #11292: 2024-10-30 - Android Joplin Profiles NextCloud Issue
### Operating system

Android

### Joplin version

Joplin 3.0.8 (prod, android)

### Desktop version info

_No response_

### Current behaviour

Forked from https://discourse.joplinapp.org/t/2024-10-03-status-of-the-joplin-profiles-nextcloud-issue/41181/2?u=coffee

As has been known since September 2023, there is an issue between the Android app Joplin with multiple profiles and NextCloud.  
There have already been several Discourse dialogues and https://github.com/laurent22/joplin/issues/9283 about this.  
Thanks to roman_r_m, it now seems clear how the problem can be solved in the code of the Android Joplin app.

> I only did a quick check but it seemed that deleting cookies before every request has solved the issue. Someone still need to implement the fix properly, unfortunately I don't have the time to do it myself at this time.

https://discourse.joplinapp.org/t/nextcloud-sync-fails-on-all-but-the-default-profile/38515/18  
https://discourse.joplinapp.org/t/nextcloud-sync-fails-on-all-but-the-default-profile/38515/30

### Expected behaviour

Both profiles (A-user and B-user) can be easily connected to the same Joplin Android app. Switching between the profiles is possible without any problems.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request fixes #11292 by setting preventing React Native from storing cookies when syncing to Nextcloud (see the [React Native issue](https://github.com/facebook/react-native/issues/23185).

# Testing plan

1. Create two profiles, `Nextcloud 1` and `Nextcloud 2`.
2. Authenticate `Nextcloud 2` with a Nextcloud account.
3. Sync.
4. Switch to `Nextcloud 1` and set up sync with a Nextcloud account on the same domain as `Nextcloud 2`.
5. Sync.
6. Verify that sync completes successfully.
7. Switch back to `Nextcloud 2`.
8. Sync.
9. Verify that sync completes successfully.

### CODE REVIEW

File: packages/lib/WebDavApi.js [hunk 1]
```diff
@@ -378,6 +378,15 @@ class WebDavApi {
...
 		fetchOptions.ignoreTlsErrors = this.options_.ignoreTlsErrors();
+		if (shim.mobilePlatform() === 'android') {
+			// Using credentials = 'omit' prevents authentication cookies from
+			// being stored. React Native has issues related to cookie authentication:
+			// https://github.com/facebook/react-native/issues/23185
+			//
+			// Auth tokens are passed through the "Authorization" header, so
+			// these cookies should not be necessary.
+			fetchOptions.credentials = 'omit';
+		}
```
Comment (personalizedrefrigerator) [inline packages/lib/WebDavApi.js:389]: **Note**: This logic is in `WebDavApi.js`. As such, this currently affects all WebDAV sync targets.

**Comment by changemewtf** [comment]
Thank you for this fix @personalizedrefrigerator !! I owe you a beer or nonalcoholic beverage of your choice!!
