### PR TITLE
Mobile: Fixes #11028: Accessibility: Fix sidebar broken in right-to-left mode, improve screen reader accessibility

### LINKED ISSUE #8999: Android UI is misaligned for RTL languages
While helping a friend setup Joplin on their mobile I noticed the following:

Left: extra (unneeded) panel space.
Middle: notebook list (too narrow and clipped).
Right: note list (I think that in the expected width).

This is unrelated to Joplin's localization, but rather to the language settings of the Android system.

## Environment

Joplin version: 2.12.3
Platform: Android 13
OS specifics: Xiaomi Note 11 / Galaxy S20

## Steps to reproduce

1. Change the Android display language to a RTL language.
2. Open Joplin.
3. Open the notebook list panel (the button will appear *on the right hand side* instead of the left).

### LINKED ISSUE #11028: Problem with the three lines that contain side options.
### Operating system

Android

### Joplin version

3.0.8

### Desktop version info

_No response_

### Current behaviour

When I click on the three lines in the top corner of the app, the sidebar appears wrong and overlapping, and I tried changing the language and it did not solve the problem.

### Expected behaviour

When you press the three lines in the upper corner of the app, the sidebar is supposed to appear covering part of the screen, but the text appears incorrectly and follows the dragging motion when the menu appears to the right. And it does not appear at the beginning of the menu on the left.

### Logs

[mobile-log.log](https://github.com/user-attachments/files/16967497/mobile-log.log)

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request replaces the unmaintained [`react-native-side-menu-updated`](https://github.com/alessiocancian/react-native-side-menu) with a custom `SideMenu` with a similar implementation: Both use React Native's [`Aniamted`](https://reactnative.dev/docs/animated) and [`PanResponder`](https://reactnative.dev/docs/panresponder).

This fixes several issues:
- Missing accessibility label for the side menu close overlay.
- Workarounds were needed to prevent side menu content from being accessibility focusable while sidemenus were closed.
- Support for right-to-left languages.

Additionally, it fixes a recent iOS regression:
- The screen reader can't focus individual items in the sidemenu.

It should also make the sidebar better at detecting fast open/close gestures.

Resolves #11028.
Resolves #8999.
**Edit**: Related to https://github.com/laurent22/joplin/issues/11661.

# Screen recordings

## Web/Firefox

[Screencast from 2024-09-15 14-16-00.webm](https://github.com/user-attachments/assets/cb17d001-5303-4b3b-baef-105151b63d76)

## Android 13

**No TalkBack**:

https://github.com/user-attachments/assets/ff6d9f58-300d-4b89-baad-4689e5de125f

**With TalkBack**:

https://github.com/user-attachments/assets/b5b8ec6f-fe73-4a86-a2ca-efc8ef85c7de

## iOS 17 (simulator)

https://github.com/user-attachments/assets/6a87a333-1a65-4340-8d5f-52a314dadaee

## iOS (simulator, reduce motion)

https://github.com/user-attachments/assets/99081755-5674-48ce-a0f9-e0467b1c9720

## iOS (simulator, right-to-left layout)

**Portrait**:

https://github.com/user-attachments/assets/ef7bba2c-3daf-4478-8798-c42950666cf1

**Landscape**:

https://github.com/user-attachments/assets/ab3f01de-1c97-427f-99b0-c463274ea3ce

Observe that there are still issues in landscape mode on iOS devices with a notch &mdash; the sidemenu can be partially covered by the notch. This, however, seems better than before (see recordings under "Compare with before").

<details><summary>Compare with before</summary>

https://github.com/user-attachments/assets/89c6f8ed-ad63-4ecb-8491-b65fbef18c89

https://github.com/user-attachments/assets/b7580f7c-c3d3-444b-a66a-165a9ba0b8a8

</details>

## iOS (simulator, VoiceOver enabled)

https://github.com/user-attachments/assets/e946966b-d361-4eee-a39f-61baace4fd9f

### CODE REVIEW

File: packages/app-mobile/utils/appDefaultState.ts [hunk 1]
```diff
@@ -11,7 +11,6 @@ export const DEFAULT_ROUTE = {
 const appDefaultState: AppState = {
 	smartFilterId: undefined,
 	...defaultState,
-	sideMenuOpenPercent: 0,
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/utils/appDefaultState.ts:14]: The `sideMenuOpenPercent` state was previously unused (only usage commented out).

File: packages/app-mobile/components/side-menu-content.tsx [hunk 2]
```diff
@@ -583,34 +581,22 @@ const SideMenuContentComponent = (props: Props) => {
...
 
 	return (
-		<AccessibleView
-			style={style}
-
-			// Accessibility, keyboard, and touch hidden.
-			inert={isHidden}
-			refocusCounter={isHidden ? undefined : 1}
-		>
+		<View style={style}>
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/side-menu-content.tsx:592]: The "hide for accessibility" and autofocus logic is now handled by `SideMenu.tsx`, so this workaround is no longer necessary.
