### PR TITLE
All: Resolves #5244: Handles OneDrive throttling responses and sets User-Agent based on Microsoft best practices

### LINKED ISSUE #5244: OneDrive throttling kills sync process
## NOTE:
Instead of forking and creating a pull request for this change, I have decided to open a discussion around the issue and my proposal fix as I have only seen indirect references to throttling issues on the Joplin Forum and nothing specific posted in the Issue Tracker. 

This is in accordance to the [CONTRIBUTING.md](https://github.com/laurent22/joplin/blob/dev/CONTRIBUTING.md#contributing-to-joplins-code) file which states: "**Before adding a new feature, ask about it in the [Github Issue Tracker](https://github.com/laurent22/joplin/issues?utf8=%E2%9C%93&q=is%3Aissue) or the [Joplin Forum](https://discourse.joplinapp.org/), or check if existing discussions exist to make sure the new functionality is desired.**"

Any thoughts/comments/confirmations that someone else has seen the same behavior would be greatly appreciated.

## Environment

Joplin version: 2.1.9
Platform: Windows 10 (also seen on Android)
OS specifics: Log data is from OS Version `10.0.17763 N/A Build 17763` (also seen on updated Windows 10 OS version `10.0.19043 N/A Build 19043` and fully patched Android device)

## Steps to reproduce

1. Have a large note collection stored on OneDrive
2. Open a fresh instance of Joplin to sync entire note collection from OneDrive.
3. If notes are sufficiently large, throttling will kill the sync process entirely.
(Note: Timestamps in this screenshot are different than the log.txt attached below. Note the sync process was exited due to a throttling error)
image

This forced failure causes the user to have to click the `Synchronise` button (potentially repeatedly if they have not waited long enough) until a sync has completed successfully.

## Describe what you expected to happen
Joplin to handle the throttling by waiting a sufficient amount of time and retrying until a success or different error.

## Logfile
[log.txt](https://github.com/laurent22/joplin/files/6879888/log.txt)

## Resolution Proposal
I propose for Joplin to retry requests until they succeed or encounter a different (non-throttling) error. 

To accomplish this task, I have updated the `handleRequestRepeat()` function in the `onedrive-api.ts` file to take in another parameter `sleep_seconds`. This parameter will default to it's current calculation to preserve functionality for all current implementations of the function. To handle throttling, we check for the error code of `activityLimitReached` and ensure the `retry-after` HTTP header is present, then use the value from the `retry-after` header to wait for that duration in seconds. I also decrement i (`i--`) to prevent increasing the retry count as this is an expected error that is assumed to succeed given an infinite amount of time. 

Note that this change will cause the Joplin client to look like the sync has stalled for possibly several minutes, I've seen upwards of 15min before OneDrive will accept a large number of requests again. Surfacing that throttling is occurring to the end user (without the user checking the dev console) seemingly requires several changes to how a "report" is generated and surfaced in the sidebar - I have left these updates out for simplicity. The sync will effectively be paused and wait for OneDrive to accept more requests to complete the sync, without any interaction from the end user.

Resources:
- [OneDrive throttling best practices](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#best-practices-to-handle-throttling)
- [HTTP Header retry-after](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After)

Proposed Changes
image

Attached below is a .txt version of the modified onedrive-api.ts for easy copy/paste testing
[onedrive-api.txt](https://github.com/laurent22/joplin/files/6879916/onedrive-api.txt)

### PR DESCRIPTION
**Pull request by alecjmaly**
# Fixes #5244 

## Note
I have created a new gulp task to generate the lib version number dynamically at build time, similar to the `compile-package-info.js` script in `/packages/app-desktop`. Please note that I have not kept the style of using a `/tools` directory and my added gulp task has been written inline within the `/packages/lib/gulpfile.js` file itself. @laurent22, Please let me know if you would like to redesign the gulp tasks to mirror the dte-desktop design (i.e. create a `/tools` within `packages/lib`) to keep code consistency, or if you prefer a different solution entirely. 

## References
- https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#best-practices-to-handle-throttling

### CODE REVIEW

File: packages/lib/onedrive-api.ts [hunk 1]
```diff
@@ -265,11 +266,12 @@ export default class OneDriveApi {
 
 		for (let i = 0; i < 5; i++) {
 			options.headers['Authorization'] = `bearer ${this.token()}`;
+			options.headers['User-Agent'] = `ISV|Joplin|Joplin/${version}`;
```
Comment (laurent22) [inline packages/lib/onedrive-api.ts:269]: I'm wondering here, should we put the lib version number or the app version number? It seems the app version would be more accurate? It can be retrieved using shim.appVersion().

Also I don't know the format of this user agent string, but shouldn't it be different for mobile/cli/desktop? Such as Joplin-Desktop, Joplin-Android, Joplin-iOS, Joplin-Cli (not sure about the format)? The platform is needed is in shim.platformName()

File: packages/lib/onedrive-api.ts [hunk 2]
```diff
@@ -265,11 +266,12 @@ export default class OneDriveApi {
...
 
-			const handleRequestRepeat = async (error: any) => {
+			const handleRequestRepeat = async (error: any, sleep_seconds: number = (i + 1) * 5) => {
```
Comment (laurent22) [inline packages/lib/onedrive-api.ts:271]: It feels weird to have variable in the default parameter (I'm surprised it even works!). Could you perhaps set it to null instead, then have in the function `sleepSeconds = sleepSeconds === null ? (i + 1) * 5 : sleepSeconds`

Also please use camelCase for the variable names, so should be "sleepSeconds"

File: packages/lib/onedrive-api.ts [hunk 3]
```diff
@@ -339,6 +341,15 @@ export default class OneDriveApi {
 
 					await handleRequestRepeat(error);
 					continue;
+				} else if (error?.code === 'activityLimitReached' && response?.headers?._headers['retry-after'][0]) {
+					// Wait for OneDrive throttling
+					// Relavent Microsoft Docs: https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#best-practices-to-handle-throttling
+					// Decrement retry count as multiple sync threads will cause repeated throttling errors - this will wait until throttling is resolved to continue, preventing a hard stop on the sync
+					i--;
```
Comment (laurent22) [inline packages/lib/onedrive-api.ts:348]: Hmm, if OneDrive keeps sending the activityLimitReached will end up in an infinite loop, although I'm not sure what else we can do about it. We can't set an upper limit I guess since on initial sync there could be many of these throttle errors.

File: packages/lib/onedrive-api.ts [hunk 4]
```diff
@@ -339,6 +341,15 @@ export default class OneDriveApi {
...
+					const sleep_seconds = response.headers._headers['retry-after'][0];
```
Comment (laurent22) [inline packages/lib/onedrive-api.ts:349]: sleepSeconds.

Could you also convert it to a number using `Number(response.headers._headers['retry-after'][0])` and perhaps also validate with `isNaN` just to be sure. If it's NaN (very unlikely), maybe just throw an error.

File: packages/lib/onedrive-api.ts [hunk 5]
```diff
@@ -339,6 +341,15 @@ export default class OneDriveApi {
...
+					logger.info(`OneDrive Throttle, sync thread sleeping for ${sleep_seconds} seconds...`);
+					await handleRequestRepeat(error, parseInt(sleep_seconds));
```
Comment (laurent22) [inline packages/lib/onedrive-api.ts:351]: parseInt is kind of broken because if you don't provide a radix it will try to guess and sometimes does it incorrectly. I think it's best to stick to `Number(string)`

File: packages/lib/onedrive-api.ts [hunk 6]
```diff
@@ -339,6 +341,15 @@ export default class OneDriveApi {
 
 					await handleRequestRepeat(error);
 					continue;
+				} else if (error?.code === 'activityLimitReached' && response?.headers?._headers['retry-after'][0]) {
+					// Wait for OneDrive throttling
+					// Relavent Microsoft Docs: https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#best-practices-to-handle-throttling
+					// Decrement retry count as multiple sync threads will cause repeated throttling errors - this will wait until throttling is resolved to continue, preventing a hard stop on the sync
+					i--;
+					const sleep_seconds = response.headers._headers['retry-after'][0];
+					logger.info(`OneDrive Throttle, sync thread sleeping for ${sleep_seconds} seconds...`);
```
Comment (laurent22) [inline packages/lib/onedrive-api.ts:350]: Makes sense to at least log it. Do you know how long they make us wait in general? As you mentioned if it takes a very long time perhaps we should display this to the user, although I'm not sure how at the moment.

**Review by laurent22 — COMMENTED** [review]
Thanks for the update. Overall it looks good.

Could you also check that the test units are working with your changes please? You would need to set the sync target to "onedrive" there:

https://github.com/laurent22/joplin/blob/6d86db3cb09e6e5f41769df4b7c19ead04a498ea/packages/lib/testing/test-utils.ts#L138

Then here it's explained how to set it up for OneDrive:

https://github.com/laurent22/joplin/blob/6d86db3cb09e6e5f41769df4b7c19ead04a498ea/packages/lib/testing/test-utils.ts#L537

The credential file should go under `~/joplin-credentials/`

Then run the tests from packages/lib using `npm test -- --runInBand`

**Comment by laurent22** [comment]
Also see CI for the linter errors.

File: packages/lib/onedrive-api.ts (hunk 2 above)
Comment (alecjmaly) [reply packages/lib/onedrive-api.ts:271]: Have defaulted the parameter to null and implemented your suggestion using the null coalescing operator:
```javascript
sleepSeconds ??= (i + 1) * 5
```

File: packages/lib/onedrive-api.ts (hunk 1 above)
Comment (alecjmaly) [reply packages/lib/onedrive-api.ts:269]: shim.appVersion() is great! I used the lib version as I didn't want to pull from another package and I honestly didn't look deep enough into shim to notice the functions being overloaded.

As for the user-agent, I'm just following the Microsoft Docs. The response returned is the same for all platforms so I don't think the user-agent being the same is an issue for OneDrive API requests. Unless you can think of a reason we should delineate between the apps?

**Source**
- https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#how-to-decorate-your-http-traffic-to-avoid-throttling

image

The documentation is a bit strange, this article (above) is written for SharePoint but mentions OneDrive. Also, OneDrive is essentially a personal SharePoint site and operates under the [same api](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/?view=odsp-graph-online). So we are trying to connect the dots and assume this change should help with the OneDrive throttling as well.

File: packages/lib/onedrive-api.ts (hunk 3 above)
Comment (alecjmaly) [reply packages/lib/onedrive-api.ts:348]: Indeed, I feel weird about this also. As I mentioned before, I assume given unlimited time/retries that the request will either succeed or result in a different error code which will then be handled normally. 

If you want to implement a failsafe we can try to think of an alternative. I tested with 20 threads and would get errors because they all would keep retrying but since there were multiple threads it kind of dragged the throttling longer for some threads which then exceeded the current 5 retry count and killed the sync completely.

File: packages/lib/onedrive-api.ts (hunk 4 above)
Comment (alecjmaly) [reply packages/lib/onedrive-api.ts:349]: Converted to Number when passing to function and test for isNaN() in if statement

```javascript
else if (error?.code === 'activityLimitReached' && response?.headers?._headers['retry-after'][0] && !isNaN(Number(response?.headers?._headers['retry-after'][0]))) {
  // Wait for OneDrive throttling
  // Relavent Microsoft Docs: https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#best-practices-to-handle-throttling
  // Decrement retry count as multiple sync threads will cause repeated throttling errors - this will wait until throttling is resolved to continue, preventing a hard stop on the sync
  i--;
  const sleepSeconds = response.headers._headers['retry-after'][0];
  logger.info(`OneDrive Throttle, sync thread sleeping for ${sleepSeconds} seconds...`);
  await handleRequestRepeat(error, Number(sleepSeconds));
  continue;
  }
```

File: packages/lib/onedrive-api.ts (hunk 6 above)
Comment (alecjmaly) [reply packages/lib/onedrive-api.ts:350]: I tested with a very aggressive 20 "max concurrent connections". 
It took about 15min before the bulk download could resume. 

The typical 'retry-count' header maxes around 5min, but with 20 threads it seemed to drag on. Essentially, you end up with 20 threads retrying every `retry-count HTTP header` seconds. If it fails due to throttling, that request still counts against your request quota and increases the duration of throttling. 

Less threads will not have such large wait times, I would imagine.

Unfortunately, as far as I can tell, Microsoft doesn't explicitly say what the limits are, so it's hard to say for certian.

As pointed out by another contributor, the batch endpoint would be a great enhancement, however, it would take a bit of a refactor.

File: packages/lib/onedrive-api.ts (hunk 1 above)
Comment (laurent22) [reply packages/lib/onedrive-api.ts:269]: Yes your user-agent is right then based on their documentation, it should be just "Joplin" as app name. And then let's used shim.appVersion for the version field then.

File: packages/lib/onedrive-api.ts (hunk 3 above)
Comment (laurent22) [reply packages/lib/onedrive-api.ts:348]: Not let's leave it as it is, and hopefully it won't be a problem. The fact that we're printing warnings to the log means we'll at least know what's happening.

**Comment by alecjmaly** [comment]
I have resolved linter issues, however, some tests are failing.

image


They seem to fail from the dev branch without modifications as well, I don't think any of my changes are causing these tests to fail. Do you know anything about these? 
The other failed tests are similar `services_SearchFilter > search type nonlatin` tests

**Comment by alecjmaly** [comment]
Linting errors should be resolved, implemented your suggestions and cleaned up my unused changes.
The main issue I see now is a few failing tests, which seem to fail from a clean build as well.

image

Do these tests fail for you as well? 
All failing tests are `services_SearchFilter > search type nonlatin`

The tests seem to fail on the `dev` branch as well, which I used as my base. 
Would you prefer me to base my changes on another branch?

**Comment by laurent22** [comment]
That's strange, how are you running the tests?

**Comment by alecjmaly** [comment]
> That's strange, how are you running the tests?

As you mentioned before.
`npm test -- --runInBand`

**Comment by alecjmaly** [comment]
Definitely strange that your builds are passing (or that mine are failing).

I literally just pulled from the dev branch on the Joplin repo and it fails.

image

```bash
date
git remote get-url origin
git branch
git pull
./node_modules/.bin/jest ./services/searchengine/SearchFilter.test.js -t 'should support filtering by updated date' --verbose false
``` 

I will spend some time trying to see if I can understand what's going on.
I just wanted to provide an update with proofs of what I'm seeing. 

Very odd.

**Comment by alecjmaly** [comment]
Ok, after some debugging I believe this is related to timezones.
I am in Eastern Standard Time (EST)

## Test code `packages/lib/services/searchengine/SearchFilter.test.js`
The Jest testing code inserts timestamps into the database by `Date.parse()`
Based on the [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse), this enters the record using UTC/GMT time.

image

### Results from entering records into database

image

```text
{
    title: 'I updated this on',
    body: 'May 20 2020',
    updated_time: 1589932800000,
    user_updated_time: 1589932800000,
    source: 'joplin',
    source_application: 'net.cozic.joplintest-cli',
    order: 1627489647402,
    id: 'fa82bbf3ee484623a82ced0fbfda7e68',
    created_time: 1627489647402,
    user_created_time: 1627489647402,
    type_: 1
}
```


### `engine.search()`
image

Note that engine.search() will eventually build a sql query from `formatLocalToMs()` in `packages/lib/time.ts` using `moment.js`

image

Note that moment.js [defaults to local time](https://momentjs.com/timezone/docs/#/using-timezones/default-timezone/).

image


This results in the following query:

```text
query = "
    SELECT
    notes.id,
    notes.title,

    notes.user_created_time,
    notes.user_updated_time,
    notes.is_todo,
    notes.todo_completed,
    notes.parent_id
    FROM notes
    WHERE 1 
    AND (  ROWID IN (
        SELECT ROWID
        FROM notes
        WHERE notes.user_updated_time >= ?
    ))
"


params = "1589947200000"
```

# Timestamp Differences

## real datetime (inserted by `Date.parse()` (utc/gmt):
1589932800000

image

## query generated from moment.js (EST - in my case):
1589947200000

image

## Result
Since the following is **FALSE** `(inserted timestamp) 1589932800000 >= (search query timestamp) 1589947200000` - no records are returned.

# Testing the theory

If I were to set the `Date.parse()` function to use my local timestamp, the tests succeed.

image

image


# Conclusions / Discussion

So, I'm curious, what timezone are you in?
I believe this is why my local tests fail, however, this does not explain the github CI pipeline. I would guess github is spinning up a VM somewhere in my timezone and somewhere else for yours? This is strange.

What are your thoughts on this?
I'm surprised this hasn't come up with other contributors, perhaps I'm mis-assessing the situation?

**Comment by alecjmaly** [comment]
Not sure why the checks passed now but ok...

**Comment by tessus** [comment]
Good find. These tests always fail for me too locally. I'm also in EST. Apparently the gh runners use UTC by default.

**Comment by alecjmaly** [comment]
> Good find. These tests always fail for me too locally. I'm also in EST. Apparently the gh runners use UTC by default.

Yup, that makes sense. I believe my last checks failed because I accidently committed back the onedrive tests as uncommented - the absence of a credential file lead to a failure, I bet.

As far as I can tell I'm done with updates on this, feel free to review at your leisure. Thanks for all your input thus far!

**Comment by leematos** [comment]
@alecjmaly nice find on those test failures! I was seeing the same in dev on my local in EST. <3

**Comment by laurent22** [comment]
Ok looks like we're good now, thanks for the fix @alecjmaly!
