### PR TITLE
Mobile: Fixes #10130: Improve note editor performance when quickly entering text

### LINKED ISSUE #10130: Android: Unable to use toolbar or back button for several seconds after quickly typing a few sentences.
### Operating system

Android

### Joplin version

3.0.0, 2.14.19

### Desktop version info

Android 13 (physical device, hardware keyboard), Android 12 (simulator)

### Current behaviour

To reproduce:
1. Type something quickly for at least 20 seconds (e.g. using an external keyboard)
    - How fast likely depends on how fast the device being tested on is. I'm able to reproduce this both on a physical Android device and an Android emulator.
2. Click the back arrow.
3. Observe that there is a several-second delay until the back button is activated and the note viewer is shown.

This issue also affects buttons on the markdown toolbar.

**Note**: I recall experiencing a similar issue on an Android 7 device with Joplin 2.14.

### Expected behaviour

There should not be a several second delay after typing a large amount of text and being able to use the editor buttons.

### Logs

Currently, `Note.tsx` updates `state.note` after every keystroke. This causes a rerender after every keystroke.

The log below shows that about two rerenders happen every second. I'm typing much faster than this in the editor.
```
 LOG  11:18:24: screens/Note: Update body to  T
 LOG  11:18:24: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:25: screens/Note: Update body to  Th
 LOG  11:18:25: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:25: screens/Note: Update body to  Thi
 LOG  11:18:25: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:25: screens/Note: Update body to  This
 LOG  11:18:25: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:25: screens/Note: Update body to  This
 LOG  11:18:25: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:26: screens/Note: Update body to  This i
 LOG  11:18:26: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:26: screens/Note: Update body to  This is
 LOG  11:18:26: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:26: screens/Note: Update body to  This is
 LOG  11:18:26: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:27: screens/Note: Update body to  This is a
 LOG  11:18:27: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:27: screens/Note: Update body to  This is a
 LOG  11:18:27: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:27: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.undoRedoButtonState"]
 LOG  11:18:28: screens/Note: Update body to  This is a t
 LOG  11:18:28: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:28: screens/Note: Update body to  This is a te
 LOG  11:18:28: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:28: screens/Note: Update body to  This is a tes
 LOG  11:18:28: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:28: screens/Note: Update body to  This is a test
 LOG  11:18:28: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:29: screens/Note: Update body to  This is a test
 LOG  11:18:29: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:29: screens/Note: Update body to  This is a test o
 LOG  11:18:29: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:29: screens/Note: Update body to  This is a test of
 LOG  11:18:29: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:30: screens/Note: Update body to  This is a test of
 LOG  11:18:30: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:30: screens/Note: Update body to  This is a test of a
 LOG  11:18:30: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:30: screens/Note: Update body to  This is a test of a
 LOG  11:18:30: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:30: screens/Note: Update body to  This is a test of a s
 LOG  11:18:30: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:31: screens/Note: Update body to  This is a test of a st
 LOG  11:18:31: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:31: screens/Note: Update body to  This is a test of a sta
 LOG  11:18:31: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:31: screens/Note: Update body to  This is a test of a stat
 LOG  11:18:31: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:32: screens/Note: Update body to  This is a test of a state
 LOG  11:18:32: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:32: screens/Note: Update body to  This is a test of a state-
 LOG  11:18:32: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:32: screens/Note: Update body to  This is a test of a state-r
 LOG  11:18:32: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:33: screens/Note: Update body to  This is a test of a state-re
 LOG  11:18:33: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 INFO  11:18:33: SearchEngine: Updating FTS table...
 LOG  11:18:33: screens/Note: Update body to  This is a test of a state-rel
 LOG  11:18:33: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:33: screens/Note: Update body to  This is a test of a state-rela
 LOG  11:18:33: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:33: screens/Note: Update body to  This is a test of a state-relat
 LOG  11:18:34: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:34: screens/Note: Update body to  This is a test of a state-relate
 LOG  11:18:34: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:34: screens/Note: Update body to  This is a test of a state-related
 LOG  11:18:34: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:34: screens/Note: Update body to  This is a test of a state-related
 LOG  11:18:34: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:35: screens/Note: Update body to  This is a test of a state-related b
 LOG  11:18:35: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:35: screens/Note: Update body to  This is a test of a state-related bu
 LOG  11:18:35: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:35: screens/Note: Update body to  This is a test of a state-related bug
 LOG  11:18:35: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:36: screens/Note: Update body to  This is a test of a state-related bug.
 LOG  11:18:36: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:36: screens/Note: Update body to  This is a test of a state-related bug.
 LOG  11:18:36: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:36: screens/Note: Update body to  This is a test of a state-related bug. I
 LOG  11:18:36: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:36: screens/Note: Update body to  This is a test of a state-related bug. I'
 LOG  11:18:36: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:37: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.undoRedoButtonState"]
 LOG  11:18:37: screens/Note: Update body to  This is a test of a state-related bug. I'm
 LOG  11:18:37: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:37: screens/Note: Update body to  This is a test of a state-related bug. I'm
 LOG  11:18:37: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:38: screens/Note: Update body to  This is a test of a state-related bug. I'm t
 LOG  11:18:38: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:38: screens/Note: Update body to  This is a test of a state-related bug. I'm ty
 LOG  11:18:38: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:38: screens/Note: Update body to  This is a test of a state-related bug. I'm typ
 LOG  11:18:38: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:39: screens/Note: Update body to  This is a test of a state-related bug. I'm typi
 LOG  11:18:39: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:39: screens/Note: Update body to  This is a test of a state-related bug. I'm typin
 LOG  11:18:39: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:39: screens/Note: Update body to  This is a test of a state-related bug. I'm typing
 LOG  11:18:39: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:39: screens/Note: Update body to  This is a test of a state-related bug. I'm typing
 LOG  11:18:39: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:40: screens/Note: Update body to  This is a test of a state-related bug. I'm typing q
 LOG  11:18:40: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:40: screens/Note: Update body to  This is a test of a state-related bug. I'm typing qu
 LOG  11:18:40: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:40: screens/Note: Update body to  This is a test of a state-related bug. I'm typing qui
 LOG  11:18:40: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:41: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quic
 LOG  11:18:41: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:41: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quick
 LOG  11:18:41: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:41: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickl
 LOG  11:18:41: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:41: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly
 LOG  11:18:41: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:42: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly,
 LOG  11:18:42: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:42: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly,
 LOG  11:18:42: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:42: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, b
 LOG  11:18:42: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:43: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.undoRedoButtonState"]
 LOG  11:18:43: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, bu
 LOG  11:18:43: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:43: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but
 LOG  11:18:43: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:43: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but
 LOG  11:18:43: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:44: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but t
 LOG  11:18:44: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:44: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but th
 LOG  11:18:44: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:44: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the
 LOG  11:18:44: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:45: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the
 LOG  11:18:45: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:45: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the l
 LOG  11:18:45: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:45: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the lo
 LOG  11:18:45: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:45: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the log
 LOG  11:18:45: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:46: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs
 LOG  11:18:46: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:46: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs
 LOG  11:18:46: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:46: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs a
 LOG  11:18:46: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:47: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs ar
 LOG  11:18:47: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:47: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are
 LOG  11:18:47: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:47: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are
 LOG  11:18:47: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:47: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are u
 LOG  11:18:47: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:48: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are up
 LOG  11:18:48: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:48: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are upd
 LOG  11:18:48: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:48: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are upda
 LOG  11:18:48: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:49: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are updat
 LOG  11:18:49: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:49: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are updati
 LOG  11:18:49: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:49: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are updatin
 LOG  11:18:49: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:50: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are updating
 LOG  11:18:50: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:50: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are updating
 LOG  11:18:50: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:50: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are updating s
 LOG  11:18:50: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:50: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are updating sl
 LOG  11:18:50: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:51: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are updating slo
 LOG  11:18:51: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:51: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are updating slow
 LOG  11:18:51: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:51: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are updating slowl
 LOG  11:18:51: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:52: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are updating slowly
 LOG  11:18:52: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 LOG  11:18:52: screens/Note: Update body to  This is a test of a state-related bug. I'm typing quickly, but the logs are updating slowly.
 LOG  11:18:52: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note"]
 INFO  11:18:52: RevisionService: maintenance: Starting...
 INFO  11:18:52: RevisionService: maintenance: Service is enabled
 LOG  11:18:52: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["props.editorFont"]
 LOG  11:18:52: models/Setting: Saving settings...
 LOG  11:18:53: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["props.editorFont"]
 LOG  11:18:53: models/Setting: Saving settings...
 LOG  11:18:53: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["props.editorFont"]
 LOG  11:18:53: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["props.editorFont"]
 LOG  11:18:53: screens/Note: Render
 LOG  componentDidUpdate. Changed keys:  ["state.note", "state.lastSavedNote"]
 LOG  11:18:54: Scheduling sync operation... 1000
 LOG  11:18:54: models/Setting: Settings have been saved.
 INFO  11:18:54: Updating items_normalized from {"id": "", "updated_time": 0}
 INFO  11:18:54: SearchEngine: Updated FTS table in 12990ms. Inserted: 1. Deleted: 0
 LOG  11:18:54: models/Setting: Settings have been saved.
```

# Notes

- This is not an issue with the plain-text editor, only with the CodeMirror-based editor.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This fixes #10130 by decreasing the frequency at which `Note.tsx` updates `state.note` based on editor events.

# Explanation

Previously, the rerender caused by updating `note.body` could take longer than the time between body updates (for example, on my tablet, when entering text with an external keyboard). This seems to have caused events to queue while waiting for rendering to complete.

Logging just before changing the content of `note.body` reveals that state can be set several seconds after actually typing the text. (See the description of #10130). As a result, this **may also fix issues raised related to the last edit not being saved** (e.g. if the user closes the app before `Note.tsx` works through the backlog of update events).

# Screen recordings

## Before

https://github.com/laurent22/joplin/assets/46334387/0d6a0ba1-e6b9-4822-83f0-dc5c783435b3

Note: The "toggle overflow" button is clicked at roughly 11s. It takes about 20s for the overflow menu to be shown.

## After

https://github.com/laurent22/joplin/assets/46334387/535ab0ac-41f6-4525-b487-e96f6b820ef0

# Testing

1. Open the editor
2. Type several sentences very quickly (or use a tool to type it quickly (e.g. `adb shell input text`)
3. Click the "toggle overflow" button
4. Verify that it takes < 1 second to show the overflow menu
5. Type several sentences very quickly
6. Click on the back arrow
7. Verify that the last typed text is saved and that the note editor opened quickl

This has been tested successfully on an Android 12 emulator.

### CODE REVIEW

File: packages/app-mobile/utils/shim-init-react.js [hunk 1]
```diff
@@ -19,7 +19,6 @@ const injectedJs = {
 	codeMirrorBundle: require('../lib/rnInjectedJs/codeMirrorBundle.bundle'),
 	svgEditorBundle: require('../lib/rnInjectedJs/svgEditorBundle.bundle'),
 	pluginBackgroundPage: require('../lib/rnInjectedJs/pluginBackgroundPage.bundle'),
-	noteBodyViewerBundle: require('../lib/rnInjectedJs/noteBodyViewerBundle.bundle'),
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/utils/shim-init-react.js:22]: Note: This change is from #10132 -- it fixes a startup issue. (Consider reviewing #10132 first).
