### PR TITLE
Mobile: Fixes #14771: Show confirmation dialog before closing tags dialog with unsaved changes

### LINKED ISSUE #14771: Mobile: Pressing the Android back button or pressing escape on a keyboard, does not close the tag association screen
### Operating system

Android

### Joplin version

3.5.9

### Desktop version info

_No response_

### Current behaviour

Reproduction steps:

1. Open a note
2. Press the kebab menu and press the tags option
3. Try to exit the screen by using the Android back button or pressing escape on a keyboard. It is not possible to do so

### Expected behaviour

The tag association screen should be dismissable by pressing the Android back button or pressing escape on a keyboard, rather than only by pressing the cancel button on the modal

### Logs

_No response_

### PR DESCRIPTION
**Pull request by zainAwan9175**
### **Description:**
**AI Assistance Disclosure**
I used AI to help identify the issue and fix some linting errors. I first wrote part of the code myself and tried to solve the problem. Then I used AI assistance to help refine the solution and remove some errors. I carefully reviewed all the code, tested the implementation on an Android device

**Problem**
Users cannot close the note tags dialog using the Android Back button or Escape key. When they press these keys, the dialog remains open. Only the Cancel button allows dismissal without saving changes, creating an inconsistent user experience and making it impossible to dismiss the dialog in certain situations.

**Solution**
I updated the NoteTagsDialog component to:

Detect when the dialog is closed using Back/Escape

Show a confirmation dialog if there are unsaved changes

Let users either discard the changes or stay and continue editing

Close the dialog normally if no changes were made

Test Plan
Manual testing on Android device:

Open a note and access the tags dialog
Make tag changes (add/remove tags)
Press Android Back button → confirmation dialog should appear
Tap "Cancel" → dialog stays open with changes intact
Press Back again and tap "OK" → dialog closes, changes discarded
### Video:

https://github.com/user-attachments/assets/e175306e-2685-471f-a465-b9f0371572b2

### CODE REVIEW

**Comment by mrjo118** [comment]
Please see comment with regards to also adding a confirmation dialog: https://github.com/laurent22/joplin/issues/14771#issuecomment-4069661993
 
Also, please read the contribution guidelines, especially regarding the AI policy, and update your PR description and title accordingly

File: packages/app-mobile/components/screens/NoteTagsDialog.tsx [hunk 1]
```diff
@@ -53,11 +55,37 @@ const NoteTagsDialogComponent: React.FC<Props> = props => {
...
+		onCancelPress();
+	}, [onCancelPress, hasUnsavedChanges]);
+
+	const modalProps = useMemo(() => {
+		return {
+			...modalPropOverrides,
+			onClose: onModalClose,
+		};
+	}, [onModalClose]);
+
```
[the remark this answers is not in the document]
Comment (personalizedrefrigerator) [reply packages/app-mobile/components/screens/NoteTagsDialog.tsx:80]: Joplin's `Modal` already passes `onClose` to React Native's `onRequestClose` prop:
https://github.com/laurent22/joplin/blob/5abd5803fb4381a55aced9af781e0a0cd18e5816/packages/app-mobile/components/Modal.tsx#L210

**Comment by zainAwan9175** [comment]
> Please see comment with regards to also adding a confirmation dialog: [#14771 (comment)](https://github.com/laurent22/joplin/issues/14771#issuecomment-4069661993)
> 
> Also, please read the contribution guidelines, especially regarding the AI policy, and update your PR description and title accordingly

Hi, I have added the confirmation dialog and updated the PR description and title. Please let me know if anything needs correction

**Comment by mrjo118** [comment]
> > Please see comment with regards to also adding a confirmation dialog: [#14771 (comment)](https://github.com/laurent22/joplin/issues/14771#issuecomment-4069661993)
> > Also, please read the contribution guidelines, especially regarding the AI policy, and update your PR description and title accordingly
> 
> Hi, I have added the confirmation dialog and updated the PR description and title. Please let me know if anything needs correction

You still have not updated the PR title in accordance to the guideline

**Comment by personalizedrefrigerator** [comment]
> Hi, I have added the confirmation dialog and updated the PR description and title.

Joplin has a [script](https://github.com/laurent22/joplin/blob/dev/packages/tools/git-changelog.ts) that parses commit titles to generate a changelog. Ideally, pull request titles should follow the format expected by the script.

**Comment by zainAwan9175** [comment]
> > Hi, I have added the confirmation dialog and updated the PR description and title.
> 
> Joplin has a [script](https://github.com/laurent22/joplin/blob/dev/packages/tools/git-changelog.ts) that parses commit titles to generate a changelog. Ideally, pull request titles should follow the format expected by the script.

Thanks for letting me know! Sorry for not following the format the first time I’ll make sure my PR titles follow the expected format going forward.

File: packages/app-mobile/components/screens/NoteTagsDialog.tsx [hunk 2]
```diff
@@ -53,11 +55,37 @@ const NoteTagsDialogComponent: React.FC<Props> = props => {
 		props.onCloseRequested?.();
 	}, [props.onCloseRequested]);
 
+	const hasUnsavedChanges = useMemo(() => {
+		return () => {
+			if (noteTags.length !== originalTags.length) return true;
+			return noteTags.some(tag => !originalTags.includes(tag)) ||
+				originalTags.some(tag => !noteTags.includes(tag));
+		};
+	}, [noteTags, originalTags]);
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/screens/NoteTagsDialog.tsx]: To make it clearer that `hasUnsavedChanges` is a callback, consider converting this to a [`useCallback`](https://react.dev/reference/react/useCallback)

**Review by personalizedrefrigerator — COMMENTED** [review]
For the most part, this looks good to me! I've tested this on web and verified that the "unsaved changes" dialog is shown when clicking outside of the tag dialog.

File: packages/app-mobile/components/screens/NoteTagsDialog.tsx (hunk 2 above)
Comment (zainAwan9175) [reply packages/app-mobile/components/screens/NoteTagsDialog.tsx]: Hi personalizedrefrigerator, thanks for the review and suggestion.
I updated the implementation to use useCallback for hasUnsavedChanges (instead of useMemo returning a callback) to make intent clearer.
I also synced the branch with the latest upstream dev and re-ran validation relevant to this change.

**Review by personalizedrefrigerator — APPROVED** [review]

**Comment by mrjo118** [comment]
@zainAwan9175 When running via the web app with this change (tested on Windows), when you press escape, the modal closes before the warning appears, which makes the warning useless. Also pressing cancel on this dialog on web, results in the UI becoming frozen.

Also, I think it would be a usability improvement to also open the warning if you press cancel while there are unsaved changes, not just when using the back button or escape

**Comment by zainAwan9175** [comment]
> @zainAwan9175 When running via the web app with this change (tested on Windows), when you press escape, the modal closes before the warning appears, which makes the warning useless. Also pressing cancel on this dialog on web, results in the UI becoming frozen.
> 
> Also, I think it would be a usability improvement to also open the warning if you press cancel while there are unsaved changes, not just when using the back button or escape

Thanks for pointing this out. I’ve opened a PR that addresses these issues, including the escape key behavior, the cancel dialog freeze, and showing the warning when pressing cancel with unsaved changes.

PR: https://github.com/laurent22/joplin/pull/14998
