### PR TITLE
Mobile: Fixes #4268: Fix downloading resource files from S3 with RN

### LINKED ISSUE #4268: Android AWS S3 sync Could not download resource. "Error: Not implemented"
Syncing on android using S3 does not download resources.

## Environment

Joplin version: 1.5.1
Platform: Android
OS specifics: Android 10 (4.14.113-user+)

## Steps to reproduce

1. Enable AWS sync on PC and sync notes with resources(.png, .svg, seems to be any file)
2. Enable AWS sync on Android and try to sync

## Describe what you expected to happen
All resources being synced without errors.

## Logfile

Joplin Bug

### PR DESCRIPTION
**Pull request by jblunck**
This fixes a problem with the S3 synchronization code using the
shim.fsDriver().writeBinaryFile() which is not implemented in
fs-driver-rn.js (React Native).

Tested with AVD Android 10.0 target.

### CODE REVIEW

**Comment by tessus** [comment]
What happens on the other clients now (desktop, cli)? Did you test the change on those platforms?

I'm asking, because I think to remember that `writeBinaryFile` was used as a fix for something else. But I could be wrong and remember it incorrectly.

**Comment by jblunck** [comment]
Yes, I've tested it with app-desktop. The existing Node implementation of `writeBinaryFile()` is just a wrapper creating a Buffer and passing it to fs-extra.

File: packages/lib/file-api-driver-amazon-s3.js [hunk 1]
```diff
@@ -219,8 +219,8 @@ class FileApiDriverAmazonS3 {
 				const filePath = options.path;
 				if (!filePath) throw new Error('get: target options.path is missing');
 
-				// TODO: check if this ever hits on RN
-				await shim.fsDriver().writeBinaryFile(filePath, output);
+				const buffer = Buffer.from(output);
+				await shim.fsDriver().writeFile(filePath, buffer.toString('base64'));
```
Comment (roman-r-m) [inline packages/lib/file-api-driver-amazon-s3.js:223]: Wouldn't this cause issues for large attachments?
Unless I'm reading it wrong, this will make Joplin to load 2 copies of the file in memory one of which is also base64 encoded.

Comment (jblunck) [reply packages/lib/file-api-driver-amazon-s3.js:223]: Yes, this isn't the right thing to do for large attachments. It is enough to attach pictures and such to notes.

Support for large attachments requires to rewrite the S3 synchronization to make use of the streams which probably also introduces another usage of RNFetchBlob for the mobile app. If that is acceptable for everyone I can do a follow-up PR to optimize this.

Comment (laurent22) [reply packages/lib/file-api-driver-amazon-s3.js:223]: Also the call to writeBinaryFile here is the right one, and how each app write this data to disk is implementation detail that should be done in the driver file. So in that case you should leave this code as it is, and modify `writeBinaryFile` in fs-driver-rn to make it do the right thing. As Roman mentioned, it would be best if you could write the data directly without converting it first to Base64. I believe rn-fetch-blob can do that.

Comment (jblunck) [reply packages/lib/file-api-driver-amazon-s3.js]: To my knowledge there is no support in RNFetchBlob or RNFS to write binary data. I've implemented `writeBinaryFile` now with the help of RNFetchBlob's FileStream API and implemented a stream Writable doing the base64 encoding. This addresses @roman-r-m 2 copies issue of having 2 copies of the file in memory.

**Comment by laurent22** [comment]
Thanks for the update @jblunck. I'm not able to test or evaluate the implementation but since it's scoped to S3 sync, and if it works for you, let's merge.
