### PR TITLE
Desktop: Fixes #4043: Update 'useMessageHandler.ts' to allow File-Links with German Umlauts 

### LINKED ISSUE #4043: File-Links with german Umlauts don't work
[Präsentation](file:///T:/...Präsentation.doc) <- nothing happens when clicking this link
[Präsentation](file:///T:/...Praesentation.doc) <- works

Drag and drop + Alt of a file with Umlauts creates a faulty link, wich also doesn't work:
[Präsentation](file:///T:/...pr%C3%A4sentation-doc)
changing the link manually by changing the symbols to an "ä" doesn't solve the issue.

## Environment

Joplin version:  1.2.6 (prod, win32)
Platform:  Win10

### PR DESCRIPTION
**Pull request by Subhra264**
### Description 
This PR fixes the issue #4043. Currently, clicking on any File-links containing German Umlauts (on platform: windows) gives an error in the console. Most likely, the issue is with electron's `shell.openExternal()`, although the issue is fixed by using the `shell.openPath()` which opens the given local file with German Umlauts(and other special characters as well like Chinese etc.) correctly.

### Manually testing
```
**Tests without umlaut:**
<h:/test.txt> not rendered as link
<file://h:/test.txt> ok
[local file](h:/test.txt) ok
[local file](file://h:/test.txt) ok

**Test with umlaut:**
<h:/test_with_umlaut_ä.txt> not rendered as link
<file://h:/test_with_umlaut_ä.txt> Working
<file://h:/test_with_umlaut_%C3%A4.txt>  Working (ä changed with %C3%A4 for UTF-8 encoding)
[local file with umlaut with file://...](file://h:/test_with_umlaut_ä.txt) Working

<https://de.wikipedia.org/wiki/Thomas_Müller> ok
[Wikipedia Thomas Müller](https://de.wikipedia.org/wiki/Thomas_Müller) ok
```
### Automated Testing
This is not done as this is just one line change and `shell.openPath(path)` opens the given path if the path is present in the local system. So, I think, the other developers would need to have the same file present in their local system in order to test.

### CODE REVIEW

File: packages/app-desktop/gui/NoteEditor/utils/useMessageHandler.ts [hunk 1]
```diff
@@ -85,8 +85,8 @@ export default function useMessageHandler(scrollWhenReady: any, setScrollWhenRea
 			}
 		} else if (urlUtils.urlProtocol(msg)) {
 			if (msg.indexOf('file://') === 0) {
-				// When using the file:// protocol, openExternal doesn't work (does nothing) with URL-encoded paths
-				require('electron').shell.openExternal(urlDecode(msg));
+				// When using the file:// protocol, openPath doesn't work (does nothing) with URL-encoded paths
+				require('electron').shell.openPath(urlDecode(msg));
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/utils/useMessageHandler.ts:89]: How do we know for sure this change didn't break something else? I seem to remember it was openPath before, then we switch to openExternal, and now back to openPath. Instead we should make sure we fully understand the problem. Why is it not possible to get it working with openExternal for example?

Comment (Subhra264) [reply packages/app-desktop/gui/NoteEditor/utils/useMessageHandler.ts:89]: > How do we know for sure this change didn't break something else?

I am quite confident because here `openPath` is used only if the link is actually a file path.  And `openPath`  efficiently handles file paths/URLs ( as it is built for opening file paths ) containing Unicode characters. 

> I seem to remember it was openPath before, then we switch to openExternal, and now back to openPath. Instead we should make sure we fully understand the problem. 

Actually, I have tested with various files (pdfs, txt files etc.) as this code change can affect at-most only the file paths ( and nothing else ) and all the tests successfully passed.

> Why is it not possible to get it working with openExternal for example?

I strongly believe that it is an `electron` issue, also it is possible that this issue exists only on windows.

It seems that `shell.openExternal` does not work correctly with file paths containing Unicode characters. Though they made a fix for this (see https://github.com/electron/electron/issues/6302 ), it only works for URLs and not File paths ( at least on windows ).

Comment (Subhra264) [reply packages/app-desktop/gui/NoteEditor/utils/useMessageHandler.ts:89]: Again, if you check the electron code, `openPath` expects a file path of type `base::FilePath&` whereas `openExternal` expects a URL of type `GURL&`.

https://github.com/electron/electron/blob/4da01641ce50cf5a8b6f39717e4c447f89455dfa/shell/common/platform_util_win.cc#L243
Here, in the `OpenExternalOnWorkerThread` function, it returns `"Failed to open"` when the condition in the if statement is true and exactly the same message gets displayed when we try to open a file link with German Umlauts by clicking on it.

It looks like( I am not sure ), the problem is with the chromium's `url.spec()` ( see https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/url/gurl.h#104 ).

On the other hand, openPath directly passes the given file path to the `ui::win::OpenFileViaShell(full_path)` function.

Comment (laurent22) [reply packages/app-desktop/gui/NoteEditor/utils/useMessageHandler.ts:89]: Thanks for clarifying, that makes a lot of sense. I'll test on macOS too just to be sure and then we can merge.

**Comment by laurent22** [comment]
Ok I think it's good then, let's merge.

**Comment by laurent22** [comment]
@Subhra264, this change broke opening links on macOS from the rich text editor. I think it's because openPath doesn't support file:// urls on macOS, but openExternal did. This is fixed in this commit: https://github.com/laurent22/joplin/commit/e8a02c26d074a4ab5f694d7a521de78bf673ec02 When you have a moment, could you check that this fix didn't break the umlauts fix?

**Comment by Subhra264** [comment]
@laurent22 Sure, I will, but unfortunately I can test on windows only. I will let you know.

>  I think it's because openPath doesn't support file:// urls on macOS, but openExternal did.

That's really weird.

**Comment by laurent22** [comment]
Thanks that would be great. We only need testing on Windows since as far as I can see it works on macOS.

**Comment by Subhra264** [comment]
@laurent22  The test result is interesting...
When using something like this :  `[local file with umlaut with file://...](file://C:/Users/chakr/Documents/test_joplin_ä.txt)`

 it gives the following error ( I am not sure if it is my device problem, but I believe it is not ) : 
umlauts test

But interestingly, if I use `file:///`(notice the three '/' after 'file:') with the same file, it works perfectly. 

Although, removing `file:///' completely, also throws the following error on the console:
umlauts test1

But I think it's completely fine to use 'file:///' instead of 'file://'.

**Comment by laurent22** [comment]
It's puzzling that you found that your change introduced a regression, but you didn't bother fixing it.

**Comment by Subhra264** [comment]
@laurent22 
> It's puzzling that you found that your change introduced a regression, but you didn't bother fixing it.

That's just one side of the story.
1.By saying ` I am not sure if it is my device problem` in my last comment,  I really meant I was not sure (and I didn't get any response, so I had a doubt if it is really my device problem).

2.
> but you didn't bother fixing it.

Nope, not true. I did in fact and I remember that I spent almost a week to figure out why it's happening. Sadly, I couldn't come up with a solution ( again I know that there must be one fix/work-around that I was missing, but I didn't find any, at least by then). If I remove `uri2path` function, then it works well in case of windows, but you said that `file://` does not open for macos. If I add that function, then maybe it works well for macos, but not for windows for `file://`.

By the way, some information that I need to share :
Check the 'How many slashes` part of [this](https://en.wikipedia.org/wiki/File_URI_scheme) wikipedia article -

>  1.The // after the file: denotes that either a hostname or the literal term localhost will follow,[2] although this part may be omitted entirely, or may contain an empty hostname.[3]
2.The single slash between host and path denotes the start of the local-path part of the URI and must be present.[4]
3.A valid file URI must therefore begin with either file:/path (no hostname), file:///path (empty hostname), or file://hostname/path.
4.file://path (i.e. two slashes, without a hostname) is never correct, but is often used.
5.Further slashes in path separate directory names in a hierarchical system of directories and subdirectories. In this usage, the slash is a general, system-independent way of separating the parts, and in a particular host system it might be used as such in any pathname (as in Unix systems).

Carefully, check the fourth point. I have seen the `file-uri-to-path` repo README.md. In the examples part, they have clearly shown what they expect, if there are only two slashes after `file:`, then there must be a hostname( which is standard as per Wikipedia). So, here in Joplin, for windows( don't know about other platforms), the `uri2path` function only correctly parse `file:///` and not `file://` which is not a bug but is expected behavior.

**Comment by laurent22** [comment]
The fix is there: https://github.com/laurent22/joplin/commit/0e11273c45f8389060df661042426f7199b91995#diff-6653deffde2ea57871b28f3a6a7745e5d0e4c411fd2f8af3fd4a349f41b66774R109

To fix this kind of issue you either need to fix the input or change the processing to handle invalid input. In that case, I've simply changed the function so that it handles file:// links even though they are not quite valid.
