### PR TITLE
Android: Fixes #5987: Cursor hard to see in dark mode

### LINKED ISSUE #5987: Android beta editor Cursor
## Environment

Joplin version: 2.6.8
Platform: Android
OS specifics: 

## Steps to reproduce

1. Switch to dark or nord theme
2. set beta editor
3. go to the editor page and look for the cursor

## Describe what you expected to happen
I would like to see the cursor, but its to dark.

### LINKED ISSUE #6316: Code Quality: Large amount of commented-out code in `app-mobile/NoteEditor/NoteEditor.tsx`
# Summary
Currently, there is a large amount of commented-out code in [`NoteEditor.tsx`](https://github.com/laurent22/joplin/blob/1b2046f2fa719832945de73f8eedb77c8693389c/packages/app-mobile/components/NoteEditor/NoteEditor.tsx#L34). It's unclear why this is the case.

# Proposed Solutions
Let's either
 * remove this commented-out code
 * document why it is commented out
 * or uncomment it and fix it

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary
Changes CodeMirror6 cursor and selection colors in dark mode. Fixes #5987. ~~**Edit**: Fixes https://github.com/laurent22/joplin/issues/6316~~

<details><summary><b>Screenshots</b></summary>

## Before
Very faint, green selection on a dark background
Very faint cursor on a dark background

## After
Note editor showing light-grey-highlighted text
Light cursor on dark background

----

</details>

# Testing
Before testing, please run `yarn buildInjectedJs` from the `/packages/app-mobile` directory.

### CODE REVIEW

File: packages/app-mobile/components/NoteEditor/NoteEditor.tsx [hunk 1]
```diff
@@ -31,143 +32,142 @@ function fontFamilyFromSettings() {
...
+function useCss(themeId: number): string {
+	const [css, setCss] = useState('');
+
+	useEffect(() => {
+		const theme = themeStyle(themeId);
+
+		// Selection in dark mode is hard to see so make it brighter.
+		// https://discourse.joplinapp.org/t/dragging-in-dark-theme/12433/4?u=laurent
+		const selectionColorCss = theme.appearance === ThemeAppearance.Dark ?
+			`.CodeMirror-selected, div[class*=cm-selection] {
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/NoteEditor/NoteEditor.tsx]: This line is questionable. `div[class*=cm-selection]` works, but `div.cm-selection` **does not**. Similarly, `.CodeMirror-selected` doesn't work...

File: packages/app-mobile/components/NoteEditor/NoteEditor.tsx [hunk 2]
```diff
@@ -31,143 +32,142 @@ function fontFamilyFromSettings() {
...
+				background: #6b6b6b !important;
+			}` : '';
+		const monospaceFonts = [];
+		// if (Setting.value('style.editor.monospaceFontFamily')) monospaceFonts.push(`"${Setting.value('style.editor.monospaceFontFamily')}"`);
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/NoteEditor/NoteEditor.tsx]: This line was commented in the original code block that I uncommented. Is there a reason for this?

File: packages/app-mobile/components/NoteEditor/NoteEditor.tsx [hunk 3]
```diff
@@ -31,143 +32,142 @@ function fontFamilyFromSettings() {
...
+				background-color: ${theme.backgroundColor};
+				/* position: absolute !important; */
+				-webkit-box-shadow: none !important; // Some themes add a box shadow for some reason
+			}
+
+			.CodeMirror-lines {
+				/* This is used to enable the scroll-past end behaviour. The same height should */
+				/* be applied to the viewer. */
+				/* Disabled on mobile */
+				/* padding-bottom: 400px !important; */
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/NoteEditor/NoteEditor.tsx]: Another change from the above CSS. Is it worth just commenting this out? Should it be removed entirely?

File: packages/app-mobile/components/NoteEditor/NoteEditor.tsx [hunk 4]
```diff
@@ -31,143 +32,142 @@ function fontFamilyFromSettings() {
 	return [f, 'sans-serif'].join(', ');
 }
 
-// function useCss(themeId:number):string {
```
Comment (laurent22) [inline packages/app-mobile/components/NoteEditor/NoteEditor.tsx:34]: Please don't comment out the old code because then we can't know what has changed from the diff.

Comment (personalizedrefrigerator) [reply packages/app-mobile/components/NoteEditor/NoteEditor.tsx:34]: I think I uncommented that line... I can break this into two commits, though!

**Edit**: This has been broken into two commits! **Edit 2**: See https://github.com/laurent22/joplin/pull/6307/commits/30339f8ddb9f2d7ef10788950c94c1536abaebbd

Comment (laurent22) [reply packages/app-mobile/components/NoteEditor/NoteEditor.tsx:34]: Thanks, but could you put this commit in this pull request? Basically there shouldn't be any commented out code in the PR as it prevents reviewing it.

Comment (personalizedrefrigerator) [reply packages/app-mobile/components/NoteEditor/NoteEditor.tsx:34]: I'm confused... The commit should be part of this pull request.

Comment (personalizedrefrigerator) [reply packages/app-mobile/components/NoteEditor/NoteEditor.tsx:34]: Highlighted minus
Please note that this is a `-` and not a `+`.

**Comment by laurent22** [comment]
Look here: https://github.com/laurent22/joplin/pull/6307/files

There's a giant block of code that's commented out: we don't want that, so please could you remove it?

**Comment by personalizedrefrigerator** [comment]
> Look here: https://github.com/laurent22/joplin/pull/6307/files
> 
> There's a giant block of code that's commented out: we don't want that, so please could you remove it?

I did! That is most of what this PR does — uncomment a large block of code. **Edit:** See https://github.com/laurent22/joplin/issues/6316.

File: packages/app-mobile/components/NoteEditor/NoteEditor.tsx (hunk 4 above)
Comment (personalizedrefrigerator) [reply packages/app-mobile/components/NoteEditor/NoteEditor.tsx:34]: See https://github.com/laurent22/joplin/issues/6316

**Comment by laurent22** [comment]
oh, ok, I missed that. But if that was commented out, it was for a good reason. Most likely because styling is done differently - so the CSS should be modified where it currently is. Especially if all we need is the cursor colour, we aren't going to randomly restore so much code because for sure there will be regressions.

**Comment by personalizedrefrigerator** [comment]
> oh, ok, I missed that. But if that was commented out, it was for a good reason. Most likely because styling is done differently - so the CSS should be modified where it currently is. Especially if all we need is the cursor colour, we aren't going to randomly restore so much code because for sure there will be regressions.

I'm looking at the commit that added this (https://github.com/laurent22/joplin/commit/8395d5daa9df40e4415b9ce47887180fb7f04646) and not seeing a different place where we're doing styling (except directly in the HTML). 

I think the reason the function was commented out was due to the changes I needed to make in https://github.com/laurent22/joplin/pull/6307/commits/30339f8ddb9f2d7ef10788950c94c1536abaebbd .

We also want to fix the selection color (and hopefully also remove the white border around the editor on iOS).

**Comment by laurent22** [comment]
I haven't looked at that code for a long time, but I see we are passing a theme object to CodeMirror, which is then used in the `createTheme`. This is actually the proper way to style CodeMirror 6 as it gives much more control. So if there's something to change it's most likely in there. You can run `yarn run buildInjectedJs` to rebuild CodeMIrror if needed.

**Comment by laurent22** [comment]
Edit: although if you can somehow hack it with a bit of CSS (something that targets only the cursor) then it could be fine too for now. We just don't want to restore that whole CSS block.

**Comment by personalizedrefrigerator** [comment]
> I haven't looked at that code for a long time, but I see we are passing a theme object to CodeMirror, which is then used in the `createTheme`. This is actually the proper way to style CodeMirror 6 as it gives much more control. So if there's something to change it's most likely in there. You can run `yarn run buildInjectedJs` to rebuild CodeMIrror if needed.

That makes sense! I can look at that!

**Comment by personalizedrefrigerator** [comment]
> I haven't looked at that code for a long time, but I see we are passing a theme object to CodeMirror, which is then used in the `createTheme`. This is actually the proper way to style CodeMirror 6 as it gives much more control. So if there's something to change it's most likely in there. You can run `yarn run buildInjectedJs` to rebuild CodeMIrror if needed.

Thank you for the advice! I think I've done this!

File: packages/app-mobile/components/NoteEditor/CodeMirror.ts [hunk 5]
```diff
@@ -36,25 +36,56 @@ function logMessage(...msg: any[]) {
 //
 // https://github.com/codemirror/theme-one-dark/blob/main/src/one-dark.ts
 //
-// Use Safari developer tools to view the content of the CodeMirror iframe while
-// the app is running. It seems that what appears as ".ͼ1" in the CSS is the
-// equivalent of "&" in the theme object. So to target ".ͼ1.cm-focused", you'd
-// use '&.cm-focused' in the theme.
```
Comment (laurent22) [inline packages/app-mobile/components/NoteEditor/CodeMirror.ts]: Please restore this. It's difficult to work with the editor on mobile so it doesn't hurt to have some debugging info.

File: packages/app-mobile/components/NoteEditor/CodeMirror.ts [hunk 6]
```diff
@@ -36,25 +36,56 @@ function logMessage(...msg: any[]) {
...
+//
+// By default, CodeMirror prepends the editor's selector (followed by a
+// space) to each rule. If we include a "&", however, the "&" is replaced
+// instead (with no space follwing it). For example,
+//  'body & .cm-focused' -> 'body .selectorForTheEditor .cm-focused'
+//  '&.cm-focused' -> '.selectorForTheEditor.cm-focused'
+//  '.cm-focused' -> '.selectorForTheEditor .cm-focused'
+//
 const createTheme = (theme: any): Extension => {
+	const darkTheme = theme.appearance === 'dark';
```
Comment (laurent22) [inline packages/app-mobile/components/NoteEditor/CodeMirror.ts]: Please name this variable `isDarkTheme`. Because we have a variable "theme", which is the whole theme. So "darkTheme" would indicate it's the whole dark theme, when in fact it's just a boolean.

**Comment by laurent22** [comment]
Looks good, thanks for making this much needed change. I've just left two minor comments and then we can merge.

**Comment by personalizedrefrigerator** [comment]
> Looks good, thanks for making this much needed change. I've just left two minor comments and then we can merge.

Be sure to publish the comments (I don't see them yet). Thank you for reviewing this PR!

**Comment by laurent22** [comment]
> Be sure to publish the comments (I don't see them yet). Thank you for reviewing this PR!

Oh indeed I forgot to submit the review. It's done now.

File: packages/app-mobile/components/NoteEditor/CodeMirror.ts (hunk 6 above)
Comment (personalizedrefrigerator) [reply packages/app-mobile/components/NoteEditor/CodeMirror.ts]: This should be fixed!

File: packages/app-mobile/components/NoteEditor/CodeMirror.ts (hunk 5 above)
Comment (personalizedrefrigerator) [reply packages/app-mobile/components/NoteEditor/CodeMirror.ts]: This should be fixed!

**Comment by laurent22** [comment]
Ok let's merge, thanks for this very useful fix!
