### PR TITLE
Desktop: Fixes #3009: Word/character counter includes Markdown syntax and HTML tags

### LINKED ISSUE #3009: Word/character counter includes Markdown syntax and HTML tags
Joplin version: Joplin 1.0.197 (prod, darwin)
Platform: MacOS 10.15.4 (19E266)

## Description

`<br>` tags and markdown syntax elements, such `##` before a heading or `- [ ]` for checkboxes are included in word counting.

## steps to reproduce

When I open the word counter for this text:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip

<br>
<br>
<br>

ex ea commodo consequat.

- [ ] Duis aute irure dolor in reprehenderit in voluptate velit
- [ ] esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```
I get this:
Screenshot 2020-04-09 at 4 42 05 PM

when I remove syntax and tags:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip


ex ea commodo consequat.

 Duis aute irure dolor in reprehenderit in voluptate velit
 esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```
I get a different count:
Screenshot 2020-04-09 at 4 42 37 PM

## Describe what you expected to happen

The system should recognize HTML and Markdown syntax and exclude it from character/word counting.

### PR DESCRIPTION
**Pull request by RedDocMD**
Fixes #3009

Previously the **content properties** dialog would show word, line, and character count for the Markdown source. With this PR, it will show counts for both the original Markdown as well as the text after remoing the Markdown.
Screenshot from 2020-04-13 13-29-26

### CODE REVIEW

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx [hunk 1]
```diff
@@ -54,28 +93,69 @@ export default function NoteContentPropertiesDialog(props:NoteContentPropertiesD
...
+		...theme.textStyle,
+		width: controlCompColumnWidth,
+		textAlign: 'center',
+	};
+
+	const tableHeader = (
+		<tr>
+			<th style={tableHeaderStyle}></th>
+			<th style={tableHeaderStyle}>{_('Raw Source')}</th>
+			<th style={tableHeaderStyle}>{_('Markdown-stripped source')}</th>
```
Comment (tessus) [inline ElectronClient/gui/NoteContentPropertiesDialog.tsx:130]: I would use `Editor` and `Viewer` here instead. (The same terms used for the layout.)

Also, what happens, if you click `Content properties` when you are in

- editor only mode
- preview only mode
- WYSIWYG editor

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx [hunk 2]
```diff
@@ -19,30 +20,68 @@ interface KeyToLabelMap {
...
 			setCharactersNoSpace(counter.characters);
 		});
 		props.text === '' ? setLines(0) : setLines(props.text.split('\n').length);
 	}, [props.text]);
 
+	useEffect(() => {
+		const strippedText: string = removeMd(props.text, {
+			gfm: false,
+		}); // After stripping out Markdown syntax
+		if (strippedText === props.text) {
```
Comment (laurent22) [inline ElectronClient/gui/NoteContentPropertiesDialog.tsx:56]: Please remove this optimisation.

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx [hunk 3]
```diff
@@ -19,30 +20,68 @@ interface KeyToLabelMap {
...
+			setStrippedLines(lines);
+		} else {
+			Countable.count(strippedText, (counter : Counter) => {
+				setStrippedWords(counter.words);
+				setStrippedCharacters(counter.all);
+				setStrippedCharactersNoSpace(counter.characters);
+			});
+			strippedText === '' ? setStrippedLines(0) : setStrippedLines(strippedText.split('\n').length);
+		}
+	}, [props.text]);
```
Comment (laurent22) [inline ElectronClient/gui/NoteContentPropertiesDialog.tsx:69]: We need unit tests for this:
- Counting words, characters, etc. on Markdown text
- Counting words, characters, etc. on stripped text

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx [hunk 4]
```diff
@@ -54,28 +93,69 @@ export default function NoteContentPropertiesDialog(props:NoteContentPropertiesD
...
-	const createItemField = (key: string, value: number) => {
-		const labelComp = <label style={Object.assign({}, theme.textStyle, theme.controlBoxLabel)}>{keyToLabel[key]}</label>;
-		const controlComp = <div style={Object.assign({}, theme.textStyle, theme.controlBoxValue)}>{value}</div>;
+	const labelCompStyle = {
+		...theme.textStyle,
+		fontWeight: 'bold',
+		width: '10em',
+	};
+
+	const controlCompColumnWidth = '7em';
```
Comment (laurent22) [inline ElectronClient/gui/NoteContentPropertiesDialog.tsx:102]: Can we do without the hard-coded width?

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx [hunk 5]
```diff
@@ -4,6 +4,7 @@ const { _ } = require('lib/locale.js');
 const { themeStyle } = require('../theme.js');
 const DialogButtonRow = require('./DialogButtonRow.min');
 const Countable = require('countable');
+const removeMd = require('remove-markdown');
```
Comment (laurent22) [inline ElectronClient/gui/NoteContentPropertiesDialog.tsx:7]: removeMd => removeMarkdown

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx [hunk 6]
```diff
@@ -54,28 +93,69 @@ export default function NoteContentPropertiesDialog(props:NoteContentPropertiesD
...
+
+	const tableHeader = (
+		<tr>
+			<th style={tableHeaderStyle}></th>
+			<th style={tableHeaderStyle}>{_('Raw Source')}</th>
+			<th style={tableHeaderStyle}>{_('Markdown-stripped source')}</th>
+		</tr>
+	);
+
 	if (textProperties) {
```
Comment (laurent22) [inline ElectronClient/gui/NoteContentPropertiesDialog.tsx:134]: This should always be set, so please remove the conditional.

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx [hunk 7]
```diff
@@ -54,28 +93,69 @@ export default function NoteContentPropertiesDialog(props:NoteContentPropertiesD
...
 		for (const key in textProperties) {
-			if (!textProperties.hasOwnProperty(key)) continue;
-			const comp = createItemField(key, textProperties[key]);
-			textComps.push(comp);
+			if (!textProperties.hasOwnProperty(key) || !strippedTextProperties.hasOwnProperty(key)) continue;
```
Comment (laurent22) [inline ElectronClient/gui/NoteContentPropertiesDialog.tsx:136]: No needed as it's our own object.

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx [hunk 8]
```diff
@@ -19,30 +20,68 @@ interface KeyToLabelMap {
...
 			setCharacters(counter.all);
 			setCharactersNoSpace(counter.characters);
 		});
 		props.text === '' ? setLines(0) : setLines(props.text.split('\n').length);
 	}, [props.text]);
 
+	useEffect(() => {
+		const strippedText: string = removeMd(props.text, {
+			gfm: false,
+		}); // After stripping out Markdown syntax
```
Comment (laurent22) [inline ElectronClient/gui/NoteContentPropertiesDialog.tsx:55]: Please remove the comment.

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx [hunk 9]
```diff
@@ -19,30 +20,68 @@ interface KeyToLabelMap {
...
+			setStrippedCharacters(characters);
+			setStrippedCharactersNoSpace(charactersNoSpace);
+			setStrippedLines(lines);
+		} else {
+			Countable.count(strippedText, (counter : Counter) => {
+				setStrippedWords(counter.words);
+				setStrippedCharacters(counter.all);
+				setStrippedCharactersNoSpace(counter.characters);
+			});
+			strippedText === '' ? setStrippedLines(0) : setStrippedLines(strippedText.split('\n').length);
```
Comment (laurent22) [inline ElectronClient/gui/NoteContentPropertiesDialog.tsx:67]: Please encapsulate this logic in a function to avoid duplicating it (and re-use that function above).

File: package-lock.json [hunk 10]
```diff
@@ -2329,7 +2329,8 @@
         "ansi-regex": {
```
Comment (laurent22) [inline package-lock.json:2329]: Please remove this file from the commit.

File: ReactNativeClient/package-lock.json [hunk 11]
```diff
@@ -4613,7 +4613,8 @@
         },
```
Comment (laurent22) [inline ReactNativeClient/package-lock.json:4613]: Please remove this file from the commit.

File: package-lock.json (hunk 10 above)
Comment (RedDocMD) [reply package-lock.json]: Done, sorry I didn't take note of this before

File: ReactNativeClient/package-lock.json (hunk 11 above)
Comment (RedDocMD) [reply ReactNativeClient/package-lock.json]: Done, sorry I didn't take note of this before

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx (hunk 1 above)
Comment (RedDocMD) [reply ElectronClient/gui/NoteContentPropertiesDialog.tsx:130]: Changed the column headers as you instructed.
The behaviour doesn't change depending on the layout. The idea of the PR is to provide the user a better idea as to how many lines, characters he/she has typed and what actually will be shown on screen.

- Both editor and viewer:
Screenshot from 2020-04-14 18-43-06

- Only editor:
Screenshot from 2020-04-14 18-46-25


- Only preview:
Screenshot from 2020-04-14 18-49-57

As for the WYSIWYG editor, there is apparently no content properties button. So this feature as of now does not apply to the WYSIWYG editor.
Screenshot from 2020-04-14 18-53-00

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx (hunk 4 above)
Comment (RedDocMD) [reply ElectronClient/gui/NoteContentPropertiesDialog.tsx:102]: Line 99 is  actually based off `themes.js`, line 183. However, I could not use the `style.controlBoxLabel` because of the `inline-block` and the `margin-right`.

As of line 102, the width has been hardcoded to fit the hardcoded strings. However, since you mention it, I think it is not an appropriate thing considering internationalisation. After making changes in the titles as asked by @tessus, I think it looks okay with the width CSS removed and allowing the width to fit the content:
Screenshot from 2020-04-14 19-02-21

If you want me to make some other changes to the styling, please tell me.

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx (hunk 3 above)
Comment (RedDocMD) [reply ElectronClient/gui/NoteContentPropertiesDialog.tsx:69]: I am working on this. Basically, we need to ensure that both `countable` and `remove-markdowon` seperately work fine.

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx (hunk 5 above)
Comment (RedDocMD) [reply ElectronClient/gui/NoteContentPropertiesDialog.tsx]: Changed as you instructed

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx (hunk 6 above)
Comment (RedDocMD) [reply ElectronClient/gui/NoteContentPropertiesDialog.tsx]: Removed as you instructed

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx (hunk 7 above)
Comment (RedDocMD) [reply ElectronClient/gui/NoteContentPropertiesDialog.tsx]: Removed as you instructed

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx (hunk 8 above)
Comment (RedDocMD) [reply ElectronClient/gui/NoteContentPropertiesDialog.tsx]: Removed as you instructed

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx (hunk 9 above)
Comment (RedDocMD) [reply ElectronClient/gui/NoteContentPropertiesDialog.tsx]: Refactored as you instrcuted

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx (hunk 2 above)
Comment (RedDocMD) [reply ElectronClient/gui/NoteContentPropertiesDialog.tsx]: Removed as you instructed

**Comment by RedDocMD** [comment]
I have already included screenshots for the Light theme. As for the Dark theme, this is a screenshot:
Screenshot from 2020-04-14 19-50-45

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx (hunk 1 above)
Comment (tessus) [reply ElectronClient/gui/NoteContentPropertiesDialog.tsx]: Thanks for the info.

I just wanted to make sure that it still worked in all layout modes.

**Comment by laurent22** [comment]
Something's weird with this PR. It has a lot of unrelated code and I even see comments from other PR. Please could you fix so that it can be reviewed?

**Comment by RedDocMD** [comment]
Gosh, this is weird. Extra files is one thing, comments from another PR is a wholly new thing to me. Looks like there is lot to fix here!

**Comment by RedDocMD** [comment]
@laurent22, I think it is fixed now. Stupid mistake on my part. Sorry. :sweat_smile:

**Comment by RedDocMD** [comment]
@laurent22, I thing it is fixed now.A combination of mistakes on my part and some of Github's quirks had let to this. :sweat_smile:

File: ElectronClient/gui/NoteContentPropertiesDialog.tsx (hunk 3 above)
Comment (laurent22) [reply ElectronClient/gui/NoteContentPropertiesDialog.tsx:69]: Maybe you can expect this logic to utility functions so that it's easier to test.

Comment (RedDocMD) [reply ElectronClient/gui/NoteContentPropertiesDialog.tsx:44]: @laurent22, I have refactored the code you were referring to. Do I need to test for every sort of Markdown syntax in the unit test or only a specific part? Because there are quite a few Markdown elements.

Comment (RedDocMD) [reply ElectronClient/gui/NoteContentPropertiesDialog.tsx:44]: @laurent22 , I submitted the tests for the stripping of markdown.

File: CliClient/tests/markdownUtils.js [hunk 12]
```diff
@@ -66,4 +67,41 @@ describe('markdownUtils', function() {
...
+			'This is a text with bold and italicized text',
+			'link to google',
+			'This is a blockquote\n And another line',
+			'List item\nList item',
+			'List item\nList item',
+			'List item\nList item',
+			'This is some inline code',
+		];
+
+		assert(inputStrings.length ==  expectedOutputStrings.length, 'inputStrings array and expectedOutputStrings array don\'t have the same size');
```
Comment (laurent22) [inline CliClient/tests/markdownUtils.js:99]: Could you change this to `expect(inputStrings.length).toBe(expectedOutputStrings.length)` and remove the dependency to `assert`? Please also make sure to update package.json and package-lock.json. Other than that, the PR looks good so we can merge.

Comment (RedDocMD) [reply CliClient/tests/markdownUtils.js:118]: One query, if there is a dependency in the `package.json` of the project root, does it automatically install in the sub-folders as well, like for the TerminalClient and the ReactNativeClient?

Comment (RedDocMD) [reply CliClient/tests/markdownUtils.js:118]: Removed the assert dependency.

Comment (laurent22) [reply CliClient/tests/markdownUtils.js:118]: > 

One query, if there is a dependency in the package.json of the project root, does it automatically install in the sub-folders as well, like for the TerminalClient and the ReactNativeClient?

No it doesn't, the dependencies at the root are only for tooling, eslint, etc.

Comment (laurent22) [reply CliClient/tests/markdownUtils.js:118]: > Removed the assert dependency.

I mean it should be removed from here too and replace by `expect(inputStrings.length).toBe(expectedOutputStrings.length)`

**Comment by laurent22** [comment]
I think this pull request is quite close to completion (just [this small issue](https://github.com/laurent22/joplin/pull/3037#discussion_r422651332) needs to be fixed). Are you still interested in completing the pull request @RedDocMD?

**Comment by RedDocMD** [comment]
My bad, forgot all about it. :sweat_smile: 
Will do it within the next 16 hrs.

**Comment by RedDocMD** [comment]
@laurent22, I think it is ready

File: ReactNativeClient/package-lock.json [hunk 13]
```diff
@@ -3338,6 +3338,11 @@
         "parse-json": "^4.0.0"
```
Comment (laurent22) [inline ReactNativeClient/package-lock.json:3338]: Please remove from the pull request (it's only for mobile).

File: ReactNativeClient/package.json [hunk 14]
```diff
@@ -19,6 +19,7 @@
     "async-mutex": "^0.1.3",
```
Comment (laurent22) [inline ReactNativeClient/package.json:19]: Please remove this file from the pull request (it's only for mobile).

File: package-lock.json [hunk 15]
```diff
@@ -1391,6 +1391,11 @@
         }
```
Comment (laurent22) [inline package-lock.json:1391]: Please remove this file from the pull request (doesn't apply to desktop app).

**Comment by RedDocMD** [comment]
The ReactNativeClient has the modules in its `package.json` because `lib/string-utils.js` and `lib/markdownUtils.js` need it.  Am I wrong about this?

I had included them also for the CLI Client but I guess that is not necessary.

Btw, the Electron app refuses to start up on running `npm start`, and the console complains that a module named `color` is missing? Why is this happening?

**Comment by RedDocMD** [comment]
@laurent22, made the updates you instructed

**Comment by laurent22** [comment]
No you're right, it should have been part of ReactNative package too then, since it's used by stringUtils. But let's merge and I'll fix it later, thanks @RedDocMD
