### PR TITLE
Desktop: Fixes #6630: Made autoMatchBraces work on CJK characters

### LINKED ISSUE #6630: CJK parenthesis not auto-paired
## Environment

Joplin version: 2.8.8
Platform: Linux
OS specifics: Arch Linux

## Steps to reproduce

1. Enabled "Auto-pair braces, parenthesis, quotations, etc."
2. Create new note
3. Insert `（`(U+FF88)

## Describe what you expected to happen
U+FF99 is auto-paired.
This issue also occurs with U+3008, U+300A, U+300C, U+300E, U+3010, U+3014, U+3016, U+3018, and U+301A.

### PR DESCRIPTION
**Pull request by wh201906**
This fixes #6630
Passing extended braces pairs to support <> and CJK characters.(‘’“”（）《》「」『』【】〔〕〖〗〘〙〚〛)
See `edit/closebrackets.js` in https://codemirror.net/5/doc/manual.html#addons for details.

I have test these codes and they work fine, but I don't know if my code style is appropriate.

### CODE REVIEW

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx [hunk 1]
```diff
@@ -848,6 +848,11 @@ function CodeMirror(props: NoteBodyEditorProps, ref: any) {
 
 	function renderEditor() {
 
+		let matchBracesOptions: boolean | object = Setting.value('editor.autoMatchingBraces');
+		if (matchBracesOptions === true) {
+			matchBracesOptions = { override: true, pairs: '<>()[]{}\'\'""‘’“”（）《》「」『』【】〔〕〖〗〘〙〚〛' };
+		}
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx]: No need for the intermediate assignment, and that way we can make the variable const.

const matchBracesOptions = Setting.value('editor.autoMatchingBraces') ? { override: true, pairs: '<>()[]{}\'\'""‘’“”（）《》「」『』【】〔〕〖〗〘〙〚〛' } : false;

Comment (wh201906) [reply packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx]: I've fixed it in the new commit. Thanks for your review.
