### PR TITLE
Mobile: Fixes #9328: Fix new note/to-do buttons not visible on app startup in some cases

### LINKED ISSUE #9328: Mobile: New note button no longer visible in "all notes" on startup
### Operating system

iOS

### Joplin version

12.13.5

### Desktop version info

_No response_

### Current behaviour

Steps to reproduce:
1. Open the "all notes" section.
2. Close the app
3. Re-open the app

After step 3, the "new note" button is not visible, "all notes" is open.  On 12.12.3 (iOS), the "new note" button is visible and the "welcome" notebook is open.

**Edited**: Added that the app needs to be restarted.

### Expected behaviour

The "new note/todo" floating action button should be visible.

### See also

https://discourse.joplinapp.org/t/cannot-create-new-notes-in-2-13-6/33708

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

Fixes new note/to-do buttons not shown on app startup if "all notes" was the last selected note grouping.

Fixes #9328.

# Notes

This pull request adds
```diff
diff --git a/packages/app-mobile/root.tsx b/packages/app-mobile/root.tsx
index 5eb8944a2..39cf3d5df 100644
--- a/packages/app-mobile/root.tsx
+++ b/packages/app-mobile/root.tsx
@@ -317,6 +317,7 @@ const appReducer = (state = appDefaultState, action: any) => {
 
 				if ('smartFilterId' in action) {
 					newState.smartFilterId = action.smartFilterId;
+					newState.selectedSmartFilterId = action.smartFilterId;
 					newState.notesParentType = 'SmartFilter';
 				}
```

I don't think `state.smartFilterId` is being used anywhere (I think it's always `state.selectedSmartFilterId`). However, to prevent possible regressions, `newState.smartFilterId = ...` is not removed.

# Testing

1. Click on "All notes" in the notebook sidebar
2. Restart the app
3. Click on the "new note" button and create a new note
4. Press the back button
5. Delete all notebooks
6. Click on "all notes"
7. Verify that the "new note" button isn't shown

This has been successfully tested on Android 7.

### CODE REVIEW

File: packages/app-mobile/root.tsx [hunk 1]
```diff
@@ -317,6 +317,7 @@ const appReducer = (state = appDefaultState, action: any) => {
 
 				if ('smartFilterId' in action) {
 					newState.smartFilterId = action.smartFilterId;
+					newState.selectedSmartFilterId = action.smartFilterId;
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/root.tsx:320]:
```suggestion
					newState.selectedSmartFilterId = action.smartFilterId;
```

A follow-up pull request (not targeting the 2.13 branch) should remove `newState.smartFilterId = ...`.

File: packages/app-mobile/components/screens/Notes.tsx [hunk 2]
```diff
@@ -223,27 +224,43 @@ class NotesScreenComponent extends BaseScreenComponent<any> {
...
+		// active folder.
+		// If the app starts showing all notes, activeFolderId/selectedFolderId are
+		// empty or null. As such, we need a special case to show the buttons:
+		const addFolderNoteButtons = !!buttonFolderId || isAllNotes;
 		const thisComp = this;
 
 		const makeActionButtonComp = () => {
+			const getTargetFolderId = async () => {
+				if (!buttonFolderId && isAllNotes) {
+					return (await Folder.defaultFolder()).id;
```
Comment (laurent22) [inline packages/app-mobile/components/screens/Notes.tsx:241]: I think you can use the activeFolderId setting here, which would be the last selected folder

Comment (personalizedrefrigerator) [reply packages/app-mobile/components/screens/Notes.tsx:241]: The source of the missing note button issue seems to be that `activeFolderId` is either `''` or `null` on startup when opening the "all notes" screen. The note screen previously only showed the floating action button if `activeFolderId` or `selectedFolderId` were not falsey.
