### PR TITLE
Mobile: Fixes #14771: Prevent Note Tags dialog from closing before discard confirmation on web

### LINKED ISSUE #14771: Mobile: Pressing the Android back button or pressing escape on a keyboard, does not close the tag association screen
### Operating system

Android

### Joplin version

3.5.9

### Desktop version info

_No response_

### Current behaviour

Reproduction steps:

1. Open a note
2. Press the kebab menu and press the tags option
3. Try to exit the screen by using the Android back button or pressing escape on a keyboard. It is not possible to do so

### Expected behaviour

The tag association screen should be dismissable by pressing the Android back button or pressing escape on a keyboard, rather than only by pressing the cancel button on the modal

### Logs

_No response_

### PR DESCRIPTION
**Pull request by zainAwan9175**
### Problem
After PR #14777 was merged, there is a web regression in the Note Tags dialog:

Pressing Escape closes the dialog before the unsaved-changes warning is handled.
Pressing Cancel with unsaved changes can leave the UI in a broken/frozen state.
The unsaved-changes warning behavior is inconsistent between close paths.
### Solution
This PR unifies dialog close handling so all close paths use the same confirmation flow:

Escape/backdrop close on web now routes through app-controlled close logic first.
Cancel button uses the same unsaved-changes confirmation flow.
The dialog only closes when the user confirms discarding changes.
If the user cancels the warning, the Note Tags dialog remains open and usable.

### Test Plan
Manual testing on web (Windows):

Open a note and open the Tags dialog.
Add/remove tags (create unsaved changes).
Press Escape.
Verify confirmation dialog appears before Note Tags dialog closes.
In confirmation dialog, click Cancel.
Verify Note Tags dialog stays open and UI remains responsive.
Press Escape again, click OK.
Verify Note Tags dialog closes and unsaved changes are discarded.
Repeat with Cancel button in Note Tags dialog.
Verify same confirmation behavior occurs and no UI freeze.
Notes
This is a regression fix following merged PR #14777.
Behavior now matches expected usability: all close actions consistently protect unsaved changes.

### Video
[screen-capture.webm](https://github.com/user-attachments/assets/ea3353b2-908b-4b31-9b24-caf9047ee8cc)

### CODE REVIEW

**Comment by mrjo118** [comment]
Thanks for the fix, but I see you're trying to make changes to the build / pipeline config to try to make the CI pass.

Please don't change any of those, but make sure there are no test or compile errors related to your change. If none of the errors are related, it is probably an intermittent issue which you just need to wait to be resolved

**Comment by mrjo118** [comment]
Also I think you need to update your branch? For some reason the PR is showing changes already included in the original PR

**Comment by zainAwan9175** [comment]
> Also I think you need to update your branch? For some reason the PR is showing changes already included in the original PR

Thanks for flagging this.
I’ll rebase onto latest dev and clean up the branch so only the intended Note Tags dialog fix remains in the PR diff.

File: packages/lib/components/Dialog.tsx [hunk 1]
```diff
@@ -139,22 +141,22 @@ const useDialogElement = (containerDocument: Document, onCancel: undefined|OnCan
...
 		dialog.classList.add('dialog-modal-layer');
 		dialog.addEventListener('cancel', event => {
-			const canCancel = !!onCancelRef.current;
-			if (!canCancel) {
-				// Prevents [Escape] from closing the dialog. In many places, this is handled
-				// by external logic.
-				// See https://stackoverflow.com/a/61021326
-				event.preventDefault();
-			}
+			// Prevent the native dialog element from auto-closing so the app can
```
Comment (mrjo118) [inline packages/lib/components/Dialog.tsx]: I'm not sure about this. This component is used by the desktop app as well in a variety of places, so there is a risk of introducing issues in other places.

There is some web specific logic on this line:
https://github.com/laurent22/joplin/blob/acd2ef4edf10b3048e3be6c8996ddff8724facff/packages/app-mobile/components/Modal.tsx#L231

Maybe you could add a new prop to the Dialog to control this change of behavior, and set it in the logic above

Comment (zainAwan9175) [reply packages/lib/components/Dialog.tsx]: > I'm not sure about this. This component is used by the desktop app as well in a variety of places, so there is a risk of introducing issues in other places.
> 
> There is some web specific logic on this line:
> 
> https://github.com/laurent22/joplin/blob/acd2ef4edf10b3048e3be6c8996ddff8724facff/packages/app-mobile/components/Modal.tsx#L231
> 
> Maybe you could add a new prop to the Dialog to control this change of behavior, and set it in the logic above

I added a new prop please check.

File: packages/lib/components/Dialog.tsx [hunk 2]
```diff
@@ -139,22 +142,24 @@ const useDialogElement = (containerDocument: Document, onCancel: undefined|OnCan
 		const dialog = containerDocument.createElement('dialog');
 		dialog.classList.add('dialog-modal-layer');
 		dialog.addEventListener('cancel', event => {
-			const canCancel = !!onCancelRef.current;
-			if (!canCancel) {
-				// Prevents [Escape] from closing the dialog. In many places, this is handled
-				// by external logic.
-				// See https://stackoverflow.com/a/61021326
+			if (preventAutoCloseOnCancel) {
```
Comment (mrjo118) [inline packages/lib/components/Dialog.tsx:147]: This still changes the behaviour when preventAutoCloseOnCancel is false or not supplied. The logic should be exactly the same when not true (all original conditions intact), to ensure nothing is broken

Comment (zainAwan9175) [reply packages/lib/components/Dialog.tsx:147]: I’ve updated the implementation when preventAutoCloseOnCancel is false/undefined, Dialog follows the original cancel/close behavior exactly.
The new app-controlled flow is now only used when preventAutoCloseOnCancel is explicitly true (web modal path).

**Comment by mrjo118** [comment]
All good now. I've tested this on web and it works as expected, and the code paths look correct to avoid impacting desktop behaviour

**Review by mrjo118 — APPROVED** [review]
