### PR TITLE
Desktop: Fixes #13196: Fixed red close button not working on macOS 26

### LINKED ISSUE #13196: MacOS 26 RC Joplin not closing
### Operating system

macOS

### Joplin version

3.4.12

### Desktop version info

Joplin 3.4.12 (prod, darwin)

Device: darwin, Apple M4
Client ID: c8b4adad90754d659b2b86a78fa2be70
Sync Version: 3
Profile Version: 48
Keychain Supported: Yes
Alternative instance ID: -

Revision: e9a9f68

Freehand Drawing: 3.1.0

### Current behaviour

The red "X" button doesn't close Joplin, I have to force quit the app to get it to close

### Expected behaviour

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by yingli-lab**
### Summary
On macOS 26, the red close button did not close the main Joplin window.
Users had to force quit the app. This PR fixes the issue.

### Fix
- Prevent default close event and properly hide the main window.
- Handle fullscreen exit before hiding to ensure consistent behavior.

### Testing
- Verified on macOS 26 (Apple M2).
- Confirmed that the red close button now hides the app window as expected.

### Demo
Before: Clicking the red close button did not close the window (macOS 26).
After: The window now hides correctly when the red close button is clicked.

https://github.com/user-attachments/assets/3c75908b-2927-4f70-acd1-c0d6b590c6ad

Fixes #13196

### CODE REVIEW

**Comment by yingli-lab** [comment]
I have read the CLA Document and I hereby sign the CLA

File: packages/app-desktop/ElectronAppWrapper.ts [hunk 1]
```diff
@@ -68,10 +68,10 @@ export default class ElectronAppWrapper {
...
 	private updaterService_: AutoUpdaterService = null;
 	private customProtocolHandler_: CustomProtocolHandler = null;
-	private updatePollInterval_: ReturnType<typeof setTimeout>|null = null;
+	private updatePollInterval_: ReturnType<typeof setTimeout> | null = null;
 
-	private profileLocker_: FileLocker|null = null;
-	private ipcServer_: IpcServer|null = null;
+	private profileLocker_: FileLocker | null = null;
+	private ipcServer_: IpcServer | null = null;
 	private ipcStartPort_ = 2658;
```
Comment (laurent22) [inline packages/app-desktop/ElectronAppWrapper.ts:76]: Please remove all the white space changes

Comment (yingli-lab) [reply packages/app-desktop/ElectronAppWrapper.ts:76]: Thanks, I’ve removed the whitespace changes. Please let me know if anything else needs adjustment.
