### PR TITLE
Desktop: Resolves #7329: Fixes import of tasklists from enex files

### LINKED ISSUE #7329: Checklists not imported correctly from Evernote
## Environment

Joplin version: 2.8.8
Platform: Windows
OS specifics: Windows 11

## Steps to reproduce

1. Create a note in Evernote containing a Checklist
2. Export note as ENEX
3. Import note into Joplin (as MD or HTML)

Sample export as generated by Evernote:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE en-export SYSTEM "http://xml.evernote.com/pub/evernote-export4.dtd">
<en-export export-date="20221222T043818Z" application="Evernote" version="10.49.4">
  <note>
    <title>Test</title>
    <created>20221122T043758Z</created>
    <updated>20221122T043813Z</updated>
    <note-attributes>
    </note-attributes>
    <content>
      <![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note><ul style="--en-todo:true;"><li style="--en-checked:true;"><div>Test1</div></li><li style="--en-checked:false;"><div>Test2</div></li><li style="--en-checked:false;"><div>Test3</div></li></ul></en-note>      ]]>
    </content>
  </note>
</en-export>
```

## Describe what you expected to happen
Note should contain a checklist with checkboxes:
- [x] Test1
- [ ] Test2
- [ ] Test3

## What actually happens
Checklist is imported as a Bulleted LIst:
- Test1
- Test2
- Test3

### PR DESCRIPTION
**Pull request by Wartijn**
Checkboxes, which Joplin already handles correctly, and checklists. which were added more recently to Evernote. A checklists is a `ul`, with a style that indicates it's a list of checkboxes. Right now Joplin imports them as normal `ul`s, but since Evernote treats them like checkboxlists, it makes sense for Joplin to do the same.

Some more info and a small discussion can be found int the issue https://github.com/laurent22/joplin/issues/7329

It seems pretty easy to change import-enex-html-gen.js to a TS file, but I didn't do that because it looks like import-enex-md-gen could use a few changes as well, so I thought I'd do that in a separate pr.

### CODE REVIEW

File: packages/lib/import-enex-md-gen.ts [hunk 1]
```diff
@@ -35,8 +35,10 @@ interface ParserStateTag {
 	isHighlight: boolean;
 }
 
+type ListTag = 'ul' | 'ol' | 'checkboxList';
```
Comment (laurent22) [inline packages/lib/import-enex-md-gen.ts]: Please make it an enum

File: packages/lib/import-enex-md-gen.ts [hunk 2]
```diff
@@ -738,7 +740,8 @@ function enexXmlToMdArray(stream: any, resources: ResourceEntity[]): Promise<Ene
 				section.lines.push(BLOCK_OPEN);
 			} else if (isListTag(n)) {
 				section.lines.push(BLOCK_OPEN);
-				state.lists.push({ tag: n, counter: 1, startedText: false });
+				const tag = nodeAttributes?.style?.toLowerCase().includes('--en-todo:true') ? 'checkboxList' : n as ListTag;
```
Comment (laurent22) [inline packages/lib/import-enex-md-gen.ts]: There's a cssValue function - could you use this please?

File: packages/lib/import-enex-md-gen.ts [hunk 3]
```diff
@@ -750,7 +753,11 @@ function enexXmlToMdArray(stream: any, resources: ResourceEntity[]): Promise<Ene
 				container.startedText = false;
 
 				const indent = '    '.repeat(state.lists.length - 1);
-				if (container.tag === 'ul') {
+
+				if (container.tag === 'checkboxList') {
+					const x = nodeAttributes?.style?.toLowerCase().includes('--en-checked:true') ? 'X' : ' ';
```
Comment (laurent22) [inline packages/lib/import-enex-md-gen.ts]: Use cssValue()

File: packages/app-cli/tests/enex_to_md/checklist.md [hunk 4]
```diff
@@ -0,0 +1,7 @@
+- [ ] One
+
+- [X] Two
+
+- [ ] Three
+
```
Comment (laurent22) [inline packages/app-cli/tests/enex_to_md/checklist.md:6]: Is that expected this white space between the list items?

Comment (Wartijn) [reply packages/app-cli/tests/enex_to_md/checklist.md:6]: I thought it was expected behavior, since that's what's happening with the list5 test, so I assumed it was meant to import them with those blank lines for some reason. But now I see the other listX files don't have that blank space, so maybe list5 shouldn't have that either? 

I think it's a bug in the tests https://github.com/laurent22/joplin/issues/7348

Comment (laurent22) [reply packages/app-cli/tests/enex_to_md/checklist.md:6]: I don't really know. If it never came up as a bug report before I guess it's fine.

File: packages/lib/import-enex-md-gen.ts [hunk 5]
```diff
@@ -738,7 +744,9 @@ function enexXmlToMdArray(stream: any, resources: ResourceEntity[]): Promise<Ene
 				section.lines.push(BLOCK_OPEN);
 			} else if (isListTag(n)) {
 				section.lines.push(BLOCK_OPEN);
-				state.lists.push({ tag: n, counter: 1, startedText: false });
+				const isCheckboxList = cssValue(this, nodeAttributes?.style, '--en-todo') === 'true';
```
Comment (laurent22) [inline packages/lib/import-enex-md-gen.ts]: nodeAttributes is always defined (or should be) so please remove the "?"

File: packages/lib/import-enex-md-gen.ts [hunk 6]
```diff
@@ -750,7 +758,11 @@ function enexXmlToMdArray(stream: any, resources: ResourceEntity[]): Promise<Ene
 				container.startedText = false;
 
 				const indent = '    '.repeat(state.lists.length - 1);
-				if (container.tag === 'ul') {
+
+				if (container.tag === ListTag.CheckboxList) {
+					const x = cssValue(this, nodeAttributes?.style, '--en-checked') === 'true' ? 'X' : ' ';
```
Comment (laurent22) [inline packages/lib/import-enex-md-gen.ts]: Remove the "?"

File: packages/lib/import-enex-html-gen.js [hunk 7]
```diff
@@ -121,9 +122,11 @@ function enexXmlToHtml_(stream, resources) {
 					section.lines = addResourceTag(section.lines, resource, nodeAttributes);
 				}
 			} else if (tagName === 'en-todo') {
-				const nodeAttributes = attributeToLowerCase(node);
 				const checkedHtml = nodeAttributes.checked && nodeAttributes.checked.toLowerCase() === 'true' ? ' checked="checked" ' : ' ';
 				section.lines.push(`<input${checkedHtml}type="checkbox" onclick="return false;" />`);
+			} else if (tagName === 'li' && nodeAttributes?.style?.includes('--en-checked:')) {
```
Comment (laurent22) [inline packages/lib/import-enex-html-gen.js]: Remove the "?s". We need to know what data we're working with, not just assume everything's broken all the time. If something's undefined we need to know why and fix it, not just ignore it with "?".

File: packages/lib/import-enex-html-gen.js [hunk 8]
```diff
@@ -121,9 +122,11 @@ function enexXmlToHtml_(stream, resources) {
...
+				const checkedHtml = nodeAttributes.style.includes('--en-checked:true') ? ' checked="checked" ' : ' ';
```
Comment (laurent22) [inline packages/lib/import-enex-html-gen.js]: I think you can use cssValue() here as well

**Comment by laurent22** [comment]
Looks good now, thanks a lot for the fix!
