### PR TITLE
Desktop: Fixes #14079: Improve updater error message on rate limit

### LINKED ISSUE #14079: Desktop's updater can hit the GitHub API rate limits
### Operating system

macOS

### Joplin version

3.4.12

### Desktop version info

Joplin 3.4.12 (prod, darwin)

Device: darwin, Apple M4 Max
Client ID: 4c77ca5dd8b74bac9d22f6f5378b5d07
Sync Version: 3
Profile Version: 48
Keychain Supported: Yes
Alternative instance ID: -

Revision: e9a9f68

Backup: 1.4.3
Freehand Drawing: 3.1.0

### Current behaviour

The "Check for update..." logic in Joplin apparently hits the GitHub API directly, which makes it subject to the lower rate limits for unauthenticated requests. Checking for updates failed for me with this error:

```
Cannot get latest release info: {"message":"API rate limit exceeded for X.X.X.X. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

(The IP is redacted. No VPN was in use.)

Probably relevant is that I was concurrently updating a software manifest in an unrelated project and which makes use of the GitHub API, but since I had forgot to configure my GitHub token, that other process made my IP hit the rate limit.

### Expected behaviour

The UX for updater errors could be better. The error dialog is a bit stark. See attached screenshot. Maybe better wording or a clear indication that this is a temporary condition and to retry?

This is likely a rare edge case given how I triggered the rate limit but I can imagine users who are not software developers not knowing what to do with this error message.

If there is some thought on better UX, I'd be willing to submit a fix.

Image

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Ashutoshx7**
Fixes #14079

When the GitHub API rate limit is hit during an update check, users currently see the raw JSON response which isn't very helpful. This replaces it with a friendly message letting them know it's temporary and to try again later. Other HTTP errors also get a clean message now instead of a raw dump. The full response is still logged for debugging.

Added tests for both cases.

### CODE REVIEW

File: packages/app-desktop/checkForUpdates.ts [hunk 1]
```diff
@@ -29,7 +29,13 @@ async function fetchLatestReleases() {
 
 	if (!response.ok) {
 		const responseText = await response.text();
-		throw new Error(`Cannot get latest release info: ${responseText.substr(0, 500)}`);
+		logger.error(`Cannot get latest release info (${response.status}): ${responseText.substr(0, 500)}`);
+
+		if ((response.status === 403 || response.status === 429) && responseText.includes('rate limit')) {
+			throw new Error(_('Could not check for updates. The server rate limit has been exceeded — this is a temporary issue, please try again later.'));
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/checkForUpdates.ts]: Currently, this logic is duplicated in `AutoUpdateService.ts`. With this approach, future changes to the rate limit error detection logic will need to be made in two places. Would it be feasible to factor this out into a shared utility function that's used in both places?

Comment (personalizedrefrigerator) [reply packages/app-desktop/checkForUpdates.ts]: Thanks!

Comment (Ashutoshx7) [reply packages/app-desktop/checkForUpdates.ts]: +1 
like i totally agreed with you on this  this would increase the code reusability and easier to maintain

File: packages/app-desktop/utils/checkForUpdatesUtils.test.ts [hunk 2]
```diff
@@ -148,4 +148,28 @@ describe('checkForUpdates', () => {
 		});
 	});
 
+	it('should throw rate limit error for 403 with rate limit text', () => {
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/utils/checkForUpdatesUtils.test.ts]: Readability: Consider using Jest's [`test.each`](https://jestjs.io/docs/api#testeachtablename-fn-timeout) here.

File: packages/app-desktop/utils/checkForUpdatesUtils.test.ts [hunk 3]
```diff
@@ -127,7 +127,7 @@ describe('checkForUpdates', () => {
 		};
 
 		const releaseData = releaseDataWithExtension('-arm64.DMG');
-		const releaseInfo = extractVersionInfo([releaseData], 'darwin', 'arm64', false, { });
```
Comment (laurent22) [inline packages/app-desktop/utils/checkForUpdatesUtils.test.ts:130]: whitespace

File: packages/app-desktop/utils/checkForUpdatesUtils.test.ts [hunk 4]
```diff
@@ -139,7 +139,7 @@ describe('checkForUpdates', () => {
 
 		// Should not match when the extension is invalid
 		expect(
-			extractVersionInfo([releaseDataWithExtension('-arm64.dmG')], 'darwin', 'arm64', false, { }),
```
Comment (laurent22) [inline packages/app-desktop/utils/checkForUpdatesUtils.test.ts:142]: whitespace

File: packages/app-desktop/utils/checkForUpdatesUtils.ts [hunk 5]
```diff
@@ -139,3 +139,14 @@ export const extractVersionInfo = (releases: GitHubRelease[], platform: Platform
 
 	return output;
 };
+
+// Throws a user-friendly error based on the HTTP response status and body.
+// Detects rate-limit errors (403/429) with case-insensitive matching and
+// throws a specific message; otherwise throws a generic error with the status code.
```
Comment (laurent22) [inline packages/app-desktop/utils/checkForUpdatesUtils.ts]: Please remove the comment as the code is already clear enough

File: packages/app-desktop/utils/checkForUpdatesUtils.test.ts (hunk 3 above)
Comment (Ashutoshx7) [reply packages/app-desktop/utils/checkForUpdatesUtils.test.ts:130]: yup i fixed it it was present alraedy in the recent code i removed the space 
should i add those back ?

File: packages/app-desktop/utils/checkForUpdatesUtils.test.ts (hunk 4 above)
Comment (Ashutoshx7) [reply packages/app-desktop/utils/checkForUpdatesUtils.test.ts:142]: yup i fixed it it was present alraedy in the recent code i removed the space
should i add those back ?

File: packages/app-desktop/utils/checkForUpdatesUtils.ts (hunk 5 above)
Comment (Ashutoshx7) [reply packages/app-desktop/utils/checkForUpdatesUtils.ts]: removed those comments

File: packages/app-desktop/utils/checkForUpdatesUtils.test.ts (hunk 3 above)
Comment (laurent22) [reply packages/app-desktop/utils/checkForUpdatesUtils.test.ts:130]: So your change should not include changes that changes only white space so please remove this change

File: packages/app-desktop/utils/checkForUpdatesUtils.test.ts (hunk 4 above)
Comment (laurent22) [reply packages/app-desktop/utils/checkForUpdatesUtils.test.ts:142]: So your change should not include changes that changes only white space so please remove this change

Comment (Ashutoshx7) [reply packages/app-desktop/utils/checkForUpdatesUtils.test.ts:142]: done

File: packages/app-desktop/utils/checkForUpdatesUtils.test.ts (hunk 3 above)
Comment (Ashutoshx7) [reply packages/app-desktop/utils/checkForUpdatesUtils.test.ts:130]: done 
and  noted never touch any whitespace

File: packages/app-desktop/services/autoUpdater/AutoUpdaterService.test.ts [hunk 6]
```diff
@@ -79,4 +79,28 @@ describe('AutoUpdaterService', () => {
...
+		global.fetch = jest.fn(() =>
+			Promise.resolve({
+				ok: false,
+				status: 500,
+				text: () => Promise.resolve('Internal Server Error'),
+			}),
+		) as jest.Mock;
+
+		await expect(service.fetchLatestRelease(false)).rejects.toThrow('Error 500');
+	});
```
Comment (laurent22) [inline packages/app-desktop/services/autoUpdater/AutoUpdaterService.test.ts]: Please remove this, that's not really testing anything and you already have the relevant tests below
