### PR TITLE
Mobile: Fixes #8687: Hide markdown toolbar completely when low on vertical space

### LINKED ISSUE #8687: Mobile: Markdown toolbar only half visible on small-height screens
## Environment

Joplin version: 5ed3d94faa4bb6a209150dab56751649321545d5
Platform: Mobile
OS specifics: Android

## Steps to reproduce

1. Open the markdown editor
2. Switch the device to landscape mode
3. Focus the markdown editor and open the onscreen keyboard

## Screenshot
screenshot: only top of markdown toolbar is visible

## Describe what you expected to happen
The markdown toolbar (and perhaps the titlebar?) should be hidden or minimized when there is not enough vertical space.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request hides the markdown toolbar completely when the editor  is low on vertical space, rather than clipping the edge of buttons.

This should fix #8687.

### CODE REVIEW

File: packages/app-mobile/components/NoteEditor/MarkdownToolbar/Toolbar.tsx [hunk 1]
```diff
@@ -77,7 +82,7 @@ const Toolbar = (props: ToolbarProps) => {
 		mainButtons.push(toggleOverflowButton);
 		mainButtons.push(...allButtonComponents.slice(-maxButtonsEachSide));
 	} else {
-		mainButtons.push(...allButtonComponents);
+		mainButtons.push(toggleOverflowButton);
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/NoteEditor/MarkdownToolbar/Toolbar.tsx:85]: This change prevents all buttons from briefly being shown in the toolbar just after being shown again.
