### PR TITLE
Desktop: Fix note list losing focus after moving note to trash

### LINKED ISSUE #10753: Desktop: Note list loses focus after moving note to trash
### Operating system

Windows

### Joplin version

3.0.13

### Desktop version info

_No response_

### Current behaviour

1. Select a note in note list
2. Press "Delete" key
3. Note is moved to trash, the note below gets the focus
5. Navigate inside the note list by pressing "Arrow up" or "Arrow down"
6. Focus remains on the same note, the note list is scrolled instead

### Expected behaviour

The focus moves to note above (by pressing "arrow up") or below (by pressing "arrow down"), the newly focused note is displayed in the editor. Note list scrolling only occurs if required.

The current behavior makes it difficult to delete multiple notes using keyboard navigation.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by anuradha1304**
**AI Assistance Disclosure** - Used an AI tool to help navigate the codebase and understand the focus 
management pattern in NoteList2.tsx. The fix approach, code, and tests were written by me. I have reviewed everything carefully and fully understand each line.

When a note is deleted, the next note becomes visually selected but keyboard focus is lost - arrow keys stop working.

The fix adds a `useRefocusOnDeletion` hook that detects when the note count drops and calls `focusNote` on the newly selected note, using the existing `usePrevious` hook.

https://github.com/user-attachments/assets/8193b241-dc2c-4ccc-b770-872b99e91297

Fixes #10753

**Test plan**
Manual: create a few notes, delete one, press arrow keys - focus moves correctly to the next note. Also verified that focus is not stolen when the editor or title field is active.

Automated: added unit tests in `useRefocusOnDeletion.test.ts` covering deletion, no-op on addition, multi-select, and the focusedField guard.

### CODE REVIEW

**Comment by anuradha1304** [comment]
I have read the CLA Document and I hereby sign the CLA

File: packages/app-desktop/gui/NoteList/NoteList2.tsx [hunk 1]
```diff
@@ -1,363 +1,360 @@
...
+		highlightedWords: state.highlightedWords,
+		plugins: state.pluginService.plugins,
+		customCss: state.customViewerCss,
+		focusedField: state.focusedField,
+		parentFolderIsReadOnly: state.notesParentType === 'Folder' && selectedFolder ? itemIsReadOnlySync(ModelType.Folder, ItemChange.SOURCE_UNSPECIFIED, selectedFolder as ItemSlice, userId, state.shareService) : false,
+		selectedFolderInTrash: itemIsInTrash(selectedFolder),
+	};
+};
+
+export default connect(mapStateToProps)(NoteList);
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteList/NoteList2.tsx]: Not sure what happened here but as you can see the diff is the entire file, so it's not possible to review it. Please check and see what could have happened - make sure you change only the relevant code

Comment (anuradha1304) [reply packages/app-desktop/gui/NoteList/NoteList2.tsx]: yes, the diff includes the entire file - this was caused by a line ending mismatch (CRLF vs LF). I'm fixing this along with the other issues flagged and will push a clean commit shortly.

Comment (anuradha1304) [reply packages/app-desktop/gui/NoteList/NoteList2.tsx]: Hi, I've pushed an updated commit. The large diff was caused by line ending differences (CRLF vs LF) which I've fixed by resetting the file to upstream. I also added a focusedField guard so focus is only restored when the note list already owned focus, which addresses the issue raised in the review. Tests have been updated to cover this as well. Please let me know if any more changes are needed

Comment (laurent22) [reply packages/app-desktop/gui/NoteList/NoteList2.tsx]: Please have a look at the changed files, they include plenty of unrelated changes so that needs to be fixed.

Comment (anuradha1304) [reply packages/app-desktop/gui/NoteList/NoteList2.tsx]: CI failure on ubuntu-22.04 appears to be a pre-existing flaky test issue (see #11534), not related to this PR's changes. All 3 changed files are in NoteList/ only.

File: packages/app-desktop/gui/NoteList/utils/useRefocusOnDeletion.ts [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+const useRefocusOnDeletion = (
+	noteCount: number,
+	selectedNoteIds: string[],
+	focusedField: string,
+	focusNote: (noteId: string)=> void,
+) => {
+	const previousNoteCount = usePrevious(noteCount, 0);
+
+	useEffect(() => {
+		const noteWasRemoved = noteCount < previousNoteCount;
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteList/utils/useRefocusOnDeletion.ts:13]: Wouldn't this also trigger if we open a different notebook that has less notes?

Comment (anuradha1304) [reply packages/app-desktop/gui/NoteList/utils/useRefocusOnDeletion.ts:13]: yes, i checked and fixed it, added a selectedFolderId check so it only refocuses when the folder hasn't changed. Added a test for this case.

File: packages/app-desktop/gui/NoteList/utils/useRefocusOnDeletion.test.ts [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+		const focusNote = jest.fn();
+		const { rerender } = renderHook(
+			({ noteCount, selectedFolderId }: { noteCount: number; selectedFolderId: string }) =>
+				useRefocusOnDeletion(noteCount, ['note-1'], '', selectedFolderId, focusNote),
+			{ initialProps: { noteCount: 3, selectedFolderId: 'folder-1' } },
+		);
+		rerender({ noteCount: 2, selectedFolderId: 'folder-2' });
+		expect(focusNote).not.toHaveBeenCalled();
+	});
+});
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteList/utils/useRefocusOnDeletion.test.ts:41]: Thank you for adding the tests but there are too many of them and they all look very similar. Please refactor using test.each or remove any test that is not really needed

Comment (anuradha1304) [reply packages/app-desktop/gui/NoteList/utils/useRefocusOnDeletion.test.ts:41]: I refactored those using test.each and kept the folder-switch test separate as it re-renders with different props.

**Comment by personalizedrefrigerator** [comment]
This pull request seems to have introduced a focus-related regression (see https://github.com/laurent22/joplin/issues/15029).
