### PR TITLE
Android: Fixes #5779: Fixed android filesystem sync

### LINKED ISSUE #5779: Android filesystem sync is broken after 2.6.3 update
* * *
**Update 20 Dec 2021:** There's currently no solution to this problem. In the meantime you may downgrade to v2.5 by downloading the APK from the official repository:

https://github.com/laurent22/joplin-android/releases/download/android-v2.5.5/joplin-v2.5.5.apk
* * *

I use filesystem synchronization with path like
/storage/emulated/0/Sync/Data/Joplin

After 2.6.3 update i get this error:
Screenshot_20211124-094935

Could it be related to app permissions? I can choose only 'Allow access to media only' option in permission manager.
Screenshot_20211124-095131

### PR DESCRIPTION
**Pull request by jd1378**
Fixes #5779

Changes summary:
created a native module for working with scoped storage on android 11 and used it in this pull request.
Iswapped the deprecated "rn-fetch-blob" with "react-native-blob-util"
a quick fix to the Dropdown component throwing error and reverting its style
updated `file-api-driver-local.js` to `file-api-driver-local.ts` and handled my driver stat in it

I know my commit names not that good, I was testing a lot and needed to commit sometimes, sorry about that.
I know this is quite large, but I think it was a important fix, so I hope it is appreciated.

### CODE REVIEW

**Comment by roman-r-m** [comment]
It's not building for me:
```
➤ YN0000: [@joplin/app-mobile]: root.tsx(73,36): error TS7016: Could not find a declaration file for module '@joplin/lib/file-api-driver-local'. '/home/roman/dev/joplin/packages/app-mobile/node_modules/@joplin/lib/file-api-driver-local.js' implicitly has an 'any' type.
➤ YN0000: [@joplin/app-mobile]:   Try `npm i --save-dev @types/joplin__lib` if it exists or add a new declaration (.d.ts) file containing `declare module '@joplin/lib/file-api-driver-local';`


```

File: packages/app-mobile/utils/fs-driver-android.ts [hunk 1]
```diff
@@ -0,0 +1,190 @@
...
+			output.push({ ...stat, uri: relativePath });
+			output = await this.readUriDirStatsHandleRecursion_(stat, output, options);
+		}
+		return output;
+	}
+
+	public async move(source: string, dest: string) {
+		if (isScopedUri(source) && isScopedUri(dest)) {
+			console.warn('move not ready');
+			await this.writeFile(dest, this.readFile(source));
```
Comment (roman-r-m) [inline packages/app-mobile/utils/fs-driver-android.ts]: This reads the source file (in base64) sends it over the RN bridge to the JS process and sends back and writes to the destination.
Pretty sure this will crash the app for sufficiently large file (e.g. a resource)

**Comment by roman-r-m** [comment]
In the place where you create an Intent (somewhere in your lib) I think you also need to add `Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION` or the sync will stop working after the device is rebooted.

File: packages/app-mobile/utils/fs-driver-android.ts (hunk 1 above)
Comment (jd1378) [reply packages/app-mobile/utils/fs-driver-android.ts]: I'll update my module to do it using streams on native side when I get home

**Comment by jd1378** [comment]
I wanted to add the mentioned flag, but it seemed it doesn't take more flags than those I used for it, android studio was giving warns.
But I'll check if it is persistent across the reboot and add the mentioned flag if necessary.

**Comment by jd1378** [comment]
> It's not building for me:
> 
> ```
> ➤ YN0000: [@joplin/app-mobile]: root.tsx(73,36): error TS7016: Could not find a declaration file for module '@joplin/lib/file-api-driver-local'. '/home/roman/dev/joplin/packages/app-mobile/node_modules/@joplin/lib/file-api-driver-local.js' implicitly has an 'any' type.
> ➤ YN0000: [@joplin/app-mobile]:   Try `npm i --save-dev @types/joplin__lib` if it exists or add a new declaration (.d.ts) file containing `declare module '@joplin/lib/file-api-driver-local';`
> ```

also note that `file-api-driver-local` lives in `packages/lib`, I have symlinked my `packages/app-mobile/node_modules/@joplin/lib` to `packages/lib` to use updated files for testing

**Comment by jd1378** [comment]
I tested to see if permission persists after reboot as is and it works, so no need to add that flag as it seems the flag you have mentioned has [other use cases](https://stackoverflow.com/questions/68593433/what-is-the-use-of-intent-flag-grant-prefix-uri-permission-when-requesting-acces)

File: packages/app-mobile/utils/fs-driver-android.ts (hunk 1 above)
Comment (jd1378) [reply packages/app-mobile/utils/fs-driver-android.ts]: It's done

**Comment by jd1378** [comment]
I've finished updating, please review
thanks

**Comment by laurent22** [comment]
If you haven't already you might want to test filesystem sync. You won't be able to test Android, but you can check that you didn't accidentally break desktop sync (since code is shared). To do so, open `test-utils.ts` and set `setSyncTargetName('filesystem')` then run all the tests.

File: packages/app-mobile/utils/fs-driver-android.ts [hunk 2]
```diff
@@ -0,0 +1,187 @@
+import { ReadDirStatsOptions } from '@joplin/lib/fs-driver-base';
```
Comment (laurent22) [inline packages/app-mobile/utils/fs-driver-android.ts]: Do we really have to have a separate file for this? Couldn't you put the new code in existing fs-driver-rn.ts, but with a some conditional when there's a special case for Android? I would prefer that to having all the business logic duplicated here.

Also I'm a bit concerned about this react-native-saf-x package because nobody else is using it. Are there no existing package that handles API 30? RNFS for example?

**Comment by roman-r-m** [comment]
The build is failing but seems to be unrelated to the change:
 > ➤ YN0000: [@joplin/app-desktop]:     SET_ME constant has not been set: env

**Comment by laurent22** [comment]
Yes there was some failing tests on dev branch, which should be fixed now.

**Comment by laurent22** [comment]
Some error in the test units:

> 2022-04-12T11:53:05.7927718Z ##[error]➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-mobile]: root.tsx(73,36): error TS7016: Could not find a declaration file for module '@joplin/lib/file-api-driver-local'. '/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/@joplin/lib/file-api-driver-local.js' implicitly has an 'any' type.

File: packages/app-mobile/utils/fs-driver-android.ts (hunk 2 above)
Comment (jd1378) [reply packages/app-mobile/utils/fs-driver-android.ts]: react-native-saf-x is a package I wrote myself specifically for this use case, and I couldn't find any other packages that could handle this correctly

I'll also see if I can put the current logic inside the old driver

**Comment by jd1378** [comment]
> Some error in the test units:
> 
> > 2022-04-12T11:53:05.7927718Z ##[error]➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-mobile]: root.tsx(73,36): error TS7016: Could not find a declaration file for module '@joplin/lib/file-api-driver-local'. '/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/@joplin/lib/file-api-driver-local.js' implicitly has an 'any' type.

have you tried symlinking `packages/app-mobile/node_modules/@joplin/lib` to `packages/lib` ? because there has been change to packages/lib in this pull request

**Comment by roman-r-m** [comment]
> > Some error in the test units:
> > > 2022-04-12T11:53:05.7927718Z ##[error]➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-mobile]: root.tsx(73,36): error TS7016: Could not find a declaration file for module '@joplin/lib/file-api-driver-local'. '/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/@joplin/lib/file-api-driver-local.js' implicitly has an 'any' type.
> 
> have you tried symlinking `packages/app-mobile/node_modules/@joplin/lib` to `packages/lib` ? because there has been change to packages/lib in this pull request

It should work without any extra steps or these steps need to be included in the PR. Otherwise it'll break CI and release builds.

**Comment by jd1378** [comment]
so I have to create a pull request with changes to packages/lib first, after publishing the package with changes then create another pull request for this change?

**Comment by jd1378** [comment]
Also I tested the filesystem sync in the way you said, and it was throwing errors. I checked the dev branch and its also throwing the same errors

```
YN0000: [@joplin/lib]: Summary of all failing tests
➤ YN0000: [@joplin/lib]: FAIL ./fsDriver.test.js
➤ YN0000: [@joplin/lib]:   ● fsDriver › should resolveRelativePathWithinDir
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:     expect(received).toBe(expected) // Object.is equality
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:     Expected: "c:\\test\\temp\\my\\file.txt"
➤ YN0000: [@joplin/lib]:     Received: "f:\\test\\temp\\my\\file.txt"
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:       17 |     it('should resolveRelativePathWithinDir', async () => {
➤ YN0000: [@joplin/lib]:       18 |             const fsDriver = new FsDriverNode();
➤ YN0000: [@joplin/lib]:     > 19 |             expect(fsDriver.resolveRelativePathWithinDir('/test/temp', './my/file.txt').toLowerCase()).toBe(platformPath('/test/temp/my/file.txt'));
➤ YN0000: [@joplin/lib]:          |                                                                                                        ^      
➤ YN0000: [@joplin/lib]:       20 |             expect(fsDriver.resolveRelativePathWithinDir('/', './test').toLowerCase()).toBe(platformPath('/test'));
➤ YN0000: [@joplin/lib]:       21 |             expect(fsDriver.resolveRelativePathWithinDir('/test', 'myfile.txt').toLowerCase()).toBe(platformPath('/test/myfile.txt'));
➤ YN0000: [@joplin/lib]:       22 |             expect(fsDriver.resolveRelativePathWithinDir('/test/temp', './mydir/../test.txt').toLowerCase()).toBe(platformPath('/test/temp/test.txt'));
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:       at Suite.<anonymous> (fsDriver.test.ts:19:94)
➤ YN0000: [@joplin/lib]:       at fsDriver.test.js:31:67
➤ YN0000: [@joplin/lib]:       at Object.<anonymous>.__awaiter (fsDriver.test.js:10:10)
➤ YN0000: [@joplin/lib]:       at Object.<anonymous> (fsDriver.test.ts:17:55)
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]: FAIL services/synchronizer/Synchronizer.basics.test.js (49.698 s)
➤ YN0000: [@joplin/lib]:   ● Synchronizer.basics › should create a new Welcome notebook on each client
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:     Error: EBUSY: resource busy or locked, unlink 'F:\Projects\joplin\packages\app-cli\tests\test data\VxQtYQ75ehZ2pUHul81zWe\resources-1\3e9fd0c76b7c46c4a5a95fffab1e15f6.tmp.png'. Path: F:\Projects\joplin\packages\lib\testing/../../app-cli/tests/test data/VxQtYQ75ehZ2pUHul81zWe/resources-1/3e9fd0c76b7c46c4a5a95fffab1e15f6.tmp.png
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:       10 |             let msg = error.toString();
➤ YN0000: [@joplin/lib]:       11 |             if (path !== null) msg += `. Path: ${path}`;
➤ YN0000: [@joplin/lib]:     > 12 |             const output: any = new Error(msg);
➤ YN0000: [@joplin/lib]:          |                                 ^
➤ YN0000: [@joplin/lib]:       13 |             if (error.code) output.code = error.code;
➤ YN0000: [@joplin/lib]:       14 |             return output;
➤ YN0000: [@joplin/lib]:       15 |     }
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:       at FsDriverNode.fsErrorToJsError_ (fs-driver-node.ts:12:23)
➤ YN0000: [@joplin/lib]:       at FsDriverNode.<anonymous> (fs-driver-node.ts:47:15)
➤ YN0000: [@joplin/lib]:           at Generator.throw (<anonymous>)
➤ YN0000: [@joplin/lib]:       at rejected (fs-driver-node.js:21:32)
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:   ● Synchronizer.basics › should not wipe out user data when syncing with an empty target
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:     EBUSY: resource busy or locked, unlink 'F:\Projects\joplin\packages\app-cli\tests\test data\VxQtYQ75ehZ2pUHul81zWe\resources-1\3e9fd0c76b7c46c4a5a95fffab1e15f6.tmp.png'
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:   ● Synchronizer.basics › should not sync deletions that came via sync even when there is a conflict
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:     expect(received).toBe(expected) // Object.is equality
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:     Expected: 10
➤ YN0000: [@joplin/lib]:     Received: 0
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:       378 |            await fileApi().clearRoot(); // oops
➤ YN0000: [@joplin/lib]:       379 |            await synchronizerStart();
➤ YN0000: [@joplin/lib]:     > 380 |            expect((await Note.all()).length).toBe(10); // but since the fail-safe if on, the notes have not been deleted
➤ YN0000: [@joplin/lib]:           |                                              ^
➤ YN0000: [@joplin/lib]:       381 |
➤ YN0000: [@joplin/lib]:       382 |            Setting.setValue('sync.wipeOutFailSafe', false); // Now switch it off
➤ YN0000: [@joplin/lib]:       383 |            await synchronizerStart();
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:       at Suite.<anonymous> (services/synchronizer/Synchronizer.basics.test.ts:380:37)
➤ YN0000: [@joplin/lib]:       at fulfilled (services/synchronizer/Synchronizer.basics.test.js:13:24)
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:   ● Synchronizer.basics › should not sync deletions that came via sync even when there is a conflict
➤ YN0000: [@joplin/lib]:
➤ YN0000: [@joplin/lib]:     EBUSY: resource busy or locked, unlink 'F:\Projects\joplin\packages\app-cli\tests\test data\VxQtYQ75ehZ2pUHul81zWe\resources-1\3e9fd0c76b7c46c4a5a95fffab1e15f6.tmp.png'
```

File: packages/app-mobile/utils/fs-driver-android.ts (hunk 2 above)
Comment (laurent22) [reply packages/app-mobile/utils/fs-driver-android.ts]: In that case would it be possible to put this package in the Joplin monorepo directly (under packages/react-native-saf-x for example)? We'd prefer that for security reasons, and also so that we don't lose the source code if for example you cannot maintain it anymore.

Comment (jd1378) [reply packages/app-mobile/utils/fs-driver-android.ts]: I can duplicate the code there, but keeping both updated will take be harder for me, so I'm not sure if I will come back to update it at some point in future
I'll see if I can do that as well, but it will probably take some time

Comment (jd1378) [reply packages/app-mobile/utils/fs-driver-android.ts]: because I want the package live outside joplin, as it is useful for scoped storages overall

**Comment by jd1378** [comment]
> > > Some error in the test units:
> > > > 2022-04-12T11:53:05.7927718Z ##[error]➤ YN0000: │ root@workspace:. STDOUT ➤ YN0000: [@joplin/app-mobile]: root.tsx(73,36): error TS7016: Could not find a declaration file for module '@joplin/lib/file-api-driver-local'. '/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/@joplin/lib/file-api-driver-local.js' implicitly has an 'any' type.
> > 
> > 
> > have you tried symlinking `packages/app-mobile/node_modules/@joplin/lib` to `packages/lib` ? because there has been change to packages/lib in this pull request
> 
> It should work without any extra steps or these steps need to be included in the PR. Otherwise it'll break CI and release builds.

I just read about yarn workspaces and how they link packages together automatically. the problem was the app-mobile package.json depends on the ~2.6 version of the lib, so yarn would download it and use it instead of linking to local files.

I'm updating the deps and checking if it works

Edit: it works properly now

**Comment by jd1378** [comment]
I've moved the react-native-saf-x inside joplin packages, just cleaning up to commit in few minutes

**Comment by jd1378** [comment]
sorry it took more time than i expected due to linting issues
it should be fine now
please review again

**Comment by jd1378** [comment]
also as the app is cross platform, I don't know how it will affect ios. please check if it breaks ios when importing the saf-x module, I don't know how to ignore the import on other platforms

Edit: I tried to fix it, but still check so it wont break app

**Comment by jd1378** [comment]
ci fail was probably from an unnecessary change of using the `react-native-blob-util` instead of `rn-fetch-blob`, please run ci again

edit: actually i don't know, I guess its from moving the new module

**Comment by jd1378** [comment]
Please rerun ci, I think this should fix it

**Comment by jd1378** [comment]
is there anything left I can do to get this merged ?

**Comment by laurent22** [comment]
Are the filesystem tests working now?

**Comment by jd1378** [comment]
it throws the same errors as when I freshly cloned repo, so no new error appeared, but still thrown.

**Comment by laurent22** [comment]
Probably the test is flaky, based on that `platformPath` function. Could you comment it out please, and run it again (to see if there are other errors elsewhere).

You might want to fix the yarn.lock conflict too. Just take yarn.lock from dev, and run `yarn install` again.

**Comment by jd1378** [comment]
the test always only fails 3 tests. i have pointed them out in an earlier comment, other than that joplin/lib does not fail any test

edit: my bad, only 2 tests fail*

**Comment by jd1378** [comment]
for some reason I cannot run yarn install after using the yarn.lock from dev branch

**Comment by jd1378** [comment]
I did what you said and theres still conflict

**Comment by laurent22** [comment]
I mean to resolve the conflict, you need to do that:

- Merge dev to your branch
- Take the yarn.lock version from dev
- Run yarn install

**Comment by jd1378** [comment]
sorry i was a bit confused at first
done now

**Comment by bacteriostat** [comment]
LGTM. Local sync has been broken on Android 11+ for a long time now. Any blockers that are keeping this from merged?

File: packages/app-mobile/components/screens/ConfigScreen.tsx [hunk 3]
```diff
@@ -37,12 +39,27 @@ class ConfigScreenComponent extends BaseScreenComponent {
...
+			try {
+				const doc = await openDocumentTree(true);
+				if (doc?.uri) {
+					this.setState({ fileSystemSyncPath: doc.uri });
+					shared.updateSettingValue(this, 'sync.2.path', doc.uri);
+				} else {
+					throw new Error('User cancelled operation');
+				}
+			} catch (e) {
+				reg.logger().info(`Didn't pick sync dir: ${e}`);
```
Comment (laurent22) [inline packages/app-mobile/components/screens/ConfigScreen.tsx]: `reg.logger().info(`Didn't pick sync dir`, e);`

File: packages/app-mobile/utils/fs-driver-rn.ts [hunk 4]
```diff
@@ -26,52 +39,105 @@ export default class FsDriverRN extends FsDriverBase {
...
+			birthtime,
+			mtime,
+			isDirectory: () => stat.type ? stat.type === 'directory' : stat.isDirectory(),
 			path: path,
 			size: stat.size,
 		};
 	}
 
+	public async isDirectory(path: string): Promise<boolean> {
+		return this.stat(path).then(result => result.isDirectory());
```
Comment (laurent22) [inline packages/app-mobile/utils/fs-driver-rn.ts]: `return (await this.stat(path)). isDirectory()` (we don't use `then()`)

File: packages/app-mobile/utils/fs-driver-rn.ts [hunk 5]
```diff
@@ -131,6 +209,10 @@ export default class FsDriverRN extends FsDriverBase {
 
 	public async unlink(path: string) {
 		try {
+			if (isScopedUri(path)) {
+				await RNSAF.unlink(path);
```
Comment (laurent22) [inline packages/app-mobile/utils/fs-driver-rn.ts:213]: Did you handle the error below? i.e. if the file doesn't exist, does your lib throw an exception? And if so, it needs to be handled below - in this case it should be a noop

File: packages/lib/file-api-driver-local.ts [hunk 6]
```diff
@@ -13,11 +13,39 @@ const { basicDelta } = require('./file-api');
 // check that it is indeed the problem, check log-database.txt of both clients, search for the note ID, and most likely both notes
 // will have been modified at the same exact second at some point. If not, it's another bug that needs to be investigated.
 
-class FileApiDriverLocal {
-	fsErrorToJsError_(error, path = null) {
+// this is the format that fs-driver-rn would return
+type StdStatResult = {
```
Comment (laurent22) [inline packages/lib/file-api-driver-local.ts]: Just `Stat`

File: packages/lib/file-api-driver-local.ts [hunk 7]
```diff
@@ -13,11 +13,39 @@ const { basicDelta } = require('./file-api');
...
+	birthtime: Date; // Created date
+	mtime: Date; // Last modified date
+	isDirectory: ()=> boolean; // Is the file a directory?
+	path: string;
+	size: number; // Size in bytes
+};
+
+type MetaData = {
```
Comment (laurent22) [inline packages/lib/file-api-driver-local.ts]: That's too vague. Maybe give it no type for now (but not "any"), as I don't know what to suggest

File: packages/lib/file-api-driver-local.ts [hunk 8]
```diff
@@ -13,11 +13,39 @@ const { basicDelta } = require('./file-api');
...
+export type FileOptions = {encoding?: string} & (
+	| {
+		source: 'file';
+		path: string;
+	}| {
+		target: 'file';
+		path: string;
+	}
+);
+
```
Comment (laurent22) [inline packages/lib/file-api-driver-local.ts]: I can't read that, sorry. Please either give it no type or make it clearer what it is

File: packages/lib/file-api-driver-local.ts [hunk 9]
```diff
@@ -13,11 +13,39 @@ const { basicDelta } = require('./file-api');
...
+export class FileApiDriverLocal {
+	static fsDriver_: any;
+
+	fsErrorToJsError_(error: Error & {code?: string} , path: string | null = null) {
 		let msg = error.toString();
 		if (path !== null) msg += `. Path: ${path}`;
-		const output = new Error(msg);
+		const output = new Error(msg) as Error & {code?: string};
```
Comment (laurent22) [inline packages/lib/file-api-driver-local.ts]: no type please

File: packages/lib/file-api-driver-local.ts [hunk 10]
```diff
@@ -138,11 +165,10 @@ class FileApiDriverLocal {
 		// });
 	}
 
-	async put(path, content, options = null) {
-		if (!options) options = {};
+	async put(path: string, content: any, options: FileOptions = null) {
 
 		try {
-			if (options.source === 'file') {
+			if (options && 'source' in options && options.source === 'file') {
```
Comment (laurent22) [inline packages/lib/file-api-driver-local.ts]: please restore the previous behaviour `if (!options) options = {}` that way there's no need to check if option is defined.

File: packages/lib/file-api-driver-local.ts (hunk 7 above)
Comment (jd1378) [reply packages/lib/file-api-driver-local.ts]: im not sure what you are referring to ? 
MetaData type you mean ?
If you mean that, well it's name was already decided by `metadataFromStat_` method, so why not use it ?
maybe `StatMetaData` ? 
my opinion is to have this type rather than inlining it

File: packages/lib/file-api-driver-local.ts (hunk 8 above)
Comment (jd1378) [reply packages/lib/file-api-driver-local.ts]:
```suggestion
export type FileOptions =
{
	encoding?: string;
	path: string;
} & ({ source: 'file' } | { target: 'file' });
```

Is this more clear?
What I did was just create a type from the usage already inside the file

Comment (jd1378) [reply packages/lib/file-api-driver-local.ts]:
```suggestion
export type FileOptions =
{
	encoding?: string;
	path?: string;
	target?: 'file';
	source?: 'file';
};
```
well since I am restoring the original options, i suggest this

File: packages/lib/file-api-driver-local.ts (hunk 9 above)
Comment (jd1378) [reply packages/lib/file-api-driver-local.ts]: if I don't give it a type, I get an error when trying to set `code` property of Error object

File: packages/app-mobile/components/screens/ConfigScreen.tsx (hunk 3 above)
Comment (jd1378) [reply packages/app-mobile/components/screens/ConfigScreen.tsx]: done

File: packages/app-mobile/utils/fs-driver-rn.ts (hunk 4 above)
Comment (jd1378) [reply packages/app-mobile/utils/fs-driver-rn.ts]: done

File: packages/app-mobile/utils/fs-driver-rn.ts (hunk 5 above)
Comment (jd1378) [reply packages/app-mobile/utils/fs-driver-rn.ts:213]: done

File: packages/lib/file-api-driver-local.ts (hunk 6 above)
Comment (jd1378) [reply packages/lib/file-api-driver-local.ts]: done

File: packages/lib/file-api-driver-local.ts (hunk 10 above)
Comment (jd1378) [reply packages/lib/file-api-driver-local.ts]: done

**Comment by jd1378** [comment]
is there anything I can do ?

**Comment by laurent22** [comment]
Sorry but could you revert back the file "file-api-driver-local.ts" to ".js"? I feel it's too much work to review that refactoring and the types are not great. This is a flaw in the original JS file, and to fix it the whole thing need to be cleaned up, methods and input/output refactors with proper type definitions.

Adding them like you've done I feel doesn't improve much. Honestly I can't read any of these types, I could learn it for sure, but I just don't want the type system to be that complicated.

**Comment by jd1378** [comment]
I get what you mean, imho it would be better to have these types, rather than no types at all, then do another refactor later on
But I'll revert it

**Comment by laurent22** [comment]
Thanks. I see your point, but I feel this PR is already complex without adding a refactor on top of it. That refactor could be done later on in a separate PR if needed.

**Comment by jd1378** [comment]
```
F:\Projects\joplin\packages\lib\file-api-driver-local.js
16:1  error  Prefer default export  import/prefer-default-export
```
this is preventing me from commiting, any help ?
should i just disable it for this file ? edit: did this
edit2: this was a mistake on my side, fixed on next commit

**Comment by jd1378** [comment]
it should be fine now i think

**Comment by laurent22** [comment]
It doesn't build: https://github.com/laurent22/joplin/runs/6969905208?check_suite_focus=true#step:12:644

**Comment by jd1378** [comment]
I had forgotten to use require, I think it should build now

**Comment by jd1378** [comment]
?

**Comment by laurent22** [comment]
Ok let's merge, thanks for implementing this @jd1378!

**Comment by laurent22** [comment]
@jd1378, is filesystem sync working for you? It seems some users are still experiencing issues: https://github.com/laurent22/joplin/issues/6779

**Comment by jd1378** [comment]
I'll check it out and open another pull request when I understand whats happening and how to solve it

**Comment by laurent22** [comment]
@jd1378, since I upgraded the project to React Native 0.70, I'm getting the following error when building the Android app:

    > Task :joplin_react-native-saf-x:verifyReleaseResources FAILED
    w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

    FAILURE: Build completed with 2 failures.

    1: Task failed with an exception.
    -----------
    * What went wrong:
    Execution failed for task ':joplin_react-native-saf-x:verifyReleaseResources'.
    > A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
      > Android resource linking failed
        ERROR:packages/app-mobile/node_modules/@joplin/react-native-saf-x/android/build/intermediates/merged_res/release/values/values.xml:2722: AAPT: error: resource android:attr/lStar not found.

I can't find any clear information on how to fix this. Do you have any ideas?

**Comment by jd1378** [comment]
I have no idea, but from a quick search:
https://stackoverflow.com/questions/52613089/getting-verifyreleaseresources-error-after-upgrading-react-native
https://github.com/yamill/react-native-orientation/issues/396#issuecomment-983442090
maybe try some of these and see if it helps ?

**Comment by laurent22** [comment]
I found this and tried it but it didn't help unfortunately

**Comment by jd1378** [comment]
this could be relevant: https://stackoverflow.com/questions/69033022/message-error-resource-androidattr-lstar-not-found
still not sure if you had found this before as well
if nothing worked, I'll hop in to try fixes myself ;)

**Comment by laurent22** [comment]
It seems this error can be caused by many things and none of those apply to our particular case, although I did try several of the proposed solutions but without success

**Comment by jd1378** [comment]
okay
I'll check it today

**Comment by jd1378** [comment]
it builds for me for dev
is it broken for production builds ? because I can certainly build and launch the app

**Comment by jd1378** [comment]
my only error during build using `gradlew :app:assembleRelease` was ``Execution failed for task ':app:packageRelease'``
so it also seems to build for release properly as well
maybe clean the project and compile and build again ?

**Comment by laurent22** [comment]
`./gradlew assembleRelease` works too?

**Comment by jd1378** [comment]
> `./gradlew assembleRelease` works too?

again `Task :app:packageRelease FAILED`, didn't see the other error you mentioned

**Comment by jd1378** [comment]
maybe clone and test the build from scratch and see how it goes ?
Also I'm on windows, if still you had problem and you were on linux, tell me

**Comment by laurent22** [comment]
> maybe clone and test the build from scratch and see how it goes ?

I did that and many other random things. Eventually I fixed it by changing the SDK version to 31 4e27600f9c2183c54434e5a85f42035dac86deaf

**Comment by jd1378** [comment]
funny thing is I hit the same exact issue when I wanted to start working on it again [on my repo](https://github.com/jd1378/react-native-saf-x)
I will commit the fix along with the rewrite of the module to fix the performance issue when it's done

**Comment by laurent22** [comment]
I was thinking that maybe changing it to version 31 bypassed a cache hidden somewhere, and so it started working. But it's possible it's not the fix at all, who knows how any of that stuff works

**Comment by jd1378** [comment]
from what it seems, the release of rn 0.71 has broken the builds somehow, by updating my project partially (build tools version, api target, gradle plugins, package.json dependencies) to rn 0.70.6 fixed the problem 
I was seeing rn 0.71 AARs being downloaded during the build (I had changed nothing, just had done yarn install to download dependencies)

**Comment by kd-fs** [comment]
Let me send you a most big screenshot
Capture d’écran du 2023-01-17 13-33-56
