### PR TITLE
Desktop: Fixes #12197: Fix inserting note links using the mouse

### LINKED ISSUE #12197: (version 3.3) Note link isn't inserted when selecting link with mouse
### Operating system

Windows

### Joplin version

3.3.7

### Desktop version info

Joplin 3.3.7 (prod, win32)

Device: win32, x64
Client ID: acf44d67875e4c478d29d7d4c738fc72
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes
Alternative instance ID: -

Revision: 76a22c3

Backup: 1.4.3
Journal: 2.0.0
Note Tabs: 1.4.0
Quick Links: 1.3.2

### Current behaviour

Steps to re-create:
1. In a note, hit the note link shortcut (shift + alt + L on windows)
2. search for a note
3. select a note from the results using left click with your mouse
4. You'll see that the note link is **not** inserted at your cursor position

### Expected behaviour

When selecting a note from the search results with left click, it should insert the note link

NOTE: It does work as expected if you select the result using the keyboard (arrow key + enter)

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request fixes an inconsistency in how `GotoAnything.tsx` returns results when activated by a command.

Fixes #12197.

**Note**: This pull request targets `release-3.3`.

# Testing

This pull request includes automated tests.

Additionally, it has been tested manually by:
1. Opening a note.
2. Pressing <kbd>alt</kbd>-<kbd>shift</kbd>-<kbd>l</kbd> to open the "insert link" dialog.
3. Searching for a note.
4. Pressing <kbd>enter</kbd>.
5. Verifying that a link to the target note has been inserted.
6. Repeating steps 1-5, but selecting the result by clicking, instead of pressing enter.

### CODE REVIEW

File: packages/app-desktop/integration-tests/models/GoToAnything.ts [hunk 1]
```diff
@@ -12,15 +12,36 @@ export default class GoToAnything {
...
+
+	public async searchForWithRetry(query: string, resultLocator: Locator) {
+		// If note indexing hasn't finished, it's sometimes necessary to search multiple times.
+		// This expect.poll retries the search if it initially fails.
+		await expect.poll(async () => {
+			await this.inputLocator.clear();
+			await this.inputLocator.fill(query);
+			await expect(resultLocator).toBeVisible({ timeout: 1000 });
+			return true;
+		}, { timeout: 6000 }).toBe(true);
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/integration-tests/models/GoToAnything.ts]: This is failing in CI, but passes locally:
```
  Error: Timed out 1000ms waiting for expect(locator).toBeVisible()

    Locator: locator('.go-to-anything-dialog[open]').getByRole('option', { name: 'Target note' })
    Expected: visible
    Received: <element(s) not found>
    Call log:
      - expect.toBeVisible with timeout 1000ms
      - waiting for locator('.go-to-anything-dialog[open]').getByRole('option', { name: 'Target note' })


       at models/GoToAnything.ts:44

      42 | 			await expect(resultLocator).toBeVisible({ timeout: 1000 });
      43 | 			return true;
    > 44 | 		}, { timeout: 6000 }).toBe(true);
         | 		                      ^
      45 | 	}
      46 |
      47 | 	public async expectToBeClosed() {
        at GoToAnything.searchForWithRetry (/home/runner/work/joplin/joplin/packages/app-desktop/integration-tests/models/GoToAnything.ts:44:25)
        at /home/runner/work/joplin/joplin/packages/app-desktop/integration-tests/goToAnything.spec.ts:102:23
```

This might need a larger timeout.

Comment (personalizedrefrigerator) [reply packages/app-desktop/integration-tests/models/GoToAnything.ts]: The issue seems to have been that `expect.poll` doesn't retry if an exception is thrown. The `expect.poll` callback has been updated to return an `Error` when a search result can't be found, rather than `throw`.
