### PR TITLE
Desktop: Fixes #8743: Fix escapes breaking linkified URLs

### LINKED ISSUE #8743: Links break down when switching from the Rich Text editor to CodeMirror
Create a link in CodeMirror, for example `This is a link: https://joplinapp.org/release_cycle/`

Switch to the RTE, and make a change

Switch back to the CodeMirror. The text is now `This is a link: https://joplinapp.org/release\_cycle/`

Ideally, we should get this back in CodeMirror:

`This is a link: https://joplinapp.org/release_cycle/`

Or at least:

`This is a link: [https://joplinapp.org/release_cycle/](https://joplinapp.org/release_cycle/)`

But a broken link is a problem

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

Changes `turndown` to not escape the content of linkified URLs.

This should fix #8743.

### CODE REVIEW

File: packages/turndown/src/commonmark-rules.js [hunk 1]
```diff
@@ -313,6 +313,13 @@ rules.inlineLink = {
     )
   },
 
+  escapeContent: function (node, _options) {
+    // Disable escaping content (including '_'s) when the link has the same URL and href.
+    // This prevents links from being broken by added escapes.
+    const doEscape = node.getAttribute('href') !== node.textContent;
+    return doEscape ? 'auto' : false;
```
Comment (personalizedrefrigerator) [inline packages/turndown/src/commonmark-rules.js]: Should be `true` or `false`.
