### PR TITLE
Desktop: Expand Tree on Search Result

### LINKED ISSUE #2616: expand tree when cilcking on 'In: Folder ...' in search result
## Environment

Joplin version: 1.0.179 and git master 6542a60d
Platform: macOS (but irrelevant)
OS specifics: 10.14.6

## Steps to reproduce

1. create a folder (`A`) with a sub-folder (`A.1`) and a sub-sub-folder (`A.1.1`)
2. create a note `xyz` in `A.1.1`
3. collapse the folders and sub-folder in `A`
4. global search: `xyz`
5. click on the folder icon `In: Folder A.1.1`
image

## Describe what you expected to happen

I expect the folder structure to be expanded for folder `A.1.1`. Currently only the folder is selected, which you can't see, because the tree is collapsed.

This is a regression, since that has worked before. Or at least I think it did.

However, only the relevant tree should be expanded. If there are other sub-folders which are collapsed, they should not be touched. Expanded folders within the folder should not be touched either.

This is a fairly easy fix. Start at the target folder id and retrieve its parent ids, until you hit the root. Then use this list of ids to expand the tree.

It would be even better, if the tree only expanded when the folder icon `In: Folder ...` was clicked a second time. Although this might be a bit too complicated for a `good first issue`.

### PR DESCRIPTION
**Pull request by rabeehrz**
Fixes #2616 

Earlier, if the result of a search is a note inside a sub-notebook whose tree has been collapsed, the tree wouldn't expand when the In: Folder button was clicked.

### CODE REVIEW

**Comment by rabeehrz** [comment]
@PackElend label me please.

File: ElectronClient/gui/NoteText.jsx [hunk 1]
```diff
@@ -1612,18 +1612,30 @@ class NoteTextComponent extends React.Component {
 		menu.popup(bridge().window());
 	}
 
+	async updateFolderTreeOnSearch(folder) {
+		while (folder && folder.parent_id) {
+			this.props.dispatch({
+				type: 'FOLDER_TOGGLE',
```
Comment (laurent22) [inline ElectronClient/gui/NoteText.jsx]: You toggle the folder - doesn't this mean that if the folder is already open you're going to close it?

By the way this logic is already in GotoAnything.jsx. Could you extract it from there, move it to models/Folder and reuse it here?

File: ElectronClient/gui/NoteText.jsx [hunk 2]
```diff
@@ -1612,18 +1612,30 @@ class NoteTextComponent extends React.Component {
...
+	}
+
 	createToolbarItems(note, editorIsVisible) {
 		const toolbarItems = [];
 		if (note && this.state.folder && ['Search', 'Tag', 'SmartFilter'].includes(this.props.notesParentType)) {
 			toolbarItems.push({
 				title: _('In: %s', substrWithEllipsis(this.state.folder.title, 0, 16)),
 				iconName: 'fa-book',
-				onClick: () => {
+				onClick: async () => {
```
Comment (laurent22) [inline ElectronClient/gui/NoteText.jsx]: Why async?

File: ElectronClient/gui/NoteText.jsx [hunk 3]
```diff
@@ -1612,18 +1612,30 @@ class NoteTextComponent extends React.Component {
...
+					let folder = this.state.folder;
```
Comment (laurent22) [inline ElectronClient/gui/NoteText.jsx]: No need for the intermediate variable

File: ElectronClient/gui/NoteText.jsx (hunk 1 above)
Comment (rabeehrz) [reply ElectronClient/gui/NoteText.jsx]: > You toggle the folder - doesn't this mean that if the folder is already open you're going to close it?

I didn't think about that. Will fix it.

File: ElectronClient/gui/NoteText.jsx (hunk 2 above)
Comment (rabeehrz) [reply ElectronClient/gui/NoteText.jsx]: Sorry about that. Earlier I retrieved the Folder directly inside the onClick handler. Later I moved it to a function. Forgot to remove it then.

**Comment by rabeehrz** [comment]
I've made the requested changes. Please review.

**Comment by mic704b** [comment]
Please don't forget to add unit tests for the changes to `Folder`.

**Comment by rabeehrz** [comment]
> Please don't forget to add unit tests for the changes to `Folder`.

I'll add them now.

**Comment by mic704b** [comment]
> > Please don't forget to add unit tests for the changes to `Folder`.
> 
> I'll add them now.
> 
> EDIT: This is more of a UI change. I don't know how to add a test for this. Could you help me out @mic704b ?

Ahh you are correct.  The change to the core probably isn't big enough to warrant a new integration test, so my bad.

However you do rely on `Folder.folderPath()` and this method doesn't have unit tests yet.  So it would be good practice to add unit tests for that function to make sure it works as you expect in all situations.

These unit tests belong to `CliClient/tests/model_Folder.js` and you can see in that file for plenty of examples.  See the build instructions on how to run tests.

**Comment by rabeehrz** [comment]
> > > Please don't forget to add unit tests for the changes to `Folder`.
> > 
> > 
> > I'll add them now.
> > EDIT: This is more of a UI change. I don't know how to add a test for this. Could you help me out @mic704b ?
> 
> Ahh you are correct. The change to the core probably isn't big enough to warrant a new integration test, so my bad.
> 
> However you do rely on `Folder.folderPath()` and this method doesn't have unit tests yet. So it would be good practice to add unit tests for that function to make sure it works as you expect in all situations.
> 
> These unit tests belong to `CliClient/tests/model_Folder.js` and you can see in that file for plenty of examples. See the build instructions on how to run tests.

Thank You. I'll add unit tests for Folder Path.

File: ReactNativeClient/lib/models/Folder.js [hunk 4]
```diff
@@ -218,6 +218,17 @@ class Folder extends BaseItem {
 		return output;
 	}
 
+	static async expandTreeOnGoto(folders, folder) {
```
Comment (laurent22) [inline ReactNativeClient/lib/models/Folder.js]: Not sure why "OnGoto". Please rename to "expandTree". Also you only need the folder parent ID in this function and it's good practice to pass to a function only what you need. So it could just be `static async expandTree(folders, folderId)`. And you call it like so `Folder.expandTree(this.props.folders, this.state.folder.parent_id)`

Comment (rabeehrz) [reply ReactNativeClient/lib/models/Folder.js]: I'll keep this in mind. I've made the requested changes and wrote a test for folderPath. Please review.

**Comment by laurent22** [comment]
Looks good now, thank you @rabeehrz.
