### PR TITLE
Desktop: Resolves #4759: Added editor focus util

### LINKED ISSUE #4759: Command palette: Focus Issues
The note looses focus after inserting a checkbox/listbox/codeblock etc. using the command palette (ctrl-shift-p)

## Environment

Joplin version: 1.7.11
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. create a new note and enter some freetext
2. press ctrl-shift-p to activate the command palette
3. start typing "check" and then press enter
4. this creates a checkbox with highlighted text "List Item"
5. the note looses focus so that I can't immediately continue writing without clicking into the note to regain focus.

Affected items (as far as my short tests went): 
Horizontal rule, Checkbox, Bullet List, Numbered List, Heading

This happens in the marktown editor in both views (ctrl-L)
In the WYSIWIG Editor, the checkbox isn't even created.

## What I expect: 
press ctrl-shift-p and insert a hyperlink -> here, the cursor is placed between the square brackets and you can immediately continue typing.

### PR DESCRIPTION
**Pull request by Aksh-Konda**
Fixes #4759

### Problem:

When executing any editor command through the command palette, the focus isn't shifted back to the editor.

### Solution:

The editor should be focused before executing any editor command. I have moved the isEditorCommand function from toolbarButtonsUtil into a new file so there is no duplicate code.

### Manual Test to check if the focus shifts to the editor:

1. Open a note.
2. Open Command Palette by clicking ctrl+shift+p.
3. Type the command ": CheckBox" and click enter.
4. A checkbox will be added at the cursor location.

The focus should shift to the MD editor.

Refer to #4805 (for previous review/discussion)

### CODE REVIEW

File: packages/app-cli/tests/services_KeymapService.js [hunk 1]
```diff
@@ -242,7 +242,7 @@ describe('services_KeymapService', () => {
 		it('should throw when the required properties are missing', () => {
 			const customKeymaps = [
 				[
-					{ commmmmand: 'gotoAnything', accelerator: 'Ctrl+Shift+G' },
+					{ command: 'gotoAnything', accelerator: 'Ctrl+Shift+G' },
```
Comment (tessus) [inline packages/app-cli/tests/services_KeymapService.js]: I think this might have been on purpose. This is called a negative test. But I might be wrong. 

Laurent would know.

Comment (tessus) [reply packages/app-cli/tests/services_KeymapService.js]: Just saw you reverted that again.

Comment (Aksh-Konda) [reply packages/app-cli/tests/services_KeymapService.js]: yeah saw it in the check logs. I thought I was fixing a typo.

Comment (Aksh-Konda) [reply packages/app-cli/tests/services_KeymapService.js]: rather it was a test that was expecting an error.

Comment (tessus) [reply packages/app-cli/tests/services_KeymapService.js]: Yep, this is called a negative test.

File: packages/app-desktop/plugins/GotoAnything.tsx [hunk 2]
```diff
@@ -378,6 +379,7 @@ class Dialog extends React.PureComponent<Props, State> {
 		});
 
 		if (item.type === BaseModel.TYPE_COMMAND) {
+			focusEditorIfEditorCommand(item.id, CommandService.instance());
```
Comment (CalebJohn) [inline packages/app-desktop/plugins/GotoAnything.tsx:382]: I think this line should come after the command is executed. It's just a small thing that likely doesn't matter, but it is best to keep the same order in both scripts to prevent inconsistency for the user.

**Comment by CalebJohn** [comment]
@Aksh-Konda I just had one comment, otherwise it looks good to me.

**Comment by CalebJohn** [comment]
LGTM

File: packages/lib/services/commands/EditorFocusUtil.ts [hunk 3]
```diff
@@ -0,0 +1,31 @@
+import CommandService from '../CommandService';
+
+// Editor commands will focus the editor after they're executed
+export function isEditorCommand(commandName: string) {
```
Comment (laurent22) [inline packages/lib/services/commands/EditorFocusUtil.ts:4]: The file is called "EditorFocusUtils" but this command is unrelated to editor focus so please move it to isEditorCommand.ts

File: packages/lib/services/commands/EditorFocusUtil.ts [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+        commandName === 'textNumberedList' ||
+        commandName === 'textBulletedList' ||
+        commandName === 'textCheckbox' ||
+        commandName === 'textHeading' ||
+        commandName === 'textHorizontalRule' ||
+        commandName === 'insertDateTime'
+	);
+}
+
+export function focusEditorIfEditorCommand(commandName: string, commandService: CommandService): void {
```
Comment (laurent22) [inline packages/lib/services/commands/EditorFocusUtil.ts:27]: Move to focusEditorIfEditorCommand.ts It should be async and should await for `commandService.execute('editor.focus')`. Calling code decides if the promise is ignored or not.

**Review by laurent22 — COMMENTED** [review]
Test units are missing.

**Comment by Aksh-Konda** [comment]
> Test units are missing.

@laurent22 ,
There is no tests folder/module inside lib. Can you please tell me where can I place the test file?

**Comment by laurent22** [comment]
> There is no tests folder/module inside lib. Can you please tell me where can I place the test file?

You would place it next to your file and name it xxx.test.ts. But after checking the code again I think it would take too much effort to test only a simple "if" condition, so you can skip the automated tests. The manual tests you've listed are sufficient.

**Comment by laurent22** [comment]
All good now, thanks @Aksh-Konda for the PR, and thanks @CalebJohn and @tessus for the review.
