### PR TITLE
Desktop: Resolve #6254: <details> elements remain closed when exporting to PDF

### LINKED ISSUE #6254: `<details>` elements remain closed when exporting to PDF
## Environment

Joplin version: 2.7.13
Platform: Linux
OS specifics: PoP! OS 21.10/Flatpak

## Steps to reproduce

1. Create a new note
2. Add the following content:
```html
<details><summary>This should expand when exported</summary>
If it doesn't expand, we lack content in the exported PDF.
</details>
```
3. Export to PDF (`Ctrl+Shift+P` > `exportPdf`)
4. View the PDF

## Describe what you expected to happen

The dropdown should be expanded in the exported PDF.

## Logfile

Should not be applicable

### PR DESCRIPTION
**Pull request by gtlsgamr**
When exporting a note to pdf, any `<details>` tags remain closed, which should not be expected behaviour since the data inside them will not be visible.
This PR opens the tags before printing the pdf and closes them once it is done, thus solving #6254

### CODE REVIEW

**Comment by gtlsgamr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gtlsgamr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gtlsgamr** [comment]
recheck

File: packages/app-desktop/InteropServiceHelper.ts [hunk 1]
```diff
@@ -78,8 +78,12 @@ export default class InteropServiceHelper {
 					shim.setTimeout(async () => {
 						if (target === 'pdf') {
 							try {
+								const openDetails = '[].forEach.call( document.querySelectorAll( \'details\' ), el => el.setAttribute( \'open\', \'\' ) )';
+								win.webContents.executeJavaScript(openDetails);
 								const data = await win.webContents.printToPDF(options);
 								resolve(data);
```
Comment (laurent22) [inline packages/app-desktop/InteropServiceHelper.ts:84]: resolve(data) should be last

File: packages/app-desktop/InteropServiceHelper.ts [hunk 2]
```diff
@@ -78,8 +78,12 @@ export default class InteropServiceHelper {
 					shim.setTimeout(async () => {
 						if (target === 'pdf') {
 							try {
+								const openDetails = '[].forEach.call( document.querySelectorAll( \'details\' ), el => el.setAttribute( \'open\', \'\' ) )';
```
Comment (laurent22) [inline packages/app-desktop/InteropServiceHelper.ts]: Why do we need this syntax `[].forEach.call`?

Comment (gtlsgamr) [reply packages/app-desktop/InteropServiceHelper.ts]: I think this [answer](https://stackoverflow.com/questions/16053357/what-does-foreach-call-do-in-javascript) describes it better.
But other than that, there is no specific reason we should be doing that. Although I don't see any reason why we could just not do 
`document.querySelectorAll( 'details' ).forEach(el=>el.setAttribute( 'open')); I will fix this right now.

File: packages/app-desktop/InteropServiceHelper.ts (hunk 1 above)
Comment (gtlsgamr) [reply packages/app-desktop/InteropServiceHelper.ts:84]: Alright I will update the PR.

File: packages/app-desktop/InteropServiceHelper.ts [hunk 3]
```diff
@@ -78,7 +78,9 @@ export default class InteropServiceHelper {
 					shim.setTimeout(async () => {
 						if (target === 'pdf') {
 							try {
+								win.webContents.executeJavaScript('document.querySelectorAll(\'details\').forEach(el=>el.setAttribute(\'open\',\'\'))');
 								const data = await win.webContents.printToPDF(options);
+								win.webContents.executeJavaScript('document.querySelectorAll(\'details\').forEach(el=>el.removeAttribute(\'open\',\'\'))');
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/InteropServiceHelper.ts]: What if some of the `details` elements had `open="true"` before line 81? It might make more sense to only close the `details` elements that were previously `open`.

Comment (gtlsgamr) [reply packages/app-desktop/InteropServiceHelper.ts]: @personalizedrefrigerator I just tested on joplin v2.9.17.
Even if you keep some `details` tags open, whenever you quit joplin and start again, it will go back to the closed state. They don't survive restarts. 

> It might make more sense to only close the details elements that were previously open.

This can be done, but the question is, do we want to do it? Because at some point the tags are gonna close by themselves. This is just simple and convenient in my opinion.

Comment (laurent22) [reply packages/app-desktop/InteropServiceHelper.ts]: I was thinking the same thing, but then I realized we're loading a temporary HTML file when printing so it's ok to make change to the DOM (since the changes won't be applied to the note).

Comment (laurent22) [reply packages/app-desktop/InteropServiceHelper.ts]: In fact, why do you close the "details" elements after printing?

Comment (gtlsgamr) [reply packages/app-desktop/InteropServiceHelper.ts]: Now that you mention it, closing them is not necessary at all. Should I remove the closing part? @laurent22 
**EDIT:** I have removed it.

**Review by gtlsgamr — COMMENTED** [review]
I have removed the unnecessary closing.

File: packages/app-desktop/InteropServiceHelper.ts [hunk 4]
```diff
@@ -78,6 +78,7 @@ export default class InteropServiceHelper {
 					shim.setTimeout(async () => {
 						if (target === 'pdf') {
 							try {
+								win.webContents.executeJavaScript('document.querySelectorAll(\'details\').forEach(el=>el.setAttribute(\'open\',\'\'))');
```
Comment (laurent22) [inline packages/app-desktop/InteropServiceHelper.ts:82]: Please add a comment above this line to explain what it does, and link to the GitHub issue

**Comment by laurent22** [comment]
All good now, thanks!

**Comment by laurent22** [comment]
I shouldn't have merged since the code doesn't pass the linter. Next time please don't commit directly from GitHub because the precommit script doesn't run here.
