### PR TITLE
Desktop: Fix #5872: Markdown search no longer scrolls to result 

### LINKED ISSUE #5872: Markdown search no longer scrolls to result
Joplin no longer scrolls to Markdown search results. Clicking on the up and down arrows to go to the next search result also does not scroll to the result. The results are still highlighted, like normal.

## Environment

Joplin version: 2.6.9
Platform: macOS (Intel)
OS specifics: Monterey 12.1

## Steps to reproduce

1. Open Joplin
2. Select Markdown
3. Search for text

## Describe what you expected to happen
The window should scroll to the search results

## Logfile
I wasn't sure what to include with the logs, so I just included the warnings from the Console tab.
[debug.log](https://github.com/laurent22/joplin/files/7736565/debug.log)

### PR DESCRIPTION
**Pull request by ken1kob**
This PR fixes #5872, 'Markdown search no longer scrolls to result'.

The cause of the bug is that excessive negating of scroll events was performed. Concretely, scroll events caused by local searches were ignored, and their positions were reverted. Some other programmatic scrolling caused by CodeMirror was also affected. For example, page up/down didn't work in most cases.

This PR fixes the excessive negating.

### CODE REVIEW

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx [hunk 1]
```diff
@@ -191,7 +191,6 @@ function Editor(props: EditorProps, ref: any) {
 		cm.on('drop', editor_drop);
 		cm.on('dragover', editor_drag);
 		cm.on('refresh', props.onResize);
-		cm.on('update', props.onResize);
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx:194]: Thanks for looking into it @ken1kob. The fact that we no longer call "onResize" in this case, doesn't it mean that the editor will no longer be properly updated in some cases, for example when it's resized?

Comment (ken1kob) [reply packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx:194]: Since resize events are covered by CodeMirror's 'refresh' events, they are not in CodeMirror's 'update' events.

I have not yet found specific event in CodeMirror's update events needed to be ignored. They were ignored on the assumption that scroll events after update events are not originated by user. The found counter-examples (such as local search) shows the assumption is wrong.

**Comment by laurent22** [comment]
Ok that makes sense then, thanks for the quick fix for this! I'll create a bug fix release relatively soon with this and a few other regressions that have just been found.
