### PR TITLE
Desktop: Fixes #8591 - Error while quitting the app

### LINKED ISSUE #8591: Fix error when quitting the app
There's a stack trace so it's probably just a null check that needs to be added:

image

### PR DESCRIPTION
**Pull request by hubertfilho**
By the stack track the error is when trying read webContents from BrowserWindow, and it's happening when the app is about to close. So, after I analysed the code and did some tests I just added a verification in the part of the code when I believe the error is happening. I couldn't reproduce the problem on my machine. I hope it solve the problem.

### CODE REVIEW

File: packages/app-desktop/ElectronAppWrapper.ts [hunk 1]
```diff
@@ -174,7 +174,7 @@ export default class ElectronAppWrapper {
 					// so that it can tell us if we can really close the app or not.
 					// Search for "appClose" event for closing logic on renderer side.
 					event.preventDefault();
-					this.win_.webContents.send('appClose');
+					if (this.win_) this.win_.webContents.send('appClose');
```
Comment (hubertfilho) [inline packages/app-desktop/ElectronAppWrapper.ts:177]: The code inside `if (isGoingToExit)` is running 3 times after closing the app and at the thirty time `this.win_ is null`. So, I think in some cases it's entering the next if statement `if (!this.rendererProcessQuitReply_)` and causing the problem. I hope it makes sense.

**Comment by laurent22** [comment]
Looks good, thanks Hubert
