### PR TITLE
Mobile: Fixes #10589: Fix selected note changes on moving to a different folder

### LINKED ISSUE #10589: Mobile: Notebook picker on new note doesn't move the note
### Operating system

Android

### Joplin version

3.0.3

### Desktop version info

Joplin 3.0.3 (dev, android)

Client ID: 23614cce830d4a05a5f779b1ba9db0d2
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Android API level: 34
WebView version: 113.0.5672.119
WebView package: com.google.android.webview
FTS enabled: 1
Hermes enabled: 1

### Current behaviour

1. Create two notebooks
2. Select one (behavior is not observed if 'All notes' is selected)
3. Use the floating action button to create a new note
4. Press on notebook name
5. Select other notebook
7. Screens blinks and the selected notebook still the same 

### Expected behaviour

1. Create two notebooks
2. Select one (behavior is not observed if 'All notes' is selected)
3. Use the floating action button to create a new note
4. Press on notebook name
5. Select other notebook
6. Notebook should be the selected one and note should be created inside of it

### Logs

While trying to fix another issue https://github.com/laurent22/joplin/issues/10252 I found this faulty behavior

The bug does not happen if instead of having a notebook selected the user is seeing 'All notes'

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request updates `reducer.ts` to not change the selected note when its parent ID changes in more cases. In particular, it allows the mobile app to specify that the selected note should not change, while preserving existing behavior on desktop.

Fixes #10589.

# Testing plan

1. Start Joplin and create a new note.
2. Before editing, move that note to a new folder.
    - On mobile, verify that the same note is still selected. Verify that the note can be edited.
    - On desktop, verify that a different note is selected.
3. Switch notes to an existing note. Move it to a new folder.
    - On mobile, verify that the same note is still selected. Verify that the note can be edited. Verify that the notebook selector can still be used.
    - On desktop, verify that a different note is selected.

Test on:
- [x] Android 13 (mobile)
- [x] Ubuntu 24.04 (desktop)

### CODE REVIEW

File: packages/lib/reducer.ts [hunk 1]
```diff
@@ -1005,7 +1005,11 @@ const reducer = produce((draft: Draft<State> = defaultState, action: any) => {
 
 				draft.notes = newNotes;
 
-				if (noteFolderHasChanged) {
+				// Ensure that the selected note is still in the current folder.
+				// For example, if the user drags the current note to a different folder,
+				// a new note should be selected.
+				// In some cases, however, the selection needs to be preserved (e.g. the mobile app).
+				if (noteFolderHasChanged && !action.preserveSelection) {
 					let newIndex = movedNotePreviousIndex;
```
Comment (personalizedrefrigerator) [inline packages/lib/reducer.ts:1013]: This approach preserves the existing note behavior on desktop (dragging the selected note to a new folder selects a different note) and the [existing back button behavior on mobile](https://github.com/laurent22/joplin/pull/10597#issuecomment-2170330379). However, it makes both the reducer logic and `Note.save` more complicated. 

Suggestions on how this solution might be improved are welcome.

Comment (laurent22) [reply packages/lib/reducer.ts:1013]: Indeed it's not ideal but can't really think of a better way. Let's go with this for now, and at least there's a comment to explain the behaviour and a test to check it.

**Comment by laurent22** [comment]
Thanks for fixing this!
