### PR TITLE
 Desktop: Fixes #12910: Fixed Custom Dictionary.txt being saved to wrong directory

### LINKED ISSUE #12910: "Custom Dictionary.txt" not portable
### Operating system

Windows

### Joplin version

3.4.3

### Desktop version info

Joplin 3.4.3 (prod, win32)

Device: win32, AMD Ryzen 9 7940HS w/ Radeon 780M Graphics     
Client ID: xxx
Sync Version: 3
Profile Version: 47
Keychain Supported: No
Alternative instance ID: -

Revision: b93ee34

Backup: 1.4.3
Cursor Sync: 2.1.0
Extra Markdown editor settings: 1.11.0
Freehand Drawing: 3.1.0
Inline TODO: 1.7.4
Note overview: 1.7.1
Persistent Editor Layout: 2.2.0
Search & Replace: 2.2.0
Space Indenter: 0.2.6

### Current behaviour

Write something Joplin marks as wrong.
Right click the word and select "Add to dictionary".
The word is added to "C:\Users\<me>\AppData\Roaming\Joplin\Custom Dictionary.txt"

### Expected behaviour

User "Custom Dictionary.txt" inside JoplinProfile in portable version.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Harsh16gupta**
Fixes: #12910

AI Disclosure:
AI was used to assist during the development of this PR. I was used to write test for the changes. All suggestions were reviewed, tested, and verified.

`Custom Dictionary.txt` was always written to Electron's default `userData` 
path instead of the active Joplin profile directory, making it non-portable 
and missing from backups.

---
Fix: The dictionary is managed manually:

- When a word is added, it is written to `profileDir/Custom Dictionary.txt`
- On startup, loadSavedWords() reads this file and adds the saved words back to the Electron spell checker.

Note: existing words saved before this update will continue to work as Electron still reads from its own location automatically.

---
Test: Manual testing + unit tests added for `SpellCheckerServiceDriverNative`.

### CODE REVIEW

File: packages/app-desktop/main.ts [hunk 1]
```diff
@@ -52,6 +52,7 @@ const { rootProfileDir } = determineBaseAppDirs(profileFromArgs, appName, altIns
 // We create the profile dir as soon as we know where it's going to be located since it's used in
 // various places early in the initialisation code.
 mkdirpSync(rootProfileDir);
+electronApp.setPath('userData', rootProfileDir);
```
Comment (laurent22) [inline packages/app-desktop/main.ts]: What other data is saved in there? What will be the impact when updating existing applications?

Comment (Harsh16gupta) [reply packages/app-desktop/main.ts]: I check there are only the word which I added to the dictionary and a `checksum_v1 = 35e41b2...` I don't remember adding this.

> What will be the impact when updating existing applications?

Only new words added after the update will go to the correct profile directory. Words added before will remain in the old location.
If you want I can try to see how to migrate them.

Comment (Harsh16gupta) [reply packages/app-desktop/main.ts]: I made a mistake, I didn't investigate properly . Moving userData also moves Electron internals like GPUCache, Network, Session Storage and other cache directories into the profile folder, which fills it with files unrelated to user data.

**Comment by Harsh16gupta** [comment]
Changes in the last commit: (Dictionary is managed manually)

- New words are saved in `profileDir/Custom Dictionary.txt.`
- When started, `loadSavedWords()` loads them into the spell checker.
- Existing words still work because Electron reads from its own location automatically, but they are not in the profile directory yet.

Should I add a one time migration that copies old words from Electron's userData into the profile directory? Without it everything works fine, but if a user switches devices or uses the portable version, their old words will be missing.

**Comment by laurent22** [comment]
> Should I add a one time migration that copies old words from Electron's userData into the profile directory? Without it everything works fine, but if a user switches devices or uses the portable version, their old words will be missing.

What's your take on this?

**Comment by Harsh16gupta** [comment]
> > Should I add a one time migration that copies old words from Electron's userData into the profile directory? Without it everything works fine, but if a user switches devices or uses the portable version, their old words will be missing.
> 
> What's your take on this?

I think if we migrate only once on the start and copy only the different words and never do that migration again then it should be good (I will not change anything in the old location).

File: packages/app-desktop/services/spellChecker/SpellCheckerServiceDriverNative.ts [hunk 2]
```diff
@@ -63,10 +78,48 @@ export default class SpellCheckerServiceDriverNative extends SpellCheckerService
...
+	}
+
 	public addWordToSpellCheckerDictionary(_language: string, word: string) {
 		// Actually on Electron all languages share the same dictionary, or
 		// perhaps it's added to the currently active language.
 		this.session().addWordToSpellCheckerDictionary(word);
+
+		// Persist the word to the profile directory so it survives
+		// independently of Electron's userData path, making it portable.
+		void this.saveWordToFile(word);
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/services/spellChecker/SpellCheckerServiceDriverNative.ts]: To correct a word mistakenly added to the dictionary, will it be necessary to remove the word from two files, rather than one?

**Note**: `this.session().addWordToSpellCheckerDictionary(word);` is still called.

Comment (Harsh16gupta) [reply packages/app-desktop/services/spellChecker/SpellCheckerServiceDriverNative.ts]: So what I checked: 
I added a word to the dictionary and the red squiggly disappeared. I then deleted it from `.config/joplindev-desktop/Custom Dictionary.txt` but the red squiggly did not come back. I also deleted it from `AppData/Roaming/Joplin/Custom Dictionary.txt` but the red squiggly still did not reappear. 
I even tried the steps from the community forum (https://discourse.joplinapp.org/t/how-to-delete-an-entry-in-the-spell-checker-dictionary/25228) on both the dev and normal app but none of them brought back the red squiggly after a word had been added to the dictionary.
am I doing something wrong?

Comment (personalizedrefrigerator) [reply packages/app-desktop/services/spellChecker/SpellCheckerServiceDriverNative.ts]: At least on Linux (Joplin 3.6.6 in release mode), the community forum suggestion seems to work. For comparison, I:
1. Opened `~/.config/Joplin/Custom Dictionary.txt` in a text editor and cleared it.
2. Recalculated the checksum (might not be necessary).
3. Restarted Joplin.

Comment (Harsh16gupta) [reply packages/app-desktop/services/spellChecker/SpellCheckerServiceDriverNative.ts]: Thanks for testing on Linux.
I tried on Windows (Joplin 3.5.13 (prod, win32) and 3.6.6) and it does not work on either of them

> To correct a word mistakenly added to the dictionary, will it be necessary to remove the word from two files, rather than one?

Yes, with this PR a user would technically need to edit both files to remove a word. I think it is better to create a new issue where we can use [session.removeWordFromSpellCheckerDictionary()](https://www.electronjs.org/blog/electron-9-0#api-changes:~:text=session.removeWordFromSpellCheckerDictionary) to remove words from the dictionary through the UI.

**Comment by laurent22** [comment]
- Existing words in the dictionary needs to be migrated to the new location
- The dictionary should exist in only one location (in the profile directory), so if the user saves this file they are guaranteed to have all their words

Could you please confirm this is how it works @Harsh16gupta? If not update to support the above

File: packages/app-desktop/services/spellChecker/SpellCheckerServiceDriverNative.ts (hunk 2 above)
Comment (Harsh16gupta) [reply packages/app-desktop/services/spellChecker/SpellCheckerServiceDriverNative.ts]: Found why it was not working for me (on windows):
Windows automatically add word to a custom dictionary so when I was clicking "add to dictionary" in joplin (dev or normal) it also add the words to the custom dictionary (windows). Because of this when I delete a word it does not get removed from the window's custom dictionary so the red squiggly never disappeared.

Problem in the current code:
When I add a word to dictionary it gets added to the both the location and It was difficult to remove it from the dictionary.

In the latest commit I have moved to a better approach.

**Comment by Harsh16gupta** [comment]
In the last commit (I moved to a better approach):

- Created a custom Electron session using `session.fromPath(profileDir)` so that chromium automatically writes Custom Dictionary.txt to the profile directory.
- Added a one time migration to copy existing words from the old `AppData/Roaming/Joplin/Custom Dictionary.txt`

---

Laurent comment :
> * Existing words in the dictionary needs to be migrated to the new location
> * The dictionary should exist in only one location (in the profile directory), so if the user saves this file they are guaranteed to have all their words

Both works perfectly, Only one issue that :

- Using `session.fromPath()` also creates some extra chromium files in the profile folder (These extra files like` GPUCache`, `IndexedDB`, clutter the folder).

There was no other clean way to solve this. Working on how to remove the extra files.

File: packages/app-desktop/ElectronAppWrapper.ts [hunk 3]
```diff
@@ -230,6 +230,39 @@ export default class ElectronAppWrapper {
 		// Load the previous state with fallback to defaults
 		const windowState = windowStateKeeper(stateOptions);
 
+		// Create a persistent session rooted at the profile directory so that
+		// Custom Dictionary.txt is stored there, making it portable.
+		// cache: false prevents large Chromium cache data from polluting the profile directory.
+		const joplinSession = electronSession.fromPath(this.profilePath_, { cache: false });
```
[the remark this answers is not in the document]
Comment (Harsh16gupta) [reply packages/app-desktop/ElectronAppWrapper.ts]: yep, I made a mistake
I only tested on the rich text editor and everything was working perfectly.
but when I switch the editor it gave me an error, almost fixed it, will push it after proper testing

**Comment by laurent22** [comment]
As it's a draft, please let us know when it's ready to test

File: packages/app-desktop/ElectronAppWrapper.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (Harsh16gupta) [reply packages/app-desktop/ElectronAppWrapper.ts]: You skipped the last review, do it now.

**Comment by Harsh16gupta** [comment]
What changed form the last post:

- registered the custom protocol handlers (`joplin-content://` and 
  `joplin-plugin://`) on this same session.


So I have a windows stepUp and when I was working on this PR and testing, windows does not allow me to delete the word form the dictionary by following the forum [post](https://discourse.joplinapp.org/t/how-to-delete-an-entry-in-the-spell-checker-dictionary/25228) process. some time it was working but most of the time it was not working. So I asked claude to give me a script file to delete the word from the custom dictionary.

Claude gave me this (Following the exact step given in the post) (attaching this here because I used this for testing on Windows):

```
# Set the words you want to remove
$wordsToRemove = @("dustin", "sadie", "xyztest")

$dictPath = "C:\Users\harsh\.config\joplindev-desktop\.spell-session\Custom Dictionary.txt"
$backupPath = "C:\Users\harsh\.config\joplindev-desktop\.spell-session\Custom Dictionary.txt.backup"

# Read all lines
$lines = [System.IO.File]::ReadAllLines($dictPath, [System.Text.Encoding]::UTF8)

# Separate words from checksum line
$words = $lines | Where-Object { $_ -notmatch '^checksum_v1' -and $_.Trim() -ne '' }

# Remove the target words (case-sensitive)
$words = $words | Where-Object { $wordsToRemove -notcontains $_ }

# Build content: each word on its own line, LF only (Electron expects LF)
$content = ($words -join "`n") + "`n"

# Calculate MD5 of that exact content
$bytes = [System.Text.Encoding]::UTF8.GetBytes($content)
$md5 = [System.Security.Cryptography.MD5]::Create()
$hashBytes = $md5.ComputeHash($bytes)
$hash = ($hashBytes | ForEach-Object { $_.ToString('x2') }) -join ''

# Append checksum line
$finalContent = $content + "checksum_v1 = $hash"

# Write back as UTF-8 without BOM, LF line endings
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($dictPath, $finalContent, $utf8NoBom)

# Also fix the backup so it does not restore the deleted words
if (Test-Path $backupPath) {
    [System.IO.File]::WriteAllText($backupPath, $finalContent, $utf8NoBom)
}

Write-Host "Done. Removed: $($wordsToRemove -join ', '). Hash: $hash"

```
Then I tested all the changes with this approach and It works perfect (Screen Recording):

https://github.com/user-attachments/assets/05fa661f-82a0-41e7-b192-aa00ee66c052

---

To solve the Issue I had three options:
1. manually manage dictionary (tried it [here](https://github.com/laurent22/joplin/pull/14749#issuecomment-4064323742) in this PR)
problem: words were being added to both the custom dictionary and it was very difficult to delete the words from the dictionary.

2. The approach which I explained in the previous [post](https://github.com/laurent22/joplin/pull/14749#issuecomment-4106350015)
problem: It creates some extra files and pollute the `.config\joplindev-desktop` directory.

3. This one is build on top of 2nd one, all the extra files are now in `.config\joplindev-desktop\.spell-session` along with the custom dictionary.
image

Note: I tried to remove the extra not wanted files but was not able to do it due to electron limitation. 

If you think this can be done in a better way then please guide me, I am happy to try it.

**Comment by personalizedrefrigerator** [comment]
> .spell-session

`.spell-session` contains more than just the custom spellchecking dictionary. As such, it could make sense to rename it to something like `.session`, `.electron-session`, or `.chromium-session`.

**Comment by laurent22** [comment]
Also does it have to be a hidden folder? It's rarely a good idea to make user folders hidden because they might be forgotten when moving or copying files

**Comment by Harsh16gupta** [comment]
> Also does it have to be a hidden folder? It's rarely a good idea to make user folders hidden because they might be forgotten when moving or copying files

I check that in mac and Linux the folder starting form `.` (hidden folder) are not visible, and the only option to remove the word from the custom dictionary is through this folder.
So changing the name to 'electron-session'

**Comment by laurent22** [comment]
It's not really session data since it stays after the app is closed, and Electron is implementation detail. Maybe something more generic like "internal"?

File: packages/app-desktop/ElectronAppWrapper.ts [hunk 4]
```diff
@@ -209,13 +210,46 @@ export default class ElectronAppWrapper {
 		}
 	}
 
+	private createJoplinSession_() {
+		const sessionPath = path.join(this.profilePath_, 'internal');
+		const joplinSession = electronSession.fromPath(sessionPath, { cache: false });
+
+		// One-time migration: copy existing dictionary words from the old Electron userData location into the new session.
+		const migrationFlagPath = path.join(this.profilePath_, '.spell-checker-migration-done');
```
Comment (laurent22) [inline packages/app-desktop/ElectronAppWrapper.ts]: Please don't make it a hidden file for the reasons we discussed earlier

Comment (Harsh16gupta) [reply packages/app-desktop/ElectronAppWrapper.ts]: updated it

File: packages/app-desktop/ElectronAppWrapper.ts [hunk 5]
```diff
@@ -209,13 +210,46 @@ export default class ElectronAppWrapper {
 		}
 	}
 
+	private createJoplinSession_() {
+		const sessionPath = path.join(this.profilePath_, 'internal');
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/ElectronAppWrapper.ts:206]: Something else to consider: Does changing the session path clear `localStorage`/`indexedDb`/etc.? If so, it might be worth checking how many/which plugins use these APIs for data storage.

Comment (Harsh16gupta) [reply packages/app-desktop/ElectronAppWrapper.ts:206]: > Does changing the session path clear `localStorage`/`indexedDb`/etc.?|

No, it does not. The main window uses `file://` protocol to load, and electron stores `localStorage` for file:// pages in the app's userData folder (independent of the session path). so `session.fromPath()` does not change it. 

To verify this, I added a value in the `local Storage` on dev branch, then switched to this pr branch (rebuild and relaunched) the value was still accessible form the pr branch.

Comment (personalizedrefrigerator) [reply packages/app-desktop/ElectronAppWrapper.ts:206]: Thank you for checking!

**Comment by laurent22** [comment]
Hello, there's a conflict on one of the files

**Comment by Harsh16gupta** [comment]
> Hello, there's a conflict on one of the files

Resolved it.
