### PR TITLE
Server: Fixes #14355: Admin emails sorting fails due to invalid user_id column

### LINKED ISSUE #14355: Server: sorting by user error in Email
### Operating system

Docker Image @ Rocky Linux 10

### Joplin version

Server 3.5.2

### Desktop version info

_No response_

### Current behaviour

1. Open server website as an admin
2. Go to Admin -> Emails
3.  Click on the User column to sort

Error: select "id", "recipient_name", "recipient_email", "recipient_id", "sender_id", "subject", "body", "sent_time", "sent_success", "error", "updated_time", "created_time", "key" from "emails" order by "user_id" asc limit $1 - column "user_id" does not exist****

### Expected behaviour

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by devanmolx**
## Description  
Fixes #14355

Sorting by the **User** column in **Admin → Emails** caused a SQL error because the table was configured to use user_id, while the emails table actually uses recipient_id.

This updates the sort field to recipient_id, aligning it with the database schema and resolving the error.

### Changes

- Replaced `user_id` with `recipient_id` in the admin emails table sorting configuration  

### Testing

- Rebuilt the server
- Confirmed the SQL error no longer occurs

### CODE REVIEW

**Comment by laurent22** [comment]
Please review your PR based on our AI policy:

https://discourse.joplinapp.org/t/policy-on-ai-assisted-contributions-during-gsoc-2026-draft/48706

**Comment by devanmolx** [comment]
I’ve updated the PR description to include the required AI disclosure.

**Comment by laurent22** [comment]
There's also this:

> We are unlikely to accept pull requests that include:
>    - Large auto-generated summaries

In other words, we don't want to have to read two pages of description for a trivial bug such as this. LLMs are great at writing a lot about nothing, and we do not want this here.

**Comment by personalizedrefrigerator** [comment]
I can confirm that this fixes the issue locally!

File: packages/server/src/routes/admin/emails.ts [hunk 1]
```diff
@@ -40,7 +40,7 @@ router.get('admin/emails', async (_path: SubPath, ctx: AppContext) => {
 				label: 'To',
 			},
 			{
-				name: 'user_id',
+				name: 'recipient_id',
```
Comment (personalizedrefrigerator) [inline packages/server/src/routes/admin/emails.ts:43]: For reference, this also aligns with the content of the corresponding column:
https://github.com/laurent22/joplin/blob/90de267c626431b80fe50347e457cd17bd5b0198/packages/server/src/routes/admin/emails.ts#L85-L87

**Review by personalizedrefrigerator — APPROVED** [review]

**Comment by laurent22** [comment]
Note that the pull request title was incorrect. Next time please read the pull request template
