### PR TITLE
Desktop: Fixes #9003: Fix pasting text into CodeMirror 6 with Cmd+V/Ctrl+V

### LINKED ISSUE #9003: Desktop/CodeMirror 6: Pasting text (without images) broken
## Environment

Joplin version: 849427d1bf2163ba772afa8e2f63d3c6f95de4bf
Platform: MacOS/Deskstop

## Steps to reproduce

1. Enable the CodeMirror 6 beta
2. Copy text
3. Paste it into a note with CodeMirror 6 enabled
4. Copy an image
5. Paste it into a note with CodeMirror 6 enabled

## Describe what you expected to happen

Both pasting text and pasting images should work.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

The paste event sent by CodeMirror 6 was incorrectly connected to the paste event handler (using the same logic as for CodeMirror 5).

The handler expected the default behavior (pasting text) of the event to run if `.preventDefault` was not called. However, the CodeMirror 6 logic prevented this default behavior.

Fixes #9003 by allowing the `onPaste` handler cancel the event with `.preventDefault`, rather than canceling it automatically.

# Testing plan

This commit has been tested **manually** on MacOS by:
1. Enable the CodeMirror 6 beta.
2. Create a new, empty note.
3. Type "This is a test..."
4. Copy "This is a test..."
5. Paste
6. Take a screenshot and copy it to the clipboard
7. Paste the screenshot into the editor

### CODE REVIEW

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/Editor.tsx [hunk 1]
```diff
@@ -37,8 +37,7 @@ const Editor = (props: Props, ref: ForwardedRef<CodeMirrorControl>) => {
 		}
 
 		const pasteEventHandler = (_editor: any, event: Event) => {
-			event.preventDefault();
-			props.onEditorPaste();
+			props.onEditorPaste(event);
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/Editor.tsx:40]: This currently relies on `getResourcesFromPasteEvent` calling `.preventDefault` when it finds a suitable resource (behavior also relied upon by the CodeMirror 5 editor). However, it might make more sense to call `.preventDefault` in the `onEditorPaste` handler (rather than a method with a name starting with `get`). For example,
```diff
	const onEditorPaste = useCallback(async (event: Event|null = null) => {
		const resourceMds = await getResourcesFromPasteEvent(event);
		if (!resourceMds.length) return;
		if (editorRef.current) {
+			// Override the default paste behavior (if any)
+			event?.preventDefault();

			editorRef.current.insertText(resourceMds.join('\n'));
		}
	}, []);
```
