### PR TITLE
Android: Fixes #13113: Fix compatibility with 16-KB-page-size devices: Remove Vosk

### LINKED ISSUE #13113: Android app must support 16 KB page size
As per Google:

> Critical message Your app is affected by Google Play's 16 KB page size requirements
> 
> We may have accidentally sent you an email with an incorrect deadline. The correct deadline is 1 Nov 2025.
> 
> You can automatically extend this deadline to 31 May 2026 in Play Console. Please see below for the corrected message.
> 
> To ensure that your app works correctly on the latest versions of Android, Google Play requires all apps targeting Android 15+ to support 16 KB memory page sizes.
> 
> From 1 Nov 2025, if your app updates do not support 16 KB memory page sizes, you won't be able to release these updates.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request removes Vosk from the Android app. 

Fixes #13113.

This removes the "Voice typing provider" from settings and transitions users from Vosk to Whisper.

# Notes

- Support for 16 KB devices will soon be required for app submission to the Google Play Store. The version of [`react-native-vosk`](https://github.com/riderodd/react-native-vosk) used by Joplin is incompatible with these devices.
- An alternative might be to upgrade `react-native-vosk` to the latest version. However, there are a number of breaking changes in the more recent Vosk releases (e.g. [a migration to Turbo modules](https://github.com/riderodd/react-native-vosk/commit/4869ff0d18e1d2e39987c3c672915f98ff4187bf) in the 2.0 release).
    - According to [the note in this commit](https://github.com/laurent22/joplin/commit/33286efe9a22b64d5a3343b40e256f585169b756) (presumably after the last attempt to upgrade Vosk), there are other breaking changes in the 1.x Vosk releases.
- Joplin currently includes both Vosk and Whisper in the Android release. Both are somewhat large and increase the size of the Android APK. Removing Vosk decreases the APK size by about 35 MiB (186 MiB -> 151 MiB).

# Testing plan

1. Build a release APK and install it on an Android emulator (see ["Set up the Android Emulator with a 16-KB-based, Android 15 system image"](https://developer.android.com/guide/practices/page-sizes#16kb-emulator)).
   - I'm testing with a 16-KB-based Android 16 emulator.
   - Joplin should be uninstalled from the emulator first, if already installed. This allows the emulator to re-show the compatibility warning, if shown previously.
2. Verify that no compatibility warning is shown when first opening the app.
2. Create a new note.
3. Show the voice typing dialog and verify that Whisper is in use.

### CODE REVIEW

File: packages/app-mobile/components/voiceTyping/SpeechToTextBanner.tsx [hunk 1]
```diff
@@ -43,8 +38,8 @@ const useVoiceTyping = ({ locale, provider, onSetPreview, onText }: UseVoiceTypi
 	voiceTypingRef.current = voiceTyping;
 
 	const builder = useMemo(() => {
-		return new VoiceTyping(locale, provider?.startsWith('whisper') ? [whisper] : [vosk]);
-	}, [locale, provider]);
+		return new VoiceTyping(locale, [whisper]);
+	}, [locale]);
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/voiceTyping/SpeechToTextBanner.tsx:42]: With this change, the `provider` setting is no longer used and voice typing defaults to Whisper.
