### PR TITLE
Desktop: Fixes #8535: Fix CodeMirror context menu not containing correct items

### LINKED ISSUE #8535: Joplin 2.12.7 - Display glitches
Windows 11 Pro 22H2

Joplin 2.12.7 : 
Right click menus for plugins have disappeared 

In **Joplin 2.12.5** (prod, win32)

Joplin 2 12 5

In **Joplin 2.12.7** (prod, win32)

Client ID: 5b723f0bee17477db971add186a7fcf6
Sync Version: 3
Profile Version: 43
Keychain Supported: No
Revision: 04f8e96

Joplin 2 12 7_a

And also :
Submenus are overlapping the top menus

Joplin 2 12 7_b

Plugins installed

Admonition markdown extension: 1.1.0
Bidirectional Links: 0.1.2
Combine notes: 1.0.1
Convert Text To New Note: 1.5.1
Cursor Sync: 2.1.0
Embed Search: 2.0.0
Enhancement: 1.2.1
Markdown Prettier: 0.1.0
Menu items, Shortcuts, Toolbar icons: 1.1.0
Note Tabs: 1.4.0
Simple Backup: 1.3.3
Victor: 1.0.0

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary
Should partially fix #8535.

## The issue
The default context menu shown in [`electron-context-menu.js`](https://github.com/laurent22/joplin/blob/087b20698218675c1e92b88be0e95df734d0e2c2/packages/app-desktop/services/electron-context-menu.js#L236) was conflicting with the context menu shown in `CodeMirror.tsx`.

With the upgrade to Electron 25, the reported `inputFieldType` for a `textarea` changed from `none` to `plainText` when spellcheck is disabled. This broke logic in `bridge.ts` that previously prevented the default context menu from being shown.

Additionally, this broke the logic that caused a custom context menu to be shown for the CodeMirror editor.

This pull request replaces the logic in `bridge.ts` that originally prevented the default context menu from being displayed with a check for whether the context menu event has had `.preventDefault` called by another event listener.

The listener in `CodeMirror.tsx` is now registered with `prependListener` so that it is called before the default context menu listener. The `CodeMirror.tsx` listener additionally calls `.preventDefault` to prevent the default context menu from being displayed.

# Testing

To verify that the updated CodeMirror context menu is working correctly,
1. Install a plugin that adds items to the context menu (e.g. Rich Markdown)
2. Restart Joplin
3. Using the CodeMirror editor, add a checklist
4. Right click on an item in the checklist

In step 4, a "Toggle Checkbox" item should be visible.

5. Enable spellcheck in the markdown editor
6. Add a misspelled checklist item
7. Right-click on the misspelling and correct it
8. Right-click on a note
9. Right-click in the rich text editor

This has been tested on Ubuntu 23.10.

### CODE REVIEW

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx [hunk 1]
```diff
@@ -782,20 +783,25 @@ function CodeMirror(props: NoteBodyEditorProps, ref: any) {
...
+			const x = params.x, y = params.y, isEditable = params.isEditable;
 			const elements = document.getElementsByClassName('codeMirrorEditor');
 
-			// inputFieldType: The input field type of CodeMirror is "textarea" so the inputFieldType = "none",
-			// and any single-line input above codeMirror has inputFieldType value according to the type of input e.g.(text = plainText, password = password, ...).
-			if (!elements.length || !isEditable || inputFieldType !== 'none') return null;
+			// Note: We can't check inputFieldType here. When spellcheck is enabled,
+			// params.inputFieldType is "none". When spellcheck is disabled,
+			// params.inputFieldType is "plainText". Thus, such a check would be inconsistent.
+			if (!elements.length || !isEditable) return null;
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx]: This logic can still be improved. With the current checks, it's possible that a password field in a dialog could pass these checks.

One way to improve this would be to check the value of `event.target` in the browser (not the electron) `contextmenu` event and use that in the above check.
