### PR TITLE
Desktop: Fixes #4767: Create own copy of images while pasting

### LINKED ISSUE #4767: Jolpin doesn't create it's own copy of images while pasting
(Note from moderator: Related to https://github.com/laurent22/joplin/issues/4602)

## Environment

Joplin version: 1.8.1
Platform: Linux
OS specifics: Deepin

## Steps to reproduce

1. Open an offline doc editor like LibreOffice.
2. Write some text. Insert an image below to it.
3. Select all and Copy (Ctrl A + Ctrl C)
4. Paste it in Joplin. (You can notice the image is dependent on the third-party file made by the local editor.)
5. Close LibreOffice without saving the document.
6. Restart Joplin.
7. Observe that image is not showing (it's broken).

## Describe what you expected to happen

The image should be present. It's a normal use case for example I start making a document in LibreOffice and now want to shift it to Joplin.

## Probable Solution

Maybe while pasting we could check if it contains any images, if it does we create a local Joplin resource for that image.

### PR DESCRIPTION
**Pull request by nishantwrp**
Create own copy of images while pasting. Fixes #4767 

## Testing

- Wrote unit tests for util function.
- Copied the content from both local and online doc editors (LibreOffice Writer and Google Docs) and verified that Joplin can now create it's own copy of images correctly.

### CODE REVIEW

File: packages/lib/htmlUtils.ts [hunk 1]
```diff
@@ -30,6 +30,17 @@ const selfClosingElements = [
...
+async function replaceAsync(str: string, regex: RegExp, asyncFn: Function) {
+	const promises: Promise<any>[] = [];
+	str.replace(regex, (match: string, ...args) => {
+		const promise = asyncFn(match, ...args);
+		promises.push(promise);
+		return null;
+	});
+	const data = await Promise.all(promises);
+	return str.replace(regex, () => data.shift());
+}
```
Comment (nishantwrp) [inline packages/lib/htmlUtils.ts:42]: Had to create this function to allow async callback in `replaceImageUrlsAsync` function.

**Comment by nishantwrp** [comment]
@laurent22 Please review. (I know that @-mention is not allowed but since 5 days passed with no reviews)

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts [hunk 2]
```diff
@@ -125,3 +126,17 @@ export async function handlePasteEvent(event: any) {
...
+			const createdResource = await shim.createResourceFromPath(imageSrc.substr(7));
+			return `file://${Resource.fullPath(createdResource)}`;
+		} else {
+			const filePath = `${Setting.value('tempDir')}/${md5(Date.now())}`;
+			await shim.fetchBlob(imageSrc, { path: filePath });
+			const createdResource = await shim.createResourceFromPath(filePath);
+			return `file://${Resource.fullPath(createdResource)}`;
+		}
+	});
+}
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts:142]: Rather than create a duplicate `replaceImageUrlsAsync` function, could you use the existing one `replaceImageUrls` in the following way:
- Loop through all the images using replaceImageUrls, and collect all the urls
- Process these `file://`, creating resources for each one and store the result in an associative array
- Run again replaceImageUrls, this time replacing the urls with the resource URL you've created

Also what happens if I paste some HTML text that contains a Joplin resource? According to your code it seems you would be duplicating the resource.

File: packages/app-desktop/gui/NoteEditor/utils/contextMenu.ts [hunk 3]
```diff
@@ -112,7 +113,12 @@ export function menuItems(): ContextMenuItems {
 		paste: {
 			label: _('Paste'),
 			onAction: async (options: ContextMenuOptions) => {
-				const content = clipboard.readHTML() ? clipboard.readHTML() : clipboard.readText();
+				let content = clipboard.readHTML() ? clipboard.readHTML() : clipboard.readText();
+
+				if (clipboard.readHTML()) {
+					content = await processPastedHtml(clipboard.readHTML());
+				}
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/utils/contextMenu.ts:120]: Please store the result of readHTML in a variable so as not to read it twice.

File: packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx [hunk 4]
```diff
@@ -1032,6 +1032,14 @@ const TinyMCE = (props: NoteBodyEditorProps, ref: any) => {
 					// HACK: TinyMCE doesn't add an undo step when pasting, for unclear reasons
 					// so we manually add it here. We also can't do it immediately it seems, or
 					// else nothing is added to the stack, so do it on the next frame.
+
+					const pastedHtml = clipboard.readHTML();
+					if (pastedHtml) {
+						event.preventDefault();
+						const modifiedHtml = await processPastedHtml(pastedHtml);
+						editor.insertContent(modifiedHtml);
+					}
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx:1041]: Does that work as expected if I select some text, then press Ctrl+V? Normally it should clear the selected text and replace it with the new one.

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts (hunk 2 above)
Comment (nishantwrp) [reply packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts]: Done. Also, modified the function to not create duplicate resources.

File: packages/app-desktop/gui/NoteEditor/utils/contextMenu.ts (hunk 3 above)
Comment (nishantwrp) [reply packages/app-desktop/gui/NoteEditor/utils/contextMenu.ts]: done

File: packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx (hunk 4 above)
Comment (nishantwrp) [reply packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx:1041]: Yes, it does work as expected.

**Comment by nishantwrp** [comment]
Hi, I've addressed all the review comments.

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts [hunk 5]
```diff
@@ -125,3 +126,40 @@ export async function handlePasteEvent(event: any) {
...
+						mappedResources[imageSrc] = `file://${Resource.fullPath(createdResource)}`;
+					}
+				} else {
+					const filePath = `${Setting.value('tempDir')}/${md5(Date.now())}`;
+					await shim.fetchBlob(imageSrc, { path: filePath });
+					const createdResource = await shim.createResourceFromPath(filePath);
+					mappedResources[imageSrc] = `file://${Resource.fullPath(createdResource)}`;
+				}
+			} catch (err) {
+				mappedResources[imageSrc] = imageSrc;
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts:157]: Please log a warning in this case. Create a new logger `const logger = Logger.create('resourceHandling');` then `logger.warn('......')`

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts [hunk 6]
```diff
@@ -125,3 +126,40 @@ export async function handlePasteEvent(event: any) {
...
+						mappedResources[imageSrc] = imageSrc;
+					} else {
+						const createdResource = await shim.createResourceFromPath(imageFilePath);
+						mappedResources[imageSrc] = `file://${Resource.fullPath(createdResource)}`;
+					}
+				} else {
+					const filePath = `${Setting.value('tempDir')}/${md5(Date.now())}`;
+					await shim.fetchBlob(imageSrc, { path: filePath });
+					const createdResource = await shim.createResourceFromPath(filePath);
+					mappedResources[imageSrc] = `file://${Resource.fullPath(createdResource)}`;
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts:154]: temp file needs to be deleted after the resource has been created

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts [hunk 7]
```diff
@@ -125,3 +126,40 @@ export async function handlePasteEvent(event: any) {
...
+		allImageUrls.push(src);
+	});
+
+	for (const imageSrc of allImageUrls) {
+		if (!mappedResources[imageSrc]) {
+			try {
+				if (imageSrc.startsWith('file')) {
+					const imageFilePath = imageSrc.substr(7);
+
+					if (imageFilePath.startsWith(Setting.value('resourceDir'))) {
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts:144]: To compare the paths, please use `path.normalize()` on each of them first. This is in case one of the paths use backslashes and the other forward slashes for example.

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts [hunk 8]
```diff
@@ -125,3 +126,40 @@ export async function handlePasteEvent(event: any) {
...
+						mappedResources[imageSrc] = imageSrc;
+					} else {
+						const createdResource = await shim.createResourceFromPath(imageFilePath);
+						mappedResources[imageSrc] = `file://${Resource.fullPath(createdResource)}`;
+					}
+				} else {
+					const filePath = `${Setting.value('tempDir')}/${md5(Date.now())}`;
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts:151]: `md5(Date.now())` doesn't make sense since it's the same as using `Date.now()` on its own. Please add `Math.random()` into the mix.

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts (hunk 5 above)
Comment (nishantwrp) [reply packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts:157]: done

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts (hunk 6 above)
Comment (nishantwrp) [reply packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts:158]: okay, done.

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts (hunk 7 above)
Comment (nishantwrp) [reply packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts]: done.

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts (hunk 8 above)
Comment (nishantwrp) [reply packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts]: oh ok. done.

**Comment by nishantwrp** [comment]
Hi, I've addressed all the review comments. Please re-review.

File: packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts (hunk 5 above)
Comment (laurent22) [reply packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts:163]: Check how and in particular **where** the logger is declared in other files.

Comment (nishantwrp) [reply packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts:163]: Actually, in this file itself, the logger is used using `reg`, as follows.

```javascript
reg.logger().error(error);
```

Comment (nishantwrp) [reply packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts:163]: Should I use it in this way?

Comment (laurent22) [reply packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts:163]: I'll fix it.

**Comment by laurent22** [comment]
@nishantwrp, your pull request broke a number of things with copy and paste:

1. When pasting plain text, all new lines are removed

2. When pasting an image, the cursor jumps back to the top of the note. It's this bug: https://github.com/laurent22/joplin/issues/4591

Both these bugs go away if I remove your code so it's definitely related. Do you know what might be the issue by any chance? One thing I've noticed is that `clipboard.readHTML()` is going to return something even if it's only plain text in the clipboard. So you should use the browser API `event.clipboardData.getData('text/html')` instead. But that doesn't solve the cursor jumping to the top of the note.

**Comment by nishantwrp** [comment]
Oh had no idea about these. Will investigate the issues asap and find what is causing it and make a fix.

**Comment by nishantwrp** [comment]
Hi @laurent22,

As you found a fix to the issue `When pasting plain text, all new lines are removed`, I investigated issue #4591.

Are you sure that this issue is due to this PR? I'm asking because I checked out to this [commit](https://github.com/laurent22/joplin/commit/a6caa357c8df77a77ceedfa74904dd18c0d95e96) and still was able to reproduce the issue. 

According to my research, the real issue seems to be the following function.

https://github.com/laurent22/joplin/blob/77b284f01fa9af686023f2ee2c822548e4b9b21d/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx#L936

This is because I tried commenting out the following line and the issue was gone.

https://github.com/laurent22/joplin/blob/77b284f01fa9af686023f2ee2c822548e4b9b21d/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx#L987

Apparently, this function causes the note to re-render when there is a new image in the note.

**Comment by laurent22** [comment]
So are you planning to create a pull request to fix the pasting issue? Not being able to paste plain text in a text editor is a major regression, so I need to know if you plan to do something or not, and it's a bit urgent.

Same question for the cursor jump issue. Are you planning to create a pull request with your findings? We need to know where we stand with all these, if something's going to be done about it.

**Comment by nishantwrp** [comment]
Yup sure. I'll create a pr for them by today. I just wanted to confirm by findings about the cursor jump issue with you first.

**Comment by laurent22** [comment]
I don't know about the cursor issue. Best would be to give it a try and see if it can fix the issue.

**Comment by nishantwrp** [comment]
Hi,
I was investigating this solution #4591, I couldn't really find the proper root cause for the issue. But here are some observations

- This issue is unrelated to this PR and was present from a long time. The actual bug is that when you copy an image in the clipboard (clipboard should have the image as content not HTML or text) and paste it in the WYSIWYG editor, the cursor moves to the top. 
- This issue is not only limited to the pasting of image, removing the image also results in cursor moving to the top.
-  It has something to do with the following function
https://github.com/laurent22/joplin/blob/77b284f01fa9af686023f2ee2c822548e4b9b21d/packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx#L936

Apparently, this function causes the cursor to move to the top when there is an image added/removed in the note.

**Comment by nishantwrp** [comment]
And about the `When pasting plain text, all new lines are removed`, I couldn't really understand the bug here that would've caused by this PR.

**Comment by laurent22** [comment]
Ok the sense I had from your initial comment is that you didn't know how to fix the issue, so next time please just say so right away, as that will save us time. Since you aren't going to fix it and it's a critical bug, I'll look into it.

**Comment by nishantwrp** [comment]
I'll take care of that from now. As I was not able to find a fix for the issue I posted my research on the issue above, that might be helpful while looking into the issue.

**Comment by laurent22** [comment]
That's the fix for the first issue, so as you can see if was in the code you've added: https://github.com/laurent22/joplin/commit/9e9bf63d706d28d4a725be870b313b807705c32c Also a bit surprised you didn't figured it out considering I've pretty much told what the issue was.

**Comment by laurent22** [comment]
You've also broken pasting HTML because TinyMCE normally applies certain filters to the HTML so that it's pasted correctly, but you've overridden this behaviour. That's three bugs in this feature. So if you're going to work on the codebase after that please be careful. Test your changes with various inputs and be absolutely sure you didn't introduce a regression.

Adding new features is the fun part, but you also need to be responsible for fixing your own bugs afterwards.

**Comment by nishantwrp** [comment]
> That's the fix for the first issue, so as you can see if was in the code you've added: [9e9bf63](https://github.com/laurent22/joplin/commit/9e9bf63d706d28d4a725be870b313b807705c32c) Also a bit surprised you didn't figured it out considering I've pretty much told what the issue was.

Oh, okay. Yup, I noticed you already provided the probable solution for this bug. Actually, I didn't know what exactly the bug was so, I could reproduce the bug. Anyways, you're right I should've figured out this.

**Comment by nishantwrp** [comment]
> You've also broken pasting HTML because TinyMCE normally applies certain filters to the HTML so that it's pasted correctly, but you've overridden this behaviour. That's three bugs in this feature. So if you're going to work on the codebase after that please be careful. Test your changes with various inputs and be absolutely sure you didn't introduce a regression.

Oh, didn't knew that TinyMCE alters the HTML while pasting. You're right I should've researched about it a bit before overrides the default behavior. I'll make sure to test everything before making a PR in the future.

**Comment by nishantwrp** [comment]
Just one doubt, does this commit (https://github.com/laurent22/joplin/commit/2226b79c46b3860c0d8732a7c366daf12236b3ff) also solve the cursor jumping to the top issue?

**Comment by laurent22** [comment]
> Just one doubt, does this commit ([2226b79](https://github.com/laurent22/joplin/commit/2226b79c46b3860c0d8732a7c366daf12236b3ff)) also solve the cursor jumping to the top issue?

No, it fixes the HTML filtering issue I mentioned above as well as improve pasting plain text (which is not related to your work).

**Comment by laurent22** [comment]
> Oh, didn't knew that TinyMCE alters the HTML while pasting. You're right I should've researched about it a bit before overrides the default behavior. I'll make sure to test everything before making a PR in the future.

No problem, there's value regardless in the feature you've added. I just want to highlight that even when it seems a feature is "done", it might turn out there's still a lot to do. These extra glitches and bugs introduced by new features aren't minor issues and we of course can't allow them to accumulate over time.
