### PR TITLE
Desktop: Fix #5626: When web clipper clipping code blocks, keep code in multiline and delete code number lines

### LINKED ISSUE #5626: Web clipper not clipping code snippets properly
When I clip content with the webclipper, newlines are removed from code blocks. The result is one long line rather than a code block in Joplin.

## Environment

Joplin version: 2.4.9
Webclipper version: 2.1.3
Browser: Brave version 1.31.87 Chromium: 95.0.4638.54
Platform: Windows 10

## Steps to reproduce

1. Go to https://devblogs.microsoft.com/dotnet/http-3-support-in-dotnet-6/
2. Use 'clip simplified page' feature of webclipper (same issue happens with other approaches).
3. Go to Joplin and find second code block in Markdown. That contains:

```
public  static  async  Task  Main(string[] args)  {  var builder =  WebApplication.CreateBuilder(args); builder.WebHost.ConfigureKestrel((context, options)  =>  { options.Listen(IPAddress.Any,  5001, listenOptions =>  {  // Use HTTP/3 listenOptions.Protocols  =  HttpProtocols.Http1AndHttp2AndHttp3; listenOptions.UseHttps();  });  });  }
```

But the actual code example in the blog post is:

```
public static async Task Main(string[] args)
{
  var builder = WebApplication.CreateBuilder(args);
  builder.WebHost.ConfigureKestrel((context, options) =>
  {
    options.Listen(IPAddress.Any, 5001, listenOptions =>
    {
      // Use HTTP/3
      listenOptions.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
      listenOptions.UseHttps();
    });
  });
}
```

1. Go to https://gomakethings.com/boolean-shorthands-and-truthiness/
2. Clip the simplified page with the web clipper.
3. Go to Joplin. The first code example in the Markdown is:

```
// Split the text content into an array, using spaces to break words // Use Array.filter() to remove any words without a length // (this removes double spaces in the content) let words = text.value.split(' ').filter(function (word) {
	return word.length;
}); 
```

But the formatting based on the website should be:

```
// Split the text content into an array, using spaces to break words
// Use Array.filter() to remove any words without a length
// (this removes double spaces in the content)
let words = text.value.split(' ').filter(function (word) {
	return word.length;
});
```

## Describe what you expected to happen
I would expect the note to keep the newlines from the original page.

## Logfile
There are no errors or warnings in the Developer Tool's window when clipping.

---

Thanks for your consideration and let me know if I can provide more information.

### PR DESCRIPTION
**Pull request by wljince007**
Desktop: Fix #5626: when clipper, keep code in multiline and delete code number lines

# See an example, clipper from  https://blog.csdn.net/qq_42025798/article/details/121727781, 
## html look:
image

## befor this modify, web clipper clipping code blocks, code blocks are in one line:
image

## after this modify, web clipper clipping code blocks, code blocks are in multiline, readability is good:
image

### CODE REVIEW

**Comment by laurent22** [comment]
We would need test units for this, but even then I don't understand what is being fixed at the moment

**Comment by personalizedrefrigerator** [comment]
> what is being fixed at the moment

From the description, this seems to fix #5626 (closed due to inactivity).

**Edit**: For reference, tests for existing Webclipper HTML->MD logic [can be found here](https://github.com/laurent22/joplin/blob/dev/packages/app-cli/tests/html_to_md/pre_1.md).

**Comment by wljince007** [comment]
Yes it is. this PR try to fix #5626, I well trying to add test units.

**Comment by wljince007** [comment]
@laurent22  Add test units packages/app-cli/tests/html_to_md/{code_multiline_1.html,code_multiline_2.html} run ok.

File: packages/turndown/src/commonmark-rules.js [hunk 1]
```diff
@@ -266,6 +266,9 @@ rules.fencedCodeBlock = {
 
     var fence = repeat(fenceChar, fenceSize)
 
+    // delete code number lines
+    code = code.replace(/(^-\s+\d+\s*$\r?\n)+/gm, '');
+
```
Comment (laurent22) [inline packages/turndown/src/commonmark-rules.js]: I'm concerned that this may also remove information that shouldn't be removed from certain code blocks. In the comment above could clarify exactly what strings are being removed? (as I'm unable to read that regex)

Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js]: This regular expression removes consecutive lines of code that start with a - followed by a number. The regular expression marker `/gm ` means that each line break is separated by a line, and can be perfectly matched with a line using` (^ - \ s+\ d+\ s * $\ r? \ n) `

Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js]: Ref: [RegExp.prototype.multiline](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/multiline)

Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js]: @laurent22  Match the lines: 
image

Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js]: Continuous lines of code starting with - followed by numbers are basically useless information.

Comment (personalizedrefrigerator) [reply packages/turndown/src/commonmark-rules.js]: It might make more sense to ignore code-block children of type `ul` with class `pre-numbering`. This should also match line numbers in the second example provided.

This would allow the web clipper (and perhaps also the Rich Text Editor) to save blocks that contain lists of numbers, while also removing line numbers.

Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js]: Thank you for your patient guidance. I will try to modify the code using the method you mentioned.

Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js]: @personalizedrefrigerator   Already edit rules.list as your guidance. Test units run ok. Thanks a lot.

Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js]: > I'm concerned that this may also remove information that shouldn't be removed from certain code blocks. 

@laurent22   This regular replacement code has been removed.

File: packages/turndown/src/commonmark-rules.js [hunk 2]
```diff
@@ -465,9 +469,18 @@ rules.code = {
...
-    if (!content) return ''
-    content = content.replace(/\r?\n|\r/g, ' ')
+  replacement: function (content, node, options) {
+    if (!content) {
+      return ''
+    }
+
+    content = content.replace(/\r?\n|\r/g, '\n')
+    // if code is multiline and in codeBlock, just return it, codeBlock well add fence(default is ```)
+    if (content.indexOf('\n') != -1 && node.parentNode && isCodeBlock(node.parentNode)){
```
Comment (laurent22) [inline packages/turndown/src/commonmark-rules.js]: Please always use strict inequality `!==`

**Comment by personalizedrefrigerator** [comment]
I've noticed that the web clipper has trouble with code blocks on Joplin's website (e.g. the [table of contents plugin tutorial page](https://joplinapp.org/help/api/tutorials/toc_plugin)). Do you know if this pull  request would also fix processing of those code blocks?

(Thank you for taking the time to work on this!)

**Comment by wljince007** [comment]
Not fixed yet：

image

# save md to :

image

I will try to track and find out the reason later on.

File: packages/turndown/src/commonmark-rules.js (hunk 2 above)
Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js]: Thanks, fixed, submitted.

**Comment by wljince007** [comment]
> I've noticed that the web clipper has trouble with code blocks on Joplin's website

Add `packages/turndown/src/commonmark-rules.js/rules.joplinOrgTokenLineSpan` to fix this. 

Copy first code blocks from: [toc_plugin](https://joplinapp.org/help/api/tutorials/toc_plugin)

## html looks:
image

## befor `rules.joplinOrgTokenLineSpan` added, on Joplin 2.13.15, save md looks:
image
 
## after `rules.joplinOrgTokenLineSpan` added,  save md looks:
image

**Comment by wljince007** [comment]
Can the rules of commonmark-rules.js in Turndown be exported as APIs for plugin systems? I am not sure if the current plugin's API already includes such an API. This way, plugins can be written instead of providing PR to Joblin to solve problems such as incorrect line breaks in code blocks.

File: packages/turndown/src/commonmark-rules.js [hunk 3]
```diff
@@ -478,6 +492,23 @@ rules.code = {
...
+    return node.nodeName === 'SPAN' && node.getAttribute('class') === 'token-line' && grandfather && isCodeBlock(grandfather); 
+  },
+
+  replacement: function (content, node, options) {
+    content = content.replace(/\r?\n|\r/g, '');
+    // If content replaced '\r\n' is empty, it indicates that the line is empty line; if not, keep the leading before and after content.
+    return content === '' ? '\n\n' :  node.flankingWhitespace.leading + content + node.flankingWhitespace.trailing + '\n';
+  }
+}
+
```
Comment (laurent22) [inline packages/turndown/src/commonmark-rules.js]: I'm struggling to review this, I don't really understand what it does

Comment (laurent22) [reply packages/turndown/src/commonmark-rules.js]: @personalizedrefrigerator, was this for the bug you mentioned, and does the fix make sense to you?

Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js:511]: Web clipper clipping contents from Joplin's website is all in one line. The format features are: <pre ...><code ...><span class="token-line"><span class="...">....  Span with class of "token-line" represent one line.

Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js:511]: At present, users can write plugins that use Renderer's plugin API to affect the process of MdToHtml. At the same time, users may also need Turndown's plugin API to write plugins that affect the process of HtmlToMd. Please consider adding a plugin API for Turndown.

Comment (personalizedrefrigerator) [reply packages/turndown/src/commonmark-rules.js]: > @personalizedrefrigerator, was this for the bug you mentioned, and does the fix make sense to you?

This was the bug I mentioned, however I'm not sure that the fix makes sense to me. I think the issue here is that the `<br/>`s at the end of Docusaurus code blocks aren't being converted to linebreaks by Turndown.

For context, I've attached simplified HTML for a Docusaurus code block (taken from [here](https://docusaurus.io/docs/create-doc#doc-front-matter)):
````html
<code class="codeBlockLines_FJaf">
    <span class="token-line" style="color: rgb(212, 212, 212);">
        <span class="token front-matter-block punctuation" style="color: rgb(212, 212, 212);">---</span>
        <br>
    </span>
    <span class="token-line" style="color: rgb(212, 212, 212);">
        <span class="token front-matter-block"></span>
        <span class="token front-matter-block front-matter yaml language-yaml key atrule" style="color: rgb(86, 156, 214);">id</span>
        <span class="token front-matter-block front-matter yaml language-yaml punctuation" style="color: rgb(212, 212, 212);">:</span>
        [...]
        <br>
    </span>
    [...]
    <span class="token-line" style="color: rgb(212, 212, 212);">
        <span class="token front-matter-block"></span>
        <span class="token front-matter-block punctuation" style="color: rgb(212, 212, 212);">---</span>
        <br>
    </span>
</code> 
````
Observe that each (inline) `token-line` span ends with a `<br>` that previously wasn't detected by Turndown.

Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js:511]: Actually `<br/>` has been correctly parsed.
The key to the problem is, if span with class "token keyword", turndown added line breaks before and after span, please see the parsing results of `async` and `function`.

`nStart: async function() {` in code blocks, it html is:

```
<span class="token-line" style="color: rgb(57, 58, 52); --darkreader-inline-color: #c5c0b9;" data-darkreader-inline-color="">
	<span class="token plain">    </span>
	<span class="token function-variable function" style="color: rgb(215, 58, 73); --darkreader-inline-color: #da4b58;" data-darkreader-inline-color="">onStart</span>
	<span class="token operator" style="color: rgb(57, 58, 52); --darkreader-inline-color: #c5c0b9;" data-darkreader-inline-color="">:</span>
	<span class="token plain"> </span>
	<span class="token keyword" style="color: rgb(0, 0, 159); --darkreader-inline-color: #6da2ff;" data-darkreader-inline-color="">async</span>
	<span class="token plain"> </span>
	<span class="token keyword" style="color: rgb(0, 0, 159); --darkreader-inline-color: #6da2ff;" data-darkreader-inline-color="">function</span>
	<span class="token punctuation" style="color: rgb(57, 58, 52); --darkreader-inline-color: #c5c0b9;" data-darkreader-inline-color="">(</span>
	<span class="token punctuation" style="color: rgb(57, 58, 52); --darkreader-inline-color: #c5c0b9;" data-darkreader-inline-color="">)</span>
	<span class="token plain"> </span>
	<span class="token punctuation" style="color: rgb(57, 58, 52); --darkreader-inline-color: #c5c0b9;" data-darkreader-inline-color="">{</span>
	<span class="token plain"></span>
	<br>
</span>
```





image

Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js:511]: If this fix `packages/turndown/src/commonmark-rules.js/rules.joplinOrgTokenLineSpan` is not suitable, can I roll back this submission and only fix # 5626?

**Comment by wljince007** [comment]
One of the main goals of Joplin's 3.0 version development is to add mobile plugin functionality. Can we take this opportunity to add a user script type for `ContentScriptType.TurndownPlugin`? So that users can write plugins to affect the process of 'HtmlToMd'. I think this feature is missing in the current Joplin plugin system.

File: packages/turndown/src/commonmark-rules.js (hunk 3 above)
Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js]: Remove `packages/turndown/src/commonmark-rules.js/rules.joplinOrgTokenLineSpan`. Analyze the current code, find the reasons for incorrect formatting in the code block, modify code for preserve the line break formatting for code block. Web clipper clipping code blocks on Joplin's website run ok.  Test case run ok.

**Comment by wljince007** [comment]
# copy [4-1.实体类](https://blog.csdn.net/qq_42025798/article/details/121727781#t15) code block: 
packages/turndown/src/commonmark-rules.js[rules.list] : Ignore code-block children of type ul with class pre-numbering.
packages/turndown/src/commonmark-rules.js[rules.code]: If code is multiline and in codeBlock, just return it, codeBlock well add fence
image
test case: packages/app-cli/tests/html_to_md/code_multiline_2.html


# copy first code block from: [toc_plugin](https://joplinapp.org/help/api/tutorials/toc_plugin/)
packages/lib/HtmlToMd.ts[turndownOpts.blankReplacement]: keep blank be empty in code block, not replaced to line break.
packages/turndown/src/turndown.js[replacementForNode] : If in code block, line breaks not trim
image
test case: packages/app-cli/tests/html_to_md/code_multiline_3.html


# copy first code block from: [JavaScript trim strings](https://blog.csdn.net/ch5256865/article/details/52957360)
packages/turndown/src/commonmark-rules.js[rules.listItem] : remove ordered list in code blocks 
packages/turndown/src/commonmark-rules.js[rules.fencedCodeBlock] : remove code block leading and trailing newlines
image
test case: packages/app-cli/tests/html_to_md/code_multiline_4.html

**Comment by laurent22** [comment]
That looks like a good improvement, thanks @wljince007 for working on this!

@personalizedrefrigerator, would you mind double-checking the code in case I missed something please?

**Comment by laurent22** [comment]
> One of the main goals of Joplin's 3.0 version development is to add mobile plugin functionality. Can we take this opportunity to add a user script type for `ContentScriptType.TurndownPlugin`? So that users can write plugins to affect the process of 'HtmlToMd'. I think this feature is missing in the current Joplin plugin system.

We could discuss it but you might want to create a thread on the forum about it. If you could mention example plugins that could benefit from it that could help decide if we add this or not

File: packages/app-cli/tests/html_to_md/code_multiline_1.html [hunk 4]
```diff
@@ -0,0 +1,24 @@
+<!-- this if from: https://devblogs.microsoft.com/dotnet/http-3-support-in-dotnet-6/ -->
```
Comment (personalizedrefrigerator) [inline packages/app-cli/tests/html_to_md/code_multiline_1.html]: I'm not seeing this `bubbleSort` implementation on the linked website (though I may have missed it! I only looked briefly.). Does the URL need to be updated?

File: packages/turndown/src/commonmark-rules.js [hunk 5]
```diff
@@ -185,34 +190,44 @@ rules.listItem = {
         .replace(/\n+$/, '\n') // replace trailing newlines with just a single one
 
     var prefix = options.bulletListMarker + ' '
-    content = content.replace(/\n/gm, '\n    ') // indent
+    if (node.isCode===false) {
```
Comment (personalizedrefrigerator) [inline packages/turndown/src/commonmark-rules.js]:
```suggestion
    if (node.isCode === false) {
```

**Non-blocking/style**: This is a very minor stylistic suggestion. Feel free to ignore it :).

File: packages/turndown/src/turndown.js [hunk 6]
```diff
@@ -241,8 +241,34 @@ function replacementForNode (node, previousNode) {
...
+      // if isCode, keep line breaks
+      //test case: packages/app-cli/tests/html_to_md/code_multiline_3.html
+
+      //If the leading blank of current node or leading blank of current node including line breaks, and the leading blank of current node is equal to the leading blank of it's first child node, and the trailing blank of the current node is equal to the leading blank of it's last child node, it indicates that the leading blank and leading blank of current node is from it's child nodes, so should not be added repeatedly, this remove multiple line breaks.
+      //test case: packages/app-cli/tests/html_to_md/code_multiline_5.html
+      if ( (whitespace.leading.indexOf('\n') !== -1 || whitespace.trailing.indexOf('\n') !== -1) && 
+        node.childNodes && node.childNodes.length > 0) {
+
+        var firstChileWhitespace = node.childNodes[0].flankingWhitespace
+        var lastChileWhitespace = node.childNodes[node.childNodes.length-1].flankingWhitespace
```
Comment (personalizedrefrigerator) [inline packages/turndown/src/turndown.js]:
```suggestion
        var firstChildWhitespace = node.childNodes[0].flankingWhitespace
        var lastChildWhitespace = node.childNodes[node.childNodes.length-1].flankingWhitespace
```

File: packages/turndown/src/commonmark-rules.js [hunk 7]
```diff
@@ -266,6 +281,9 @@ rules.fencedCodeBlock = {
 
     var fence = repeat(fenceChar, fenceSize)
 
+    // remove code block leading and trailing newlines
+    code = code.replace(/^( *\t*\n)+/, '').replace(/( *\t*\n)+( *\t*)*$/, '')
```
Comment (personalizedrefrigerator) [inline packages/turndown/src/commonmark-rules.js]:
```suggestion
    // remove code block leading and trailing empty lines
    code = code.replace(/^( *\t*\n)+/, '').trimEnd()
```
Is `.replace(/( *\t*\n)+( *\t*)*$/, '')` equivalent to `.trimEnd()` in this case? If so, it could make sense to replace this.

**Review by personalizedrefrigerator — COMMENTED** [review]
I've left a few comments based on a quick read through the code.

Thank you for working on this!

File: packages/app-cli/tests/html_to_md/code_multiline_1.html (hunk 4 above)
Comment (wljince007) [reply packages/app-cli/tests/html_to_md/code_multiline_1.html]: yes, fix to https://flaviocopes.com/bubble-sort-javascript/

File: packages/turndown/src/commonmark-rules.js (hunk 5 above)
Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js]: thanks, fixed.

File: packages/turndown/src/commonmark-rules.js (hunk 7 above)
Comment (wljince007) [reply packages/turndown/src/commonmark-rules.js]: Yes, they are equal, fix to `code = code.replace(/^([ \t]*\n)+/, '').trimEnd()`

File: packages/turndown/src/turndown.js (hunk 6 above)
Comment (wljince007) [reply packages/turndown/src/turndown.js]: typo error, fixed

**Comment by wljince007** [comment]
> We could discuss it but you might want to create a thread on the forum about it. If you could mention example plugins that could benefit from it that could help decide if we add this or not

Add [Feature request: Add content script type of ContentScriptType.TurndownPlugin](https://discourse.joplinapp.org/t/feature-request-add-content-script-type-of-contentscripttype-turndownplugin/37484)

File: packages/app-cli/tests/html_to_md/code_multiline_5.html [hunk 8]
```diff
@@ -0,0 +1,42 @@
+<!-- this if from: https://www.slingacademy.com/article/python-aiohttp-how-to-download-files-using-streams/ -->
```
Comment (personalizedrefrigerator) [inline packages/app-cli/tests/html_to_md/code_multiline_5.html]:
```suggestion
<!-- this is from: https://www.slingacademy.com/article/python-aiohttp-how-to-download-files-using-streams/ -->
```

File: packages/turndown/src/commonmark-rules.js [hunk 9]
```diff
@@ -185,34 +190,44 @@ rules.listItem = {
...
-        // But not:
-        //
-        // 9.  my content
-        //     second line
-        // 10.  next one
-        //     second line
-        //
-        prefix = indexStr + '.' + ' '.repeat(3 - indexStr.length)
+        if (node.isCode) {
+          // remove ordered list in code blocks
```
Comment (personalizedrefrigerator) [inline packages/turndown/src/commonmark-rules.js]:
```suggestion
          // Ordered lists in code blocks are often for line numbers. Remove them. 
```

File: packages/turndown/src/commonmark-rules.js [hunk 10]
```diff
@@ -465,9 +483,19 @@ rules.code = {
...
-    if (!content) return ''
-    content = content.replace(/\r?\n|\r/g, ' ')
+  replacement: function (content, node, options) {
+    if (!content) {
+      return ''
+    }
+
+    content = content.replace(/\r?\n|\r/g, '\n')
+    // If code is multiline and in codeBlock, just return it, codeBlock well add fence(default is ```).
+    // See https://github.com/laurent22/joplin/pull/10126 .
```
Comment (personalizedrefrigerator) [inline packages/turndown/src/commonmark-rules.js]:
```suggestion
    // If code is multiline and in codeBlock, just return it, codeBlock will add fence(default is ```).
    //
    // This handles the case where a <code> element is nested directly within a <pre> and
    // should not be turned into an inline code region.
    //
    // See https://github.com/laurent22/joplin/pull/10126 .
```

Feel free to ignore this suggestion — I'm suggesting this change because I found the original comment difficult to understand.

File: packages/turndown/src/turndown.js [hunk 11]
```diff
@@ -241,8 +241,35 @@ function replacementForNode (node, previousNode) {
...
+        node.childNodes && node.childNodes.length > 0) {
+
+        var firstChildWhitespace = node.childNodes[0].flankingWhitespace
+        var lastChildWhitespace = node.childNodes[node.childNodes.length-1].flankingWhitespace
+
+        if (whitespace.leading === firstChildWhitespace.leading && 
+          whitespace.trailing === lastChildWhitespace.trailing){
+            content = content.trim()
+          }
+      }else {
```
Comment (personalizedrefrigerator) [inline packages/turndown/src/turndown.js]:
```suggestion
      } else {
```

File: packages/turndown/src/turndown.js [hunk 12]
```diff
@@ -241,8 +241,35 @@ function replacementForNode (node, previousNode) {
...
+      if ( (whitespace.leading.indexOf('\n') !== -1 || whitespace.trailing.indexOf('\n') !== -1) && 
+        node.childNodes && node.childNodes.length > 0) {
+
+        var firstChildWhitespace = node.childNodes[0].flankingWhitespace
+        var lastChildWhitespace = node.childNodes[node.childNodes.length-1].flankingWhitespace
+
+        if (whitespace.leading === firstChildWhitespace.leading && 
+          whitespace.trailing === lastChildWhitespace.trailing){
+            content = content.trim()
+          }
```
Comment (personalizedrefrigerator) [inline packages/turndown/src/turndown.js]:
```suggestion
        if (whitespace.leading === firstChildWhitespace.leading && 
          whitespace.trailing === lastChildWhitespace.trailing) {
            content = content.trim()
        }
```

**Review by personalizedrefrigerator — COMMENTED** [review]
I've tested this locally with Joplin's website and it works!!!

I've left a few minor stylistic/commenting suggestions. For the most part, I think this is ready to merge!

**Comment by wljince007** [comment]
Thank you for the revision. My English proficiency is relatively weak and annotations are not well expressed. Thank you for your guidance.

**Review by personalizedrefrigerator — APPROVED** [review]

**Comment by laurent22** [comment]
Thanks for implementing this @wljince007 and thanks for the review @personalizedrefrigerator!
