### PR TITLE
All: Fixes #14419: Added validation for Joplin Server URL protocol

### LINKED ISSUE #14419: Joplin server sync fails on iPad only
### Operating system

iOS

### Joplin version

13.5.3

### Desktop version info

It’s on iOS mobile

Joplin Mobile 13.5.3 (prod, ios)

Gerät: ios
Client-ID: d90e25c9405b4ee3945cb77313e35218
Sync-Version: 3
Profil-Version: 49
Unterstützter Schlüsselbund: Nein
Alternative Instanz ID: -

Revision: e75875c1b (release-3.5)

iOS-Version: 17.7.10
FTS aktiviert: 1
Hermes aktiviert: 1

### Current behaviour

I run a local Joplin server on docker and authenticate via authentik and the saml provider. In general this works (eg my iPhone).

It fails on my iPad Pro 1st gen, iOS 17.7.10 using the app.

I can start the flow and get the code on the browser pop up. However it is not accepted in the app. I just instantly get an error: the connection could not be established. Please try again. I can’t identify anything related in the logs on docker or the app?

### Expected behaviour

Complete the Authentication flow and sync

### Logs

[mobile-log.log](https://github.com/user-attachments/files/25462725/mobile-log.log)

### PR DESCRIPTION
**Pull request by Ash092016**
**Description**
Fixes #14419 

**What does this PR do?**
When setting up Joplin Server (SAML) or general WebDAV/Server synchronization, if a user enters the URL without the HTTP/HTTPS protocol prefix (e.g. `joplin.domain.de`), the Web-based SAML popup logic succeeds due to browser autofill behavior. However, the subsequent internal `fetch` API requests from the Joplin application fail instantly because a valid protocol prefix is required, resulting in a confusing error: `"the connection could not be established"`. 

This PR resolves this UX issue by:
1. Adding validation logic to [checkConfig](cci:1://file:///c:/Users/BIT/Desktop/joplin/packages/lib/SyncTargetJoplinServer.ts:82:1-144:2) in [SyncTargetJoplinServer](cci:2://file:///c:/Users/BIT/Desktop/joplin/packages/lib/SyncTargetJoplinServer.ts:44:0-165:1) and [SyncTargetJoplinServerSAML](cci:2://file:///c:/Users/BIT/Desktop/joplin/packages/lib/SyncTargetJoplinServerSAML.ts:54:0-143:1) that intercepts requests lacking an `http://` or `https://` prefix to return a clear, localized error prior to performing network calls.
2. Hooking an equivalent check directly into the Settings configuration flow ([packages/lib/models/settings/settingValidations.ts](cci:7://file:///c:/Users/BIT/Desktop/joplin/packages/lib/models/settings/settingValidations.ts:0:0-0:0)) to immediately flag invalid inputs when saving for targets `sync.5.path`, `sync.6.path`, `sync.9.path`, and `sync.11.path`.

**Testing:**
* Attempt to save or check settings with `joplin.domain.de` (verify the localized error string appears: _"The URL must include the protocol prefix (http:// or https://)."_).
* Attempt to save or check settings with `https://joplin.domain.de` (process continues normally).

### CODE REVIEW

**Comment by laurent22** [comment]
video is missing

File: packages/lib/models/settings/settingValidations.ts [hunk 1]
```diff
@@ -8,8 +8,20 @@ import Setting from '../Setting';
 // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Old code before rule was applied
 type ValidationHandler = (oldValue: any, newValue: any)=> Promise<string>;
 
+const validateUrlProtocol = async (_oldValue: string, newValue: string) => {
+	if (newValue && !newValue.match(/^https?:\/\//)) {
+		return _('The URL must include the protocol prefix (http:// or https://).');
```
[the remark this answers is not in the document]
Comment (Ash092016) [reply packages/lib/models/settings/settingValidations.ts]: Done! Thanks for pointing it out

**Comment by Ash092016** [comment]
Hi @laurent22 ! Entering a URL without the protocol prefix (`joplincloud.com`) now shows a clear, localized validation error: *"The URL must include the protocol prefix (http:// or https://)"*. Adding the prefix (`https://joplincloud.com`) passes validation and proceeds to connect normally.


https://github.com/user-attachments/assets/b364f788-26fb-4ed4-856b-16ec150c3596

File: packages/lib/SyncTargetJoplinServer.ts [hunk 2]
```diff
@@ -80,12 +80,18 @@ export default class SyncTargetJoplinServer extends BaseSyncTarget {
...
+	public static async checkConfig(options: FileApiOptions, syncTargetId: number = null, fileApi: FileApi | null = null) {
 		const output = {
 			ok: false,
 			errorMessage: '',
 		};
 
+		const path = options.path();
+		if (!path || !/^https?:\/\//i.test(path)) {
+			output.errorMessage = _('The URL must include the protocol prefix (http:// or https://).');
+			return output;
```
Comment (laurent22) [inline packages/lib/SyncTargetJoplinServer.ts:94]: Validation cannot be in two places - that needs to be fixed

File: packages/lib/SyncTargetJoplinServerSAML.ts [hunk 3]
```diff
@@ -87,8 +87,16 @@ export default class SyncTargetJoplinServerSAML extends SyncTargetJoplinServer {
 
 	public static override async checkConfig(fileApi: FileApiOptions) {
 		try {
+			const path = fileApi.path();
+			if (!path || !/^https?:\/\//i.test(path)) {
+				return {
+					ok: false,
+					errorMessage: _('The URL must include the protocol prefix (http:// or https://).'),
```
Comment (laurent22) [inline packages/lib/SyncTargetJoplinServerSAML.ts]: well looks like you have it in three places actually

**Comment by Ash092016** [comment]
Hi @laurent22 , I have refactored the URL protocol validation into a shared utility function validateUrlProtocol in **urlUtils.ts** and updated all three locations to use it. This removes the code duplication as requested. Thanks for the feedback!

File: packages/lib/SyncTargetJoplinServer.ts [hunk 4]
```diff
@@ -80,12 +81,19 @@ export default class SyncTargetJoplinServer extends BaseSyncTarget {
 		return super.fileApi();
 	}
 
-	public static async checkConfig(options: FileApiOptions, syncTargetId: number = null, fileApi: FileApi|null = null) {
+	public static async checkConfig(options: FileApiOptions, syncTargetId: number = null, fileApi: FileApi | null = null) {
```
Comment (laurent22) [inline packages/lib/SyncTargetJoplinServer.ts]: whitespace

File: packages/lib/SyncTargetJoplinServerSAML.ts [hunk 5]
```diff
@@ -54,7 +55,7 @@ export const authenticateWithCode = async (code: string) => {
 // Based on the regular Joplin Server sync target.
 export default class SyncTargetJoplinServerSAML extends SyncTargetJoplinServer {
 
-	private lastFileApiOptions_: FileApiOptions|null = null;
+	private lastFileApiOptions_: FileApiOptions | null = null;
```
Comment (laurent22) [inline packages/lib/SyncTargetJoplinServerSAML.ts]: whitespace

File: packages/lib/SyncTargetJoplinServerSAML.ts [hunk 6]
```diff
@@ -107,7 +117,7 @@ export default class SyncTargetJoplinServerSAML extends SyncTargetJoplinServer {
 						if (json.error) {
 							message = json.error;
 						}
-					} catch (_e) {} // eslint-disable-line no-empty -- Keep the plain text response as the error message, ignore the parsing exception
+					} catch (_e) { } // eslint-disable-line no-empty -- Keep the plain text response as the error message, ignore the parsing exception
```
Comment (laurent22) [inline packages/lib/SyncTargetJoplinServerSAML.ts]: whitespace

**Comment by Ash092016** [comment]
Hi @laurent22 , I have removed the extra whitespaces at the three locations mentioned. Ready for another look, thank you!

**Comment by laurent22** [comment]
Reverted in https://github.com/laurent22/joplin/pull/15384
