### PR TITLE
Mobile: Fixes #14975: Fix E2EE password validation: Upgrade react-native-quick-crypto to v1.0.19

### LINKED ISSUE #14975: Mobile: Entering the wrong password in encryption config causes local notes to be encryted with a corrupt or non-existent encryption key
### Operating system

Android

### Joplin version

3.6.14

### Desktop version info

_No response_

### Current behaviour

Reproduction steps:
1. On a new profile (profile A), setup file system sync
2. Enable encryption using password aaa
3. Sync the changes
4. Create a new profile and open it (profile B)
5. Setup file system sync to the same directory and click sync
6. Tap the banner to go to encryption config
7. Enter password bbb save it, the password will be saved onto the key, but it will ask for the master password above it
8. Enter password aaa and save it, then trigger sync
9. Go to the note list and observe that the notes from profile A were still not decrypted
10. Create a new profile (profile C) and open it
11. Setup file system sync to the same directory and click sync
12. Tap the banner to go to encryption config
13. Enter password aaa save it, then trigger sync
14. Observe that the notes from profile A were decrypted, but the notes from profile B are not, and there is a banner saying some items cannot be synchronized
15. Create a new profile (profile D) and open it
16. Setup file system sync to the same directory and click sync
17. Tap the banner to go to encryption config
18. Enter password bbb save it, then trigger sync
19. Observe that notes from 2 profiles now cannot be decrypted, which means both password aaa and bbb is unable to decrypt items where the wrong encryption password was entered, and the key is therefore corrupted or missing

**See video:**
https://github.com/user-attachments/assets/7b6d6c9f-4dc2-4331-a2e0-2628d537252c

Also, for a profile which already has encryption enabled in the mobile app, if you disable encryption, then re-enable it with a different password, this will also result in the same issue, without any kind of validation to validate against an existing master password.

This problem was mentioned in the comment here https://github.com/laurent22/joplin/issues/14659#issuecomment-4150740927

### Expected behaviour

It should not be possible to encrypt local notes with a corrupt or non-existent encryption key. All password entry fields (for initial encryption enablement, for entering password on an individual key, and for entering the master password) should all be validated to present an error if the password or not correct or does not match the existing master password when one exists, in the same way as the desktop app handles this

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Problem

Entering an invalid E2EE master password could cause notes to be encrypted with an invalid master key. See https://github.com/laurent22/joplin/issues/14975.

`react-native-quick-crypto` v0.7.17 seems to have not validated the authentication tag when decrypting AES GCM (see https://github.com/margelo/react-native-quick-crypto/issues/798).

# Solution

Upgrade `react-native-quick-crypto` from 0.7.17 to v1.0.19.

Fixes https://github.com/laurent22/joplin/issues/14975.

# Testing

## iOS (release build)

1. Enable E2EE.
2. Set up sync with Joplin Server.
3. Sync.
4. Switch profiles.
5. Enable E2EE.
6. Set up sync with the same Joplin Server account.
7. When prompted, enter an incorrect E2EE password.
   - A "Password is invalid" alert is shown.
8. Enter the correct E2EE password and save.
9. Sync.

Screen recording (2x speed):

https://github.com/user-attachments/assets/1abe8a8c-f6b5-4526-a17e-3647f96e1958

## Android API 36 Emulator (dev build)

Verified that the new startup test passes.

## Android API 36 Emulator (release build)

1. Create a new profile and set up file system sync.
2. Sync.
3. Enable E2EE with password "aaa".
4. Sync.
5. Switch to a new profile and set up file system sync with the same directory.
6. Sync.
7. When prompted, enter "bbb" for the E2EE password.
8. Dismiss settings and sync.
   - Verify that "Could not encrypt item" is shown.
9. Open settings and enter "aaa" for the E2EE password.
10. Sync and verify that notes are synced successfully.

**Screen recording**:

|Before|After|
|------|-----|
| <video src="https://github.com/user-attachments/assets/62ff38b0-f1bd-4d9b-9747-b611f56f03f3"/> | <video src="https://github.com/user-attachments/assets/c8c69909-4567-400b-b327-4b396cd0e641"/>|

### CODE REVIEW

**Comment by laurent22** [comment]
Wow that's interesting. Thanks @mrjo118 and @personalizedrefrigerator for looking into this, we should definitely add this to 3.6

**Comment by mrjo118** [comment]
I have done some tests with this code change on the web and android apps using profiles from both mobile and desktop, and tested changing the master password and having multiple encryption keys too. I can confirm this fixes pretty much all scenarios whereby data can get encrypted by an invalid master key, as in such cases the operation is blocked by the master key being unable to be decrypted.

There is one edge case which is not covered by this fix, which is if you disable and re-enable encryption on a synced profile on mobile, which already had encryption enabled with a different password. But this has an issue because of having 2 encryption keys with different passwords, and only the old password is able to be accepted in the UI upon entry. This is out of scope for this PR and can be dealt with separately.

**Review by mrjo118 — APPROVED** [review]

File: packages/lib/services/e2ee/cryptoTestUtils.ts [hunk 1]
```diff
@@ -67,6 +67,16 @@ export async function checkDecryptTestData(data: DecryptTestData, options: Check
 		messages.push(`Failed to decrypt data: Error: ${error}`);
 	}
 
+	try {
```
Comment (mrjo118) [inline packages/lib/services/e2ee/cryptoTestUtils.ts:70]: Will this test run on the Android CI? If not, can a test be added which will run on there too?

Comment (personalizedrefrigerator) [reply packages/lib/services/e2ee/cryptoTestUtils.ts:70]: > Will this test run on the Android CI?

No. This test currently only runs:
- With NodeJS (in CI).
- With web crypto when starting the web app in dev mode.
- With `react-native-quick-crypto` when starting the iOS/Android app in dev mode.

Comment (personalizedrefrigerator) [reply packages/lib/services/e2ee/cryptoTestUtils.ts:70]: > If not, can a test be added which will run on there too?

This would be complicated, since `react-native-quick-crypto` relies on native code (we currently don't run an Android emulator in CI).

Comment (mrjo118) [reply packages/lib/services/e2ee/cryptoTestUtils.ts:70]: "With react-native-quick-crypto when starting the iOS/Android app in dev mode" - I guess that should be ok, but where are the test results reported? Would it be obvious if the test failed there?

Comment (personalizedrefrigerator) [reply packages/lib/services/e2ee/cryptoTestUtils.ts:70]: I'm in the process of double-checking, but if a test fails, the app should fail to start (an `Error` should be thrown during [this startup task](https://github.com/laurent22/joplin/blob/94560fb340a08d4b83274a1dbdfa06d964ae720f/packages/app-mobile/utils/buildStartupTasks.ts#L490)). 

**Update**: A "Something went wrong while starting the application" alert dialog (with details on the test failure) is shown when a startup test fails.

**Comment by mrjo118** [comment]
@laurent22 This is good to merge from my perspective
