### PR TITLE
Android: Fixes #10122: Fix screen reader touch-to-focus broken on note list and note viewer pages

### LINKED ISSUE #10122: Android: Accessibility tap-to-focus broken
### Operating system

Android

### Joplin version

3.0.0

### Desktop version info

_No response_

### Current behaviour

On Android, accessibility tap-to-focus is broken when the note list is visible. Caused by https://github.com/callstack/react-native-paper/issues/4064 and related to https://github.com/laurent22/joplin/issues/8794.

### Expected behaviour

Tap-to-focus should work. See [issue](https://github.com/laurent22/joplin/issues/8794) for details.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

Resolves #10122 by working around https://github.com/callstack/react-native-paper/issues/4064.

Previously, tap-to-focus was broken on Android with TalkBack on the note list and note preview screens. This was caused by the full-screen, invisible background of these components. These [components use pointer-events="box-none"](https://github.com/callstack/react-native-paper/blob/813cdd47a90ee3bb693c6ec143af73092cd3edae/src/components/FAB/FABGroup.tsx#L345), but that seems to only be respected by VoiceOver (the iOS equivalent of TalkBack).

> [!NOTE]
>
> After this is merged, I plan to create an issue to track this workaround.
>

# Testing

1. Navigate to the note list
2. Create a new note using the FAB
3. Add content to the new note and go to the note rendered view
4. Click "Edit"
5. Go back to the note list and open a note by tapping on its title
6. Repeat steps 1-5 for a to-do
7. Enable RTL layout (settings > developer > force RTL layout direction)
8. Restart Joplin
9. Repeat steps 1-6
10. Disable RTL layout and enable TalkBack
11. Open Joplin and repeat steps 1-6 using tap-to-navigate.

This has been tested successfully on an Android 12 emulator.

To-do:
- [ ] Test on an Android emulator with a notch or otherwise non-rectangular screen.
- [ ] Test on iOS

### CODE REVIEW

File: packages/app-mobile/components/ActionButton.tsx [hunk 1]
```diff
@@ -57,11 +59,27 @@ const ActionButton = (props: ActionButtonProps) => {
...
+	// RN Paper, a large action button has size 96x96. As such, we allocate
+	// a larger than this space for the button.
+	//
+	// To prevent the accessibility issue from regressing (which makes it
+	// very hard to access some UI features), we also enable this when Talkback
+	// is disabled.
+	//
+	// See https://github.com/callstack/react-native-paper/issues/4064
+	const windowSize = useWindowDimensions();
+	const adjustMargins = !open && shim.mobilePlatform() === 'android';
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/ActionButton.tsx:73]: Optional: Use `AccessibilityInfo.isScreenReaderEnabled()` here. It's `async` though, so could make the code a bit more complicated.
