### PR TITLE
Desktop: Fixes #11274: Fix content dropped into the Markdown editor is missing a cursor preview or dropped at the wrong location

### LINKED ISSUE #11274: Dragging and dropping text no longer shows preview caret
### Operating system

macOS

### Joplin version

3.1.20

### Desktop version info

Joplin 3.1.20 (prod, darwin)

Client ID: 11cb0a2d420047cd9119a44d443e827c
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: 8199362

Backup: 1.4.2
Note Statistics: 1.0.4

### Current behaviour

1. Open a note in the Markdown editor
2. Highlight text
3. Click and drag the text elsewhere
While dragging, there is no caret under the cursor.

https://github.com/user-attachments/assets/06cc31ff-91af-4e96-b25e-cdcc4ed68fb7

### Expected behaviour

The editor should show a caret underneath the cursor to hint where text will be dropped. This is the behavior before version 3.1, and what currently happens in the WYSIWYG editor.

https://github.com/user-attachments/assets/31cc9690-d97f-4be6-8310-f5f4d9006126

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request:
1. resolves #11274
2. resolves a similar (but not identical) issue reported [on the forum](https://discourse.joplinapp.org/t/drag-and-drop-text-cursor/41568).

In particular:
1. In-editor content was dropped at the correct location, but no preview cursor was shown.
2. Notes were dropped at the last editor cursor location.

> [!NOTE]
>
> This pull request targets `release-3.1`.

# Screen recording

[Screencast from 2024-10-29 15-54-21.webm](https://github.com/user-attachments/assets/cd015504-be27-4519-b430-64d180c0c0e5)

# Manual testing plan

**MacOS (Sequoia)**: (MacOS testing done before rebasing on release-3.1).
1. Drag a note from the note list over the editor.
2. Verify that a preview cursor is visible.
3. Drop the note at a location distinct from the current editor cursor.
4. Verify that the note is dropped at that position.

**Fedora 41**:
1. Open Chromium.
   - Files from Firefox and the Files app often fail to drop into Joplin. This is the case with both with the new and legacy editors. Drag and drop from Chromium's "Downloads" list seems to work consistently.
2. Download 2-3 images (2 PNGs, 1 SVG).
3. Drop a PNG from the downloads list into Joplin's Markdown editor.
4. Verify that the image drops successfully.
5. Drop the SVG from the downloads list into a different location in Joplin's Markdown editor.
7. Verify that the image is dropped at the mouse's last location.
8. Drop a note from the note list into the editor.
9. Verify that a note link is added at the mouse's last location.
10. Select text in the editor.
11. Drag and drop the text to a different part of the editor.
12. Verify that the text is moved.

### CODE REVIEW

File: packages/editor/CodeMirror/createEditor.ts [hunk 1]
```diff
@@ -253,6 +254,8 @@ const createEditor = (
 
 				// Apply styles to entire lines (block-display decorations)
 				decoratorExtension,
+				dropCursor(),
```
Comment (personalizedrefrigerator) [inline packages/editor/CodeMirror/createEditor.ts:257]: This change shows where content will be dropped. See [the CodeMirror documentation for `dropCursor`](https://codemirror.net/docs/ref/#view.dropCursor).

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/useEditorCommands.ts [hunk 2]
```diff
@@ -38,13 +38,22 @@ const useEditorCommands = (props: Props) => {
 		};
 
 		return {
-			// eslint-disable-next-line @typescript-eslint/no-explicit-any -- Old code before rule was applied
-			dropItems: async (cmd: any) => {
+			dropItems: async (cmd: DropCommandValue) => {
+				let pos = cmd.pos && editorRef.current.editor.posAtCoords({ x: cmd.pos.clientX, y: cmd.pos.clientY });
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/useEditorCommands.ts:42]: `posAtCoords` is how [CodeMirror internally determines the drop location for content](https://github.com/codemirror/view/blob/49e68f7cbe0440501fa666c600639fe281109d90/src/dropcursor.ts#L79) &mdash; this makes the drop location of content processed by Joplin match CodeMirror's drop cursor.
