### PR TITLE
Chore: Fixes #9678: Fix API and mobile startup regressions caused by folder refactor

### LINKED ISSUE #9678: Mobile: Fails to start with error "cannot set property dispatch of undefined"
### Operating system

Android

### Joplin version

2bf2395f1b9e4910e5a00d8f9cadfee48a6c796d

### Desktop version info

_No response_

### Current behaviour

Currently, when running the mobile app, an error is logged to the console and the screen remains white.

To reproduce:
1. Run the mobile app

### Expected behaviour

Joplin should launch without an error.

### Logs

```
 WARN  Possible Unhandled Promise Rejection (id: 3):
TypeError: Cannot set property 'dispatch' of undefined
TypeError: Cannot set property 'dispatch' of undefined
    at ?anon_0_ (http://localhost:8081/root.bundle?platform=android&app=net.cozic.joplin&modulesOnly=true&dev=true&minify=false&runModule=true&shallow=true:357:106)
    at next (native)
    at fulfilled (http://localhost:8081/root.bundle?platform=android&app=net.cozic.joplin&modulesOnly=true&dev=true&minify=false&runModule=true&shallow=true:15:30)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/5815x2p5/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/5815x2p5/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:27987:26)
    at _callTimer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:27906:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:27936:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:28099:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4267:46)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4079:45)
    at __guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4251:15)
    at flushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4078:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=net.cozic.joplin&modulesOnly=false&runModule=true:4072:33)
```

The error seems to come from this line:

https://github.com/laurent22/joplin/blob/2bf2395f1b9e4910e5a00d8f9cadfee48a6c796d/packages/app-mobile/root.tsx#L519

### Notes

There may be a similar issue with the Joplin API:

https://github.com/laurent22/joplin/blob/2bf2395f1b9e4910e5a00d8f9cadfee48a6c796d/packages/lib/services/rest/routes/folders.ts#L8

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

Fixes two regressions related to 763716397b0ece953e69c17af9f7bc361bc6c001 (fixes #9678).

**Note**:
- This pull request fixes an unreleased regression. As such, it has been labeled `Chore`.
- The regression should affect the web clipper and mobile apps (and also possibly some desktop plugins). As such, an alternative pull request title could be `Mobile,Clipper,Desktop: Fixes #9678: Fix regressions caused by folder refactor`.

# Testing

This pull request adds an automated test to verify that the API-related change works.

The mobile fix was tested on Android 7 by
1. starting the mobile app, and
2. syncing.

### CODE REVIEW

File: packages/lib/services/rest/routes/folders.ts [hunk 1]
```diff
@@ -5,13 +5,13 @@ import paginatedResults from '../utils/paginatedResults';
...
 import Folder from '../../../models/Folder';
-const { FoldersScreenUtils } = require('../../../folders-screen-utils.js');
+import { allForDisplay } from '../../../folders-screen-utils';
 const { ErrorNotFound } = require('../utils/errors');
 
 export default async function(request: Request, id: string = null, link: string = null) {
 	if (request.method === 'GET' && !id) {
 		if (request.query.as_tree) {
-			const folders = await FoldersScreenUtils.allForDisplay({ fields: requestFields(request, BaseModel.TYPE_FOLDER) });
+			const folders = await allForDisplay({ fields: requestFields(request, BaseModel.TYPE_FOLDER) });
```
Comment (laurent22) [inline packages/lib/services/rest/routes/folders.ts:14]: I don't know how I missed that, thanks for the fix!
