### PR TITLE
All: Resolves #4613: Improve search with Asian scripts

### LINKED ISSUE #4613: The combined search returns no results for Chinese
The fantastic search feature is a bold reason that I'm using Joplin. When I search one Chinese word it works pretty well, and it's fast and accurate. I recently found that when I type in two Chinese words seperated by ' '(space) in the search box, there's always no result returned, despite what words I search and what they are organized in the original notes. I used to think that it is as design, but recently I found that when I type in two English words it works pretty well and returns the notes that contain both of the words.

## Environment

Joplin version: 
Platform: macOS
OS specifics: Catalina 10.15.7

## Steps to reproduce

1. create a note with content "目录  文件" (two spaces between the Chinese words) or "文件目录"
2. in the search bar, input "目录 文件" (one spaces between the Chinese words which implies "AND") 
3. No notes were found.

## Describe what you expected to happen

The search results contain all of the notes that contain both word "目录" and word "文件".

### PR DESCRIPTION
**Pull request by mablin7**
Fixes #4613

As discussed on [this forum thread](https://discourse.joplinapp.org/t/improving-search-with-asian-scripts/17457), I've created a new search mode besides basic and FTS, called `SEARCH_TYPE_NONLATIN_SCRIPT`, which has all of the features of FTS, but works for languages which the latter does not support. This new mode is automatically selected when a character from either Chinese, Japanese, Korean or Taiwanese is detected in the search string.

Most of this is done by refactoring functions in `queryBuilder` to be more generic and work without FTS, plus a few changes to `SearchEngine` to create and use the new search mode. I also added tests in a new file, by copying the existing `SearchFilter` tests, changing the strings to Chinese text and removing some irrelevant cases.

I tested this myself with randomly generated Chinese texts and to me it seemed to work fine, _but I don't speak Chinese_, so it could be that I missed something. It could be great if someone who does speak one of the above mentioned languages could try this fix on their collection (after backing it up of course :wink: )! If needed I can provide pre-built binaries for windows or linux.

### Supported features
- Multi-term search - match notes which contain _all_ of the space separated terms
- Quoted terms - match an exact sequence of terms
- Wildcards - use `*` as a wildcard
- `-` negated terms
- All filters that FTS supports: `type`, `any`, `iscompleted`, etc.

### Caveats
- Matches are not ranked smartly - the ranking algorithm relies on extra metadata returned by FTS
- On very large collections of notes or mobile devices it's probably slower, however I was not able to measure a significant slowdown on my fairly outdated desktop, with test sets of 1000 notes, 5000 characters each:

|                                                 | Time  |
|-----------------------------------------|-------|
| FTS search *         | ~800ms |
| Basic search          | ~800ms |
| New search mode  | ~900ms |

*On an equal number of English notes

### CODE REVIEW

File: packages/lib/services/searchengine/SearchEngine.ts [hunk 1]
```diff
@@ -580,14 +575,32 @@ export default class SearchEngine {
...
+
+			let rows: any;
+			if (searchType === SearchEngine.SEARCH_TYPE_NONLATIN_SCRIPT) {
+				try {
+					const { query, params } = queryBuilder(parsedQuery.allTerms, false);
+					rows = await this.db().selectAll(query, params);
+				} catch (error) {
+					this.logger().warn(`Cannot execute LIKE query: ${searchString}: ${error.message}`);
+					return [];
+				}
```
Comment (laurent22) [inline packages/lib/services/searchengine/SearchEngine.ts:597]: It looks like the same code as for SEARCH_TYPE_FTS expect with boolean true/false, so please refactor to avoid duplicate code.

File: packages/lib/services/searchengine/SearchEngine.ts [hunk 2]
```diff
@@ -580,14 +575,32 @@ export default class SearchEngine {
...
 				this.processResults_(rows, parsedQuery);
 				return rows;
 			} catch (error) {
 				this.logger().warn(`Cannot execute MATCH query: ${searchString}: ${error.message}`);
 				return [];
 			}
+		} else {
+			searchString = this.normalizeText_(searchString);
+
+			let rows: any;
```
Comment (laurent22) [inline packages/lib/services/searchengine/SearchEngine.ts:589]: Shouldn't it be at any[]? And any chance you could define an interface for it? You don't have to apply it everywhere, just in the code you've added here. I guess it's just something like `interface Row { title: string; body: string; etc. }` ?

File: packages/lib/services/searchengine/SearchFilterNonLatin.test.js [hunk 3]
```diff
@@ -0,0 +1,453 @@
+/* eslint-disable no-unused-vars, @typescript-eslint/no-unused-vars, prefer-const */
```
Comment (laurent22) [inline packages/lib/services/searchengine/SearchFilterNonLatin.test.js:1]: I know it's copied and pasted but normally new files should be TypeScript and with no estlint-disable.

File: packages/lib/services/searchengine/queryBuilder.ts [hunk 4]
```diff
@@ -65,12 +66,12 @@ const _notebookFilter = (notebooks: string[], requirement: Requirement, conditio
 
 };
 
-const notebookFilter = (terms: Term[], conditions: string[], params: string[], withs: string[]) => {
+const notebookFilter = (terms: Term[], conditions: string[], params: string[], withs: string[], useFTS: boolean) => {
```
Comment (laurent22) [inline packages/lib/services/searchengine/queryBuilder.ts:69]: Should be camel case - `useFts` (I need to add an eslint rule about this).

File: packages/lib/services/searchengine/queryBuilder.ts [hunk 5]
```diff
@@ -321,44 +331,61 @@ const dateFilter = (terms: Term[], conditons: string[], params: string[], relati
...
+														SELECT *
+															FROM (
+																SELECT ROWID
+																FROM notes_fts
+																EXCEPT
+																SELECT ROWID
+																FROM notes_fts
+																WHERE notes_fts${type} MATCH ?
+														)
+													)`);
```
Comment (laurent22) [inline packages/lib/services/searchengine/queryBuilder.ts:382]: Not sure if it's the diff doing this but could you check these strings and make sure they are indented properly?

File: packages/lib/services/searchengine/queryBuilder.ts [hunk 6]
```diff
@@ -404,47 +437,51 @@ const getConnective = (terms: Term[], relation: Relation): string => {
...
-	notes_fts.is_todo,
-	notes_fts.todo_completed,
-	notes_fts.parent_id
-	FROM notes_fts
+	${tableName}.id,
+	${tableName}.title,
+	${useFTS
+		? 'offsets(notes_fts) AS offsets, matchinfo(notes_fts, \'pcnalx\') AS matchinfo,'
+		: ''
+}
```
Comment (laurent22) [inline packages/lib/services/searchengine/queryBuilder.ts:456]: Could you put this one line please?

**Review by laurent22 — COMMENTED** [review]
For the test units, can't we do better than copying and pasting the complete test units? Your implementation is smart as you add the feature while making only a few changes. So the logic is that it's possible to do something similar with the tests.

For example, can't you run the test unit once with useFts on, then a second time with useFts off? Using Chinese characters is not necessary to check the new search type, is it? So maybe you could run them with the English strings that are in the original tests but with useFts = false.

In synchronizer_MigrationHandler.test.ts, the same tests run for each sync target migration. Maybe something similar can be done here?

**Comment by laurent22** [comment]
> Matches are not ranked smartly - the ranking algorithm relies on extra metadata returned by FTS

Actually what would be the ranking logic for this new search type?

File: packages/lib/services/searchengine/SearchEngine.ts (hunk 2 above)
Comment (mablin7) [reply packages/lib/services/searchengine/SearchEngine.ts]: I removed this variable, do you think the interface is still needed?

File: packages/lib/services/searchengine/queryBuilder.ts (hunk 5 above)
Comment (mablin7) [reply packages/lib/services/searchengine/queryBuilder.ts]: That's weird, it was looking way better in my editor. I did remove some indentation though to make it uniform with the other strings in the file.

File: packages/lib/services/searchengine/SearchEngine.ts (hunk 2 above)
Comment (laurent22) [reply packages/lib/services/searchengine/SearchEngine.ts]: No, no need to worry about this. Even better if removed the variable.

**Comment by mablin7** [comment]
Thanks for the feedback! I hope it's looking better now. 

> Actually what would be the ranking logic for this new search type?

Well now it's the same as basic, which is based on just a few simple metrics defined here
https://github.com/laurent22/joplin/blob/89bc1810720561d116ea25737a3c5b62b7fe8c78/packages/lib/services/searchengine/SearchEngine.ts#L356-L373

I'm not sure how it could be improved without the extra data that FTS provides, I haven't really looked into how the BM25 algorithm works. Maybe a future PR :)

**Comment by laurent22** [comment]
> I'm not sure how it could be improved without the extra data that FTS provides, I haven't really looked into how the BM25 algorithm works. Maybe a future PR :)

Yes this is good enough for now. Actually could you please update the documentation and mention how this mode works, and to which languages it applies?

Regarding the tests, are you confident that the existing filter tests will also cover your new search type? Is there anything specific to it that could be covered in an additional test?

**Comment by mablin7** [comment]
> Actually could you please update the documentation and mention how this mode works, and to which languages it applies?

I hope I added it in the right place.

> Regarding the tests, are you confident that the existing filter tests will also cover your new search type? Is there anything specific to it that could be covered in an additional test?

No, I couldn't think of any specific cases. The main logic is pretty much left intact, mostly only the table names are changed. The filter that required the most change is the text filter, but that actually is simple in non-FTS mode, than in FTS and the existing tests cover all the things that can go wrong, in my opinion.

File: README.md [hunk 7]
```diff
@@ -407,6 +407,12 @@ For more information see [Plugins](https://github.com/laurent22/joplin/blob/dev/
 
 Joplin implements the SQLite Full Text Search (FTS4) extension. It means the content of all the notes is indexed in real time and search queries return results very fast. Both [Simple FTS Queries](https://www.sqlite.org/fts3.html#simple_fts_queries) and [Full-Text Index Queries](https://www.sqlite.org/fts3.html#full_text_index_queries) are supported. See below for the list of supported queries:
 
+One caveat of SQLite FTS is that it does not support languages which do not use Latin word boundaries (spaces, tabs, punctuation). To solve this issue, Joplin has a custom search mode, that does not use FTS, but still has all of its features (multi term search, filters, etc.). Its only drawback is that it can get slow on larger note collections. This search mode is currently enabled if one of the following languages are detected:
```
Comment (laurent22) [inline README.md:410]: Probably should be "Its only drawback" => "One of its drawback". Also please mention that sorting is less accurate too (since for FTS we can use BM25). And how about prefix queries? Do they work with this new mode?

**Review by laurent22 — COMMENTED** [review]
Thanks for the update @mablin7. I've just left one comment and then I think it's ready to merge.

**Comment by laurent22** [comment]
Great, thanks for the update @mablin7!
