### PR TITLE
Desktop: Fixes panels overflowing window

### LINKED ISSUE #4864: Broken editor children widths after disabling noteTabs plugin
After disabling Note Tabs plugin, the application layout is broken. In `settings.json`, a child is not removed:

```json
{
	"$schema": "https://joplinapp.org/schema/settings.json",
	"locale": "en_GB",
	"markdown.plugin.softbreaks": false,
	"markdown.plugin.typographer": true,
	"noteVisiblePanes": [
		"editor",
		"viewer"
	],
	"revisionService.ttlDays": 50,
	"newNoteFocus": "title",
	"markdown.plugin.deflist": true,
	"markdown.plugin.abbr": true,
	"markdown.plugin.multitable": true,
	"style.editor.fontSize": 13,
	"sync.interval": 3600,
	"sync.target": 7,
	"clipperServer.autoStart": true,
	"windowContentZoomFactor": 90,
	"autoUpdateEnabled": false,
	"notes.sortOrder.field": "order",
	"editor.codeView": true,
	"notes.sortOrder.reverse": false,
	"spellChecker.language": "pl",
	"ui.layout": {
		"key": "root",
		"children": [
			{
				"key": "sideBar",
				"width": 246,
				"visible": true
			},
			{
				"key": "noteList",
				"width": 169,
				"visible": true
			},
			{
				"key": "editor",
				"visible": true,
				"width": 1987
			},
			{
				"key": "plugin-view-joplin.plugin.note.tabs-note.tabs.panel",
				"context": {
					"pluginId": "joplin.plugin.note.tabs"
				},
				"visible": false
			}
		],
		"visible": true
	},
}
```

which results in the following broken layout:
image

The viewer is wider than the editor. 

Also, there is not button for WYSIWYG.
image

## Environment

Joplin version: 1.8.1, prod, sync 2, profile 34
Platform: Windows
OS specifics: Windows 10

## Steps to reproduce

1. Install Note Tabs plugin and enable it
2. use it, tweak its options
3. disable Note Tabs plugin

## Describe what you expected to happen

Everything should go back to normal. The viewer should be as wide as the editor.

### PR DESCRIPTION
**Pull request by mablin7**
Fixes #4864 (specifically the issue [raised in this comment](https://github.com/laurent22/joplin/issues/4864#issuecomment-843288171), the original seems to have been fixed already).

The problem was that the layout logic had no way to handle maximum sizes, so if a panel was too big it simply overflowed and could even push other panes completely off-screen (see recordings below).

My fix is to add a extra logic to `useLayoutItemSizes()`, which
1. keeps track of the minimum space that should be reserved, such that all panels are visible (using the `minWidth`/`minHeight` props or `40px` per pane if not defined)
2. if the panes with definite size don't leave enough room, makes the largest one smaller
3. calculates a maximum possible size for each pane

The calculated max size is then passed to the `Resizable` component, so that it's enforced during resizing. I thought the cleanest way to do this is to extend the `sizes` object, which keeps the calculated size of each item. It now also contains their minimum and maximum sizes.

I included a few unit tests which hopefully cover all the new functionality.

Steps to check manually
---

Resizing with the mouse
1. Open Joplin
2. Resize the note list, as wide as it goes
Without the fix, the note editor is pushed off-screen. With the fix, it should stop when the note editor becomes only 40px wide.

Resizing the window
1. Open Joplin and maximize it
2. Resize the note list, really wide
3. Unmaximize Joplin
Without the fix, the note editor suddenly becomes invisible. With the fix, it should be visible and 40px wide (its minimum size).

Screen recordings
---

Before
panel-nonworking-manres

After
panel-working-manres opt

### CODE REVIEW

**Review by laurent22 — COMMENTED** [review]
Thanks for the pull request. The code is well written but I'm not entirely sure the logic to set the min/max is ideal. For me, an item can have a min width or height - either it's explicitly set, or its default. But here you are dynamically setting a min and max every time the component is resized, which doesn't feel like the right approach.

So I'm wondering, would it be possible to get it working without creating this new current/min/max interface? If not, why is that? I guess if I could understand that part, the rest would make more sense too.

**Comment by mablin7** [comment]
> Thanks for the pull request. The code is well written but I'm not entirely sure the logic to set the min/max is ideal. For me, an item can have a min width or height - either it's explicitly set, or it's default. But here you are dynamically setting a min and max every time the component is resized, which doesn't feel like the right approach.
> 
> So I'm wondering, would it be possible to get it working without creating this new current/min/max interface? If not, why is that? I guess if I could understand that part, the rest would make more sense too.

Well yeah in hindsight I can see the way I used max size is pretty ambiguous, because it doesn't work like in css for eg. The idea was that `max.width` gives the total available width for a particular item, so that when it's being resized the `Resizable` component knows where to stop. It's just the item's width + all the remaining width in the container. That's why the max widths need not add up in the test: 
https://github.com/laurent22/joplin/blob/eb592a50d7c98a902186fddad6d3eb5709478788/packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts#L145-L157
If col1 is being resized, it can be expanded all the way up to 90px and then there would be exactly 40px left for col3:
col1 90px + col2 70px + col3 40px = 200px
After col1 is resized the max widths are updated, so col2's max width would become it's actual width, 70px, since there's no more free space. I swear it made sense when I wrote it. 😥

Now it occurred to me that the max size is only required for the item that's being currently resized. So probably the code in  `calculateChildrenSizes` for calculating it could be moved to a new function, which can be called from `ResizableLayout` when the resize begins. 

Do you think that's a better approach?

**Comment by mablin7** [comment]
I moved the code for calculating the maximum available size to a function, `calculateMaxSizeAvailableForItem()`, instead of storing it for each item, which I know realize was pretty unclear. 

This function is only needed so that I can pass a `maxWidth`/`maxHeight` to `Resizable`, so it stops when an item would become too large and would push others off-screen. It kind of works without it, since `useLayoutItemSizes` then would anyway make the item smaller to fit, but I found that to be quite jerky (probably because there's a delay in recomputing the layout), while passing `maxWidth` works very smoothly.

The only small issue is that for this new function a bit of code is replicated from `useLayoutItemSizes`, but I just couldn't figure out how to avoid that, and it's really only 4 lines.

File: packages/app-desktop/gui/ResizableLayout/ResizableLayout.tsx [hunk 1]
```diff
@@ -112,14 +111,18 @@ function ResizableLayout(props: Props) {
...
 		}
 
 		function onResize(_event: any, direction: string, _refToElement: any, delta: any) {
-			const newWidth = Math.max(itemMinWidth, resizedItem.initialWidth + delta.width);
-			const newHeight = Math.max(itemMinHeight, resizedItem.initialHeight + delta.height);
+			let newWidth = Math.max(resizedItem.minSize.width, resizedItem.initialSize.width + delta.width);
+			let newHeight = Math.max(resizedItem.minSize.height, resizedItem.initialSize.height + delta.height);
+
+			newWidth = Math.min(newWidth, resizedItem.maxSize.width);
+			newHeight = Math.min(newHeight, resizedItem.maxSize.height);
```
[the remark this answers is not in the document]
Comment (mablin7) [reply packages/app-desktop/gui/ResizableLayout/ResizableLayout.tsx]: It turns out these lines weren't even necessary. I just figured they might be needed because the minimum size was also applied here, but everything seems to work fine without adding these.

File: packages/app-desktop/gui/ResizableLayout/ResizableLayout.tsx [hunk 2]
```diff
@@ -35,7 +32,7 @@ function itemVisible(item: LayoutItem, moveMode: boolean) {
 	return item.visible !== false;
 }
 
-function renderContainer(item: LayoutItem, parent: LayoutItem | null, sizes: LayoutItemSizes, onResizeStart: Function, onResize: Function, onResizeStop: Function, children: any[], isLastChild: boolean, moveMode: boolean): any {
+function renderContainer(item: LayoutItem, parent: LayoutItem | null, sizes: LayoutItemSizes, resizeMaxSize: Size | null, onResizeStart: Function, onResize: Function, onResizeStop: Function, children: any[], isLastChild: boolean, moveMode: boolean): any {
```
Comment (laurent22) [inline packages/app-desktop/gui/ResizableLayout/ResizableLayout.tsx:35]: As I understand resizeMaxSize is the max size of the items being currently resized, is that correct? If so, maybe make it more explicit `resizedItemMaxSize`, so that we know it's related to `resizedItem`.

File: packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts [hunk 3]
```diff
@@ -138,4 +138,157 @@ describe('useLayoutItemSizes', () => {
...
+					minWidth: 50,
+				},
+			],
+		});
+
+		const { result } = renderHook(() => useLayoutItemSizes(layout));
+		const sizes = result.current;
+
+		expect(sizes.col1.width).toBe(50);
+		expect(sizes.col2.width).toBe(100);
```
Comment (laurent22) [inline packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts:167]: Maybe also add a check for sizes.col3?

File: packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts [hunk 4]
```diff
@@ -138,4 +138,157 @@ describe('useLayoutItemSizes', () => {
...
+					key: 'col3',
+					minWidth: 50,
+				},
+			],
+		});
+
+		const { result } = renderHook(() => useLayoutItemSizes(layout));
+		const sizes = result.current;
+
+		expect(sizes.col2.width).toBe(100);
```
Comment (laurent22) [inline packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts:196]: I'm not sure what this test demonstrates. Does it imply that col3 width is 100? If so could you add a check for col3 too please?

File: packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts [hunk 5]
```diff
@@ -138,4 +138,157 @@ describe('useLayoutItemSizes', () => {
...
+		expect(sizes.col3.width).toBe(50);
```
Comment (laurent22) [inline packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts:230]: Likewise I think all tests would be easier to follow if you check for the width of each column. Otherwise you have to guess based on what you might know about the algorithm, and that's assuming the algorithm is working.

File: packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts [hunk 6]
```diff
@@ -138,4 +138,157 @@ describe('useLayoutItemSizes', () => {
...
+					key: 'col3',
+				},
+			],
+		});
+
+		const { result } = renderHook(() => useLayoutItemSizes(layout));
+		const sizes = result.current;
+		const maxSize = calculateMaxSizeAvailableForItem(layout.children[0], layout, sizes);
+
+		expect(maxSize.width).toBe(90);
```
Comment (laurent22) [inline packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts:262]: Again I think it would be best to test all the columns. I understand the calculation but that's because I know the min width is 40 (something I'll forget by next week :). Or perhaps add a comment that explains the reasoning (or both)?

File: packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts [hunk 7]
```diff
@@ -138,4 +138,157 @@ describe('useLayoutItemSizes', () => {
...
+					minWidth: 60,
+				},
+			],
+		});
+
+		const { result } = renderHook(() => useLayoutItemSizes(layout));
+		const sizes = result.current;
+		const maxSize = calculateMaxSizeAvailableForItem(layout.children[0], layout, sizes);
+
+		expect(maxSize.width).toBe(70);
```
Comment (laurent22) [inline packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts:291]: Same here, tests for all columns and/or comment.

File: packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.ts [hunk 8]
```diff
@@ -47,10 +54,43 @@ function calculateChildrenSizes(item: LayoutItem, parent: LayoutItem | null, siz
...
 
 		sizes[child.key] = { width: w, height: h };
+
 		if (w !== null) remainingSize.width -= w;
 		if (h !== null) remainingSize.height -= h;
-		if (w === null) noWidthChildren.push({ item: child, parent: item });
-		if (h === null) noHeightChildren.push({ item: child, parent: item });
+		if (w === null) {
+			noWidthChildren.push({ item: child, parent: item });
+			noWidthChildrenMinWidth += child.minWidth || itemMinWidth;
```
Comment (laurent22) [inline packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.ts:62]: That implies that minWidth and minHeight cannot be zero, which is reasonable I guess. If that's the behaviour you want, then please add a test unit for it.

**Review by laurent22 — COMMENTED** [review]
Thanks for the update @mablin7, I feel the logic is clearer now. I've added a few comments but nothing tricky I think.

**Comment by mablin7** [comment]
Thanks for the feedback! Hope the tests are clearer now as well.

**Comment by laurent22** [comment]
Looks good now, thanks @mablin7!
