### PR TITLE
MacOS: Resolves #9488: Add "Window" menu to toolbar on MacOS

### LINKED ISSUE #9488: macos cmd+m shortcut doesn't work in desktop app
### Operating system

macOS

### Joplin version

2.13.9

### Desktop version info

Joplin 2.13.9 (prod, darwin)

Client ID: 2d7ab95cbeb4489db005cb8d545a7077

### Current behaviour

1. Open joplin on macos
2. Press cmd+m

### Expected behaviour

Joplin should minimise to macos dock. That's standard macos shortcut and described here: https://support.apple.com/en-us/HT201236 ). 

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request resolves #9488 by allowing the MacOS "Window" menu to be shown. This pull request also allows configuring "minimizeWindow" through Joplin's keyboard shortcut settings.

Other apps I've looked at (VSCode, Firefox, Finder, Calculator, Safari, Terminal) also show the "Window" menu. Additionally, [it's mentioned in Apple's Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/the-menu-bar/#Window-menu).

# Screenshot

screenshot: Window menu contains Tile Window to Left of Screen, Tile Window to Right of Screen, Replace Tiled Window (greyed), Remove Window From Set (greyed), and Minimize

# Notes

- If launching Joplin in development mode, the development tools are initially shown. This causes tab-related menu items to be shown in the menu. This does not seem to be an issue in release mode, where the development tools are not shown on startup. ([Related StackOverflow post](https://stackoverflow.com/a/77458809)).
    - screenshot: Window menu shows extra items related to tabs

# To-do

- [x] Test on a non-MacOS computer and verify that the "Window" menu is not shown.

# Testing

**MacOS**:
1. Start Joplin
2. Press <kbd>cmd</kbd>-<kbd>m</kbd> and verify that the window is minimized
3. Unminimize Joplin
4. Open Joplin's settings and change the keyboard shortcut for "minimise" to <kbd>cmd</kbd>-<kbd>shift</kbd>-<kbd>j</kbd>.
5. Close settings and press <kbd>cmd</kbd>-<kbd>shift</kbd>-<kbd>j</kbd>
6. Unminimize Joplin
7. Open the "Window" menu and click "minimize"
8. Verify that Joplin has been minimized.
9. Open the "Window" menu and click "Tile window to left of screen". Verify that the window has been tiled.

This has been successfully tested on MacOS Sonoma.

**Linux**:
1. Start Joplin
2. Verify that the "Window" menu is not visible
3. Open settings > Keyboard shortcuts
4. Verify that "minimise" is not a command in the  keyboard shortcut settings pane.

This has been tested successfully on Ubuntu 23.10.

### CODE REVIEW

File: packages/app-desktop/gui/MenuBar.tsx [hunk 1]
```diff
@@ -851,7 +869,7 @@ function useMenu(props: Props) {
 						accelerator: keymapService.getAccelerator('help'),
 						click() { void bridge().openExternal('https://joplinapp.org'); },
 					}, {
-						label: _('Joplin Forum'),
+						label: _('Joplin Forumm'),
```
Comment (laurent22) [inline packages/app-desktop/gui/MenuBar.tsx]: A typo here, otherwise I think we can merge

File: packages/app-desktop/gui/KeymapConfig/utils/getLabel.ts [hunk 2]
```diff
@@ -20,6 +20,8 @@ const getLabel = (commandName: string): string => {
 		return _('Website and documentation');
 	case 'hideApp':
 		return _('Hide Joplin');
+	case 'minimizeWindow':
+		return _('Minimize');
```
Comment (laurent22) [inline packages/app-desktop/gui/KeymapConfig/utils/getLabel.ts]: The text should be "Minimise" (the command name however should indeed use US English)
