### PR TITLE
Server: Resolves #5790: Do not set the auth option when authUser or authPassword is set

### LINKED ISSUE #5790: Server tries to authenticate to smtp server, while no mailer credentials are provided
When the environment variables `MAILER_AUTH_USER` and `MAILER_AUTH_PASSWORD` are _not set_, joplin server still tries to authenticat to the SMTP server, which will always fail. This makes it impossible to use the SMTP server even when authentication is not required.

## Environment

Joplin server version: 2.6.11 (dev)
Platform: linux

## Steps to reproduce

1. Set the environment variables for the mailer service to point to a mail server that does not require authentication on smtp port 25 / 465 (mail.my.domain in the example below)
```
export MAILER_ENABLED=1
export MAILER_HOST=mail.my.domain
export MAILER_PORT=25
export MAILER_SECURE=0
export MAILER_NOREPLY_NAME=test
export MAILER_NOREPLY_EMAIL=test@my.domain
```
2. run the server
```
npm run start-dev
``` 

## Describe what you expected to happen

I would expect the EmailService to report "Maintenance completed" without throwing an exception and disabling the mailer function

### PR DESCRIPTION
**Pull request by MovingEarth**
Even when `config.mailer.authUser` and `config.mailer.authPassword` are empty, joplin server still configures the `auth` option on the `SMTPTransport`.

This pull request, changes this behavior by only setting the auth option when  both config.mailer.authUser and config.mailer.authPassword have a value (and are thus set using the environment variables). This allows the EmailService to be used when no authentication to the SMTP server is required.

### CODE REVIEW

File: packages/server/src/services/EmailService.ts [hunk 1]
```diff
@@ -24,16 +25,18 @@ export default class EmailService extends BaseService {
...
 				}
-
-				this.transport_ = createTransport({
+				const options: SMTPTransport.Options = {
 					host: this.config.mailer.host,
 					port: this.config.mailer.port,
 					secure: this.config.mailer.secure,
-					auth: {
+				};
+				if (this.config.mailer.authUser !== '' && this.config.mailer.authPassword !== '') {
```
Comment (laurent22) [inline packages/server/src/services/EmailService.ts:33]: `this.config.mailer.authUser || this.config.mailer.authPassword`

**Review by laurent22 — COMMENTED** [review]
I've just one comment but otherwise it's good to merge.

File: packages/server/src/services/EmailService.ts (hunk 1 above)
Comment (MovingEarth) [reply packages/server/src/services/EmailService.ts]: Yes looks good, your suggestion looks a lot cleaner. It changes the behavior a little because it tries to do authentication if only one of the two required environment variables are set. But,he, if you set one, you probably want to set the other too.
I changed it as suggested.

**Comment by laurent22** [comment]
Thanks for the update @MovingEarth, let's merge!
