### PR TITLE
Mobile/iOS: Resolves #6685: Respect system accessibility font size in rendered markdown

### LINKED ISSUE #6685: Mobile: iOS/Accessibility: Note content does not respect system font scale
## Environment

Joplin version: f0831f1d607fc2adad94a321dd940053a314ddc5
Platform: iOS
OS specifics: iOS 15.6

## Steps to reproduce

1. Increase the text size under `System Settings → Accessibility → Display & Text Size → Larger Accessibility Sizes`
2. Observe the rendered markdown's size
3. Decrease the text size
4. Observe the rendered markdown's size

## Describe what you expected to happen
The rendered markdown's font size should change.

## See also
[The original bug report (on the forum).](https://discourse.joplinapp.org/t/increase-font-size-in-ipad-app/26576).

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary
On iOS, loads additional CSS that sets the font family of the body to `-apple-system-body`. This scales the font size in the `WebView` with the accessibility system settings.

Fixes #6685

# See also
 * https://discourse.joplinapp.org/t/increase-font-size-in-ipad-app/26576/8

# Testing plan
## iOS
1. Enable the beta editor and open a note (viewing mode)
2. Click the edit button
3. Click the back arrow
4. Check the 'Larger accessibility sizes' box in `System Settings → Accessibility → Display & Text Size → Larger Accessibility Sizes`
5. Also in `System Settings → Accessibility → Display & Text Size → Larger Accessibility Sizes`, increase the font size
6. In Joplin, click the edit button
7. Click the back arrow

In steps 6 and 7, the font size in both the editor and viewer should be larger than in steps 1 and 2.

## Android
1. Enable the beta editor and open a note
2. Click the edit button
3. Click the back button
4. Increase the font size in `Settings → Display → Font size`
5. Navigate back to the note
6. Click `edit` again

As above, in steps 5 and 6, the font size should be larger than in steps 1 and 2.

### CODE REVIEW

File: packages/app-mobile/components/NoteBodyViewer/hooks/useSource.ts [hunk 1]
```diff
@@ -139,13 +139,27 @@ export default function useSource(noteBody: string, noteMarkupLanguage: number,
 			js.push('}');
 			js.push('true;');
 
+			// iOS doesn't automatically adjust the WebView's font size to match users'
+			// accessibility settings. To do this, we need to tell it to match the system font.
+			// See https://github.com/ionic-team/capacitor/issues/2748#issuecomment-612923135
+			const iOSSpecificCss = `
+				@media screen {
+					:root body {
+						font: -apple-system-body;
```
Comment (laurent22) [inline packages/app-mobile/components/NoteBodyViewer/hooks/useSource.ts:148]: Won't that conflict with the font family defined in the settings?

Comment (personalizedrefrigerator) [reply packages/app-mobile/components/NoteBodyViewer/hooks/useSource.ts:148]: I'm not seeing a way to change the `NoteBodyViewer`'s font (on mobile) in settings. If it is conflicting, setting `font: -apple-system-body` on `:root` and setting the `body`'s `font-size` to `inherit` might work.

Comment (laurent22) [reply packages/app-mobile/components/NoteBodyViewer/hooks/useSource.ts:148]: Oh that's right, the font can only be changed for the editor. So I think this is fine then

**Comment by laurent22** [comment]
Thanks for implementing this!
