### PR TITLE
Desktop: Fixes #3628: Add scroll offset for dragging notes (ui_update branch)

### LINKED ISSUE #3628: Scrolling breaks drag and drop reordering of notes
## Environment

Joplin version: 1.0.233
Platform: Linux
OS specifics: Debian 8

## Steps to reproduce
It seems farily common to have a notebook with more notes than can fit on one screen, such that the note list has a scrollbar. Let's say we have scrolled until the end of this list. When we try to drag and drop a note, it will be moved into the top of the list, sometimes even outside the currently visible area.

In the screenshot below, I have tried dragging a note titled "--- section header ---". You can see that the black bar indicating where it will be dropped is in a different position than the mouse.

joplin_drag_and_drop_scroll_not_working

This is because current implementation seems to be using window coordinates to determine the target position (indicated by the black bar in the UI). I guess it should be simple to fix, something like changing [MouseEvent.pageY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/pageY) to [MouseEvent.clientY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientY). I didn't look into the source code though, so this is just my speculation based on how drag and drop is usually implemented.

### PR DESCRIPTION
**Pull request by DarinDev1000**
Fixes laurent22/joplin#3628

The note dragging was not taking into account the scroll distance.
This caused the notes to be dragged to a different location than the mouse.
This scroll offset should fix that issue.

This fix was moved to ui_update branch instead of dev branch.
[Original pull request](https://github.com/laurent22/joplin/pull/3643) on dev branch

### CODE REVIEW

**Comment by DarinDev1000** [comment]
Was the " - 1" at the end of the dragging notes calculation on purpose?
It does not line up with the mouse if it is there.

File: ElectronClient/gui/NoteList/NoteList.tsx [hunk 1]
```diff
@@ -141,7 +141,7 @@ class NoteListComponent extends React.Component {
 	}
 
 	dragTargetNoteIndex_(event:any) {
-		return Math.abs(Math.round((event.clientY - this.itemListRef.current.offsetTop()) / this.itemHeight)) - 1;
+		return Math.abs(Math.round((event.clientY - this.itemListRef.current.offsetTop() + this.itemListRef.current.offsetScroll()) / this.itemHeight));
```
Comment (DarinDev1000) [inline ElectronClient/gui/NoteList/NoteList.tsx:144]: Was the - 1 at the end of the dragging notes calculation on purpose?
It does not line up with the mouse if it is there.
It makes the drag location 1 note high.

**Comment by DarinDev1000** [comment]
Fixes laurent22/joplin#3628

**Comment by DarinDev1000** [comment]
For some reason, I can't link the issue laurent22/joplin#3628 to this pull request.

File: ElectronClient/gui/NoteList/NoteList.tsx (hunk 1 above)
Comment (laurent22) [reply ElectronClient/gui/NoteList/NoteList.tsx:144]: Yes I've added that as the index somehow was off by 1 at some point while I was testing. But maybe it was some other issue, or your change fixes it properly. I'll give it a try to be sure.

Comment (DarinDev1000) [reply ElectronClient/gui/NoteList/NoteList.tsx:144]: OK, I'm not sure which way it needs to be.

Comment (DarinDev1000) [reply ElectronClient/gui/NoteList/NoteList.tsx:144]: How's this look?

Comment (laurent22) [reply ElectronClient/gui/NoteList/NoteList.tsx:144]: I will test this change once I get back to the UI update, which should be relatively soon.

**Comment by laurent22** [comment]
The fix was good, thanks @DarinDev1000!

**Comment by DarinDev1000** [comment]
Thanks
