### PR TITLE
Desktop,Mobile: Resolves #10073, #10080: Fix conflicts notebook doesn't work with the trash feature

### LINKED ISSUE #10073: Conflicts notebook crashes application
### Operating system

Linux (Ubuntu 23.10), Android

### Joplin version

3.0.0

### Desktop version info

Joplin 3.0.0 (dev, linux)

Client ID: 46b55b8904d64022a2426a6ed967f3cf
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: 70c7804a4

ABC Sheet Music Plugin: 1.0.4
Backup: 1.4.0
CodeMirror 6 snippets: 0.0.5
Freehand Drawing: 2.7.1
Math Mode: 0.6.2

### Current behaviour

To reproduce:
1. Sync two clients with a sync target
    - I tested using file system sync
2. Make a change to a synced note on client 1, but don't sync
3. Make a change to the same note on client 2
4. Sync both clients such that a `Conflicts` notebook is created

Currently, just after step 4, the `Joplin encountered a fatal error and could not continue.` screen is shown.

**Notes**:
- This may also be an issue with the `Conflicts (attachments)` notebook.
- I have also been able to reproduce this on Android 7 (also Joplin 3.0.0).

### Expected behaviour

Conflicts should not crash Joplin.

### Logs

Error screen content:
````
Error
Joplin encountered a fatal error and could not continue.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/laurent22/joplin/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.yml#), which will temporarily disable all plugins.

Message
Missing "deleted_time" or "parent_id" property: {"type_":2,"id":"c04f1c7c04f1c7c04f1c7c04f1c7c04f","parent_id":"","title":"Conflicts","updated_time":1709749989897,"user_updated_time":1709749989897,"share_id":"","is_shared":0,"note_count":1}

Version info
Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 3.0.0 (dev, linux)

Client ID: 46b55b8904d64022a2426a6ed967f3cf
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: 70c7804a4

ABC Sheet Music Plugin: 1.0.4
Backup: 1.4.0
CodeMirror 6 snippets: 0.0.5
Freehand Drawing: 2.7.1
Math Mode: 0.6.2
Plugins
[
    {
        "id": "io.github.jackgruber.backup",
        "name": "Backup",
        "enabled": true,
        "version": "1.4.0"
    }
]
Stack trace
Error: Missing "deleted_time" or "parent_id" property: {"type_":2,"id":"c04f1c7c04f1c7c04f1c7c04f1c7c04f","parent_id":"","title":"Conflicts","updated_time":1709749989897,"user_updated_time":1709749989897,"share_id":"","is_shared":0,"note_count":1}
    at getDisplayParentId (/home/builder/Documents/joplin/packages/lib/services/trash/index.js:32:15)
    at folderHasChildren_ (/home/builder/Documents/joplin/packages/lib/components/shared/side-menu-shared.js:13:63)
    at renderFoldersRecursive_ (/home/builder/Documents/joplin/packages/lib/components/shared/side-menu-shared.js:43:29)
    at renderFolders (/home/builder/Documents/joplin/packages/lib/components/shared/side-menu-shared.js:58:12)
    at SidebarComponent (/home/builder/Documents/joplin/packages/app-desktop/gui/Sidebar/Sidebar.js:528:61)
    at renderWithHooks (/home/builder/Documents/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:16305:18)
    at updateFunctionComponent (/home/builder/Documents/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:19588:20)
    at beginWork (/home/builder/Documents/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:21601:16)
    at beginWork$1 (/home/builder/Documents/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:27426:14)
    at performUnitOfWork (/home/builder/Documents/joplin/packages/app-desktop/node_modules/react-dom/cjs/react-dom.development.js:26557:12)
Component stack

    at SidebarComponent (/home/builder/Documents/joplin/packages/app-desktop/gui/Sidebar/Sidebar.js:103:50)
    at ConnectFunction (/home/builder/Documents/joplin/packages/app-desktop/node_modules/react-redux/lib/components/connect.js:246:74)
    at div
    at I (/home/builder/Documents/joplin/packages/app-desktop/node_modules/styled-components/dist/styled-components.cjs.js:1:19269)
    at div
    at Resizable (/home/builder/Documents/joplin/packages/app-desktop/node_modules/re-resizable/lib/index.es5.js:211:28)
    at div
    at ResizableLayout (/home/builder/Documents/joplin/packages/app-desktop/gui/ResizableLayout/ResizableLayout.js:47:45)
    at div
    at MainScreenComponent (/home/builder/Documents/joplin/packages/app-desktop/gui/MainScreen/MainScreen.js:77:9)
    at ConnectFunction (/home/builder/Documents/joplin/packages/app-desktop/node_modules/react-redux/lib/components/connect.js:246:74)
    at div
    at NavigatorComponent (/home/builder/Documents/joplin/packages/app-desktop/gui/Navigator.js:7:1)
    at ConnectFunction (/home/builder/Documents/joplin/packages/app-desktop/node_modules/react-redux/lib/components/connect.js:246:74)
    at exports.ThemeProvider (/home/builder/Documents/joplin/packages/app-desktop/node_modules/styled-components/dist/styled-components.cjs.js:1:25001)
    at ae (/home/builder/Documents/joplin/packages/app-desktop/node_modules/styled-components/dist/styled-components.cjs.js:1:13440)
    at RootComponent (/home/builder/Documents/joplin/packages/app-desktop/gui/Root.js:103:1)
    at ConnectFunction (/home/builder/Documents/joplin/packages/app-desktop/node_modules/react-redux/lib/components/connect.js:246:74)
    at ErrorBoundary (/home/builder/Documents/joplin/packages/app-desktop/gui/ErrorBoundary.js:21:9)
    at Provider (/home/builder/Documents/joplin/packages/app-desktop/node_modules/react-redux/lib/components/Provider.js:19:3)
````

### LINKED ISSUE #10080: Desktop: Resource links broken
### Operating system

Windows

### Joplin version

3.0.0

### Desktop version info

Joplin 3.0.0 (dev, linux)

Client ID: 44da07c87ebf4662aa0e0f97f77f7f38
Sync Version: 3
Profile Version: 46
Keychain Supported: No

Revision: e59211dee

ABC Sheet Music Plugin: 1.0.4
Backup: 1.4.0
CodeMirror 6 snippets: 0.0.5
Freehand Drawing: 2.7.1

### Current behaviour

1. Add a resource link to a note (e.g. with "attach file")
    - I've tested with PDF and Python files.
2. Try to open the link

Currently, this fails with a "missing property: `deleted_time`" error.

### Expected behaviour

Joplin should be able to open resource links.

### Logs

````
08:29:25: Updating items_normalized from {updated_time: 1709687458116, id: 'bb87f4b4a25a499eaa8c8219c5d03186'}
main-html.js:54 08:29:25: models/Setting: Saving settings...
main-html.js:54 08:29:25: models/Setting: Settings have been saved.
main-html.js:54 08:29:25: SearchEngine: Updated FTS table in 174ms. Inserted: 2. Deleted: 0
main-html.js:54 Got ipc-message: joplin://36403c758d9c40c08e8ba550b3b35541 {resourceId: '36403c758d9c40c08e8ba550b3b35541'}
main-html.js:54 08:29:26: CommandService::execute: openItem joplin://36403c758d9c40c08e8ba550b3b35541
main-html.js:54 Error: Missing property "deleted_time": {"id":"36403c758d9c40c08e8ba550b3b35541","title":"output.pdf","mime":"application/pdf","filename":"","created_time":1709828964028,"updated_time":1709828964287,"user_created_time":1709828964028,"user_updated_time":1709828964287,"file_extension":"pdf","encryption_cipher_text":"","encryption_applied":0,"encryption_blob_encrypted":0,"size":6226,"is_shared":0,"share_id":"","master_key_id":"","user_data":"","blob_updated_time":1709828964028,"ocr_text":"this is a test\ntesting\ntest","ocr_details":"","ocr_status":2,"ocr_error":"","type_":4}
    at checkObjectHasProperties (/home/builder/Documents/joplin/packages/utils/dist/object.js:17:19)
    at itemIsReadOnlySync (/home/builder/Documents/joplin/packages/lib/models/utils/readOnly.js:86:43)
    at /home/builder/Documents/joplin/packages/app-desktop/gui/NoteEditor/utils/contextMenu.js:67:55
    at Generator.next (<anonymous>)
    at fulfilled (/home/builder/Documents/joplin/packages/app-desktop/gui/NoteEditor/utils/contextMenu.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
````

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request improves how conflicts are handled with the trash feature.

Fixes #10080 and #10073.

# Notes

This PR does the following:
- Fixes a crash when displaying the conflicts folder.
- Fixes deleting items in the conflicts folder.
    - Previously, clicking "delete" would move an item to the trash, but it would still be visible in the conflicts folder. Additionally, clicking "restore" on such items did nothing.
 - Fixes an issue where opening an item in the conflicts folder would throw a `Missing property "deleted_time"` exception.
     - This change also fixes #10080.
- Refactors `getConflictFolderId` and `getTrashFolderId` into separate files to prevent a circular import issue.

When a conflict is deleted to trash, it now
1. Keeps the conflict as a conflict (`is_conflict = 1`)
2. Marks the conflict as deleted (`deleted_time ≠ 0`)
3. Shows the conflict in trash, but not in the "conflicts" folder

When a conflict is restored from trash, it is moved back to the conflicts folder.

## Remaining issues

I've noticed the following remaining issues that could be addressed in a follow-up pull request:
- Currently, dragging a conflict note out of trash always moves it to "Conflicts".
- Editing a note in "Conflicts" causes the conflict note to disappear until another notebook is opened, then "Conflicts" is opened again.

# Testing

To manually test this change,
1. Launch Joplin Server.
2. Connect to two different Joplin Server accounts.
3. Share a notebook from one account to the other.
4. Verify that it's still possible to open and edit a shared note.
5. Verify that it's still possible to delete and restore a shared note.
6. Create a conflict and verify that it can be deleted to trash.
7. Verify that a conflict can be restored from trash back to the conflicts notebook.
8. Verify that a conflict can be moved out of the conflicts notebook.

This has been tested successfully on Ubuntu 23.10.

On Android:
1. Create a conflict.
2. Verify that the application doesn't crash.
3. Delete a note from the conflicts notebook.
4. Verify that it is moved to the trash folder.

This has been tested successfully on Android 13.

### CODE REVIEW

File: packages/lib/models/utils/readOnly.ts [hunk 1]
```diff
@@ -75,13 +76,17 @@ export const checkIfItemCanBeAddedToFolder = async (itemType: ModelType, Folder:
...
+	if (!sharePermissionCheckOnly && isTrashableItem({ id: item.id, type_: itemType })) {
+		checkObjectHasProperties(item, ['deleted_time']);
+	}
 
 	// Item is in trash
 	if (!sharePermissionCheckOnly && item.deleted_time) return true;
 
 	if (!needsShareReadOnlyChecks(itemType, changeSource, shareState)) return false;
 
+	checkObjectHasProperties(item, ['share_id']);
```
Comment (personalizedrefrigerator) [inline packages/lib/models/utils/readOnly.ts:88]: This check was moved from the top of the function to after `needsShareReadOnlyChecks`. This matches the behavior of the function prior to [this commit](https://github.com/laurent22/joplin/commit/f19b1c536439bc0a9f04253203371c15b60f65b3#diff-aecd8fde4b82749dc0274923415a72d3b1bab247aacf2d7bff82036be9c681e0L70).

This seems to be necessary to allow the new resource-related test to pass (see `readOnly.test.ts`).

**Comment by personalizedrefrigerator** [comment]
Marking as a draft until the test failures have been resolved (this should be done in the next few hours).

**Edit**: Fixed.
