### PR TITLE
Desktop: Fixes #13574: Fix crash when opening the legacy Markdown editor

### LINKED ISSUE #13574: Text editor not working
### Operating system

Linux

### Joplin version

3.5.6

### Desktop version info

Joplin 3.5.6 (prod, linux)

Device: Linux, AMD Ryzen 7 5700X3D 8-Core Processor
Client ID: cc0410ad4df44b1ca4089d3e3a48221c
Sync Version: 3
Profile Version: 49
Keychain Supported: No
Alternate Instance ID: –

Revision: ffb3276

### Current behaviour

1. Open Joplin
2. Open some note
3. Text editor show fatal error about some plugin.

I disabled all optional plugins and restarted Joplin, but the error persists. 

### Expected behaviour

1. Open Joplin
2. Open some note
3. Text editor works.

### Logs

Error
The text editor encountered a fatal error and could not continue. The error might be due to a plugin, so please try to disable some of them and try again.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/laurent22/joplin/issues#), which will temporarily disable all plugins.

Message
e.setOption is not a function

Version info
Joplin for Desktop

Copyright © 2016-2025 Laurent Cozic
Joplin 3.5.6 (prod, linux)

Dispositivo: linux, AMD Ryzen 7 5700X3D 8-Core Processor
ID do cliente: cc0410ad4df44b1ca4089d3e3a48221c
Versão Sync: 3
Versão do Perfil: 49
Keychain Suportada: Não
ID da instância alternativa: -

Revisão: ffb3276

Backup: 1.4.3
Freehand Drawing: 3.1.0
Plugins
[
    {
        "id": "io.github.jackgruber.backup",
        "name": "Backup",
        "enabled": false,
        "version": "1.4.3"
    },
    {
        "id": "io.github.personalizedrefrigerator.js-draw",
        "name": "Freehand Drawing",
        "enabled": false,
        "version": "3.1.0"
    }
]
Stack trace
TypeError: e.setOption is not a function
    at useEditorSearchExtension (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:5305:28158)
    at Editor (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:5391:282013)
    at renderWithHooks (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:3851:419)
    at updateForwardRef (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:3867:3827)
    at beginWork (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:3869:14160)
    at beginWork$1 (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:3886:2573)
    at performUnitOfWork (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:3882:25989)
    at workLoopSync (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:3882:25495)
    at renderRootSync (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:3882:25216)
    at recoverFromConcurrentError (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:3882:20906)
Component stack

    at Editor (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:5391:281749)
    at div
    at div
    at div
    at ErrorBoundary (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:5313:1200)
    at CodeMirror (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:5391:285565)
    at div
    at div
    at div
    at NoteEditorContent (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:5560:15380)
    at ConnectFunction (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:3914:23757)
    at div
    at div
    at I (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:4349:3264)
    at div
    at LayoutItemContainer (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:4557:17410)
    at div
    at LayoutItemContainer (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:4557:17410)
    at ResizableLayout (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:4557:18337)
    at div
    at MainScreenComponent (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:5569:491)
    at ConnectFunction (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:3914:23757)
    at div
    at NavigatorComponent (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:5799:9916)
    at ConnectFunction (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:3914:23757)
    at PopupNotificationProvider (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:4742:1008)
    at Ey.ThemeProvider (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:4362:264)
    at ae (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:4347:2902)
    at RootComponent (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:6359:62)
    at ConnectFunction (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:3914:23757)
    at ErrorBoundary (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:5313:1200)
    at Provider (file:///tmp/.mount_JoplinZMCyXC/resources/app.asar/main-html.bundle.js:3918:1460)

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request fixes a regression that caused the editor to crash when opening the legacy Markdown editor.

Fixes #13574.

# Details

The regression was caused by b3bd4e03b902911a0b3c84c5e9f4cfc07cb40988, which was mistakenly included in https://github.com/laurent22/joplin/pull/13551. b3bd4e03b902911a0b3c84c5e9f4cfc07cb40988. b3bd4e03b902911a0b3c84c5e9f4cfc07cb40988 was intended to fix a multi-window support bug, but 1) was not fully tested and 2) was only a partial fix.

b3bd4e03b902911a0b3c84c5e9f4cfc07cb40988 should have been pushed to a separate branch and had its own pull request with its own manual testing plan.

# Testing plan

## Automated testing

This pull request adds a new automated test that verifies that the legacy Markdown editor can load successfully.

## Manual testing

1. Open the Markdown editor.
1. Search for something using global search.
2. Click on one of the results.
3. Verify that the results are highlighted.
4. Repeat steps 2-4 for the legacy Markdown editor.

<details><summary>Screen recording</summary>

[Screencast from 2025-10-30 09-05-46.webm](https://github.com/user-attachments/assets/cf77cbc2-f24a-4d04-b95f-4b9fe8c3b09b)

</details>

### CODE REVIEW

File: packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useEditorSearchExtension.ts [hunk 1]
```diff
@@ -49,99 +37,7 @@ const searchOverlay = (query: RegExp) => {
 	} };
 };
 
-const addCodeMirrorExtension = (CodeMirror: CodeMirror5Emulation) => {
-	CodeMirror.defineOption('joplin.search-highlight-state', null, ()=>{});
-	// eslint-disable-next-line @typescript-eslint/no-explicit-any -- Old code before rule was applied
-	CodeMirror?.defineExtension('setMarkers', function(keywords: any, options: any) {
```
Comment (personalizedrefrigerator) [inline packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useEditorSearchExtension.ts:55]: This pull request converts `setMarkers` from a CodeMirror 5 legacy extension to a regular function. One of the issues that b3bd4e03b902911a0b3c84c5e9f4cfc07cb40988 tried to address was that legacy CodeMirror 5 extensions are defined for all editor instances. As a result, `clearMarkers`/`setMarkers` would often use state associated with the wrong editor. This issue is easier to to address if the `setMarkers` function is a standard function that accepts an editor as input.

The legacy editor crash was caused by differences in the CodeMirror 6 compatibility layer and CodeMirror 5. In particular, the way that the current editor state was passed to the `searchMarkers` extension worked with the CodeMirror 6 compatibility layer, but not CodeMirror 5.
