### PR TITLE
Desktop: Fixes #13267: Fixed image load failure when path contains '#' (13267)

### LINKED ISSUE #13267: Image at D:\xxxxx Failed to Load
### Operating system

Windows

### Joplin version

3.4.12

### Desktop version info

Joplin 3.4.12 (prod, win32)

Device: win32, AMD Ryzen 9 3900X 12-Core Processor            
Client ID: 37e8bb9cb4ef439fa60080a445d4e5ab
Sync Version: 3
Profile Version: 48
Keychain Supported: Yes
Alternative instance ID: -

Revision: e9a9f68

Backup: 1.4.3
Favorites: 1.3.2
Freehand Drawing: 3.1.0
Joplin DDDot: 0.4.2
Note Link System: 0.8.0
Note list (Preview): 1.1.0
Note overview: 1.7.1
Rich Markdown: 0.15.1
Search & Replace: 2.2.0

### Current behaviour

Drag image from certain folders into a note, it fails with the error message in the subject line.

Image

### Expected behaviour

I expected it to work as it does if I copy the same failing image from "D:\TMP\### Download ###" to the desktop folder.

### Logs

09:35:07: resourceHandling: Attaching D:\TMP\### Download ###\Plan - 461_Ray-756-10.png
/D:/TMP/###%20Download%20###\Plan%20-%20461_Ray-756-10.png:1 
            
            
           GET file:///D:/TMP/ net::ERR_FILE_NOT_FOUND
Image
handleResizeImage_ @ shim-init-node.ts:239
di.default.createResourceFromPath @ shim-init-node.ts:371
await in di.default.createResourceFromPath
di.default.attachFileToNoteBody @ shim-init-node.ts:420
commandAttachFileToBody @ resourceHandling.ts:50
(anonymous) @ TinyMCE.tsx:149
execCommand @ TinyMCE.tsx:243
(anonymous) @ useDropHandler.ts:73
(anonymous) @ TinyMCE.tsx:895
dispatch @ tinymce.min.js:384
dispatch @ tinymce.min.js:384
PO @ tinymce.min.js:384
o @ tinymce.min.js:384
executeHandlers @ tinymce.min.js:4
i @ tinymce.min.js:4
Logger.ts:317 09:35:07: resourceHandling: Error: Image at D:\TMP\### Download ###\Plan - 461_Ray-756-10.png failed to load.
    at h.onerror (shim-init-node.ts:242:34)

----[log.txt]-------------
2025-09-22 09:34:23: resourceHandling: Attaching D:\TMP\### Download ###\Plan - 461_Ray-756-10.png
2025-09-22 09:34:23: resourceHandling: [error] Error: Image at D:\TMP\### Download ###\Plan - 461_Ray-756-10.png failed to load.
Error: Image at D:\TMP\### Download ###\Plan - 461_Ray-756-10.png failed to load.
    at h.onerror (file:///C:/Users/Dennis/AppData/Local/Programs/Joplin/resources/app.asar/main-html.bundle.js:3340:46608)
2025-09-22 09:35:07: resourceHandling: Attaching D:\TMP\### Download ###\Plan - 461_Ray-756-10.png
2025-09-22 09:35:07: resourceHandling: [error] Error: Image at D:\TMP\### Download ###\Plan - 461_Ray-756-10.png failed to load.
Error: Image at D:\TMP\### Download ###\Plan - 461_Ray-756-10.png failed to load.
    at h.onerror (file:///C:/Users/Dennis/AppData/Local/Programs/Joplin/resources/app.asar/main-html.bundle.js:3340:46608)

### PR DESCRIPTION
**Pull request by yingli-lab**
### Description

This pull request fixes [#13267](https://github.com/laurent22/joplin/issues/13267), where images failed to load if their file path contained the # character.

### Problem
When dragging an image from a folder whose name includes #, the app displayed an error such as:
Image at /Users/Example/Pictures/foo#bar/image.png failed to load.

This happened because the Image.src property in shim-init-node.ts was assigned a raw file system path.
Electron’s Image element treated # as a URL fragment, causing the load failure.

### Fix
Updated packages/lib/shim-init-node.ts to use Node’s built-in pathToFileURL() when assigning Image.src.

pathToFileURL() correctly normalizes slashes and percent-encodes reserved characters (#, ?, [, ]), preventing them from being misinterpreted as URL fragments.

### Result
Images now load correctly when their file path or parent folder contains #, both works on my macOS and Windows.

https://github.com/user-attachments/assets/fb004e26-82e9-4856-bc98-68b4894f05fb

### CODE REVIEW

File: packages/lib/shim-init-node.ts [hunk 1]
```diff
@@ -20,6 +20,7 @@ import { Size } from '@joplin/utils/types';
 import { cpus } from 'os';
 import type PdfJs from './utils/types/pdfJs';
 const { _ } = require('./locale');
+const { pathToFileURL } = require('url');
```
Comment (laurent22) [inline packages/lib/shim-init-node.ts]: For new code we should use `import` so as to enable type checking

Comment (yingli-lab) [reply packages/lib/shim-init-node.ts]: Thanks Laurent! I’ve updated it to use import { pathToFileURL } from 'url'; for proper type checking. The change has been pushed.

**Comment by laurent22** [comment]
Thank you for fixing this!
