### PR TITLE
Android: Fixes #14268: Fix additional space included above keyboard

### LINKED ISSUE #14268: Mobile: Viewport resizes to less than the available vertical space, when keyboard is showing (3.6 regression)
### Operating system

Android

### Joplin version

3.6.12

### Desktop version info

When the on screen keyboard is opened, there is a fixed size gap of whitespace above the keyboard. The size of the gap is the same, regardless of whether gesture or 3 button navigation is enabled.

Image

Image

Image

Image

Tested on Android 16 emulator

### Current behaviour

_No response_

### Expected behaviour

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
## Summary

Fixes a regression from #14232 in which Android >= API 35 devices had additional space between the top of the keyboard and the Markdown toolbar.

Fixes #14268.

## Testing

Manual testing (Android 16/dev mode, Android 12/dev mode):
- Initial configuration:
  - Android 16: The software keyboard should be preconfigured to be docked to the bottom of the screen (disable the floating keyboard).
- Testing plan
  1. Start Joplin.
  2. Open the note editor and the software keyboard.
  3. Verify that the autocompletion bar is above the keyboard with no space between the completion bar and the top of the keyboard.

### CODE REVIEW

File: packages/app-mobile/components/app-nav.tsx [hunk 1]
```diff
@@ -63,17 +63,17 @@ const AppNavComponent: React.FC<Props> = (props) => {
 
 	const theme = themeStyle(props.themeId);
 	const styles = useStyles(theme);
-	const autocompletionBarPadding = keyboardState.keyboardVisible ? safeAreaPadding.top : 0;
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/app-nav.tsx:66]: Previously, the `autocompletionBarPadding` was non-zero even if the `<KeyboardAvoidingView` was not rendered. The `autocompletionBarPadding` workaround was originally added in https://github.com/laurent22/joplin/pull/12027, with an earlier workaround for the same issue added in https://github.com/laurent22/joplin/pull/6823.

As per [comment](https://github.com/laurent22/joplin/pull/14232#discussion_r2756452607), it may make sense to migrate away from `<KeyboardAvoidingView` in the future.
