### PR TITLE
Desktop,Cli: Fixes #14954: Fix changes made in an external editor are sometimes ignored

### LINKED ISSUE #14954: Losing data upon external editor save
### Operating system

Linux

### Joplin version

3.5.13

### Desktop version info

Joplin 3.5.13 (prod, linux)

Device: linux, AMD Ryzen 7 8845HS w/ Radeon 780M Graphics
Client ID: 9959465eea794e60b1b95760c308ca91
Sync Version: 3
Profile Version: 49
Keychain Supported: No
Alternative instance ID: -

Revision: 0c1511f

Backup: 1.5.1
Combine notes: 1.2.3
Conflict Resolution: 1.2.3
Diff view: 0.3.1
Extra Markdown editor settings: 1.11.0
Hotfolder: 1.2.3
Import local CSS: 1.1.0
Inline tags: 1.3.0
Inline TODO: 2.0.5
Note list (Preview): 1.1.0
Note list and sidebar toggle buttons: 1.0.3
Note Rename: 1.0.0
Note Tabs: 1.4.0
Persistent Editor Layout: 2.2.0
Quick Links: 1.3.2
Save Note as MD: 1.0.2
Space Indenter: 0.2.6
Tagging: 1.0.3
Templates: 3.0.0
YesYouKan: 1.1.3

### Current behaviour

As discussed in the Discord, I will happen upon a note where a huge chunk of it has disappeared. Sometimes I will be blithely edit a note even after it has lopped off a 1000 lines that I haven't realized. And so, trying to figure out the diff between these notes in order to repair them is very challenging. Especially since I am a writer and sometimes it is a comma here, and typo fixed there, and ... You get the picture.

What I *think* the order of operations is …
- I use Zed as my external editor (current version Zed 0.228.0)
  - Note, I am switching editors TODAY. I am terrified of losing more work. Not that I think Zed does anything odd. Maybe I need to steer clear of external editors for awhile.
- I save, close, come back later, and see a massive chunk of the note is missing.
  - never the beginning. Always somewhere in the middle of the note and onwards. (a buffering issue?)
- I see a closely timed sync operation in at least one of these logs. Could there be some write-lock shenanigans going on? (I sync to Joplin Cloud and it is scheduled for every 10 minutes.)
- It also seems to happen with longer notes. I have a lot of longer notes.

Note. I have only once seen the issue happen in real time: I had Zed in one monitor, and the rendered view of the note in Joplin on the other screen. I CTRL-S'ed in Zed (save) and saw the view truncated. (The note in Zed remained as it should. I made a small change and saved again and the note was restored.)

I am sending two sets of logs.

## (1) note `45dd0e13258b4ab4b0ffda9e3ac15c91` (change at 03-29 15:01)

Image

[log-saved-45dd0e13258b4ab4b0ffda9e3ac15c91.txt](https://github.com/user-attachments/files/26336950/log-saved-45dd0e13258b4ab4b0ffda9e3ac15c91.txt)

## (2) note `0b10dcc6961547d5a15f1f5c2235c90a` (change at 03-27 17:55).

Image

[log-saved-0b10dcc6961547d5a15f1f5c2235c90a.txt](https://github.com/user-attachments/files/26336946/log-saved-0b10dcc6961547d5a15f1f5c2235c90a.txt)

### Expected behaviour

Joplin retains note integrity.

### Logs

Supplied. See above.

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Problem

The external edit watcher could miss changes in a rapidly-changing file.

Joplin uses [Chokidar](https://github.com/paulmillr/chokidar/tree/7c50e25d10a497ce4409f6e52eb630f0d7647b97) to watch for file changes. Currently, file change events are interpreted roughly as "the file just changed". Joplin reads the file from disk and updates the note. However, Chokidar can throttle events:
1. If the file changes multiple times in the same 50ms, Chokidar only emits the first event (see the upstream [`index.js/_throttle`](https://github.com/paulmillr/chokidar/blob/7c50e25d10a497ce4409f6e52eb630f0d7647b97/index.js#L659) and [usage](https://github.com/paulmillr/chokidar/blob/7c50e25d10a497ce4409f6e52eb630f0d7647b97/index.js#L616)).
2. If there's another change event, greater than, e.g., 51ms after the emitted change, Chokidar emits the event.
   - This won't be exactly 50ms, since Chokidar uses `setTimeout` and there might be a delay in clearing the event throttling.

*May* fix #14954.

# Solution

Defer processing of `Update` changes so that Joplin reads the file just after the **end** of each 50ms block, rather than the start.

# Testing

This pull request includes an automated test that fails if the changes to `ExternalEditWatcher.ts` are reverted. This test:
1. Creates a note and starts watching it.
2. Appends to the note.
3. After 10ms, appends to the note again.
4. Repeats (3) two more times.
5. Verifies that the note includes all of the changes.

If I revert the changes to `ExternalEditWatcher`, the test (**edit**: usually, but not always) fails with
```
    - Expected  - 1
    + Received  + 1

      Object {
    -   "body": "test1234",
    +   "body": "test123",
        "title": "Testing",
      }

      66 |                      // Should detect both changes
      67 |                      await waitFor(async () => {
    > 68 |                              expect(await Note.load(note.id)).toMatchObject({
         |                                                               ^
      69 |                                      title: 'Testing',
      70 |                                      body: 'test1234',
      71 |                              });

      at toMatchObject (services/ExternalEditWatcher.test.ts:68:38)
      at waitFor (testing/waitFor.ts:14:4)
      at Object.<anonymous> (services/ExternalEditWatcher.test.ts:67:4)
```

### CODE REVIEW

File: packages/lib/services/ExternalEditWatcher.ts [hunk 1]
```diff
@@ -162,6 +152,51 @@ export default class ExternalEditWatcher {
...
+		// In some very rare cases, the "change" event is going to be emitted but the file will be empty.
+		// This is likely to be the editor that first clears the file, then writes the content to it, so if
+		// the file content is read very quickly after the change event, we'll get empty content.
+		// Usually, re-reading the content again will fix the issue and give back the file content.
+		// To replicate on Windows: associate Typora as external editor, and leave Ctrl+S pressed -
+		// it will keep on saving very fast and the bug should happen at some point.
+		// Below we re-read the file multiple times until we get the content, but in my tests it always
+		// work in the first try anyway. The loop is just for extra safety.
+		// https://github.com/laurent22/joplin/issues/1854
+		if (!noteContent) {
```
Comment (personalizedrefrigerator) [inline packages/lib/services/ExternalEditWatcher.ts:176]: We *might* be able to remove this workaround. If the original issue was caused by Chokidar's throttling, the new logic might be sufficient to fix the issue.

File: packages/lib/testing/test-utils.ts [hunk 2]
```diff
@@ -503,6 +503,8 @@ async function setupDatabaseAndSynchronizer(id: number, options: any = null) {
 	resourceFetchers_[id] = new ResourceFetcher(() => { return synchronizers_[id].api(); });
 	kvStores_[id] = new KvStore();
 
+	BaseItem.revisionService_ = revisionServices_[id];
```
Comment (personalizedrefrigerator) [inline packages/lib/testing/test-utils.ts]: This change is needed to prevent test failures related to `Note.save`:
```
09:49:38: AsyncActionQueue: Unhandled error: Error: BaseItem.revisionService_ is not set!!
    at Function.revisionService (/home/self/Documents/joplin/packages/lib/models/BaseItem.ts:505:37)
    at Function.revisionService [as save] (/home/self/Documents/joplin/packages/lib/models/Note.ts:825:40)
    at ExternalEditWatcher.onNoteChange_ (/home/self/Documents/joplin/packages/lib/services/ExternalEditWatcher.ts:194:3)
```

File: packages/lib/services/ExternalEditWatcher.ts [hunk 3]
```diff
@@ -236,6 +271,8 @@ export default class ExternalEditWatcher {
 	public async stopWatching(noteId: string) {
 		if (!noteId) return;
 
+		await this.changeEventQueue_.processAllNow();
+
```
[the remark this answers is not in the document]
Comment (personalizedrefrigerator) [reply packages/lib/services/ExternalEditWatcher.ts:275]: Hmmm... Calling `waitForAllDone` could also cause problems if the queue is busy. For example, if an external editor auto-changes the file every 30ms, `waitForAllDone` will never complete.

**Edit**: Note that `stopWatching(noteId)` seems only to be called in response to a note deletion or an action taken by a user.

File: packages/lib/testing/test-utils.ts (hunk 2 above)
Comment (personalizedrefrigerator) [reply packages/lib/testing/test-utils.ts]: This isn't actually needed. The error was caused by a missing call to `switchClient`.
