### PR TITLE
Mobile,Desktop,Cli: Fixes #10896: Fix "Enable auto-updates" enabled by default and visible on unsupported platforms

### LINKED ISSUE #10896: "Enable auto-updates" visible in mobile settings screen
### Operating system

Linux

### Joplin version

3.1.0

### Desktop version info

Joplin Mobile 3.1.0 (prod, web)

Client ID: a98ce21ce53247e0a10036b6567de82a
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: b3437fa (dev)

Extra Markdown viewer settings: 0.2.0
Menu items, Shortcuts, Toolbar icons: 1.1.0

User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
FTS enabled: 1
Hermes enabled: 0

### Current behaviour

1. Open "Configuration"
2. Click "Application"
3. Observe that an "Enable auto-updates" setting is visible.

### Expected behaviour

The auto-update setting should only be visible on desktop.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request fixes #10896 -- "enable auto-updates" (which only applies to desktop) was visible in mobile settings (and also likely in CLI).

# Testing plan

1. Start Joplin (Web)
2. Open "Configuration"
3. Verify that the "Application" tab is not visible.
4. Search for "updates".
5. Verify that the "enable auto-updates" setting is not visible.

---

1. Start Joplin (desktop, Windows).
2. Open settings.
3. Open the "Application" tab.
4. Verify that the "Enable auto-updates" setting is visible.

### CODE REVIEW

File: packages/lib/models/settings/builtInMetadata.ts [hunk 1]
```diff
@@ -1553,12 +1553,14 @@ const builtInMetadata = (Setting: typeof SettingType) => {
...
 		'featureFlag.autoUpdaterServiceEnabled': {
-			value: true,
+			value: false,
 			type: SettingItemType.Bool,
 			public: true,
 			storage: SettingStorage.File,
+			appTypes: [AppType.Desktop],
 			label: () => 'Enable auto-updates',
 			description: () => 'Enable this feature to receive notifications about updates and install them instead of manually downloading them. Restart app to start receiving auto-updates.',
+			show: () => shim.isWindows() || shim.isMac(),
```
Comment (personalizedrefrigerator) [inline packages/lib/models/settings/builtInMetadata.ts:1563]: Auto-updates [seems to be unsupported on Linux](https://github.com/laurent22/joplin/commit/72163018b4a168d8ae0001010cb1dcdb76932303#diff-c8f06d858a0995504e445e3918df266a32acc754589994fcc4bccef75a8e9959R574).
