### PR TITLE
Mobile: fixed bold text not visible in dark theme

### LINKED ISSUE #2900: Android: Bold text is black color in dark and oled dark themes
Both the dark theme and oled dark themes on android are showing bold text in a black color when in view mode. This is particularly bad in oled dark as the text becomes invisible. 

image

image

image

image

## Environment

Joplin version: 1.0.324
Platform: Android

### PR DESCRIPTION
**Pull request by ishantgupta777**
closes #2900 
@PackElend  please label my PR.

Before:
Annotation 2020-03-26 082032
After:
Screenshot_1585190823

Annotation 2020-03-26 081016

### CODE REVIEW

File: ReactNativeClient/lib/components/global-style.js [hunk 1]
```diff
@@ -153,6 +153,8 @@ function themeStyle(theme) {
 
 		output.colorUrl = '#7B81FF';
 
+		output.strongTextColor = 'rgb(220,220,220)';
```
Comment (CalebJohn) [inline ReactNativeClient/lib/components/global-style.js]: This should be `output.colorBright`. Unless I'm missing some reason for adding a new theme variable.

Comment (ishantgupta777) [reply ReactNativeClient/lib/components/global-style.js]: Sir, I changed the variable name to color bright. I added a new variable because I thought color bright won't be a good name for all themes, as it sounds like it's for the light theme. 
Please check it now.
Thanks

**Comment by CalebJohn** [comment]
LGTM
