### PR TITLE
Chore: Mobile: Fix Note.test.tsx warnings

### LINKED ISSUE #12442: Remove app-mobile warnings from test units
```
[@joplin/app-mobile]: Warning: An update to Connect(ShareNoteDialog) inside a test was not wrapped in act(...).
[@joplin/app-mobile]: 
[@joplin/app-mobile]: When testing, code that causes React state updates should be wrapped into act(...):
[@joplin/app-mobile]: 
[@joplin/app-mobile]: act(() => {
[@joplin/app-mobile]:   /* fire events that update state */
[@joplin/app-mobile]: });
[@joplin/app-mobile]: /* assert on the output */
[@joplin/app-mobile]: 
[@joplin/app-mobile]: This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
[@joplin/app-mobile]:     at useMemo (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/react-redux/lib/components/connect.js:246:74)
[@joplin/app-mobile]:     at View
[@joplin/app-mobile]:     at View (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/react-native/jest/mockComponent.js:33:18)
[@joplin/app-mobile]:     at NoteScreenComponent (/home/runner/work/joplin/joplin/packages/app-mobile/components/screens/Note/Note.tsx:190:3)
[@joplin/app-mobile]:     at NoteScreenWrapper (/home/runner/work/joplin/joplin/packages/app-mobile/components/screens/Note/Note.tsx:1763:28)
[@joplin/app-mobile]:     at useMemo (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/react-redux/lib/components/connect.js:246:74)
[@joplin/app-mobile]:     at apply (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/@callstack/react-theme-provider/src/createThemeProvider.js:14:3)
[@joplin/app-mobile]:     at View
[@joplin/app-mobile]:     at View (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/react-native/jest/mockComponent.js:33:18)
[@joplin/app-mobile]:     at PortalHost (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/react-native-paper/src/components/Portal/PortalHost.tsx:45:32)
[@joplin/app-mobile]:     at RNCSafeAreaProvider
[@joplin/app-mobile]:     at Component (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/react-native/jest/mockNativeComponent.js:17:18)
[@joplin/app-mobile]:     at children (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/react-native-safe-area-context/src/SafeAreaContext.tsx:35:3)
[@joplin/app-mobile]:     at children (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/react-native-paper/src/core/SafeAreaProviderCompat.tsx:38:50)
[@joplin/app-mobile]:     at theme (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/react-native-paper/src/core/PaperProvider.tsx:25:11)
[@joplin/app-mobile]:     at View
[@joplin/app-mobile]:     at View (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/react-native/jest/mockComponent.js:33:18)
[@joplin/app-mobile]:     at View
[@joplin/app-mobile]:     at View (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/react-native/jest/mockComponent.js:33:18)
[@joplin/app-mobile]:     at _classCallCheck (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/react-native-popup-menu/src/MenuProvider.js:28:22)
[@joplin/app-mobile]:     at FocusControlProvider (/home/runner/work/joplin/joplin/packages/app-mobile/components/accessibility/FocusControl/FocusControlProvider.tsx:20:48)
[@joplin/app-mobile]:     at store (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/react-redux/lib/components/Provider.js:19:3)
[@joplin/app-mobile]:     at TestProviderStack (/home/runner/work/joplin/joplin/packages/app-mobile/components/testing/TestProviderStack.tsx:15:32)
[@joplin/app-mobile]:     at WrappedNoteScreen
```

Not sure if this one is part of the same warning:

```
[@joplin/app-mobile]: [UNINITIALIZED GLOBAL LOGGER] debug: focusHandler: [ 'Action "focus" from "editorCommands::focus"' ]
```

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request fixes two warnings observed in Note.test.tsx:
- An "uninitialized global logger" warning -- fixed by initializing the global logger within the webview.
- A "wrap state modifications in act()" -- fixed by wrapping cleanup code in act().

Fixes https://github.com/laurent22/joplin/issues/12442, https://github.com/laurent22/joplin/issues/11127.

# Testing plan

**Web**: 
1. Open a note.
2. Switch to the note editor.
3. Click just below the note editor.
4. Check the console for an "uninitialized global logger" warning.
    - **Note**: There may be other warnings related to "`BackHandler` is not supported on web" or the runtime `fsDriver` tests. I plan to fix these in a follow-up pull request.

### CODE REVIEW

File: packages/app-mobile/components/NoteEditor/CodeMirror/CodeMirror.ts [hunk 1]
```diff
@@ -15,6 +15,18 @@ import CodeMirrorControl from '@joplin/editor/CodeMirror/CodeMirrorControl';
...
+
+let loggerCreated = false;
+export const setUpLogger = () => {
+	if (!loggerCreated) {
+		const logger = new Logger();
+		logger.addTarget(TargetType.Console);
+		logger.setLevel(Logger.LEVEL_WARN);
+		Logger.initializeGlobalLogger(logger);
+		loggerCreated = true;
+	}
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/NoteEditor/CodeMirror/CodeMirror.ts:28]: **Note**: In the note editor WebView, this logger is currently only used for logging `focus(...)` calls. As a result, setting the level to `LEVEL_WARN` silences these messages. This could alternatively be `LEVEL_DEBUG`, but this will lead to more output during tests and the debug output would still not be transferred to Joplin's logs at runtime.

In the future, it may make sense to transfer note editor logs to Joplin's log output, perhaps with something similar to what is currently done for the plugin WebViews.
