### PR TITLE
All: Fixes #6197: Fixed import empty directory create empty subnotebooks

### LINKED ISSUE #6197: Desktop: Import Markdown + Front Matter Directory should not create empty subnotebooks
## Environment

Joplin version: 2.6.10 / Portable and 2.7.13 / portable
Platform: Windows
OS specifics: Win10

## Steps to reproduce

1. Launch JoplinPortable from a clean install
2. Select File / Import / MD Markdown + Front Matter (Directory)
3. Wait for completion

## Describe what you expected to happen

All empty subdirectories from the import Directory should not create a subnotebook in Joplin. More specifically, subdirs with images used by md files (images that will be imported to Joplin) should not create a subnotebook if it does not include any MD file (just images). At the end of the import process, many subnotebooks exist but are empty ... 
(Note : those subdirs come from Typora and are used to store assets : they are usually named XXX.assets where XXX is the name of the MD file being imported)

Besides, when importing only one MD file (with a subdir XXX.asset where images are stored), no subnotebook are created.

### PR DESCRIPTION
**Pull request by Retr0ve**
This PR checks whether a directory and all of its subdirectories contain md file before creating a subnotebook.
Fixed #6197 .

### CODE REVIEW

File: packages/lib/services/interop/InteropService_Importer_Md.ts [hunk 1]
```diff
@@ -63,6 +67,28 @@ export default class InteropService_Importer_Md extends InteropService_Importer_
...
+				if (!await this.isDirectoryEmpty(`${dirPath}/${basename(stat.path)}`, innerStat)) {
+					isEmpty = false;
+					break;
+				}
+			} else if (supportedFileExtension.indexOf(fileExtension(innerStat.path).toLowerCase()) >= 0) {
+				isEmpty = false;
+				break;
+			}
+		}
+		return isEmpty;
```
Comment (laurent22) [inline packages/lib/services/interop/InteropService_Importer_Md.ts:88]: return true

File: packages/lib/services/interop/InteropService_Importer_Md.ts [hunk 2]
```diff
@@ -63,6 +67,28 @@ export default class InteropService_Importer_Md extends InteropService_Importer_
 		}
 	}
 
+	// If the directory's all subdirectories are empty, we don't want to create a folder with no notes
+	private async isDirectoryEmpty(dirPath: string, stat: any) {
```
Comment (laurent22) [inline packages/lib/services/interop/InteropService_Importer_Md.ts:71]: Please give meaningful names to your variables - it's very confusing now because dirPath is not the directory you're testing, and "stat" is not the dir stats, but one of its child item stat. Maybe you need to rewrite this so that it takes only one argument - the directory to be tested.

File: packages/app-cli/tests/support/test_notes/directory/non-empty/non-empty/sample.md [hunk 3]
```diff
@@ -0,0 +1,3 @@
+# Markdown
+
+Test sample.
```
Comment (laurent22) [inline packages/app-cli/tests/support/test_notes/directory/non-empty/non-empty/sample.md:3]: Please remove all these test files. Usually when we have such files it's to test things like parsing and rendering, but in this case it doesn't make much sense. Could you create them dynamically in a temp directory and delete them when it's done? Use createTempDir from test-utils.ts for this.

Comment (Retr0ve) [reply packages/app-cli/tests/support/test_notes/directory/non-empty/non-empty/sample.md]: Done

File: packages/lib/services/interop/InteropService_Importer_Md.ts [hunk 4]
```diff
@@ -63,6 +67,28 @@ export default class InteropService_Importer_Md extends InteropService_Importer_
...
+		const supportedFileExtension = this.metadata().fileExtensions;
+		let isEmpty = true;
+		const innerStats = await shim.fsDriver().readDirStats(`${dirPath}/${basename(stat.path)}`);
+		for (let i = 0; i < innerStats.length; i++) {
+			const innerStat = innerStats[i];
+
+			if (innerStat.isDirectory()) {
+				if (!await this.isDirectoryEmpty(`${dirPath}/${basename(stat.path)}`, innerStat)) {
```
[the remark this answers is not in the document]
Comment (Retr0ve) [reply packages/lib/services/interop/InteropService_Importer_Md.ts]: It works without brackets, but I now added them in case of misunderstanding.

File: packages/lib/services/interop/InteropService_Importer_Md.ts (hunk 2 above)
Comment (Retr0ve) [reply packages/lib/services/interop/InteropService_Importer_Md.ts]: Done

**Comment by laurent22** [comment]
Please read again the pull request reviews, in particular:

> Please do not `@mention` contributors and mentors and **do not ask for pull request reviews**. Sometimes it takes time before we can review your pull request or answer your questions but we'll get to it sooner or later. `@mentioning` someone just adds to the pile of notifications we get and it won't make us look at your issue faster.

File: packages/lib/services/interop/InteropService_Importer_Md.test.ts [hunk 5]
```diff
@@ -1,21 +1,34 @@
...
 		importer.setMetadata({ fileExtensions: ['md', 'html'] });
 		return await importer.importFile(path, 'notebook');
 	}
-
+	async function importNoteDirectory(path: string) {
+		const importer = new InteropService_Importer_Md();
+		importer.setMetadata({ fileExtensions: ['md', 'html'] });
+		return await importer.importDirectory(path, 'notebook');
+	}
+	beforeAll(async () => {
```
Comment (laurent22) [inline packages/lib/services/interop/InteropService_Importer_Md.test.ts]: Should be done in beforeEach / afterEach, otherwise you can't know if your tests are valid since they may use data from previous tests.

File: packages/lib/services/interop/InteropService_Importer_Md.test.ts [hunk 6]
```diff
@@ -117,4 +130,30 @@ describe('InteropService_Importer_Md: importLocalImages', function() {
...
+		expect(allFolders.map((f: any) => f.title).indexOf('empty')).toBe(-1);
+	});
+	it('should import directory with non-empty subdirectory', async function() {
+		await fs.mkdirp(`${rootDir}/non-empty-subdir/non-empty-subdir/subdir-empty`);
+		await fs.mkdirp(`${rootDir}/non-empty-subdir/non-empty-subdir/subdir-non-empty`);
+		await fs.writeFile(`${rootDir}/non-empty-subdir/non-empty-subdir/subdir-non-empty/sample.md`, '# Sample');
+
+		await importNoteDirectory(`${rootDir}/non-empty-subdir`);
+		const allFolders = await Folder.all();
+		expect(allFolders.map((f: any) => f.title).indexOf('non-empty-subdir')).toBeGreaterThanOrEqual(0);
```
Comment (laurent22) [inline packages/lib/services/interop/InteropService_Importer_Md.test.ts]: any => FolderEntity

File: packages/lib/services/interop/InteropService_Importer_Md.test.ts [hunk 7]
```diff
@@ -117,4 +130,30 @@ describe('InteropService_Importer_Md: importLocalImages', function() {
 		const preservedAlt = note.body.includes('alt="../../photo.jpg"');
 		expect(preservedAlt).toBe(true);
 	});
+	it('should import non-empty directory', async function() {
+		await fs.mkdirp(`${rootDir}/non-empty/non-empty`);
+		await fs.writeFile(`${rootDir}/non-empty/non-empty/sample.md`, '# Sample');
+
+		await importNoteDirectory(`${rootDir}/non-empty`);
+		const allFolders = await Folder.all();
+		expect(allFolders.map((f: any) => f.title).indexOf('non-empty')).toBeGreaterThanOrEqual(0);
```
Comment (laurent22) [inline packages/lib/services/interop/InteropService_Importer_Md.test.ts]: Please replace all the "any" with FolderEntity

File: packages/lib/services/interop/InteropService_Importer_Md.ts [hunk 8]
```diff
@@ -47,13 +47,16 @@ export default class InteropService_Importer_Md extends InteropService_Importer_
...
 	async importDirectory(dirPath: string, parentFolderId: string) {
 		console.info(`Import: ${dirPath}`);
-
 		const supportedFileExtension = this.metadata().fileExtensions;
 		const stats = await shim.fsDriver().readDirStats(dirPath);
 		for (let i = 0; i < stats.length; i++) {
 			const stat = stats[i];
 
 			if (stat.isDirectory()) {
+				if (await this.isDirectoryEmpty(`${dirPath}/${basename(stat.path)}`)) {
```
Comment (laurent22) [inline packages/lib/services/interop/InteropService_Importer_Md.ts]: Why "basename"? It should be `dirPath + stat.path` or the logic is not right.

File: packages/lib/services/interop/InteropService_Importer_Md.ts [hunk 9]
```diff
@@ -63,6 +66,24 @@ export default class InteropService_Importer_Md extends InteropService_Importer_
...
 	}
 
+	private async isDirectoryEmpty(dirPath: string) {
+		const supportedFileExtension = this.metadata().fileExtensions;
+		const innerStats = await shim.fsDriver().readDirStats(dirPath);
+		for (let i = 0; i < innerStats.length; i++) {
+			const innerStat = innerStats[i];
+
+			if (innerStat.isDirectory()) {
+				if (!(await this.isDirectoryEmpty(`${dirPath}/${basename(innerStat.path)}`))) {
```
Comment (laurent22) [inline packages/lib/services/interop/InteropService_Importer_Md.ts]: Why "basename"?

File: packages/lib/services/interop/InteropService_Importer_Md.test.ts (hunk 5 above)
Comment (Retr0ve) [reply packages/lib/services/interop/InteropService_Importer_Md.test.ts]: Thanks for your review, I'm just creating a rootDir for testing here, all the tests runs in their sperate subdir. Therefore it should not be a issue. Or maybe it is better to create a temp folder for every test instead of one rootDir?

File: packages/lib/services/interop/InteropService_Importer_Md.ts (hunk 8 above)
Comment (Retr0ve) [reply packages/lib/services/interop/InteropService_Importer_Md.ts]: Yes, it should be `dirPath + stat.path`. It is a mistake.

File: packages/lib/services/interop/InteropService_Importer_Md.test.ts (hunk 5 above)
Comment (laurent22) [reply packages/lib/services/interop/InteropService_Importer_Md.test.ts]: Yes creating a temp folder and deleting it after each test would be better, to make sure there's no interference between tests. And please rename it tempDir, or anything other than rootDir.

**Comment by laurent22** [comment]
Looks like it's all good now, thanks for fixing this @Retr0ve!
