### PR TITLE
All: Switch to aws-sdk-js-v3 resolves #4810 & resolves #4610

### LINKED ISSUE #4610: IOS App use awss3 synchronous show error "XMLParserError: Non-whitespace before first tag"
## Environment

Joplin version: 10.7.2
Platform: iPhone12
OS specifics: IOS14.3

## Steps to reproduce

1.Import data from evernote
2. window use awss3 to sync
3. open e2ee
4. iphone complete synchronization
5. iphone input e2ee password start decryption
6. show the error message：“XMLParserError: Non-whitespace before first tag.”

## Logfile
3e494a1811dfc309bb06e22e6ffa275
5229a8c03ba2d4cffce17c0ec7a322f

### LINKED ISSUE #4810: AWS S3 Synchronisation Error on iOS deivce
## Environment

Joplin version: 10.7.2 (Latest on iOS for now)
Platform: iOS
OS specifics: 14.4.1 on iPhone (Latest for now)

## Steps to reproduce

1. First time synchronisation on windows with E2EE enable
2. Synchronisation to AWS S3 Server
3. First time synchronisation on iOS
4. got an error like this:
         “XMLParserError：Non-whitespace before first tag.
         Line: 0
         Column: 1
         Char: S”。

## Describe what you expected to happen
The notes seems fine in the first time that I synchronisation on iOS (This Error message appear when the synchronisation is almost finished) , but when this error appear,  the synchronisation function is totally broken and noting can be synchronisation neither other platform---->iOS nor iOS-----> other platform.

The notes that I have, almost all notes is I manually added, and a few is I import form md files that I exported from Notion app. 

I tried 10 times, even change the provider of the server and it can be resocced every time.
## Logfile

IMG_0782
IMG_0783
IMG_0784
IMG_0785

### PR DESCRIPTION
**Pull request by leematos**
This change resolves #4810 and resolves #4610 🎉 

I wasn't able to get the iOS specific fix to work and my prior MR left in the large aws-sdk package which this change can now safely remove.

I've tested via my iOS simulator with a bucket that would exhibit the problem and have never hit an error uploading to my test buckets after this change. I think the core of the problem was something to do with xml2js which v3 replaces with fast-xml-parser. This still needs testing on Linux (do you target any specific distros for testing?) and android/mac/windows as well.

You can see the changes are pretty straightforward, but I do expect there could be gremins with electron vs. react-native but they should be pretty obvious once tested. (I can test Linux/Mac/iOS but not Android/Windows).

### CODE REVIEW

**Comment by laurent22** [comment]
To check if there's any issue please run the test units:

- In lib/testing/test-utils, `setSyncTargetName('amazon_s3')`
- Create the file app-cli/tests/support/amazon-s3-auth.json as described in test-utils
- Run `npm test` from /lib

**Comment by laurent22** [comment]
Also do search for "aws-sdk" to make sure you remove all instances of the package (see failed tests)

**Comment by laurent22** [comment]
If it works on macOS and Linux, there's a good chance it will work on Windows. However I wouldn't be so sure about Android, so please make sure you find someone who can check.

**Comment by roman-r-m** [comment]
I could check if someone could share account details as I don't have one.

**Comment by leematos** [comment]
@roman-r-m awesome -- shoot me an email at (find dot creativity at github username dot com) and I can get you a test bucket.

**Comment by leematos** [comment]
Roman and I have been in contact and I've passed him access to a bucket in Frankfurt, DE. (chosen because we hardcode `us-east-1` as a region as per the SDK needs, and it _should_ be ignored. This will confirm that.)

**Comment by leematos** [comment]
Roman and I both ran into an issue with initial syncs on desktop where attempting to get info.json on first sync bombs out. I'll dig into this some more, but this change didn't change any "sync logic" so it's strange to me. Lemme see what I can find.

```
12:53:25: FileApi: get info.json
main-html.js:48 12:53:48: NoSuchKey: NoSuchKey
    at deserializeAws_restXmlGetObjectCommandError (/Users/lbot/Development/joplin/packages/lib/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:6280:41)
    at async /Users/lbot/Development/joplin/packages/lib/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /Users/lbot/Development/joplin/packages/lib/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/Users/lbot/Development/joplin/packages/lib/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)
    at async /Users/lbot/Development/joplin/packages/lib/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
```

**Comment by leematos** [comment]
It seems to be dying here: https://github.com/laurent22/joplin/blob/75cc73cc0c16fca976d9689011adf3e5cca117be/packages/lib/services/synchronizer/MigrationHandler.ts#L40

and this logic isn't catching the error code: https://github.com/laurent22/joplin/blob/75cc73cc0c16fca976d9689011adf3e5cca117be/packages/lib/file-api-driver-amazon-s3.js#L244

Makes sense as my prior attempts were with a bucket that already had state. Lemme see what needs to change.

**Comment by laurent22** [comment]
> It seems to be dying here:

Not sure if it's related, but you need to make sure that when a GET call fails, it returns NULL instead. Basically for the synchronizer it means that the item doesn't exist.

**Comment by roman-r-m** [comment]
Looks like you just need to change `code` to `name` here
https://github.com/laurent22/joplin/blob/75cc73cc0c16fca976d9689011adf3e5cca117be/packages/lib/file-api-driver-amazon-s3.js#L28-L31

Desktop syncs ok with this change, now on to Android

**Comment by roman-r-m** [comment]
UPD Not so fast - another error
```
main-html.js:48 20:48:24: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at MigrationHandler.<anonymous> (MigrationHandler.ts:46)
    at Generator.next (<anonymous>)
    at fulfilled (/home/roman/dev/joplin/packages/lib/services/synchronizer/MigrationHandler.js:5)
```

Having a look

**Comment by roman-r-m** [comment]
The content of `info.json` that Joplin sees in the above method is literally `[object Object]`, not sure if that's because it parses the response incorrectly or the file was created like this initially.

Hope this helps.

**Comment by leematos** [comment]
@roman-r-m heh, we are racing. Got the code -> name one sorted and am exactly where you are.

It's down to https://github.com/laurent22/joplin/pull/5212/files#diff-d06c6d5b2a13f7fa8da76bfd1d45a14e77df2d2ad3f92995e7dfe8c13a0616efR229 

I am trying a more robust streaming attempt now: https://github.com/aws/aws-sdk-js-v3/issues/1877#issuecomment-755387549

**Comment by roman-r-m** [comment]
> @roman-r-m heh, we are racing

Nah, all yours

**Comment by leematos** [comment]
Just pushed up a working change that works on my mac desktop client. trying my iOS build now. 🎉

**Comment by roman-r-m** [comment]
Could you clean the bucket you've given me? I don't think I can

File: packages/lib/file-api-driver-amazon-s3.js [hunk 1]
```diff
@@ -27,8 +28,18 @@ class FileApiDriverAmazonS3 {
...
+		return error.name.indexOf(errorCode) >= 0;
+	}
+
+
+	streamToString_(stream){
+		return new Promise((resolve, reject) => {
+			const chunks = [];
+			stream.on("data", (chunk) => chunks.push(chunk));
+			stream.on("error", reject);
+			stream.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
```
Comment (laurent22) [inline packages/lib/file-api-driver-amazon-s3.js:41]: If there's an error, are you sure that the "end" handler is not also being called? I had weird issues like this with streams that meant that both reject and resolve handlers ended up being called.

Comment (leematos) [reply packages/lib/file-api-driver-amazon-s3.js:41]: lemme try and create that case. This is the "recommended" approach from the aws-sdk-v3 folks so gonna wrap my head around it more.

**Comment by leematos** [comment]
@roman-r-m in theory you can with something like s3cmd/cyberduck, but I just emptied the contents for you now.

**Comment by roman-r-m** [comment]
Ok, now I am getting these errors when starting Android app
```
[Tue Jul 20 2021 21:34:33.854]  ERROR    TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[8], "stream").Readable.Readable')
[Tue Jul 20 2021 21:34:33.854]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Tue Jul 20 2021 21:34:33.854]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```
I think the 2nd and 3rd errors are caused by the 1st one.

It started fine before your most recent fixes.

File: packages/lib/file-api-driver-amazon-s3.js [hunk 2]
```diff
@@ -3,6 +3,8 @@ const { basename } = require('./path-utils');
 const shim = require('./shim').default;
 const JoplinError = require('./JoplinError').default;
 const { Buffer } = require('buffer');
+const { Readable } = require('stream').Readable;
```
Comment (leematos) [inline packages/lib/file-api-driver-amazon-s3.js:6]: The desktop app will load this fine.

on iOS I get `TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[8], "stream").Readable.Readable')` 

if I change it to `const Readable  = require('stream').Readable;` or `const { Readable }  = require('stream');`  I get undefined errors from the stream on iOS:

`[TypeError: stream.on is not a function. (In 'stream.on("data", function (chunk) {
            return chunks.push(chunk);
          })', 'stream.on' is undefined)]`

What am I missing?

Comment (leematos) [reply packages/lib/file-api-driver-amazon-s3.js:6]: seems this could fix it: https://github.com/laurent22/joplin/pull/5212#issuecomment-883691212

Comment (roman-r-m) [reply packages/lib/file-api-driver-amazon-s3.js:6]: I've updated my comment above with a SO link

With that the app starts but fails to connect returning `SignatureDoesNotMatch`. I did put invalid password initially but I think I have fixed it since, and yet..
I'm going to reinstall the app and see if it helps.

Btw, @laurent Joplin probably shouldn't do this (or maybe it's caused by the PR):
```
[Tue Jul 20 2021 21:44:47.477]  INFO     Saving sync.8.password <plain text password here>
```

Comment (leematos) [reply packages/lib/file-api-driver-amazon-s3.js:6]: afaik, the password logging bit happened before this change as I saw it in early troubleshooting.

**Comment by roman-r-m** [comment]
Interesting.. After a clean install I am now getting a different error
```
[Tue Jul 20 2021 21:50:30.986]  LOG      21:50:30: FileApi: get info.json
[Tue Jul 20 2021 21:50:52.257]  ERROR    21:50:51: [TypeError: stream.on is not a function. (In 'stream.on("data", function (chunk) {
            return chunks.push(chunk);
          })', 'stream.on' is undefined)]
```

I think maybe that SO link it's quite the solution, sure the app can start now but what's the point if it can't sync.
Or maybe I have applied it incorrectly by adding this:
```
				'stream': require.resolve('stream-browserify'),
```
I have to admit - I've no idea what this metro.config is

**Comment by leematos** [comment]
@roman-r-m metro.config.js is a react-native config. 

The problem is stream handling on node-js vs. react-native.

On node, we need go one way (the way we see now) and on react-native a much simpler Response(Response.Body).text worked well. I may be able to get node to accept the Response style call but no success yet.

File: packages/lib/file-api-driver-amazon-s3.js (hunk 2 above)
Comment (roman-r-m) [reply packages/lib/file-api-driver-amazon-s3.js:6]: Indeed, it's not related to your change.
It's here: https://github.com/laurent22/joplin/blob/366ef025dca9aad7c4254f198d5ef0d85e5b5bd4/packages/lib/components/shared/config-shared.js#L88

Comment (laurent22) [reply packages/lib/file-api-driver-amazon-s3.js:6]: Thanks for spotting this, it's debugging code that should have been removed. Actually could you remove it in this pr while you're at it?

Comment (roman-r-m) [reply packages/lib/file-api-driver-amazon-s3.js:6]: There's `SettingItem.secure` that can potentially be used to mask/filter log. Though I'm not sure if that value is available at the place where it's logged.

File: packages/lib/file-api-driver-amazon-s3.js [hunk 3]
```diff
@@ -3,7 +3,7 @@ const { basename } = require('./path-utils');
 const shim = require('./shim').default;
 const JoplinError = require('./JoplinError').default;
 const { Buffer } = require('buffer');
-const { Readable } = require('stream').Readable;
+//const Response = require('node-fetch').Response;
```
Comment (leematos) [inline packages/lib/file-api-driver-amazon-s3.js:6]: we are at a sort of impasse here that I don't know how best to resolve. 

Desktop needs this line, where react-native on iOS doesn't.

@roman-r-m if you want to pull and try both (uncomment for desktop / comment for android) to confirm the behaviour is the same. I'm not sure how to do a conditional import or if there is some other way to load this only on desktop.

Comment (roman-r-m) [reply packages/lib/file-api-driver-amazon-s3.js:6]: I'll give it a try today after work.

Something like `shim.isNode/isElectron/isReactNative` might help here.

Comment (laurent22) [reply packages/lib/file-api-driver-amazon-s3.js:6]: Indeed usually we use the shim, and in particular shim-init-node and shim-init-react to load certain things on desktop and others on mobile. See for example `shim.Geolocation`

Comment (roman-r-m) [reply packages/lib/file-api-driver-amazon-s3.js:6]: Seems to work fine on Android, I can sync both ways.

Comment (leematos) [reply packages/lib/file-api-driver-amazon-s3.js:6]: awesome! I'll take a look to see how I can shim that in appropriately for desktop.

Comment (leematos) [reply packages/lib/file-api-driver-amazon-s3.js]: @laurent22 thanks for that great example with Geolocation. In my latest commits I've used the shim and it's working in my env on desktop and iOS. 🎉 

I'm going to run the tests, and @roman-r-m if you could pull latest and confirm it works for you on desktop/android that would be appreciated. ❤️

File: packages/lib/shim-init-node.js [hunk 4]
```diff
@@ -16,6 +16,7 @@ const https = require('https');
 const toRelative = require('relative');
 const timers = require('timers');
 const zlib = require('zlib');
+const Response = require('node-fetch').Response;
```
Comment (leematos) [inline packages/lib/shim-init-node.js:19]: I'm new to node and modern JS. Is this acceptable or is it preferred to do `const { Response } = require('node-fetch');` which I think should have the same result?

File: packages/lib/file-api-driver-amazon-s3.js (hunk 2 above)
Comment (leematos) [reply packages/lib/file-api-driver-amazon-s3.js]: Solved in my latest commit.

File: packages/lib/file-api-driver-amazon-s3.js (hunk 1 above)
Comment (leematos) [reply packages/lib/file-api-driver-amazon-s3.js]: This is resolved as the latest approach is using Response to handle this.

File: packages/lib/shim-init-node.js (hunk 4 above)
Comment (laurent22) [reply packages/lib/shim-init-node.js:19]: I don't mind either way but I'd do the second option as it avoids a bit of redundant code.

**Comment by leematos** [comment]
Switched to Dev branch to run tests. I'm getting the failures on the following tests:

```
  ● services_SearchFilter › search type fts › should support filtering by created date
  ● services_SearchFilter › search type fts › should support filtering by between two dates
  ● services_SearchFilter › search type fts › should support filtering by updated date
  ● services_SearchFilter › search type nonlatin › should support filtering by created date
  ● services_SearchFilter › search type nonlatin › should support filtering by between two dates
  ● services_SearchFilter › search type nonlatin › should support filtering by updated date
```

Noting on this PR as I start testing my changes.

**Comment by leematos** [comment]
ok, on my current branch I'm currently getting some failures on tests that I don't fully understand yet:

```
      09:23:54: JoplinError: Cannot acquire sync lock because the following client has an exclusive lock on the sync target: (cli #edc0b81607cf49f1a2cfdd3c390944ea)
          at LockHandler.<anonymous> (/Users/lbot/Development/joplin/packages/lib/services/synchronizer/LockHandler.ts:167:12)
          at Generator.next (<anonymous>)
          at fulfilled (/Users/lbot/Development/joplin/packages/lib/services/synchronizer/LockHandler.js:13:24)
          at processTicksAndRejections (internal/process/task_queues.js:97:5) {
        code: 'hasExclusiveLock',
        details: null
```

```
      09:24:29: JoplinError: Cannot acquire sync lock because the following client has an exclusive lock on the sync target: (cli #d3dea777f87848119062b3502bc4e1a6)
          at LockHandler.<anonymous> (/Users/lbot/Development/joplin/packages/lib/services/synchronizer/LockHandler.ts:167:12)
          at Generator.next (<anonymous>)
          at fulfilled (/Users/lbot/Development/joplin/packages/lib/services/synchronizer/LockHandler.js:13:24)
          at processTicksAndRejections (internal/process/task_queues.js:97:5) {
        code: 'hasExclusiveLock',
        details: null
```

I thought the tests were making "fake mobile locks" from my quick read? I've never gotten this error in my simulator/desktop testing, so not sure if the tests hammer the bucket or are somehow not giving enough time for request -> response cycle?

**Comment by laurent22** [comment]
Isn't it an issue with S3 eventual consistency model? One client deletes the lock but when the other client checks the lock file still appears to be there.

There's no fake locks in testing, indeed to ensure that the lock mechanism is working properly and it seems it doesn't in this case.

**Comment by leematos** [comment]
> Isn't it an issue with S3 eventual consistency model? One client deletes the lock but when the other client checks the lock file still appears to be there.
> 
> There's no fake locks in testing, indeed to ensure that the lock mechanism is working properly and it seems it doesn't in this case.

Possibly. And apologies, when I said "fake" I meant that it looked like it was creating locks that identified as "mobile 2222". 

I need to re-test current dev and make sure it's hitting my S3 bucket and see if I get the same behavior.

**Comment by laurent22** [comment]
No problem, just clarifying that it's always activated. The mobile test you saw is probably part of the test units that are specifically for the lock system, but otherwise even in regular sync tests the lock system is active.

So maybe to debug your issue you could try to run only the lock handler tests only, which can be done by running `npm test -- synchronizer_LockHandler` from packages/lib

**Comment by roman-r-m** [comment]
Somewhat off-topic but I could never understand what the purpose of the sync lock is. Since it depends on the clientId, I don't think it'd prevent 2 different apps from synchronizing at the same time, only from running 2 parallel syncs from the same app.

Anyway, @leematos your change works fine for me on Android. Tested on Android 11 running in emulator.

**Comment by laurent22** [comment]
> Somewhat off-topic but I could never understand what the purpose of the sync lock is. Since it depends on the clientId, I don't think it'd prevent 2 different apps from synchronizing at the same time, only from running 2 parallel syncs from the same app.

The way it works is described in sync_lock.md and indeed there can be multiple SYNC lock, but there can be only one EXCLUSIVE lock, and this is the main purpose of the lock system. It allows a client to acquire an exclusive lock, then safely upgrade the sync target, while being sure that no other client is going to make change in the meantime. There hasn't been many sync target upgrades but it was used for that, and there might be others later on.

**Comment by leematos** [comment]
The plot thickens:

```
lib % npm test -- synchronizer_LockHandler

> @joplin/lib@2.2.0 test /Users/lbot/Development/joplin/packages/lib
> jest "synchronizer_LockHandler"

 PASS  services/synchronizer/synchronizer_LockHandler.test.js (167.388 s)
  synchronizer_LockHandler
    ✓ should acquire and release a sync lock (3101 ms)
    ✓ should not use files that are not locks (2594 ms)
    ✓ should allow multiple sync locks (2660 ms)
    ✓ should auto-refresh a lock (52390 ms)
    ✓ should call the error handler when lock has expired while being auto-refreshed (27208 ms)
    ✓ should not allow sync locks if there is an exclusive lock (2551 ms)
    ✓ should not allow exclusive lock if there are sync locks (2436 ms)
    ✓ should allow exclusive lock if the sync locks have expired (62768 ms)
    ✓ should decide what is the active exclusive lock (2142 ms)

Test Suites: 1 passed, 1 total
Tests:       9 passed, 9 total
Snapshots:   0 total
Time:        167.494 s
Ran all test suites matching /synchronizer_LockHandler/i.

```

I'm should have some time tomorrow to try to figure out which test is throwing the error I saw above.

**Comment by leematos** [comment]
Interestingly, when I run the tests ` npm test -- --runInBand` so that they run sequentially I have not hit the error on the 3 runs I tried. It seems like a race condition in testing if they are run in parallel. Should I be trying to hunt that down more?

If you'd like to test yourself I'm happy to get you a bucket on my account (email is here: https://github.com/laurent22/joplin/pull/5212#issuecomment-883480404)

**Comment by laurent22** [comment]
Indeed I hadn't thought about this, but the S3 tests aren't setup to run in parallel. To do that, there should be some code to dynamically create sync directories with unique names. Otherwise all the tests running in parallel share the same directory so obviously that cannot work. In fact could you add `mustRunInBand()` in the S3 conditional of test-utils please?

**Comment by laurent22** [comment]
Also there are still some errors on the CI test units related to the AWS package.

**Comment by leematos** [comment]
@laurent22 Thanks for your patience and help with this Pull Request. I think this is just about all set for your final review?

I haven't tested on Linux, and if you'd like me to, I can see about spinning up a virtualbox for a quick test.

**Comment by leematos** [comment]
err, Let me take a look at a few tests. These were my most recent failures locally as of my last commit:

New and could be related to this change:
 ```
● Synchronizer.resources › should sync resources
● Synchronizer.resources › should set the resource file size if it is missing
```

OLD and I believe present on dev:
```
● services_SearchFilter › search type fts › should support filtering by created date
● services_SearchFilter › search type fts › should support filtering by between two dates
● services_SearchFilter › search type fts › should support filtering by updated date
● services_SearchFilter › search type nonlatin › should support filtering by created date
● services_SearchFilter › search type nonlatin › should support filtering by between two dates
● services_SearchFilter › search type nonlatin › should support filtering by updated date
```

**Comment by leematos** [comment]
I'm currently failing here:

https://github.com/laurent22/joplin/blob/dev/packages/lib/services/synchronizer/Synchronizer.resources.test.ts#L60

With the following output for content 1 and 2:

```
 console.log
    CONTENT1

      at fileContentEqual (testing/test-utils.ts:678:2)

  console.log
    /9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5Ojf/2wBDAQoKCg0MDRoPDxo3JR8lNzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzf/wAARCAByAHsDASIAAhEBAxEB/8QAHAAAAAcBAQAAAAAAAAAAAAAAAAECAwQFBgcI/8QAOxAAAQMCBAQDBQUHBQEAAAAAAQACAwQRBRIhMQYTQVEiYYEUMnGR0QcjQqGxFSRSYpPB8DM0coOS8f/EABgBAAMBAQAAAAAAAAAAAAAAAAABAgME/8QAHhEBAQEBAQEAAgMAAAAAAAAAAAERAiExA0ESMkL/2gAMAwEAAhEDEQA/ANeRdupKbLQlg6I1yt4Jjb7p6NiSwDRSoQNEgdgZoLgKoxniERSmlw9gfKNHy2uGnyHVT8SqHRU7ooSRK9pAIHujus7R4TlkImALN7jS6cEivrJamcjnPkc8mwN73UK+RwEjQCNiRutl7BA4Wy5SOo6Jk4VT8vLmzEHS52RqmWM7iwiONrTbeyVR4rV0Tmy00wBvq0tFneRB0stFJgkb4CI2C438SzGLU/sMro26tIu4D8KcKui8MY/Q43EIZoYIq0DWPILPHdt/0V8aWC2kEX/gfRcLZUPopRKwva9pzskGmo2sV13griBvEOEcyRw9qgdknaO/Q+o/QqmV8Wwo4Da8EJ/6wlexUo0NND/Tb9FICO1wkEV9FSZdaWn/AKTfomzQ0d/9nT/0G/RTS0ZUWW+uqQYqwQR20SgAk0BjbjRSInBoJcbWCaamMTmENC9oNnSeBvqkED218s7pbmzzoPLopAe4tJVfC02BJGnUFToy02bv59k1DdV2B3PRRhJmc7U/mnpI2+6dT2SfZ2MALTYjcIB2CZziAZA0dR3VFxBHI6OR2Yk2OXMen9lZyHIDe4PS2l/mqPEq18mZjSOXrc33FvgUQqycs4tyg/3Qb9XE6fJaD7N8ZdQ8V0sJltDWDkytubEn3d+oNvmszVi0heCXWuAHi1v82SMNl5GJUc7Dd0c7HAHfQgrfPGFem7CyUEkdwljZZU4J3u7aox8EHHRKukGFB02SmtuiyFKa0231SaFMCz/Gb/Z4qeoeX8sEsIZfc/8AxaFjDfdUfFmZzKeEHUkv27bfqlPpxTtgqoY21VLzDC/3XXztJ9FJxOump6OKQacy2o6FIo5ZuWymfI49MrRYAeikY3BG+COGzS0D3fLsmauoaueWQMqMVvIRmDY4wQR8SbKYMV5RcOa2fuMxDh6fRJbR08sAHLADyHOAkIBIFht5G1trFRcRw44lXx1Lo2UuVoDeQ0NGnU9z5p+F7Er9psrYSYyLE6i/RZrGaoQyOzxl0jj4crxtre9vort1FHTkGKXM7ZzibX81nuIhNJPG2MPu7Y2Vc5pdbimmrC9uRpJZvta6mcOU37U4mw+ny5RNUtuG9Be5/JMUTKWKdwqWOqJGmzYLljXHzI19FvvstwoYjj5xlmHikpqWNzW5CS10h0Fs2ugJv6LS3GTrwN9UoIg1KAsVkQnDRENksi4sUWX4JKYwBKARgaBKA1U1Y2hZviwkVtMOhjJ381pmjTRZ3jOEsFLUgEgXYbeev1RDn1TR4jBRyt5pyi3vHQfNN1GO4TMyUGo5kjWkNLWnL8bpFO1kjnOks/8Al9VMNJRlmYRx2FrsDbKvFXT+E1AloWEixe3MNE1U1Nr6ggbhPCeOMsFw1uwA7qgxiuZGTdwvc/NE9o3IdnqmE2B1FtFCnrGODnOJ8HUC/wCipjWyvOcF1gNQnJ5RNDZrnMaR4yO60/izvWl0VM19SyrdLE6TmAtiZe56AdgvQHDmFswfBqWhZa8TPGQLZnnVx+ZK4n9nlAcS4ww9lSTIyJzpnZtblguPzsu/tFt0dIowEZsiQUkCGndBEgMgNkpgQDdkto1WbQtg6KPjdD7fhc9OwDmFuZl/4hqFKjCksag3JsOhg+9bVSPjle465yLdLeSXW4ZBLYnEpQGDQ3buNf8AArvjfBWU1UKwMBppz4vDo1/X52v81mpIaRsZ5DjqDdpFx5q4r9A6aRoEPtBmDD7xFr/5oqfEp2ySEWHY3CXPyqZr8mcvdsSRoq17JJS43JA132V8xnaS5xjZcDTcHsgycvyte4262G/xUigw2sxaUQ0EDpTsX7NHxOy3fDXB9Nh72z1oFTUtIIvoxh8u58zZVepCnNqfwLB+wKCbG66AguZpHlGdsY3Nuh627BdOpZ4qqnjnge18UjQ5rmm4IK55xdikeGcP1JuDLOwxRh2ty4WP5XKyHA3HdTw9MykrLzYa53iZ+KLzb9FElvo6mO8olHoK2mxGkiq6KZk1PK27HsOhUkfBJIgjQ2QTDKtaE41qJo2SwdFlWg2DVSmWsq2qxCjomF9XUxQtGvjeB+SyHEP2iQwtdBgo5sh0M7xYN+A6+qqTQ0fHGM0GH4HUwVLGVE0zMrYD5/iPYDf0WTwzhinr8JpqkySsM0IcQLEEn0WHxLEayq+8qpnSSyaF7tyF2Xg1kb8GwtthdtOwnysFVlkErDzcH4myVzJ4qeNu4kfK7Uf8bf3Uyj4Rpg4Pr5DVFp8MZbkZ8co39SV0zFImOjDyAS3bRZWsIac5ffXQdFN6qucpgBkDOVC3IwaNYwWa0eiMVZaNctye3ZR82Z5LneQ1t6Kj4uxL2OkMMZtLKC0EG1m9UpNqr5Gb4vxp2LV4ZGf3eAFrLHc9SqFzbdE4B4j163QdqumTJjC3V1wtxdinDMn7nIH07nXfA/VrvofNdy4X4nw/iSk51G/LKwDmwOPijP8Acea83lwsbb91IwrFKzCK1lZh9Q+Gdh0c3qOxHUeSV50nqVBc54a+1PDayNsONXo6jQc0NJjd8tR6/NdBgmiqImzQytfG8Xa5rrghQbnPE/FdNgUOUZZqxw8EV9vM+Swc3G2N1ZPMqhDGT7kDA3Ttff8ANZmoqJqueSeeRz5JHXc5x1JRhgto657JziQakVM75p5HvkdI5+737puNhL7jMW+qcjDS22d4J2sVJigaTla+9tSRpdPcMVLRPxDFqeiYdHOGbplG5Xc8HjibDBFBoI8offs0aD9CuScDwSSYpVVLTblsLRc9SdvkF1nBI3RxkucTcDU9z/gWfd9xUnmnqyZ7MRvLJaDJl93br+qqa6B0hvGzM3o4a3Cn4tcO0ucwBAKpclwHZNbfJQvmGquniooXTzyssG5iGHMdBrfoPmuX41iD8Rr5J3AhhPgb2C1nHFeaembSxOAdMPF5N7LA3v1Wv45+0d39Hrk6bJt56BGx2uiDnA6E/JaMzFvFqgSg8FAC26YA76KSyrqGNDWTSBo2GYpgBFmCQJduljYoIIBTXG51PunqpcRIvYkb/oEEEqcX3Az3BlRZx1kHXyXR8Knm5T/vZN/4j2QQWXX9l/5CvmlLT96/3T+I9lDL33953XqggpVPjnPGjnHE9XE+Ebn+ULPjdBBbc/GfX041IPvH4oIKkkv/ANQ/FF2QQQAfuiO6CCYf/9k=

      at fileContentEqual (testing/test-utils.ts:679:2)

  console.log
    CONTENT2

      at fileContentEqual (testing/test-utils.ts:681:1)

  console.log
    77+977+977+977+9ABBKRklGAAEBAQBIAEgAAO+/ve+/vQBDAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5Ojfvv73vv70AQwEKCgoNDA0aDw8aNyUfJTc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc377+977+9ABEIAHIAewMBIgACEQEDEQHvv73vv70AHAAAAAcBAQAAAAAAAAAAAAAAAAECAwQFBgcI77+977+9ADsQAAEDAgQEAwUFBwUBAAAAAAEAAgMEEQUSITEGE0FRImHvv70UMnHvv73vv70HI0Lvv73vv70VJFJi77+977+977+9MzRy77+977+977+977+977+9ABgBAAMBAQAAAAAAAAAAAAAAAAABAgME77+977+9AB4RAQEBAQEBAAIDAAAAAAAAAAABEQIhMQNBEjJC77+977+9AAwDAQACEQMRAD8A15F277+9Smzvv70l77+977+9Ne+/ve+/vQnvv73vv73vv73vv73Yku+/vTRS77+9A0Tvv73vv70Z77+977+9Cu+/vRnvv70RFO+/ve+/vQ9gfO+/vUfvv71r77+977+9Ie+/vU/Eqh0VO++/ve+/ve+/vSvvv71AIHvvv73vv73vv73vv73vv705ZCJgCzfvv73vv73vv73vv70i77+977+9Wu+/ve+/ve+/vT5HPO+/vQN777+9Qu+/vUcBI0AjYkbvv71l77+9EDhbLlI677+977+977+977+9U++/ve+/ve+/ve+/vUHvv73vv71kau+/vWM777+9CO+/vTbvv73vv717JVHvv710Tmzvv73vv70Ab++/vUtF77+977+9Qe+/ve+/vUUmCRvvv70iNgvvv73vv71LMe+/vVPvv70M77+977+977+977+977+977+9D8KcKu+/vTHvv73vv73vv71xCGbvv70I77+9QO+/vTzvv73vv70d77+9f++/vV8aWC3vv70Rf++/vX0XC2VD77+9Eu+/ve+/ve+/vWnvv73vv70G77+977+977+9V13vv70gbxDvv70c77+9HD3vv70HZO+/ve+/ve+/vUPvv70/Qu+/ve+/ve+/vWwo77+9Nu+/vRDvv73vv73vv71X77+9Uu+/vQ00P++/vW/vv71ICO+/vXDvv71FfRUmXWlp77+9AO+/vd+ibO+/ve+/ve+/ve+/ve+/vT/vv70b77+9U0tGVFlv77+977+9Birvv70Edu+/vSgA77+9QGNuNFIicGgl77+977+9Ce+/ve+/vTE577+9NC9oNnTvv70G77+977+9ED3vv73vv73vv73vv71ubO+/ve+/ve+/vQfvv73vv73vv71fC03vv70kae+/vRU6Mu+/vWbvv73vv73vv701De+/vXYHc++/vUYSZnPvv70/77+9ekjvv73vv71PZO+/vWdjAC02I3Dvv712Ce+/ve+/vQHvv700dR3vv70XEEcj77+977+92Yk2OXMe77+977+9We+/vXIDe++/ve+/ve+/vV/vv73vv70q77+9yZnvv70j77+977+977+977+9Fu+/vRRC77+977+977+977+9cu+/ve+/ve+/vW/vv73vv73vv73vv71aD++/vXxl77+9PFdLCe+/ve+/ve+/vQ5M77+977+977+9J++/vd+oNu+/ve+/ve+/vVjvv73vv73vv73vv71a77+9B++/vVvvv73vv70jDe+/ve+/ve+/vVHvv73vv713RzscAe+/vUIK77+9PGFe77+977+977+9UEkd77+9WO+/vWVOCe+/ve+/vdqjHwQcdErvv71B77+9B03vv73vv73bou+/vVLvv73vv71t77+9Se+/vUwLP++/vW/vv71477+977+9Hl/vv70E77+977+9X3Pvv70AxaFjDe+/vVR8We+/vcyn77+9HUkv27bfqlPvv73vv707YO+/ve+/vTbvv71S77+9DC/vv71dfO+/vSfvv71J77+966an77+977+9Qe+/vTLaju+/vSLvv71Z77+9bO+/vXzvv709Mu+/vVgB77+9Y3BG77+9I++/ve+/vS0D77+977+97Jmr77+9au+/vUDKjFbvv70R77+9Njjvv70EfEnvv73vv70xXlFw77+9fu+/vTEOHu+/vUTvv73vv73vv73vv70AHO+/vQPvv71z77+977+977+9SBYbeRtbaxUXEcOOJV8dS++/vWUuVu+/ve+/vUNDRu+/vU9z5p+F77+9Su+/ve+/ve+/ve+/vUnvv73vv70T77+977+9Re+/ve+/vWrvv70yOzxl77+9OO+/vXLvv71t77+977+9b++/ve+/vXUUdO+/vRjvv73vv73vv73vv71tfzXvv73vv70hNO+/ve+/ve+/ve+/ve+/ve2NlXPvv71dbinvv73vv70vbkbvv71Z77+91rrvv73DlN+1OO+/vQ/vv73LlE1S24bvv70X77+977+977+9FEzvv73vv713Cu+/vTrvv71G77+9Ngvvv70177+9zI19Fu+/ve+/vQoY77+9PnHvv71h4pKa77+9NzXvv70JLXTvv71BbO+/ve+/vQnvv73vv73vv73vv71k77+977+977+9VO+/ve+/vTUoCxXvv70J77+9RENk77+9LixRZe+/vSTvv70wBO+/vRHvv73vv71KA1U1Y2hZ77+9LCRW77+9Du+/vTJ377+9Wmbvv700We+/vTPvv73vv71S1IBIF2Hvv73vv73vv71UQ++/vVTvv73vv70wUe+/ve+/vWnvv70t77+9HQfvv703Ue+/ve+/vTMyUGo577+9Ne+/vTTvv73vv70v77+977+9FO+/vWTvv71z77+977+977+9AO+/ve+/vUw077+9Ze+/ve+/vXHvv71a77+9De+/ve+/vRV077+9E1Al77+9YSLvv73vv73vv700TVTvv73vv73vv73vv70G77+9PCfvv70y77+9cO+/ve+/vQDvv70x77+977+9Rk3vv70vc++/vUTvv73vv73vv712eu+/vRNgdRbvv71C77+977+977+9DnPvv73vv711Au+/vQDvv73vv70177+977+977+9Be+/vQNQ77+977+9UTQ2a++/vcaR77+9I++/ve+/ve+/ve+/ve+/vWl0VO+/vX1LKu+/vSxO77+977+9C2Jl77+9egHvv70vQHDvv70W77+9Hwbvv73vv71l77+9EzxkC2Z577+977+977+9Su+/vX9n77+9BxLvv70MPe+/vSTvv73InOmdm1vvv70L77+977+9y7/vv71bdHTvv70wEe+/vSJBSQIad0ESAyA2SmBAN2Tvv73vv71WbQtg77+977+9dD7fhe+/vU7vv70577+977+977+9f++/vRrvv70qMO+/ve+/ve+/vTcmw6Hvv73vv71bVSPvv73vv70677+9Iu+/vS3vv71b77+9QS3vv73EpQHvv71Ddu+/vTXvv70AAu+/ve+/vXwV77+977+9Qu+/vTAaac+Lw6Nf77+977+9a++/ve+/vWpIaRsZ77+9OO+/vQ3vv71Fx5rvv73vv73vv706aRoEPu+/vWYMPu+/vRbvv73vv73vv73vv73Ep2zvv70RYe+/ve+/vSXvv73Kpmvvv71nL3bEke+/ve+/vXsk77+977+93JA177+9ZXzvv71277+977+9GO+/vXA077+9Hu+/vTJy77+977+9e++/ve+/ve+/vW/vv71SKDDvv73vv71aUQ0EDu+/ve+/vV/vv71H77+977+9fDXvv73vv73vv71777+9PWgVNS0g77+977+977+9Hy7vv73vv73vv71V77+9Qu+/vdqf77+977+9fu+/ve+/ve+/vRvvv73vv73vv73vv71pHlHvv73vv73vv73Nuh7vv73vv70XTu+/ve+/vSrvv71477+977+9fFI0Oe+/vWnvv70g77+9ee+/vdikeGcP1Jvvv70s77+9MUYd77+9y4Xvv73vv71y77+9HA3vv711PD0zKSsvNhrvv71477+977+977+977+9b++/vUTvv73vv70677+977+9KO+/vXoK77+9bEbvv70q77+9Ke+/vTU877+977+9HsOhUkfvv70k77+9I0NkEwzvv71aE++/vWom77+977+977+977+9ZVoN77+9VSnvv73vv73vv73vv73vv70o77+9X1dTFC0a77+977+9B++/vRxD77+977+9DC10GCjvv73vv710M++/vVg377+9Ou+/ve+/ve+/vUNH77+9GO+/vQYf77+977+977+9Uu+/vVRNMzLvv70D77+977+977+9YDfvv71ZPDPvv70p77+977+9au+/vSTvv70zQhxA77+9BO+/vUXvv73EsRrKr++/ve+/ve+/ve+/vUsm77+977+93IXvv714Ne+/ve+/vQbvv73vv71hdtOw77+9KwVWWQTvv70877+9H++/ve+/vVcyeO+/ve+/vW7vv71H77+977+9R++/vW3vv73vv73vv70+Ee+/vQ4P77+977+977+9Fu+/vQxl77+9Ge+/ve+/vTfvv70ldO+/vVImOjDvv70BLe+/vUXvv73vv70h77+9OX3vv73vv710U3rvv73vv70p77+9GQM5UO+/vSMG77+9YwXvv73vv73vv71V77+977+9ctye3ZR82Z5L77+977+9Ne+/ve+/ve+/ve+/ve+/vUvvv73vv70MMe+/vUsoLQQbWe+/vVLvv71q77+977+977+977+977+9adi1eGRn77+9eAFrLHc9Su+/vXNt77+9OAfvv73vv73vv710He+/ve+/vSYw77+9V1wt77+92KcM77+977+977+977+977+977+9de+/vQPvv71r77+977+977+9dy4X77+9fD/vv70pOe+/vW/vv70rAO+/ve+/ve+/ve+/ve+/vQBx77+977+9XCxt77+9dSMK77+9KzDvv73vv71WYe+/vQ/vv712HRzeo++/vR1H77+9V++/vSfvv71QXOeGvu+/ve+/ve+/ve+/ve+/vQ41ejrvv70HNDTvv73vv73vv73vv71677+977+9Qe+/vWjvv70ibO+/ve+/ve+/ve+/ve+/vXbvv73vv73vv70hQe+/ve+/vRPvv71dNgUOUe+/vWrvv70PBFfvv73vv73vv70sHO+/vW3vv73Vk8yqEO+/vU/vv70DA3Tvv71977+9ADXvv73vv73vv73vv73vv715J++/vUc+SR13Oe+/vVJR77+9C2jvv73vv73vv70kGu+/vVM777+9R++/vUdI77+977+977+97puN77+977+977+9MW/vv71yMO+/ve+/vWd4J2sVJigaTlbvv73vv73Uke+/ve+/ve+/vTFS77+9PxDFqe+/vXRz77+9bu+/vUbvv713PB4477+9DBFB77+977+9KH3vv700aD9C77+9JwPvv70k77+977+9VUtN77+9bC0XPUnvv73vv70XWe+/vSN0ce+/ve+/vRNwNT3vv73vv70Wfe+/vXFSee+/ve+/vSZ7MRvvv70l77+9yZfvv73br++/vWvvv71077+977+9M3o4a3Dvv73vv73vv70O77+977+9MAQC77+9clwHZO+/ve+/vSUL77+9Gu+/ve+/ve+/ve+/vRdPPO+/ve+/vW5iGHMdBu+/ve+/vT5r77+977+9WO+/ve+/vRrvv70ncCHvv73vv70b77+9LWccV++/vXpm77+977+977+9HTDvv715N++/ve+/ve+/ve+/vVbvv73vv71+77+977+977+9Hu+/vTps77+9ee+/vRHvv73vv73og5wO77+977+977+977+977+9W8WqBO+/ve+/vVAC26YA76KSyrrvv700Ne+/vUgaNhnvv71gBFnvv71A77+9bu+/vTYoIO+/vVNcbnU+77+977+977+9SO+/ve+/vRvvv73vv70EEu+/vRfvv70M77+9BlRZ77+9WQdfJe+/ve+/ve+/ve+/vT/vv71k77+977+977+9ZBBZde+/ve+/ve+/vULvv71pS0/ev++/vT/vv73vv71Q77+977+9f3nvv71677+977+977+9T++/vXPGjnHvv73vv71xPhHvv73vv71Q77+977+9dBBbc++/vV9ONSDvv73vv73vv70K77+9S++/vQDvv70/FF3vv71BAB/vv70j77+9CCYf77+977+9
```

I'm trying to figure out _what_ encoding that is for the second file. Have you seen something like this before?

**Comment by leematos** [comment]
I actually think both test failures are caused by this decoding challenge.

Failure _Synchronizer.resources › should sync resources_ is upset because the formatting is different. (I tested images on desktop and ios and both worked AFAIR.)

Failure _Synchronizer.resources › should set the resource file size if it is missing_ is upset because the size ends up wrong, even though I've confirmed that when we get the photo it's showing the expected size:

```
     at FileApiDriverAmazonS3.get (file-api-driver-amazon-s3.js:234:12)

  console.log
    photo.jpg
    
    id: 4fed0b99b0004871bcc492ca792884ee
    mime: image/jpeg
    filename: 
    created_time: 2021-08-02T17:47:15.630Z
    updated_time: 2021-08-02T17:47:15.630Z
    user_created_time: 2021-08-02T17:47:15.630Z
    user_updated_time: 2021-08-02T17:47:15.630Z
    file_extension: jpg
    encryption_cipher_text: 
    encryption_applied: 0
    encryption_blob_encrypted: 0
    size: 2720
    is_shared: 0
    share_id: 
    type_: 4
```
I suspect it's wrong in the test because of something to do with the decoding... Not sure yet, still trying to wrap my head around where the decoding goes awry.

**Comment by laurent22** [comment]
It seems to be the same data but indeed with a weird encoding. It looks a bit like base64 except there's no = at the end for some reason.

**Comment by leematos** [comment]
I'm being lazy right now and not doing more formal testing but progress:

image

The top window is the image on my local system that gets parsed strangely, which doesn't open cleanly on preview on mac.

The bottom window is a download of that file from my server which does open on preview on mac.

I _think_ https://github.com/laurent22/joplin/blob/7f94dfa0936d87d827a82be5fb4f30d13e1c1e61/packages/lib/file-api-driver-amazon-s3.js#L240 is the problem line, where in the past we needed this, but now I think I may be able to use a different write method.

**Comment by laurent22** [comment]
Or maybe this? https://github.com/laurent22/joplin/blob/7f94dfa0936d87d827a82be5fb4f30d13e1c1e61/packages/lib/file-api-driver-amazon-s3.js#L233

It's reading as text even though the content is binary. That probably explains the additional chars in the second output as it's escaping the non-ascii characters.

**Comment by laurent22** [comment]
Is it not possible to use fetchBlob like for the other sync targets?

**Comment by leematos** [comment]
Thanks for the idea, looking into fetchBlob now.

I'm not sure we can use fetchBlob as I think that will treat it as a "generic HTTP request"? I'm wrapping my head around it now and looking at the dropbox exec function as the example.

I'm trying to set up a test function now to see.

**Comment by leematos** [comment]
I got a fix that passes tests, now to try it in the simulator and on my local machine. I'm not sure how this didn't break earlier when I tested a photo on my iOS simulator 🤔.

Basically, I shouldn't .text() at that spot, but either .buffer() in the file  case, or .text() later in the text case.

**Comment by leematos** [comment]
ugh. Classic. This solution works on desktop, but not currently on mobile. Exploring more fetchblob now as that can hopefully work 🤞

**Comment by leematos** [comment]
@laurent22 so I spent some time last night reading the fetchBlob code and in aws-sdk-v2 api, there was an option to "build a signed URL" which then you could fetch.

In v3, I see no such option, so as far as I understand fetchBlob won't work here. If I'm misunderstanding fetchBlob and it's the hero I need, do let me know :D I haven't been able to reconcile using the aws-sdk commands with fetchBlob.

The problem is boiling down to on ReactNative the response.Body is a blob and this sequence doesn't work:

```
const streamed_response = new shim.Response(response.Body);

// works on node because the response is not a blob but 
// a ReadableStream, on RN it appears Response/blob doesn't have buffer()
output = await streamed_response.buffer(); 

await shim.fsDriver().writeBinaryFile(filePath, output);
```

This is writeBinaryFile:

https://github.com/laurent22/joplin/blob/80b16dd17e227e3f538aa221d7b6cc2d81688e72/packages/app-mobile/utils/fs-driver-rn.ts#L29-L48

We die at buffer.from with:

`Could not download resource: b343e59de4c5429aac822ca101ee9efc TypeError: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object`

Best/easiest/fastest way to cast this to a buffer? (I attempted to cast to an ArrayBuffer, but it looks like RN doesn't implement ArrayBuffer......)

I've toyed around with an `output = Buffer.from(output, 'binary'); `(shim and no shim) to no avail. 

I feel like I'm running in circles on the dumbest thing... Any insights?

**Comment by laurent22** [comment]
When you get the object here:

`const response = await this.s3GetObject(remotePath);`

In which format is `response.Body`? Do you really have to wrap it using `new Response()`. Maybe if you write `response.Body` directly using writeBinaryFile it would work?

**Comment by leematos** [comment]
response.Body depending on the platform will either be ReadableStream/Readable/blob. The response wrapping is an attempt to actually get the data by using the .text()/.buffer() methods on Response. (which appears to be implemented differently in React Native and Node.)

**Comment by laurent22** [comment]
Maybe you need to have some conditional to read/write the data in one way on mobile and another way on desktop? You can use shim.mobilePlatform() to do that.

**Comment by leematos** [comment]
Agreed. The problem I'm having at the moment is I cannot seem for the life of me to be able to get this blob converted to a buffer. If I can do that, I'm pretty sure writeBinaryFile will "just work".

**Comment by laurent22** [comment]
Yes maybe regular fetch blobs aren't supported using React Native, which is why we have `fetchBlob()`. If you could figure out the signed URL it should normally work. Maybe by copying the function from the aws-sdk-v2 source code? Or you could probably get there too by following the AWS doc although and be quite error prone: https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

**Comment by leematos** [comment]
Actually, it looks like writeBinaryFile is _just_ used by the aws file driver (according to my github search.) If so, I'm gonna see if I can add logic on the RN on to pass a blob to rn-fetch-blob (what powers writeBinaryFile) as I _think_ this could work.

**Comment by leematos** [comment]
nah, that's wrong, it's also used here: https://github.com/laurent22/joplin/blob/8a00eef901b2b70076e4fa19b124269c49e9b93d/packages/lib/models/Resource.ts#L248-L249

But, I have some ideas now.

**Comment by laurent22** [comment]
If I remember well this writeBinaryFile function was indeed added by the person who implemented the first S3 sync target. Resource.setContent is not used anywhere as far I can see.

**Comment by leematos** [comment]
@roman-r-m Can I ask you to pull latest and try once more, specifically:

- on a desktop build connected to the bucket, attach an image to a note1, sync UP desktop.
- On mobile, sync DOWN that note1 , and confirm it works.
- on mobile, attach an image to a note2, and sync UP mobile.
- on desktop, sync DOWN that note2, and confirm it works.

This will put the new get method on android through it's paces and confirm it works as it does in my environment! 

This loop works for me on Mac/iOS and once we confirm no gremlins on Android, this change is good to go!



@laurent22 -- Thanks for the fetchBlob suggestion, was able to get that working and I'm way more confident in fetchBlob  vs the writeBinaryFile variant that was present earlier.

A L M O S T   D O N E !

**Comment by roman-r-m** [comment]
@leematos just got to testing this, something's not working on Android, getting this after pressing "Check synchronization configuration":
```
2021-08-08 20:46:28.596 15412-15526/net.cozic.joplin W/ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
    Error: not implemented
    get@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:33730:24
    parseUrl@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:310800:24
    normalizeEndpoint@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:310962:50
    resolveEndpointsConfig@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:310948:51
    S3Client@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:302571:63
```

**Comment by leematos** [comment]
ah. I think I need to update the check configuration code. It's due for a refactor because its not DRY. Lemme take a look.

**Comment by leematos** [comment]
In theory, you should still be able to sync.

**Comment by roman-r-m** [comment]
> In theory, you should still be able to sync

Sorry I accidentally edited your comment instead of replying - reverted now.

Getting this when trying to sync (1st line is extra logging I added):
```
[Sun Aug 08 2021 20:57:29.910]  LOG      api: new client: {"region":"us-east-1","credentials":{"accessKeyId":"...","secretAccessKey":"..."},"UseArnRegion":true,"forcePathStyle":true,"endpoint":"https://eu-central-1.linodeobjects.com"}
[Sun Aug 08 2021 20:57:29.914]  INFO     20:57:29: Could not acquire synchroniser:
[Sun Aug 08 2021 20:57:29.914]  INFO     20:57:29: [Error: not implemented]
```

**Comment by leematos** [comment]
Hmmm. Strange. I'm not exactly sure what isn't implemented. 

I suspected https://github.com/laurent22/joplin/blob/bacd09e530f4c1aa069cb9464c4344b86287afbf/packages/lib/file-api-driver-amazon-s3.js#L175-L177

but your error has a _lowercase_ n.

I don't see any with a lowercase n in the joplin codebase so it has to be something deeper.

It looks like it's something to do with the s3client and get.

**Comment by leematos** [comment]
@roman-r-m any chance you can put the app in debug mode (In the node window that pops up if you press 'd' it should slide open a drawer on the app, and you can choose debug mode.)

That error on the config check then should resolve to a file instead of the bundle and we should be able to get a better sense of where in the code we are dying.

I just tested again on ios simulator, and sync and config check work for me.

I suspect it's something to do possibly with the URL polyfill that the API wants but I'm not sure.

**Comment by roman-r-m** [comment]
@leematos looks like this all was an error on my part. It seems I have applied your patch incorrectly, now that I have reset the repo and reapplied the patch, it all syncs perfectly both ways.

**Comment by leematos** [comment]
Swoosh! Happens to me all the time <3.

@laurent22 not sure if there is anything else that you'd like to see here or want me to test, but I think this is good to go!

(I'm using the S3 sync daily now, so basically if we get any new errors I'm happy to take a look.)

**Comment by laurent22** [comment]
The last thing is that now that you've switched to a new aws package, we should make sure we're no longer importing the old one anywhere. So could you search for "aws-sdk" and make sure all instances are removed? I think there's one under app-cli but I guess it can be removed (maybe shouldn't have been there in the first place). If you change any package.json, please run "npm install" to make sure package-lock is updated too.

**Comment by leematos** [comment]
Sorry about that, thought I got them all.

Pushing that change shortly.

I'm not exactly sure what I should do about https://github.com/leematos/joplin/blob/aws-sdk-v3-js/packages/app-mobile/index.js#L34-L37

I didn't notice any new errors on startup with the new package so not sure if I should remove, or adjust these to be the new package.

**Comment by laurent22** [comment]
You can ignore these warning filters for now. Maybe we'll update them some other time.

**Comment by leematos** [comment]
Huh. Hitting a strange problem. I removed aws-sdk from the app-cli/package.json

I normally run npm install from the project root and just let it do it's thing.

It didn't update app-cli/package-lock.json? Is that expected?

if I npm install from app-cli, the package.json gets updated, BUT it still thinks that joplin/lib requires the _old_ package?

```
    "@joplin/lib": {
+      "version": "2.1.1",
+      "resolved": "https://registry.npmjs.org/@joplin/lib/-/lib-2.1.1.tgz",
+      "integrity": "sha512-mePMxOEC7+T7gTRuIO3ZWxkyDhAhuoNNGi3wsf4g633TcYD0SEX9peokCdjAnQC5l4BjrqxmgY1qTmk2sx+9TA==",
+      "requires": {
+        "@joplin/fork-htmlparser2": "^4.1.28",
+        "@joplin/fork-sax": "^1.2.32",
+        "@joplin/renderer": "^1.8.2",
+        "@joplin/turndown": "^4.0.50",
+        "@joplin/turndown-plugin-gfm": "^1.0.32",
+        "async-mutex": "^0.1.3",
+        "aws-sdk": "^2.588.0",
```

What am I missing?

**Comment by laurent22** [comment]
I think it's because you need to bump the joplin/lib package but you don't need to worry about this now, it's done when the cli app is released.

**Comment by leematos** [comment]
I think I've caught them all, and we should be good to go.

**Comment by laurent22** [comment]
That's great, thanks @leematos and @roman-r-m! Let's merge then so that it can be part of the 2.2 release.
