### PR TITLE
Desktop: Fixes #4788: Set plain/text clipboard while copying

### LINKED ISSUE #4788: Copied text from Rich Text editor cannot be pasted outside of Joplin
- Select some text in Rich Text editor
- Try to paste it inside the editor itself - it works
- Try to paste it in an external editor - it doesn't work

on v1.8

### PR DESCRIPTION
**Pull request by nishantwrp**
## Automated Tests
The tests were already written for the main function in #4724. This PR fixes #4788, a bug which appeared due to that PR.

## Manual Testing

- Write some text in a note
- Add image
- Select both of them
- Paste in a Rich Text Editor (Libre Office) [Pasted successfully]
- Paste in a text editor (VS Code) [Pasted successfully]

### CODE REVIEW

File: packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx [hunk 1]
```diff
@@ -1041,7 +1042,14 @@ const TinyMCE = (props: NoteBodyEditorProps, ref: any) => {
...
 			const copyableContent = getCopyableContent(copiedContent);
-			clipboard.writeHTML(copyableContent);
+
+			// In that case we need to set both HTML and Text context, otherwise it
+			// won't be possible to paste the text in, for example, a text editor.
+			// https://github.com/laurent22/joplin/issues/4788
+			clipboard.write({
+				text: htmlUtils.stripHtml(copiedContent),
+				html: copyableContent,
+			});
```
Comment (laurent22) [inline packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx:1052]: When you copy and paste code from elsewhere like this, it makes it hard to maintain the code. Now whenever we want to improve or fix something related to copying text, there's two places to change and we have to remember that (and of course, we won't).

So please refactor the code so that the context menu and Ctrl+C run the same function. Create for example a utility function that takes HTML and, optionally, plain text as input, and copy that to the clipboard in the correct way.

Comment (nishantwrp) [reply packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx:1052]: Got it, actually, I was also thinking of the same. Also, should I refactor to include Cut from context menu and (Ctrl X) in that function. Because technically in a cut we copy the text before erasing it.

**Comment by nishantwrp** [comment]
## Manual Testing Steps

Write some text in a note
Add image
Select both of them
Copy them [Tested with both Context Menu and Ctrl+C]
Paste in a Rich Text Editor (Libre Office) [Pasted successfully]
Paste in a text editor (VS Code) [Pasted successfully]

File: packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx (hunk 1 above)
Comment (nishantwrp) [reply packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx]: done, please review.

**Comment by nishantwrp** [comment]
Hi, this pr is ready to be reviewed.

**Comment by laurent22** [comment]
Yes looks like it's working well now, thanks for the fix @nishantwrp
