### PR TITLE
Mobile: Upgrade to React Native 0.81

### LINKED ISSUE #14197: Upgrade expo-modules-core to 3.0.14+
Android startup time is significantly impacted by `expo-modules-core` 2.5.x due to expensive module registration, most notably `ExpoFetchModule`. Profiling shows ~1 second of CPU time spent in Expo module registration during app startup, largely caused by Kotlin reflection and allocation-heavy initialisation.

`expo-modules-core` ≥ **3.0.14** includes fixes that remove this reflection-based overhead and should materially improve startup performance.

https://github.com/expo/expo/blob/main/packages/expo-modules-core/CHANGELOG.md#3014--2025-09-08

### Observed behaviour (current state)

On Android (release build, Hermes enabled):

* App displays a native splash immediately (first frame ~2 ms after `activityStart`)
* React Native UI (`DispatchUI`) is delayed by **~1.3 seconds**
* Total perceived startup time is ~3 seconds

Perfetto trace analysis shows the delay is dominated by Expo module registration and constants initialisation.

#### Expo module registration (major contributor)

```
[ExpoModulesCore] ModuleRegistry.register(class expo.modules.fetch.ExpoFetchModule)
≈ 520 ms (single module)
```

Aggregated CPU time:

```
ExpoFetchModule              ≈ 1039 ms
Process React packages       ≈ 1424 ms
```

The Fetch module alone accounts for ~1 second of CPU time when including GC overhead.

This exactly matches the issue addressed in:
[https://github.com/expo/expo/pull/39389](https://github.com/expo/expo/pull/39389)

### Proposal

Upgrade:

```
expo-modules-core: 2.5.x → 3.0.14
```

Then:

* Re-run Perfetto startup trace
* Compare:

  * Time to first `DispatchUI`
  * Expo module registration duration
  * GC time during startup

### PR DESCRIPTION
**Pull request by personalizedrefrigerator**
# Summary

This pull request:
- upgrades React Native
- enables React Native's [New Architecture](https://reactnative.dev/architecture/landing-page).

Resolves https://github.com/laurent22/joplin/issues/14197.

# Key changes

- Upgrades from React Native [0.79.2](https://reactnative.dev/blog/2025/04/08/react-native-0.79) to [0.81.5](https://reactnative.dev/blog/2025/08/12/react-native-0.81).
- Upgrades from Expo SDK 53 to SDK 54.
    - See [the Expo native project upgrade helper](https://docs.expo.dev/bare/upgrade/?fromSdk=53&toSdk=54#androidappbuildgradle).
- Enables the New Architecture.
    - The Legacy Architecture is [frozen](https://github.com/reactwg/react-native-new-architecture/discussions/290) and [logs a deprecation warning](https://github.com/facebook/react-native/blame/41057d011802b44cef29e9e5cf184f2b9f6ce56f/packages/react-native/Libraries/ReactNative/renderApplication.js#L114).
- Fixed padding on devices with SafeArea padding (see [commit](https://github.com/laurent22/joplin/pull/14232/changes/48989a07c24a56f29efa80f177b94d8212767300)).
    - Prior to this change, in landscape mode, a test Android 12 device had a large amount of unnecessary padding between the right edge of the editor and the edge of the screen. This was caused by a conflict between the `SideMenu.tsx` component and the `SafeAreaView`.
    - This fixes what would have been a regression on certain Android devices — React [Native 0.81/Expo SDK 54 seems to enable edge-to-edge](https://expo.dev/blog/edge-to-edge-display-now-streamlined-for-android) on more Android devices.
- Voice typing refactor:
    - Makes the Whisper.cpp voice typing logic compatible with the New Architecture.
       - Moves the `whisper.cpp` C++ and Kotlin code to a new `whisper-voice-typing` package based on [react-native-nitro-modules](https://nitro.margelo.com/docs/what-is-nitro).
       - `react-native-nitro-modules` is used by [several popular React Native packages](https://nitro.margelo.com/docs/awesome-nitro-modules) including the 1.x versions of [react-native-quick-crypto](https://github.com/margelo/react-native-quick-crypto) (Joplin uses react-native-quick-crypto 0.x). `react-native-nitro-modules` seems to be easier to set up for C++ and have better documentation than the official [React Native Turbo Modules](https://reactnative.dev/docs/0.79/the-new-architecture/pure-cxx-modules).
    - **Additional benefit:** It should now be much easier to add support for Whisper.cpp-based voice typing on iOS.
- Replaces packages that are incompatible with the New Architecture:
   - `react-native-fs` was replaced with `@dr.pogodin/react-native-fs` (a maintained fork).
   - `react-native-exit-app` was replaced with Expo's `reloadAppAsync`.
   - `@bam.tech/react-native-image-resizer` was replaced with `expo-image-manipulator`.

# Testing plan

## Android

Most testing was done prior to https://github.com/laurent22/joplin/pull/14232/changes/48989a07c24a56f29efa80f177b94d8212767300 (fix sidemenu edge-to-edge handling):

Android 15 emulator:
1. Create a release build of the Android app.
3. Install the release APK on an Android 15 emulator.
4. Start Joplin.
5. Create a new to-do.
6. Set the to-do's alarm for two minutes in the future.
7. Minimize Joplin and open the notification center.
8. Wait...
9. Click on the task reminder.
10. Open the kebab menu, click "attach", and attach a photo.
11. Create a new note (with a docked on-screen keyboard).
12. Verify that the Markdown toolbar is shown above the keyboard.
13. Add a tag to the note.
14. Open settings, install the "YesYouKan" plugin.
15. Create a new note. Paste the YesYouKan plugin's default sample note content (from its README).
16. Close and re-open the note.
17. Switch to the YesYouKan plugin view.
18. Move a card from one column to another.
19. Close and re-open the note.
20. Verify that the change from step 17 has been saved.
21. Close Joplin.
22. From the home screen, long-press on the "Joplin" icon.
23. Click "New attachment" in the quick actions menu.
   - Note: Quick actions menu items are missing icons. This does not seem to be a regression.
24. Select a file in the file picker.
25. Verify that a new note has been created with the file attached.
26. Enable TalkBack.
27. Open the note list.
28. Mark a to-do item as complete.
29. Enter selection mode by double-tapping and holding.
30. Exit selection mode by pressing the Android back button.
31. Open a note. Change the title.

Android 12 emulator:
1. With the Rich Text editor enabled, create a new note.
2. Focus the note body and open the onscreen keyboard.
3. Verify that the editor toolbar is shown above the keyboard.
4. Navigate back to the note list.
5. Repeat steps 1-3 for the Markdown editor.

Android 13 physical device:
1. Install the release APK.
2. Verify that voice typing adds text to a note (language: English).

## iOS 

iOS 26.2 simulator:
1. Run Joplin in release mode.
6. Open the "Welcome to Joplin" release notes page.
7. Long-press on the attached image.
8. Click "open".
9. Verify that the image is opened in fullscreen mode.
10. Open the kebab menu, attach a large photo.
11. Choose to resize the photo.
12. Verify that the photo is attached to the note.
13. Edit the note in the Markdown editor.
14. Show the software keyboard.
15. Verify that the Markdown toolbar is shown above the keyboard.
16. Click the "keyboard" button in the toolbar to dismiss the keyboard.
17. Open toolbar settings and remove the "H2" button from the toolbar.
18. Switch to the Rich Text Editor.
19. Add a new item to the "organising your notes" list.
20. Go back to the note viewer.
21. Go back to the note list.
22. Create a to-do.
23. Set an alarm for 1-2 minutes in the future.
24. Open the device's home screen.
25. Open the notifications list.
26. Wait...
27. Open Joplin from the task's notification.
28. Install the "Joplin debug tool" plugin.
29. Verify that it's possible to open the "note info" plugin panel.
30. Set up synchronization with Joplin Server and enable E2EE.
32. Verify that the initial sync completes successfully.
33. Open an existing note and attach a drawing.
34. Switch profiles.
35. Create a new note from the camera.
   - Since it's running on an iOS simulator, the camera output will be blank.
36. Close Joplin.
37. Quick actions: Create a new note by long-pressing the "Joplin" home screen icon.

## Web

Chrome:
1. Verify that it's possible to open the web app and create a new note.

> [!NOTE]
> Most changes in this pull request shouldn't affect the web app.

### CODE REVIEW

File: packages/app-mobile/components/app-nav.tsx [hunk 1]
```diff
@@ -50,20 +62,18 @@ const AppNavComponent: React.FC<Props> = (props) => {
...
 		<KeyboardAvoidingView
-			enabled={keyboardAvoidingViewEnabled}
-			behavior={Platform.OS === 'ios' ? 'padding' : null}
-			style={style}
+			style={styles.keyboardAvoidingView}
+			enabled={
+				// Workaround: On Android 15, the main app content seems to auto-resize when the keyboard is shown.
+				// On earlier Android versions (and in modals), this does not seem to be the case.
+				(Platform.OS === 'android' && Platform.Version < 35)
+				|| Platform.OS === 'ios'
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/app-nav.tsx]: Joplin currently has several `KeyboardAvoidingView`-related workarounds. In the future, it may make sense to migrate to [`react-native-keyboard-controller`](https://kirillzyusko.github.io/react-native-keyboard-controller/). `react-native-keyboard-controller` is [mentioned in the Expo "Keyboard handling" documentation](https://docs.expo.dev/guides/keyboard-handling/) and is [mentioned as an alternative](https://github.com/facebook/react-native/issues/29614#issuecomment-2558457550) to KeyboardAvoidingView in at least one of the upstream issues.

File: packages/app-mobile/components/ExtendedWebView/index.tsx [hunk 2]
```diff
@@ -141,7 +142,8 @@ const ExtendedWebView = (props: Props, ref: Ref<WebViewControl>) => {
 			onLoadEnd={props.onLoadEnd}
 			onContentProcessDidTerminate={refreshWebViewAfterCrash}
 			onRenderProcessGone={refreshWebViewAfterCrash}
-			decelerationRate='normal'
+			// See https://github.com/react-native-webview/react-native-webview/issues/3814
+			decelerationRate={Platform.OS === 'ios' ? 'normal' : undefined}
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/components/ExtendedWebView/index.tsx:146]: See https://github.com/react-native-webview/react-native-webview/issues/3814#issuecomment-3490180045.

**Comment by personalizedrefrigerator** [comment]
Converting to a draft, pending voice typing testing.

File: packages/app-mobile/package.json [hunk 3]
```diff
@@ -5,7 +5,7 @@
   "version": "3.6.0",
   "private": true,
   "scripts": {
-    "start": "BROWSERSLIST_IGNORE_OLD_DATA=true react-native start --reset-cache",
+    "start": "BROWSERSLIST_IGNORE_OLD_DATA=true react-native start",
```
Comment (personalizedrefrigerator) [inline packages/app-mobile/package.json]: `--reset-cache` was removed while debugging startup issues. Although it might be safe to remove (`--reset-cache` has been present since [at least 2020](https://github.com/laurent22/joplin/blob/421d7a947f4f7e856ca09557494c75802b2a82ee/ReactNativeClient/package.json)), it would probably be best to do so in a separate pull request.

File: packages/app-mobile/ios/Joplin/Info.plist
Comment (personalizedrefrigerator) [inline packages/app-mobile/ios/Joplin/Info.plist:1]: Note: The order of the entries in this file was automatically changed either by XCode or `npx expo install --fix`.

**Comment by laurent22** [comment]
Thanks for implementing this, that's quite a big change. I'm going to create a pre-release so that we can get this tested as much as possible before the final release

**Comment by personalizedrefrigerator** [comment]
> Thanks for implementing this, that's quite a big change. I'm going to create a pre-release so that we can get this tested as much as possible before the final release

Thank you for creating the release!

For reference, I'm linking to probable regressions:
- https://github.com/laurent22/joplin/issues/14265
- https://github.com/laurent22/joplin/issues/14268
- https://github.com/laurent22/joplin/issues/14267
- https://github.com/laurent22/joplin/issues/14266

(Thank you @mrjo118 for reporting these!)

**Comment by mrjo118** [comment]
@personalizedrefrigerator After pulling this change, if I build the web app via 'yarn web' I can no longer run it in production mode using 'npx serve web/dist' in the app-mobile directory. I get this error in the browser console at runtime. Any ideas?:

COOP/COEP Service Worker registered http://localhost:3000/web/dist/ serviceWorker.bundle.js:2:3900
Uncaught Error: React Refresh runtime should not be included in the production bundle.
    13662 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    15808 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    11095 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    5272 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    78888 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    15916 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    61096 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    46666 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    11261 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    41046 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    92653 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    12066 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    32571 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    51431 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    <anonymous> http://localhost:3000/web/dist/app.bundle.js:2
    <anonymous> http://localhost:3000/web/dist/app.bundle.js:2
app.bundle.js:2:5517782
    13662 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    15808 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    11095 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    5272 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    78888 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    15916 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    61096 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    46666 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    11261 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    41046 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    92653 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    12066 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    32571 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    51431 http://localhost:3000/web/dist/app.bundle.js:2
    __webpack_require__ http://localhost:3000/web/dist/app.bundle.js:2
    <anonymous> http://localhost:3000/web/dist/app.bundle.js:2
    <anonymous> http://localhost:3000/web/dist/app.bundle.js:2

**Comment by mrjo118** [comment]
I'm also getting an error running the Android app locally. I intermittently get an error about a missing whisper module when I run yarn tsc in app-mobile (despite having updated dependencies with yarn install at the root), but even after successfully rebuilding I get a consistent error when I install the dev app on Android emulator:

BUILD FAILED in 8s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build completed with 2 failures. 1: Task failed with an exception. ----------- * Where: Build file 'C:\joplin-dev\packages\whisper-voice-typing\android\build.gradle' line: 39 * What went wrong: A problem occurred evaluating project ':joplin_whisper-voice-typing'. > Could not read script 'C:\joplin-dev\packages\whisper-voice-typing\nitrogen\generated\android\WhisperVoiceTyping+autolinking.gradle' as it does not exist. * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. ============================================================================== 2: Task failed with an exception. ----------- * What went wrong: A problem occurred configuring project ':joplin_whisper-voice-typing'. > Android Gradle Plugin: project ':joplin_whisper-voice-typing' does not specify `compileSdk` in build.gradle (C:\joplin-dev\packages\whisper-voice-typing\android\build.gradle). * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. ============================================================================== BUILD FAILED in 8s.
info Run CLI with --verbose flag for more details.

**Comment by personalizedrefrigerator** [comment]
>  Uncaught Error: React Refresh runtime should not be included in the production bundle.

That should be fixed by #14285!
